# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 2.1

"El precio de la gasolina aumentó considerablemente durante los
años que van desde 2003 hasta 2006 y, sin embargo, el consumo de
gasolina creció." ¿Contradice esta afirmación la ley de la demanda?


** Answer

No: la ley sólo es válida cuando el único determinante de la demanda
que cambia es el precio del bien. A lo largo del periodo 2003--2006 no
sólo cambió el precio, sino que también se modificaron otros
determinantes de la demanda de gasolina (como la renta de los
consumidores, el precio de otros combustibles, etc).


* 2.2

Considere un mercado competitivo donde participan \num{1000}
compradores idénticos, cada uno de ellos con curva de demanda:
#+begin_export latex
\[
  Q^d_i(P) = 5 - P, \qquad i = 1, ..., \num{1000}.
\]
#+end_export
En el mercado hay también \num{625} vendedores idénticos con curvas de
oferta individuales:
#+begin_export latex
\[
  Q^o_j(P) = 2.4 P , \qquad j = 1, ..., \num{625}.
\]
#+end_export

a) Halle y represente gráficamente el equilibrio de mercado.

b) ¿Qué ocurriría si el precio fuera \price{4}? ¿Y si fuera
   \price{1}?


** Answer

a) Obtenemos la demanda de mercado sumando las cantidades demandadas por cada uno de los compradores:
   #+begin_export latex
   \[
     Q^d(P) = Q_{1}^{d}(P) + Q_{2}^{d}(P) + \dots + Q_{\num{1000}}^{d}(P)
   \]
   #+end_export
   Como todas las demandas individuales son iguales:
   #+begin_export latex
   \[
     Q^d(P) = \num{1000} (5 - P) = \num{5000} - \num{1000} P
   \]
   #+end_export
   Razonando de forma análoga, obtenemos la curva de oferta de mercado:
   #+begin_export latex
   \[
     Q^o(P) = 625 Q^{o}_{i} = 625 \times 2.4 P = \num{1500} P
   \]
   #+end_export
   El equilibrio de mercado se produce cuando se igualan la demanda y
   la oferta de mercado.

   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-market-eq-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Equilibrio de mercado:
   #+begin_export latex
   \begin{gather*}
     P^{*} = \price{2}, \\
     Q^{*} = \text{\num{3000} unidades.}
   \end{gather*}
   #+end_export
   #+xxx: endcol


b) Si el precio de mercado es $P = \price{4}$ se produce un exceso de
   oferta de \num{5000} unidades. Si $P = \price{1}$ se produce un
   exceso de demanda de \num{2500} unidades.


* 2.3

En un mercado competitivo sólo hay tres compradores y sus curvas de demanda individuales son:
#+begin_export latex
\begin{gather*}
  \text{Comprador 1:\ } Q^d_1(P) = \num{1000} - 10 P \\
  \text{Comprador 2:\ } Q^d_2(P) = 600 - 2 P \\
  \text{Comprador 3:\ } Q^d_3(P) = 750 - 5 P
\end{gather*}
#+end_export
Determine la curva de demanda de mercado.


** Answer

- Si $P \leq 100$, participan los 3 compradores:
  #+begin_export latex
  \[
    Q^d(P) = Q^d_1(P) + Q^d_2(P) + Q^d_3(P) = \num{2350} - 17 P
  \]
  #+end_export

- Si $100 < P \leq 150$, compran 2 y 3:
  #+begin_export latex
  \[
    Q^d(P) = Q^d_2(P) + Q^d_3(P) = \num{1350} - 7 P
  \]
  #+end_export

- Si $150 < P \leq 300$, sólo compra 2:
  #+begin_export latex
  \[
    Q^d(P) = Q^d_2(P) = 600 - 2 P
  \]
  #+end_export
- Por último,  si $P > 300$ no se compra ninguna unidad.

La curva de demanda de mercado es:
#+begin_export latex
\[
  Q^d(P) =
  \begin{cases}
    0 & \text{si $P > 300$} \\
    600 - 2 P   & \text{si $150 < P \leq 300$} \\
    \num{1350} - 7 P  & \text{si $100 < P \leq 150$} \\
    \num{2350} - 17 P & \text{si $P \leq 100$} \\
  \end{cases}
\]
#+end_export

#+xxx: fig fig-ans-probl-2_1004-market-demand-*.pdf


* 2.4

El mercado de coches eléctricos de un país es competitivo y las
curvas de demanda y oferta son:
#+begin_export latex
\begin{gather*}
  Q_{d}(P) = \num{10000} - P/6 \\
  Q_{o}(P) = \num{-6000} + P/2
\end{gather*}
#+end_export
a) Determine el precio y la cantidad de equilibrio.

b) Calcule y represente el nuevo equilibrio si la demanda aumenta
   en un 20% (la cantidad demandada es un 20% superior para cada
   precio) y la oferta pasa a ser:
   #+begin_export latex
   \[
     Q_o(P) = \num{-2700} + P/2
   \]
   #+end_export


** Answer

a) El equilibrio se produce cuando coinciden las curvas de demanda y
   oferta de mercado.

   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-cars1-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Equilibrio:
   #+begin_export latex
   \begin{gather*}
     P^{*}_a = \price{24000}, \\
     Q^{*}_a = \text{\num{6000} coches.}
   \end{gather*}
   #+end_export
   #+xxx: endcol

b) La cantidad demandada aumenta un 20% para cada posible precio. Por
   tanto:
   #+begin_export latex
   \[
     Q'_{d}(P) = 1.2 Q_{d}(P) = \num{12000} - P/5
   \]
   #+end_export
   Hallamos el equilibrio igualando las nuevas curvas de demanda y
   oferta de mercado:
   #+begin_export latex
   \begin{gather*}
     Q'_{d}(P) = \num{12000} - P/5 \\
     Q'_{o}(P) = \num{-2700} + P/2
   \end{gather*}
   #+end_export

   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-cars2-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Equilibrio:
   #+begin_export latex
   \begin{gather*}
     P^{*}_b = \price{21000}, \\
     Q^{*}_b = \text{\num{7800} coches.}
   \end{gather*}
   #+end_export
   #+xxx: endcol


* 2.5

Las curvas de demanda y de oferta del mercado del bien $X$ son:
#+begin_export latex
\begin{gather*}
  X_d = \num{85000} - 20 P_X \\
  X_o = \num{15000} + 15 P_X
\end{gather*}
#+end_export

a) Determine el precio y la cantidad de equilibrio.

b) Represente gráficamente los efectos sobre el equilibrio de un
   aumento del precio de un bien sustitutivo. ¿Es posible predecir
   inequívocamente cómo cambiará el precio de equilibrio del bien
   $X$? ¿Y la cantidad de equilibrio?

c) Partiendo del equilibrio inicial, considere ahora los efectos
   de un aumento de la renta de los consumidores. ¿Es posible
   predecir con total certeza cómo cambiarán el precio y la
   cantidad de equilibrio?


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-comp1-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Equilibrio:
   #+begin_export latex
   \begin{gather*}
     P^*_X = \price{2000}, \\
     X^* = \units{45000}.
   \end{gather*}
   #+end_export
   #+xxx: endcol

b)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-comp2-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Si se eleva el precio de un bien sustitutivo, la demanda
   aumentará. Tanto el precio como la cantidad de equilibrio se
   incrementan en este caso.
   #+xxx: endcol

c) No es posible determinar qué ocurrirá con el precio y la cantidad
   de equilibrio sin saber si el bien es normal o inferior.  Al crecer
   la renta aumentarán el precio y la cantidad de equilibrio si se
   trata de un bien normal, pero disminuirán el precio y la cantidad
   de equilibrio en el caso de un bien inferior.

   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-comp3-*.pdf
   #+begin_center
   Bien normal
   #+end_center
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-comp4-*.pdf
   #+begin_center
   Bien inferior
   #+end_center
   #+xxx: endcol
   #+latex: \vspace*{2ex}




* 2.6

Un país se enfrenta a un aumento del consumo de drogas. Los
expertos han propuesto dos explicaciones alternativas:

- El presupuesto policial cada vez más reducido ha incrementado la
  presencia de drogas en la calle.

- Los recortes en programas educativos han reducido la consciencia
  acerca de los peligros de las drogas.

Utilice diagramas de oferta y demanda para analizar cada una de
esas hipótesis. ¿Es posible discriminar entre esas dos
explicaciones observando qué ha ocurrido con el precio y el
consumo de drogas?


** Answer

- Menor presupuesto policial: la oferta de drogas se incrementa al
  tener los traficantes de droga menos dificultades.

- Recortes en programas educativos: la demanda aumenta al ser los
  compradores potenciales menos conscientes de los riesgos asociados
  al consumo de drogas.

En los dos casos aumenta la cantidad consumida, pero el precio
disminuye en el primer escenario y aumenta en el segundo. Observando
la dirección del cambio en el precio es posible determinar cuál de las
dos hipótesis es correcta.

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-2_1004-drugs1-*.pdf
#+begin_center
Menos policía
#+end_center
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-2_1004-drugs2-*.pdf
#+begin_center
Recortes educación
#+end_center
#+xxx: endcol
#+latex: \vspace*{2ex}



* 2.7

El mercado de un bien inferior se encuentra en equilibrio. Si
simultáneamente aumentan los costes de producción y la renta de
los consumidores, ¿disminuirán tanto el precio como la cantidad en
el nuevo equilibrio?


** Answer

Tanto la demanda como la oferta disminuyen. En consecuencia, la
cantidad de equilibrio disminuye. El precio podría aumentar o
disminuir.

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-2_1004-inferior1-*.pdf
#+begin_export latex
\begin{center}
  \begin{minipage}{0.9\linewidth}
    El precio baja si el cambio en la oferta es relativamente menor
    que el cambio en la demanda.
  \end{minipage}
\end{center}
#+end_export
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-2_1004-inferior2-*.pdf
#+begin_export latex
\begin{center}
  \begin{minipage}{0.9\linewidth}
    El precio sube si el cambio en la oferta es relativamente mayor
    que el cambio en la demanda.
  \end{minipage}
\end{center}
#+end_export
#+xxx: endcol
#+latex: \vspace*{2ex}




* 2.8

Los precios de las habitaciones de hotel en las grandes ciudades
suelen depender del día de la semana en que se alquilan. En una semana
típica, los precios de las habitaciones son mucho más bajos los fines
de semana que los días laborables. Utilice diagramas de oferta y
demanda para explicar este comportamiento.


** Answer

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-2_1004-hotels-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
La oferta de habitaciones de hotel es la misma entre semana que en fin
de semana: la curva de oferta no cambia.  Pero la demanda entre
semana, $D_e$, es muy diferente a la demanda de fin de semana, $D_f$.
#+xxx: endcol
#+latex: \vspace*{2ex}


- Entre semana se demandan muchas habitaciones por motivos laborales y
  de negocios. Este tipo de viajeros tiene una elevada disposición a
  pagar por las habitaciones.

- En fin de semana la demanda de habitaciones por motivos de turismo y
  ocio es mayoritaria. Este tipo de viajeros tiene una menor
  disposición a pagar y, si el precio de las habitaciones es muy
  elevado, buscará destinos alternativos más baratos.



* 2.9

Una fuerte sequía ha dañado considerablemente la cosecha de café en
los principales países productores.

a) ¿Qué consecuencias tendrá la sequía sobre el equilibrio en el
   mercado mundial de café? Razone y represente gráficamente.

b) ¿Cuáles serán las consecuencias de la mala cosecha de café sobre el
   equilibrio en el mercado mundial de té? Razone y represente
   gráficamente.


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-coffee-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   La oferta mundial de café se contrae y la demanda no se ve
   afectada. El precio del café de equilibrio se eleva, mientras que
   la cantidad intercambiada disminuye.
   #+xxx: endcol

b)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-tea-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El café y el té son bienes sustitutivos y un alza del precio del
   café provocará un aumento de la demande de té. En el nuevo
   equilibrio el precio del té es más elevado y se vende una cantidad
   mayor.
   #+xxx: endcol



* 2.10

El mercado de patinetes eléctricos de un país es competitivo y se
encuentra en equilibrio. Razone y represente gráficamente cómo
afectarían las siguientes situaciones al equilibrio de mercado.

a) Baja el precio de las baterías que los fabricantes montan en los
   patinetes.

b) Un informe alerta de problemas de seguridad graves y cada vez más
   frecuentes para los usuarios de patinetes eléctricos.

c) El Gobierno aprueba leyes destinadas a reducir la contaminación y
   las emisiones de $\text{CO}_2$ en las ciudades y que limitan
   considerablemente la circulación de coches en las ciudades.

d) Una nueva regulación del mercado de trabajo eleva los costes
   laborales de los fabricantes de patinetes.


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-scooters-a-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   La reducción de los costes de fabricación de los patinetes,
   desplaza la oferta hacia abajo y a la derecha. El precio de
   equilibrio disminuirá y la cantidad intercambiada aumentará.
   #+xxx: endcol

b)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-scooters-b-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Un informe que cuestione la seguridad de los patinetes reducirá la
   demanda de los mismos y provocará una disminución tanto del precio
   como de la cantidad de equilibrio.
   #+xxx: endcol

c)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-scooters-c-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   La búsqueda de medios de transporte urbano alternativos a los
   coches elevará la demanda de patinetes. En el nuevo equilibrio se
   venden más patinetes a un precio mayor.
   #+xxx: endcol

d)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-2_1004-scooters-d-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El aumento de los costes laborales reduce la oferta de patinetes.
   El precio aumentará y la cantidad disminuirá en el nuevo
   equilibrio.
   #+xxx: endcol
