#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 6


* Los costes

1. La función de producción de una empresa viene dada por: $Q = 2 K
   L$. El salario por hora es \wage{2} y el precio unitario del factor
   capital es de \price{4}.

   a) Si la empresa dispone de un presupuesto de \money{200} para
      contratar factores, ¿cuál será la combinación óptima de
      $L$ y $K$? ¿Cuál será la producción de la empresa?

   b) La función de producción de la empresa pasa a ser $Q = 4 K
      L$. Calcule el coste total asociado y las cantidades de factores
      utilizados si el nivel de producción es de \units{2500}.

2. La tecnología que usa una empresa puede representarse mediante la
   función de producción: $Q = (KL)^{1/2}$

   a) Calcule la demanda condicionada para cada uno de los factores
      de producción.

   b) Obtenga la función de costes a largo plazo si $w =\wage{1}$ y $r
      = \price{1}$.

   c) Obtenga las funciones de coste marginal y coste medio a largo plazo.

   d) Obtenga las funciones de coste total medio, coste variable medio
      y coste marginal a corto plazo para un nivel de capital $K =
      \units{25}$.

3. La función de producción de una empresa es: $F(K, L) = K
   L^{2}$. Los precios de los factores son: $r = \price{5}$ y $w =
   \wage{2}$.

   a) Señale el tipo de rendimientos de escala que presenta la
      tecnología que usa la empresa.

   b) Si se desea alcanzar un nivel de producción igual a \units{200},
      calcule las cantidades de cada factor de producción que debería
      adquirir la empresa para minimizar el coste de producción.

   c) Determine la función de costes de producción y el coste total
      para un nivel de producción $Q = \units{200}$.

4. Una empresa tiene la función de producción: $Q = 2 K^{1/2}
   L^{3/2}$. Actualmente contrata 8 unidades de trabajo y 2 unidades
   de capital. Si esta es la combinación óptima de factores a largo
   plazo y si los costes totales son iguales a \money{16}, ¿cuáles son
   los precios del capital y del trabajo?

5. Una empresa opera con la tecnología $Q = K L$ y usa 3 unidades de
   capital a corto plazo. Los precios de los factores son $w=
   \wage{1}$ y $r=\price{1}$.

   a) ¿Cuál es la demanda condicionada del factor trabajo en el corto
      plazo? ¿Y la función de costes? ¿Y la de costes marginales?

   b) ¿Cuál es el único nivel de producción en el que coinciden los
      costes a largo plazo y los costes a corto plazo? ¿Por qué? ¿Qué
      ocurre en cualquier otro nivel de producción?

6. Explique y justifique si considera correcta o incorrecta cada una
   de las siguientes afirmaciones (use el análisis gráfico cuando lo
   considere oportuno):

   a) Si el coste marginal coincide con el coste medio, el coste
      medio se maximiza.

7. Considere una función de producción del tipo $Q = 2 L^2K$, siendo
   el salario igual a \wage{1} y el precio del capital igual a
   \price{4}.

   a) Calcule la función de costes a corto plazo, el coste fijo
      medio, el coste variable medio y el coste marginal si $K =
      \units{16}$.

   b) Calcule la función de costes a largo plazo y el coste medio a
      largo plazo. Compare las curvas de costes medios a corto y a
      largo plazo.

8. Suponga que la función de producción de una empresa es $Q = K L$ y
   que los precios unitarios de los factores son iguales a \money{2}.

   a) Determine qué tipo de rendimientos de escala presenta la
      función de producción y calcule la función de costes a largo
      plazo.

   b) Si la empresa decide producir $Q = \units{3600}$, determine el
      coste total, coste medio y coste marginal a largo plazo.

   c) Calcule el coste a corto plazo de producir $Q = \units{3600}$,
      si la empresa utiliza 5 unidades de capital.

9. Una empresa opera con una función de producción $Q = K L$ y paga
   por cada unidad de factor productivo \money{5}.

   a) Obtenga la función de costes a largo plazo. Si la empresa desea
      producir 100 unidades, ¿cuál es el coste mínimo en que
      incurriría?

   b) Calcule la curva de costes a corto plazo dada la cantidad de
      capital óptima que resulte del apartado anterior.

   c) ¿El coste a corto plazo de producir 100 unidades es mayor o
      menor que el coste a largo? ¿Y si el capital usado a corto
      hubiera sido menor? Justifique su respuesta.

10. La función de producción de una empresa es: $Q = K L^{1/2}$. Por
    cada unidad que usa del factor trabajo la empresa paga \money{8},
    mientras que por cada unidad del factor capital paga
    \money{54}. Sabiendo que a corto plazo está utilizando
    $80$ unidades de capital, ¿cuál es la curva de costes a corto
    plazo? Obtenga también la curva de costes a largo plazo, compare
    los costes de producir \num{1000} unidades a corto y a largo plazo
    y explique las diferencias.

    #+begin_answer
    - Sustituimos el capital a corto plazo, $\overline{K} = 80$, en la
      función de producción y despejamos el trabajo para obtener la
      demanda condicional de trabajo a corto plazo:
      \begin{equation*}
        L(Q) = Q^{2}/\num{6400}
      \end{equation*}
      Usamos esta expresión y los precios de los factores, $w = 8$ y $r
      = 54$, para obtener la curva de costes a corto plazo:
      \begin{equation*}
        C_{CP}(Q) = r \overline{K} + w L(Q) = 4320 + Q^2/800
      \end{equation*}


    - La relación marginal de sustitución técnica es:
      \begin{equation*}
        \mathit{RMST} = \frac{1}{2}\frac{K}{L}
      \end{equation*}
      La minimización de costes a largo plazo implica: $\mathit{RMST} =
      w / r$. De esta condición se obtiene:
      \begin{equation*}
        K = \frac{8}{27} L
      \end{equation*}
      Sustituyendo esta expresión en la función de producción y
      operando, obtenemos las demandas condicionadas de $L$ y $K$ a
      largo plazo:
      \begin{equation*}
        L(Q) = \frac{9}{4} Q^{2/3}; \qquad K(Q) = \frac{2}{3} Q^{2/3}
      \end{equation*}
      Curva de costes a largo plazo:
      \begin{equation*}
        C_{LP}(Q) = r K(Q) + w L(Q) = 54 Q^{2/3}
      \end{equation*}

    - El coste de producir \num{1000} unidades es superior a corto plazo:
      \begin{equation*}
        C_{CP}(1000) = \money{5570} > C_{LP}(1000) = \money{5400}
      \end{equation*}
      En general, los costes a corto plazo son superiores a los costes
      a largo plazo porque los niveles de factores que pueden usarse a
      corto plazo no coinciden con los que minimizan el coste de
      producción a largo plazo, cuando la empresa no está sujeta a
      ninguna restricción: $\overline{K}_{CP} = 80 \neq K_{LP} = 2/3 \cdot
      1000^{2/3} \approx 66.7$).
    #+end_answer

11. La función de producción de una empresa es $Q = K^{2} L$. Los
    precios de los factores de producción son: $P_K = 8$ y $P_L = 4$. A
    corto plazo, el capital es fijo e igual a $K = 2$.

    a) Obtenga la curva de costes a corto plazo de la empresa y
       determine si los costes variables medios son decrecientes.
       #+begin_answer
         La producción a corto plazo es:
         $Q = 2^2 L = 4 L$,
         y la demanda condicional de trabajo a corto plazo es:
         \[ L(Q) = Q / 4 \]
         Costes a corto plazo:
         \[ C(Q) = P_K \cdot \overline{K} + P_L \cdot L(Q) \]
         así que:
         \[ C(Q) = 16 + Q \]

         Los costes variables medios son $\mathit{CVMe(Q)} =
         \mathit{CV}(Q) / Q$. En nuestro caso $\mathit{CV}(Q) = Q$ y
         $\mathit{CVMe}(Q) = 1$ que no cambia con el nivel de
         producción: los costes variables medios no son decrecientes.
       #+end_answer

    b) Obtenga la curva de costes a largo plazo de la
       empresa.
       #+begin_answer
         A largo plazo se debe cumplir que
         \[ \mathit{RMST} = \frac{1}{2} \frac{K}{L} = \frac{4}{8} = \frac{P_L}{P_K} \]
         De esta condición obtenemos la senda de expansión de la producción:
         \[ K = L \]
         Sustituyendo esta expresión en la función de producción y
         despejando $L$ obtenemos la demanda condicional de trabajo a
         largo plazo:
         \[ L(Q) = Q^{1/3} \]
         De acuerdo con la senda de expansión $K = L$, por lo que:
         \[ K(Q) = Q^{1/3} \]
         Costes a largo plazo:
         \[ C(Q) = P_K \cdot K(Q) + P_L \cdot L(Q) \]
         así que:
         \[ C(Q) = 12 Q^{1/3} \]
       #+end_answer
