# -*- ispell-dictionary: "spanish" -*-
#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 1


1. En una economía se producen dos bienes, automóviles y comida,
   usando trabajo como único factor de producción. Se dispone de un
   máximo de \num{50000} horas de trabajo. La siguiente tabla muestra
   las cantidades que pueden producirse dependiendo de las horas de
   trabajo que se dediquen a cada actividad:

   #+ATTR_LATEX: :booktabs t :center t :align rrp{1cm}rr
   |-------------+--------------+---+-------------+--------------|
   | Trabajo     | Automóviles  |   | Trabajo     | Comida       |
   | (horas)     | (unidades)   |   | (horas)     | (kg)         |
   |-------------+--------------+---+-------------+--------------|
   | \num{0}     | \num{0}      |   | \num{0}     | \num{0}      |
   | \num{12500} | \num{40000}  |   | \num{12500} | \num{50000}  |
   | \num{25000} | \num{70000}  |   | \num{25000} | \num{75000}  |
   | \num{37500} | \num{90000}  |   | \num{37500} | \num{90000}  |
   | \num{50000} | \num{100000} |   | \num{50000} | \num{100000} |
   |-------------+--------------+---+-------------+--------------|

   a) Represente gráficamente la Frontera de Posibilidades de
      Producción, FPP.

      #+begin_answer

          #+MATS: fig fig-probl-1_1004-ppf-sh1-*.pdf

      #+end_answer

   b) ¿Qué efecto tendría sobre la FPP una mejora en las técnicas
      agrícolas que aumentara la producción de comida por hora de
      trabajo? ¿Y una mejora organizativa en la cadena de producción
      de automóviles? ¿Y si ambas mejoras se produjesen
      simultáneamente como consecuencia de un progreso técnico
      generalizado en la sociedad?

      #+begin_answer
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-sh2-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          Una mejora tecnológica en la producción de comida.
        #+end_minipage

        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-sh3-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          Una mejora organizativa en la producción de automóviles.
        #+end_minipage

        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-sh4-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          Mejoras en los dos sectores.
        #+end_minipage
      #+end_answer

   c) ¿Qué consecuencias tendría sobre la FPP la reducción a la mitad
      de las horas de trabajo como consecuencia de un conflicto
      bélico?

      #+begin_answer
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-sh5-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          Desplazamiento a la izquierda de la FPP.
        #+end_minipage
      #+end_answer
      #+latex: \ClearPage{}

2. La tabla adjunta presenta diferentes combinaciones eficientes de
   producción para una economía en la que únicamente se producen dos
   bienes: $X$ e $Y$.

   #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{r}
   |-----+------------+------------|
   |     | $X$        | $Y$        |
   |     | (unidades) | (unidades) |
   |-----+------------+------------|
   | *A* | \num{20}   | \num{0}    |
   | *B* | \num{18}   | \num{1}    |
   | *C* | \num{15}   | \num{2}    |
   | *D* | \num{11}   | \num{3}    |
   | *E* | \num{6}    | \num{4}    |
   | *F* | \num{0}    | \num{5}    |
   |-----+------------+------------|

   a) Represente la Frontera de Posibilidades de Producción, FPP. ¿Qué
      tiene de particular la forma de la FPP?

      #+begin_answer
        #+attr_latex: :options {0.6\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-oc1-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.4\linewidth}
        #+begin_minipage
          La FPP es cóncava.
        #+end_minipage
      #+end_answer
      #+latex: \ClearPage{}

   b) ¿Se pueden producir \num{2} unidades de $Y$ y \num{10} unidades
      de $X$?  ¿Qué ocurre en esta situación?

      #+begin_answer
        #+attr_latex: :options {0.6\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-oc2-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.4\linewidth}
        #+begin_minipage
          La combinación es factible pero ineficiente.
        #+end_minipage
      #+end_answer

   c) Construya una tabla que refleje el coste de oportunidad de
      producir cada unidad del bien $Y$.

      #+begin_answer
        #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{r}*{3}{c}
        |-----+----------+---------+------------+------------+---------------------------|
        |     | $X$      | $Y$     | $\incr{X}$ | $\incr{Y}$ | $\abs{\incr{X}/\incr{Y}}$ |
        |-----+----------+---------+------------+------------+---------------------------|
        | *A* | \num{20} | \num{0} | ---        | ---        | ---                       |
        | *B* | \num{18} | \num{1} | \num{-2}   | \num{1}    | \num{2}                   |
        | *C* | \num{15} | \num{2} | \num{-3}   | \num{1}    | \num{3}                   |
        | *D* | \num{11} | \num{3} | \num{-4}   | \num{1}    | \num{4}                   |
        | *E* | \num{6}  | \num{4} | \num{-5}   | \num{1}    | \num{5}                   |
        | *F* | \num{0}  | \num{5} | \num{-6}   | \num{1}    | \num{6}                   |
        |-----+----------+---------+------------+------------+---------------------------|
      #+end_answer

   d) ¿A cuántas unidades de $X$ se debe renunciar para producir la
      primera unidad de $Y$? ¿Y la segunda?

      #+begin_answer
        Para poder producir la primera unidad de $Y$ hay que renunciar
        a $2$ unidades de $X$, mientras que el coste de oportunidad de
        la segunda es $3$ unidades de $X$.
      #+end_answer
      #+latex: \ClearPage{}

3. El siguiente gráfico representa la frontera de posibilidades de
   producción de una economía donde sólo se producen cocos y pescado:

   #+MATS: fig fig-probl-1_1004-ppf-*.pdf

   Ordene las opciones de producción $A$, $B$, $C$ y $D$ de mayor a
   menor coste de oportunidad de producir pescado.

   #+begin_answer
     El coste de oportunidad sería mayor en $D$ que en $A$, ya que la
     pendiente es más pronunciada en $D$.  Combinaciones como $B$ no
     son eficientes y el coste de oportunidad es $0$. Puntos como
     el $C$ son inaccesibles y el coste de oportunidad no está
     definido.
   #+end_answer

4. Argumente la veracidad o falsedad de la siguiente afirmación:
   "Cuando un gran número de desempleados encuentra un puesto de
   trabajo, se produce un desplazamiento de la frontera de
   posibilidades de producción hacia la derecha."

   #+begin_answer

   #+end_answer

5. El mercado de un bien está formado por tres compradores cuyas
   curvas de demanda son:

   #+ATTR_LATEX: :center t :align lc
   | Comprador 1: | $q_1 = 1000 - 10 P$. |
   | Comprador 2: | $q_2 = 600 - 2 P$.   |
   | Comprador 3: | $q_3 = 750 - 5 P$.   |

   Determine la curva de demanda de mercado.

   #+begin_answer

   #+end_answer

6. En el mercado de un bien participan \num{1000} compradores
   idénticos, cada uno de ellos con curva de demanda:
   #+begin_export latex
   \[
     Q^d_i = 5 - P, \qquad i = 1, ..., \num{1000}.
   \]
   #+end_export
   El bien es vendido por \num{500} empresas idénticas, cada una
   con curva de oferta:
   #+begin_export latex
   \[
     Q^o_j = 2.4 P , \qquad j = 1, ..., \num{500}.
   \]
   #+end_export

   a) Halle las curvas de demanda y oferta de mercado y la
      solución de equilibrio. Represente gráficamente.

      #+begin_answer

      #+end_answer

   a. ¿Qué ocurriría si el precio de mercado fuera \price{4}? ¿Y si
      el precio de mercado fuera \price{1.5}?

      #+begin_answer

      #+end_answer

7. "Durante los años que van desde 2003 hasta 2006 el precio de la
   gasolina aumentó considerablemente y, sin embargo, el consumo de
   gasolina creció." ¿Contradice esta afirmación la ley de la demanda?

   #+begin_answer

   #+end_answer

8. Considere un mercado competitivo de manzanas y use un diagrama de
   oferta y demanda para analizar cómo afectaría al equilibrio una
   enfermedad de los manzanos que perjudique a la cosecha. ¿Es posible
   que los ingresos de los agricultores aumenten en este caso? ¿Qué
   condiciones se tendrían que cumplir?

   #+begin_answer
     Una enfermedad de los manzanos afectará a la curva de oferta de
     manzanas, que se desplazará hacia la izquierda y hacia
     arriba. Como consecuencia en el mercado se venden menos manzanas
     a un precio superior.

     #+MATS: fig fig-probl-1_1004-apples-*.pdf

     El efecto sobre los ingresos de los productores puede ser
     positivo o negativo. Los ingresos solo crecerán si disminuye la
     producción en una proporción menor a la que aumenta el precio: el
     mercado se encontraría en un /tramo inelástico de la curva de
     demanda/.
   #+end_answer

9. Ante el aumento del consumo de drogas en un país, los expertos han
   señalado dos posibles explicaciones alternativas:

   - Una presencia policial cada vez más reducida en las calles ha
     facilitado el tráfico de drogas.

   - La reducción de programas de educación y de apoyo a los adictos
     han reducido la concienciación de una parte de la sociedad acerca
     de los peligros de las drogas.

   Utilice diagramas de oferta y demanda para analizar cada una de
   esas hipótesis. ¿Es posible discriminar entre esas dos
   explicaciones observando qué ha ocurrido con el precio y la
   cantidad consumida de drogas?

   #+begin_answer

   #+end_answer

10. Las medicinas tienen una demanda inelástica mientras que los
    ordenadores tienen una demanda elástica. Suponga que como
    consecuencia del progreso tecnológico la oferta de ambos productos
    se duplica.

    a) ¿Qué ocurrirá con el equilibrio en estos mercados?

       #+begin_answer

       #+end_answer

    b) ¿En qué mercado se experimentará el mayor cambio en el precio?
       ¿Y el mayor cambio en la cantidad?

       #+begin_answer

       #+end_answer

    c) ¿Cómo se verá afectado el gasto de los consumidores en cada
       bien?

       #+begin_answer

       #+end_answer

11. En el mercado del bien $X$ las curvas de demanda y de oferta son:
    \begin{gather*}
      X^d = \num{85000} - 20 P_X \\
      X^o = \num{15000} + 15 P_X
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

       #+begin_answer

       #+end_answer

    b) Represente gráficamente los efectos sobre el equilibrio de un
       aumento del precio de un bien sustitutivo, /ceteris
       paribus/. ¿Es posible predecir inequívocamente cómo cambiará el
       precio de equilibrio del bien $X$? ¿Y la cantidad de equilibrio?

       #+begin_answer

       #+end_answer

    c) Partiendo de la situación inicial, represente los efectos sobre
       el equilibrio de un aumento de la renta de los consumidores,
       /ceteris paribus/. ¿Es posible predecir inequívocamente cómo
       cambiarán el precio y la cantidad de equilibrio?

       #+begin_answer

       #+end_answer

12. Si en un mercado competitivo en equilibrio simultáneamente se
    encarecen los costes de producción y aumenta la renta de los
    consumidores, ¿aumentarán tanto el precio como la cantidad en el
    nuevo equilibrio?

    #+begin_answer

    #+end_answer

13. Cuando un país subió los impuestos sobre el tabaco, el precio
    medio de la cajetilla subió de \money{4} a \money{4.6}. Se estimó
    que como consecuencia de esta subida de precio la cantidad
    demandada cayó de $52$ a $47.5$ millones de cajetillas.  Calcule
    la elasticidad de la demanda de tabaco.

    #+begin_answer

    #+end_answer

14. Dos conductores repostan todos los lunes en la misma
    gasolinera. Ninguno de los dos mira nunca el precio y siempre
    actúan igual: mientras que uno pide $15$ litros, el otro pide
    \money{20} de gasóleo. ¿Cuál es la elasticidad precio de la
    demanda de cada conductor?

    #+begin_answer

    #+end_answer

15. Ana paga \money{2} por cada unidad de alimentos, gasta \money{5000}
    en alimentos al año y su renta monetaria anual es de
    \money{25000}. En esta situación, la elasticidad-precio de su
    demanda anual de alimentos es $-1$ mientras que la
    elasticidad-renta es $-0.5$. ¿Cuál sería el consumo de alimentos de
    Ana si obtiene una beca de \money{1000} que puede gastar libremente
    en aquello que prefiera?

    #+begin_answer
      Dividiendo el gasto en alimentos por el precio obtenemos las
      unidades de alimentos que inicialmente compra Ana durante un año:
      \begin{equation*}
        Q = 5000 / 2 = \units{2500}
      \end{equation*}
      La elasticidad renta
      mide en qué porcentaje varía el consumo de alimentos por cada 1%
      de aumento de la renta:
      \begin{equation*}
        E_{d}^{M} = \frac{\Delta\,\% Q}{\Delta\,\% M} = -0.5
      \end{equation*}
      El incremento porcentual de la renta de Ana a causa de la beca es
      $\num{1000} / \num{25000} \times 100 = 4\%$.  Usando la
      elasticidad renta calculamos la variación del consumo de
      alimentos: $\Delta\,\% Q = E_{d}^{M} \times \Delta\,\% M = -0.5 \times 4
      = -2\%$. Por tanto, el consumo de alimentos de Ana disminuye un
      2% y será igual a $Q' = (1 - 0.02) \times 2500 = 2450$ unidades,
      lo que supone un gasto anual de \money{4900}.
    #+end_answer

16. El mercado del bien $X$ está caracterizado por las siguientes
    funciones de demanda y oferta:
    #+begin_export latex
    \begin{gather*}
      X = 250 - 30 P_{X} + 2 R - 5 P_{Y}, \\
      X = 24 P_{X} - 24,
    \end{gather*}
    #+end_export
    donde $R$ es la renta media de los consumidores y $P_Y$ el precio
    del bien $Y$. Actualmente $R = \money{100}$ y $P_Y = \price{5}$.

    a) Calcule el precio y la cantidad de equilibrio y represéntelo
       gráficamente.

       #+begin_answer

       #+end_answer

    b) Calcule la elasticidad cruzada de la demanda. ¿Qué tipo de
       relación existe entre los bienes $X$ e $Y$?

       #+begin_answer

       #+end_answer

    c) Si la renta media de los consumidores disminuye en \money{10},
       ¿se puede afirmar que $X$ es un bien inferior?

       #+begin_answer

       #+end_answer

17. La empresa que gestiona un túnel se está planteando alterar el
    peaje que cobra a los usuarios del túnel. Actualmente el peaje es
    de \money{6} y \num{2400} conductores utilizan el túnel
    diariamente. Una consultora ha estimado que la función $Q =
    \num{6000} - \num{600} P$ describe la demanda diaria del túnel.

    a) ¿Cuál es la elasticidad de la demanda al precio actual?

       #+begin_answer

       #+end_answer

    b) Si la empresa persigue aumentar sus ingresos, ¿sería conveniente
       que rebajase el peaje?

       #+begin_answer

       #+end_answer

    c) ¿Cuál es el peaje que maximizaría los ingresos de la empresa?

       #+begin_answer

       #+end_answer

18. La demanda de mercado de un bien es lineal y, al precio actual, la
    elasticidad precio es unitaria. ¿Aumentarán los ingresos totales
    de los vendedores si disminuye el precio del bien?

    #+begin_answer

    #+end_answer

19. Un club de fútbol dispone de un cupo máximo de \num{125000} socios.
    La demanda de abonos anuales de los aficionados es: \[Q =
    \num{125000} - 100 P +10 P_O + 10 M,\] donde:

    - $P$ es el precio del abono del club.

    - $P_O$ es el precio del abono del otro club con estadio en la
      misma ciudad

    - $M$ es la renta anual media de los aficionados.

    Este año el club rival ha anunciado un precio de sus abonos de $P_O
    = \money{600}$. Por otro lado, se estima que $M =  \money{15000}$.

    a) Represente gráficamente las curvas de demanda y de oferta de
       abonos y determine el equilibrio en este mercado.

       #+begin_answer

       #+end_answer

    b) Calcule las elasticidades de la demanda y de la oferta de abonos
       del club en la situación de equilibrio e interprete los valores
       y los signos de esas elasticidades.

       #+begin_answer

       #+end_answer

    c) Calcule la elasticidad de la demanda con respecto al precio del
       abono del equipo rival en la situación de equilibrio e
       interprete el valor y el signo obtenidos.

       #+begin_answer

       #+end_answer

    d) Calcule la elasticidad renta de la demanda en la situación de
       equilibrio e interprete el valor y el signo obtenidos.

       #+begin_answer

       #+end_answer

20. En el mercado del bien $X$ las curvas de demanda y de oferta son:
    \begin{gather*}
      X^d = \num{100000} - 20 P_X \\
      X^o = \num{40000} + 40 P_X
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

       #+begin_answer

       #+end_answer

    b) Describa y represente gráficamente los efectos sobre el mercado
       del bien $X$ del establecimiento de un impuesto sobre los
       vendedores de \money{150} por unidad vendida.

       #+begin_answer

       #+end_answer

    c) ¿Cuál habría sido el resultado si el impuesto hubiese recaído
       sobre los compradores?

       #+begin_answer

       #+end_answer

21. En el mercado del bien $X$ las curvas de demanda y de oferta son:
    \begin{gather*}
      X^d = \num{100000} - 25 P_X \\
      X^o = \num{50000} + 25 P_X
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

       #+begin_answer

       #+end_answer

    b) Describa y represente gráficamente los efectos sobre el mercado
       del bien $X$ del establecimiento de un precio mínimo de
       \price{1200}. ¿Cuántas unidades se venderían? ¿A qué precio?

       #+begin_answer

       #+end_answer

22. En un mercado competitivo en equilibrio se venden \num{96000}
    unidades a un precio de \price{300}. En esta situación la
    elasticidad precio de la demanda es $-1.5$ mientras que la
    elasticidad de la oferta es igual a $2$. Usando esta información
    estime el efecto que sobre la cantidad demandada y la cantidad
    ofrecida tendría una ley que establezca un precio máximo de
    \price{294}.

    #+begin_answer

    #+end_answer

23. Las curvas de demanda y oferta de mercado del bien $X$ son:
    \begin{gather*}
      X = 200 - 5 P_{X} + 3 P_{Y} + 2 R \\
      X = 100 + 2 P_{X}
    \end{gather*}
    donde $R$ es la renta media de los consumidores y $P_Y$ es el
    precio del bien $Y$, siendo $R = \money{100}$ y $P_Y =
    \price{5}$. Una ley prohíbe que el precio de $X$ supere
    los $\money{50}$.
    a) ¿Qué cantidad se venderá del bien $X$? ¿A qué
       precio? Represente gráficamente.

       #+begin_answer
         Obtenemos la curva de demanda sustituyendo $R = \money{100}$ y
         $P_Y = \price{5}$ en la función de demanda: \[ X = 200 - 5
         P_X + 3 \cdot 5 + 2 \cdot 100 = 415 - 5 P_X. \] Obtenemos el
         precio de equilibrio igualando oferta y demanda: \[ 415 - 5
         P_X^* = 100 + 2 P_X^* \] por lo que $P_X^* = \price{45}$ y $X^*
         = 190$ unidades. Dado que el precio máximo es superior al
         precio de equilibrio, nada impide que se alcance el equilibrio
         en este mercado.

         #+MATS: fig fig-probl-1_1004-eq1-*.pdf
       #+end_answer

    b) Si la renta media aumenta hasta $R = \money{170}$, calcule
       cuántas unidades de $X$ se venderán ahora y a qué
       precio. Represente gráficamente.

       #+begin_answer
         Cuando $R = \money{170}$ la función de demanda es: \[ X =
         200 - 5 P_X + 3 \cdot 5 + 2 \cdot 170 = 555 - 5 P_X. \] En
         esta ocasión igualando oferta y demanda se obtiene un precio
         de equilibrio igual a $P_X^* = \price{65}$. Puesto que éste es
         superior al precio máximo, el mercado no puede alcanzar el
         equilibrio. A un precio de $P_X = P_{X}^{\max} = \price{50}$
         se venderían todas las unidades ofrecidas, $X^o = 100 + 2\cdot
         50 = 200$, y se produciría una situación de escasez dado que
         la demanda sería mucho mayor: $X^d = 555 - 5 \cdot 50 =
         305$ unidades.

         #+MATS: fig fig-probl-1_1004-eq2-*.pdf
       #+end_answer

24. Razone la veracidad o falsedad de la siguiente afirmación: "Si se
    establece un precio máximo superior al precio de equilibrio, la
    cantidad comprada y la cantidad vendida coincidirá con el
    equilibrio en este mercado."

    #+begin_answer

    #+end_answer

25. El mercado de alquiler en una ciudad está representado por las
    curvas de demanda y de oferta:
    #+begin_export latex
    \begin{gather*}
      Q^{d} = \num{25000} - 30 P \\
      Q^{o} = \num{5000} +10 P
    \end{gather*}
    #+end_export

    a) Determine el equilibrio en este mercado.

       #+begin_answer

       #+end_answer

    b) Si se establece una subvención a cada inquilino de \money{200},
       ¿cuánto dinero pagarán los inquilinos? ¿Cuál será el alquiler
       que recibirán los caseros?

       #+begin_answer

       #+end_answer
