# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

#+TITLE: Exercise Booklet 5


* Production

1. Discuss the truth or fallacy of the following comments:

   a) If the marginal product is decreasing, the average product must
      also be decreasing.

   b) After hiring a worker, the manager of a factory discovers that
      the average product of labor has increased. Therefore, the
      manager assumes that the marginal product of the new worker is
      lower than the average output prior to hiring him.

   c) The marginal product of labor for a company is equal to the
      average product. If you were one of the workers to be hired by
      the company, you would prefer that your wage were equal to
      the marginal rather than average product.

2. Given the production function $Q = L^2K - L^3$ and knowing that $K =
   \units{4}$, determine:

   a) The total product of labor function.

   b) The average and marginal product of labor functions.

   c) The levels of labor that maximize the marginal product, the
      average product and the total product. Represent graphically the
      results.

3. Consider the following production functions:

   + $Q  = K^{1/4} L^{1/4}$

   + $Q  = (2KL)^{1/2}$

   + $Q  = 2K + 3L$

   + $Q  = K^2 L^2$

   For each case:

   a) Which type of returns to scale does the production function exhibit?

   b) Obtain the marginal rate of substitution between the production
      factors.

   c) Check if the law of diminishing returns to labor holds when
      $K=\units{4}$.
