# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 2


1. Un consumidor gasta su renta $M$ en los bienes $X$ e $Y$.

   a) ¿Como cambiaría su recta presupuestaria si se establece un
      impuesto sobre el consumo que eleva el precio de los bienes en
      un 25%?

      #+begin_answer
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
      # #+MATS: fig fig-probl-2_1004-budget1-*.pdf
      *Gráfico*
      #+end_minipage
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
        La recta presupuestaria después del impuesto al consumo es:
        \begin{equation*}
          M = 1.25 P_X X + 1.25 P_Y Y
        \end{equation*}
      #+end_minipage
      #+end_answer

   b) ¿Y si, en vez del impuesto al consumo, se establece un impuesto
      sobre la renta que reduce $M$ un 25%?

      #+begin_answer
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
      # #+MATS: fig fig-probl-2_1004-budget1-*.pdf
      *Gráfico*
      #+end_minipage
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
        La recta presupuestaria después del impuesto a la renta es:
        \begin{equation*}
          0.75 M = P_X X + P_Y Y
        \end{equation*}
      #+end_minipage
      #+end_answer

   c) ¿Cuál de las dos opciones preferirá el consumidor?

      #+begin_answer
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
      # #+MATS: fig fig-probl-2_1004-budget1-*.pdf
      *Gráfico*
      #+end_minipage
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
        La restricción del apartado /a/) puede escribirse como:
        \begin{equation*}
          0.8 M = P_X X + P_Y Y
        \end{equation*}
        El consumidor preferiría el impuesto al consumo.
      #+end_minipage
      #+end_answer

2. Un consumidor dispone de \money{20} para comprar carne y
   patatas. En el supermercado en el que suele hacer la compra, la
   carne se vende a \price[kg]{4} mientras que el kilo de patatas
   cuesta \money{2}.

   a) Obtenga y represente la restricción presupuestaria.

      #+begin_answer
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
      #+MATS: fig fig-probl-2_1004-budget1-*.pdf
      #+end_minipage
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
        La restricción presupuestaria original es:
        \begin{equation*}
          20 = 4 C + 2 P
        \end{equation*}
      #+end_minipage
      #+end_answer

   b) El supermercado introduce una oferta por la que regala
      \units[kg]{2} más de patatas a todo el que compre \units[kg]{4}
      o más. Obtenga y represente la restricción presupuestaria en
      este caso.

      #+begin_answer
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
      #+MATS: fig fig-probl-2_1004-budget2-*.pdf
      #+end_minipage
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
        Nueva restricción presupuestaria:
        \begin{equation*}
          C =
          \begin{cases}
            5 - P / 2 & \text{si $P < 4$} \\
            6 - P / 2 & \text{si $P \geq 6$}
          \end{cases}
        \end{equation*}
      #+end_minipage
      #+end_answer

3. A Amaia le gusta el pescado, mientras que el pollo ni le gusta ni
   le disgusta. Por su parte, a Alejandro no le gusta el pescado pero
   sí el pollo y sólo está dispuesto a comer algo de pescado si a
   cambio recibe una porción extra de pollo. Represente las
   preferencias de Amaia y de Alejandro.

   #+begin_answer
     #+attr_latex: :options {0.5\linewidth}
     #+begin_minipage
       #+latex: \begin{center}
       #+latex: \begin{minipage}{0.85\linewidth}
         Amaia: el pollo es neutral.
       #+latex: \end{minipage}
       #+latex: \end{center}
       # #+MATS: fig fig-probl-1_1004-medicines-*.pdf
       *Gráfico*
     #+end_minipage
     #+attr_latex: :options {0.5\linewidth}
     #+begin_minipage
       #+latex: \begin{center}
       #+latex: \begin{minipage}{0.95\linewidth}
        Alejandro: el pescado es un mal.
       #+latex: \end{minipage}
       #+latex: \end{center}
       # #+MATS: fig fig-probl-1_1004-computers-*.pdf
       *Gráfico*
     #+end_minipage
   #+end_answer

4. Las preferencias de un consumidor están representadas por la
   función de utilidad: $U(X, Y)= 5X Y^2$. La renta del consumidor es
   de \money{900} y los precios de los bienes $X$ e $Y$ son $P_X =
   \price{10}$ y $P_Y = \price{5}$. Calcule y represente la elección
   óptima del consumidor.

   #+begin_answer
     #+attr_latex: :options {0.5\linewidth}
     #+begin_minipage
     # #+MATS: fig fig-probl-2_1004-budget2-*.pdf
     *Gráfico*
     #+end_minipage
     #+attr_latex: :options {0.5\linewidth}
     #+begin_minipage
       Recta presupuestaria:
       #+begin_export latex
       \[
         900 = 10 X + 5 Y
       \]
       #+end_export

       Condición de tangencia:
       #+begin_export latex
       \[
         Y = 4 X
       \]
       #+end_export

       Cesta óptima:
       #+begin_export latex
       \[
         X^* = \units{30} \quad Y^* = \units{120}
       \]
       #+end_export
     #+end_minipage
   #+end_answer

5. La cesta óptima de un consumidor con preferencias regulares
   contiene cantidades positivas de todos los bienes. Si aumenta el
   precio de un bien, ¿se reducirá la utilidad del consumidor?
   Justifique su respuesta.

   #+begin_answer
     Con los nuevos precios no puede comprar la cesta inicial. Tiene
     que elegir una cesta que podría haber elegido con los precios
     iniciales pero no lo hizo: su utilidad es menor.
   #+end_answer

6. La función de utilidad de un consumidor es $U(X, Y) = X Y$. La
   cesta óptima está compuesta por 10 unidades del bien $X$ y 5
   unidades del bien $Y$. Sabiendo que el precio del bien $X$ es de
   \price{6}, ¿cuál es la renta del consumidor?

   #+begin_answer
     Solución interior: $\RMS = Y/X = 5 / 10$ es igual a $P_X / P_Y =
     6 / P_Y$. Por tanto, $P_Y = 12$. Finalmente, $M = \money{120}$.
   #+end_answer

7. Un consumidor posee una renta de \money{4} que gasta en los bienes
   $X$ e $Y$, cuyos precios son $P_X = \price{3}$ y $P_Y =
   \price{2}$. Cuando consume $2$ unidades de $Y$ y no consume nada de
   $X$, la relación marginal de sustitución es igual a $2$. ¿Es esta
   la elección óptima del consumidor o estaría mejor consumiendo más
   unidades de $X$ y menos de $Y$?

   #+begin_answer
     Cuando compra $X=0$ e $Y=2$, $\RMS = 2 > P_X/P_Y = 1.5$.  Su
     utilidad aumentaría si disminuye el consumo de $Y$ y aumenta el
     de $X$.
   #+end_answer

8. Las preferencias de un consumidor entre leche, $L$, y un bien
   compuesto, $Y$, que recoge las compras del consumidor en los
   restantes bienes, están representadas por la función de utilidad:
   $U(L, Y)= (L + 30) Y$. El precio de la leche es de $P_L =
   \price[l]{1}$ y la renta del consumidor es $M = \money{40}$.

   a) Obtenga y represente la elección óptima del consumidor.

      #+begin_answer
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
        # #+MATS: fig fig-probl-2_1004-budget2-*.pdf
        *Gráfico*
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          Recta presupuestaria:
          #+begin_export latex
          \[
            40 = L + Y
          \]
          #+end_export

          Condición de tangencia:
          #+begin_export latex
          \[
            Y = L + 30
          \]
          #+end_export

          Cesta óptima:
          #+begin_export latex
          \[
            L^* = \units[l]{5} \quad Y^* = \money{35}
          \]
          #+end_export
        #+end_minipage
      #+end_answer

   b) El Gobierno quiere fomentar el consumo de leche y está
      estudiando diferentes alternativas:

      + Una subvención que reduce un 20% el precio de los primeros 12
        litros de leche.

      + Entregar a cada consumidor un vale con el que puede obtener
        gratis 12 litros de leche.

      + Entregar a cada consumidor \money{12} en metálico.

      ¿Cuál sería la elección del consumidor en cada uno de estos
      casos?

      #+begin_answer
        * Subvención: $L^* = \units[l]{10} \quad Y^* = \money{32}$.
        * Donación: $L^* = \units[l]{12} \quad Y^* = \money{40}$.
        * Metálico: $L^* = \units[l]{11} \quad Y^* = \money{41}$.
      #+end_answer

   c) ¿Cuál de las opciones preferirá el consumidor? Razone su respuesta.

      #+begin_answer
        * Situación inicial: $U = 1225$.
        * Subvención: $U = 1280$.
        * Donación: $U = 1680$.
        * Metálico: $U = 1681$.
      #+end_answer

9. Un consumidor dispone de una renta de \money{800} para comprar los
   bienes $X$ e $Y$, cuyos precios son $P_X = \price{4}$ y $P_Y =
   \price{2}$. Sus preferencias pueden describirse con la función de
   utilidad:
   #+begin_export latex
   \[
     U(X, Y) = X^{0.25} Y^{0.75}
   \]
   #+end_export

   a) Obtenga la elección óptima del consumidor.

      #+begin_answer
        Restricción presupuestaria: $800 = 4 X + 2 Y$.

        Condición de tangencia: $Y = 6 X$

        Elección óptima: $X^* = \units{50}$; $Y^* = \units{300}$.
      #+end_answer

   b) ¿Cómo cambiaría la elección si el consumidor obtiene un
      descuento de \money{2} por cada unidad comprada del bien $X$ por
      encima de \num{75} unidades?

      #+begin_answer
        La restricción presupuestaria tiene dos tramos:
        #+begin_export latex
        \[
          Y =
          \begin{cases}
            400 - 2 X & \text{si $X < 75$} \\
            325 - X & \text{si $X \geq 75$}
          \end{cases}
        \]
        #+end_export

        Obtenemos la solución en cada uno de los tramos:

        #+ATTR_LATEX: :booktabs t :center t :align lrr
        |----------+-----------------------+-----------------------------|
        |          | $X < 75$              | $X > 75$                    |
        |----------+-----------------------+-----------------------------|
        | RP       | $800 = 4 X + 2 Y$     | $650 = 2X + 2Y$             |
        | CT       | $Y = 6 X$             | $Y = 3 X$                   |
        | Óptimo   | $X^* = 50, Y^* = 300$ | $X^* = 81.25, Y^* = 243.75$ |
        | Utilidad | $191.68$              | $185.21$                    |
        |----------+-----------------------+-----------------------------|
        Las dos soluciones cumplen las condiciones de óptimo interior,
        pero la utilidad que obtiene el consumidor es mayor eligiendo
        $X^* = 50$ e $Y^* = 300$: la elección no cambiaría.
      #+end_answer

10. Las preferencias de un consumidor pueden representarse por la
    función de utilidad: $U(X, Y) = X (Y + 100)$. El precio del bien
    $X$ es \price{1} y el del bien $Y$ es \price{4}. El consumidor
    dispone de una renta monetaria de \money{250}.

    a) Calcule la elección óptima de consumo.

       #+begin_answer
         Recta presupuestaria: $250 = X + 4 Y$.

         $\RMS = (Y + 100) / X$.

         Solución de esquina: $X^* = 250; Y^* = 0$.
       #+end_answer

    b) Si se raciona el bien $X$ de forma que no es posible consumir
       más de 100 unidades de $X$, ¿cuál sería la elección
       óptima?. Represente gráficamente.

       #+begin_answer
         #+attr_latex: :options {0.5\linewidth}
         #+begin_minipage
         # #+MATS: fig fig-probl-2_1004-budget1-*.pdf
         *Gráfico*
         #+end_minipage
         #+attr_latex: :options {0.5\linewidth}
         #+begin_minipage
           $X^* = 100; Y^* = 37.5$.
         #+end_minipage
       #+end_answer

11. La función de utilidad de un individuo respecto de los bienes $X$ e
    $Y$ viene dada por $U(X,Y) = 3X + 3Y$. Los precios de mercado son
    $P_X = \price{2}$ y $P_Y = \price{5}$ y la renta monetaria del
    consumidor es $M = \money{100}$.

    a) ¿Es $(X,Y) = (10, 40)$ una cesta óptima? ¿Por qué?

       #+begin_answer
         No, no tiene suficiente renta para comprarla.
       #+end_answer

    b) ¿Cuál es la elección óptima del consumidor?

       #+begin_answer
         $\RMS = 1 > P_X / P_Y = 0.4$. Solución de esquina: $X^* = 50;
         Y^* = 0$.
       #+end_answer

    c) ¿Cómo se vería modificada la elección del consumidor si $P_X =
       \price{10}$?

       #+begin_answer
         $\RMS = 1 < P_X / P_Y = 2$. Solución de esquina: $X^* = 0;
         Y^* = 20$.
       #+end_answer

12. Un consumidor /siempre/ está dispuesto a intercambiar 2 unidades del
    bien $Y$ por 1 unidad del bien $X$. El precio del bien $X$ es de
    $4$ €/unidad y el precio del bien $Y$ es de $3$ €/unidad. Con esta
    información, ¿es posible determinar cuantas unidades del bien $X$
    consumirá? ¿Y del bien $Y$? Razone la respuesta.

    #+begin_answer
      $\RMS = 2 > P_X / P_Y = 4/3$. El consumidor gastará toda su
      renta en $X$, $X^* = M/4$, y no consumirá ninguna unidad de $Y$,
      $Y^* = 0$.
    #+end_answer

13. A Rocío le gusta tomar leche con cereales. Para combinarlos
    utiliza siempre la misma proporción: por cada \units[ml]{250} de
    leche añade exactamente \units[g]{20} de cereales y desecha
    cualquier cantidad sobrante de leche o cereales.

    a) Represente las preferencias de Rocío con respecto a la leche y
       los cereales.

       #+begin_answer
         #+attr_latex: :options {0.5\linewidth}
         #+begin_minipage
         # #+MATS: fig fig-probl-2_1004-budget1-*.pdf
         *Gráfico*
         #+end_minipage
         #+attr_latex: :options {0.5\linewidth}
         #+begin_minipage
           Preferencias sobre $L$, litros de leche, y $C$, kg de cereales:
           #+begin_export latex
           \[
             U = \min\{L/0.250, C/0.020\}
           \]
           #+end_export
           Por tanto:
           #+begin_export latex
           \[
             U = \min\{4L, 50C\}
           \]
           #+end_export
         #+end_minipage
       #+end_answer

    a) Si Rocío gasta \money{6} al mes en leche y cereales, el precio
       de la leche es de \price[l]{0.80} y el de los cereales es de
       \price[kg]{2}, ¿cuál será su elección óptima?.
       #+begin_answer
         #+attr_latex: :options {0.5\linewidth}
         #+begin_minipage
         # #+MATS: fig fig-probl-2_1004-budget1-*.pdf
         *Gráfico*
         #+end_minipage
         #+attr_latex: :options {0.5\linewidth}
         #+begin_minipage
           Restricción presupuestaria:
           #+begin_export latex
           \[
             6 = 0.8 L + 2 C
           \]
           #+end_export
           Las combinaciones con las proporciones exactas cumplen:
           #+begin_export latex
           \[
             4L = 50C
           \]
           #+end_export
           Óptimo:
           #+begin_export latex
           \[
             L^* = \units[l]{6.250} \quad C^* = \units[kg]{0.500}
           \]
           #+end_export
         #+end_minipage

       #+end_answer
