# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 1


1. En una economía se producen dos bienes, automóviles y comida,
   usando trabajo como único factor de producción. Se dispone de un
   máximo de \num{50000} horas de trabajo. La siguiente tabla muestra
   las cantidades que pueden producirse dependiendo de las horas de
   trabajo que se dediquen a cada actividad:

   #+ATTR_LATEX: :booktabs t :center t :align rrp{1cm}rr
   |-------------+--------------+---+-------------+--------------|
   | Trabajo     | Automóviles  |   | Trabajo     | Comida       |
   | (horas)     | (unidades)   |   | (horas)     | (kg)         |
   |-------------+--------------+---+-------------+--------------|
   | \num{0}     | \num{0}      |   | \num{0}     | \num{0}      |
   | \num{12500} | \num{40000}  |   | \num{12500} | \num{50000}  |
   | \num{25000} | \num{70000}  |   | \num{25000} | \num{75000}  |
   | \num{37500} | \num{90000}  |   | \num{37500} | \num{90000}  |
   | \num{50000} | \num{100000} |   | \num{50000} | \num{100000} |
   |-------------+--------------+---+-------------+--------------|

   a) Represente gráficamente la Frontera de Posibilidades de
      Producción, FPP.

      #+begin_answer
        #+MATS: fig fig-probl-1_1004-ppf-sh1-*.pdf
      #+end_answer

   b) ¿Qué efecto tendría sobre la FPP una mejora en las técnicas de
      elaboración de comida que aumentara la producción por hora de
      trabajo? ¿Y una mejora organizativa en la cadena de producción
      de automóviles? ¿Y si ambas mejoras se produjesen
      simultáneamente como consecuencia de un progreso técnico
      generalizado en la sociedad?

      #+begin_answer
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-sh2-*.pdf

          #+latex: \begin{center}
          #+latex: \begin{minipage}{0.8\linewidth}
            Una mejora tecnológica en la producción de comida.
          #+latex: \end{minipage}
          #+latex: \end{center}
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-sh3-*.pdf

          #+latex: \begin{center}
          #+latex: \begin{minipage}{0.8\linewidth}
            Una mejora organizativa en la producción de automóviles.
          #+latex: \end{minipage}
          #+latex: \end{center}
        #+end_minipage

        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-sh4-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          Mejoras en los dos sectores.
        #+end_minipage
      #+end_answer

   c) ¿Qué consecuencias tendría sobre la FPP la reducción a la mitad
      de las horas de trabajo como consecuencia de un conflicto
      bélico?

      #+begin_answer
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-sh5-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          Desplazamiento a la izquierda de la FPP.
        #+end_minipage
      #+end_answer

2. La tabla adjunta presenta diferentes combinaciones eficientes de
   producción para una economía en la que únicamente se producen dos
   bienes: $X$ e $Y$.

   #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{>{\raggedleft\arraybackslash}p{2cm}}
   |-----+------------+------------|
   |     | $X$        | $Y$        |
   |-----+------------+------------|
   | *A* | \num{20}   | \num{0}    |
   | *B* | \num{18}   | \num{1}    |
   | *C* | \num{15}   | \num{2}    |
   | *D* | \num{11}   | \num{3}    |
   | *E* | \num{6}    | \num{4}    |
   | *F* | \num{0}    | \num{5}    |
   |-----+------------+------------|

   a) Represente la Frontera de Posibilidades de Producción, FPP. ¿Qué
      tiene de particular la forma de la FPP?

      #+begin_answer
        #+attr_latex: :options {0.6\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-oc1-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.4\linewidth}
        #+begin_minipage
          La FPP es cóncava.
        #+end_minipage
      #+end_answer

   b) ¿Se pueden producir \num{2} unidades de $Y$ y \num{10} unidades
      de $X$?  ¿Qué ocurre en esta situación?

      #+begin_answer
        #+attr_latex: :options {0.6\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-ppf-oc2-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.4\linewidth}
        #+begin_minipage
          La combinación es factible pero ineficiente.
        #+end_minipage
      #+end_answer

   c) Construya una tabla que refleje el coste de oportunidad de
      producir cada unidad del bien $Y$.

      #+begin_answer
        #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{r}*{3}{c}
        |-----+----------+---------+------------+------------+---------------------------|
        |     | $X$      | $Y$     | $\incr{X}$ | $\incr{Y}$ | $\abs{\incr{X}/\incr{Y}}$ |
        |-----+----------+---------+------------+------------+---------------------------|
        | *A* | \num{20} | \num{0} | ---        | ---        | ---                       |
        | *B* | \num{18} | \num{1} | \num{-2}   | \num{1}    | \num{2}                   |
        | *C* | \num{15} | \num{2} | \num{-3}   | \num{1}    | \num{3}                   |
        | *D* | \num{11} | \num{3} | \num{-4}   | \num{1}    | \num{4}                   |
        | *E* | \num{6}  | \num{4} | \num{-5}   | \num{1}    | \num{5}                   |
        | *F* | \num{0}  | \num{5} | \num{-6}   | \num{1}    | \num{6}                   |
        |-----+----------+---------+------------+------------+---------------------------|
      #+end_answer

   d) ¿A cuántas unidades de $X$ se debe renunciar para producir la
      primera unidad de $Y$? ¿Y la segunda?

      #+begin_answer
        Para poder producir la primera unidad de $Y$ hay que renunciar
        a $2$ unidades de $X$, mientras que el coste de oportunidad de
        la segunda es $3$ unidades de $X$.
      #+end_answer

3. El siguiente gráfico representa la frontera de posibilidades de
   producción de una economía donde sólo se producen cocos y pescado:

   #+MATS: fig fig-probl-1_1004-ppf-*.pdf

   Ordene las opciones de producción $A$, $B$, $C$ y $D$ de mayor a
   menor coste de oportunidad de producir pescado.

   #+begin_answer
     El coste de oportunidad sería mayor en $D$ que en $A$, ya que la
     pendiente es más pronunciada en $D$.  Combinaciones como $B$ no
     son eficientes y el coste de oportunidad es $0$. Puntos como
     el $C$ son inaccesibles y el coste de oportunidad no está
     definido.
   #+end_answer

4. Argumente la veracidad o falsedad de la siguiente afirmación:
   "Cuando un gran número de desempleados encuentra un puesto de
   trabajo, se produce un desplazamiento de la frontera de
   posibilidades de producción hacia la derecha."

   #+begin_answer
     La FPP no se desplaza ya que no hay más factores de producción
     que en la situación inicial. La economía se mueve de un punto
     ineficiente a otro, ambos situados debajo de la FPP.
   #+end_answer

5. El mercado de un bien está formado por tres compradores cuyas
   curvas de demanda son:

   #+ATTR_LATEX: :center t :align lc
   | Comprador 1: | $Q^d_1(P) = 1000 - 10 P$ |
   | Comprador 2: | $Q^d_2(P) = 600 - 2 P$   |
   | Comprador 3: | $Q^d_3(P) = 750 - 5 P$   |

   Determine la curva de demanda de mercado.

   #+begin_answer
   - Si $P \leq 100$ participan los 3 compradores:
     #+begin_export latex
     \[
       Q^d(P) = Q^d_1(P) + Q^d_2(P) + Q^d_3(P) = 2350 - 17 P
     \]
     #+end_export

   - Si $100 < P \leq 150$ compran 2 y 3:
     #+begin_export latex
     \[
       Q^d(P) = Q^d_2(P) + Q^d_3(P) = 1350 - 7 P
     \]
     #+end_export

   - Si $150 < P \leq 300$ sólo compra 2:
     #+begin_export latex
     \[
       Q^d(P) = Q^d_2(P) = 600 - 2 P
     \]
     #+end_export

   #+attr_latex: :options {0.45\linewidth}
   #+begin_minipage
     #+MATS: fig fig-probl-1_1004-market-demand-*.pdf
   #+end_minipage
   #+attr_latex: :options {0.55\linewidth}
   #+begin_minipage
     #+begin_export latex
     \[
       Q^d(P) =
       \begin{cases}
         600 - 2 P   & \text{si $150 < P \leq 300$} \\
         1350 - 7 P  & \text{si $100 < P \leq 150$} \\
         2350 - 17 P & \text{si $P \leq 100$} \\
       \end{cases}
     \]
     #+end_export

   #+end_minipage
   #+end_answer

6. En el mercado de un bien participan \num{1000} compradores
   idénticos, cada uno de ellos con curva de demanda:
   #+begin_export latex
   \[
     Q^d_i(P) = 5 - P, \qquad i = 1, ..., \num{1000}.
   \]
   #+end_export
   El bien es vendido por \num{625} empresas idénticas, cada una
   con curva de oferta:
   #+begin_export latex
   \[
     Q^o_j(P) = 2.4 P , \qquad j = 1, ..., \num{625}.
   \]
   #+end_export

   a) Halle las curvas de demanda y oferta de mercado y la
      solución de equilibrio. Represente gráficamente.

      #+begin_answer
        Demanda y oferta de mercado:
        #+begin_export latex
        \begin{gather*}
          Q^d(P) = \sum_{i=1}^{1000} Q^d_i(P) = 5000 - 1000 P \\
          Q^o(P) = \sum_{i=1}^{625} Q^o_i(P) = 1500 P
        \end{gather*}
        #+end_export

        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
          #+MATS: fig fig-probl-1_1004-market-eq-*.pdf
        #+end_minipage
        #+attr_latex: :options {0.5\linewidth}
        #+begin_minipage
        - Equilibrio:
          #+begin_export latex
          \[
            P^* = \price{2}; \quad Q^* = \units{3000}.
          \]
          #+end_export
        #+end_minipage
      #+end_answer

   b) ¿Qué ocurriría si el precio de mercado fuera \price{4}? ¿Y si
      el precio de mercado fuera \price{1}?

      #+begin_answer
      Si el precio de mercado es $P = \price{4}$ se produce un exceso
      de oferta de \units{5000}.

      Si el precio de mercado es $P = \price{1}$ se produce un exceso
      de demanda de \units{2500}.
      #+end_answer

7. "Durante los años que van desde 2003 hasta 2006 el precio de la
   gasolina aumentó considerablemente y, sin embargo, el consumo de
   gasolina creció." ¿Contradice esta afirmación la ley de la demanda?

   #+begin_answer
     No: la ley de la demanda sólo es válida cuando lo único que
     cambia es el precio. A lo largo del periodo 2003--2006 cambiaron
     también otros determinantes de la demanda de gasolina.
   #+end_answer

8. Considere un mercado competitivo de manzanas y use un diagrama de
   oferta y demanda para analizar cómo afectaría al equilibrio una
   enfermedad de los manzanos que perjudique a la cosecha. ¿Es posible
   que los ingresos de los agricultores aumenten en este caso? ¿Qué
   condiciones se tendrían que cumplir?

   #+begin_answer
     #+attr_latex: :options {0.5\linewidth}
     #+begin_minipage
       #+MATS: fig fig-probl-1_1004-apples-*.pdf
     #+end_minipage
     #+attr_latex: :options {0.5\linewidth}
     #+begin_minipage
       Una enfermedad de los manzanos reducirá la oferta de
       manzanas. Como consecuencia se venden menos manzanas a un
       precio superior.
     #+end_minipage

     Los ingresos de los productores solo crecerán si disminuye la
     producción en una proporción menor a la que aumenta el precio: el
     mercado se encontraría en un /tramo inelástico de la curva de
     demanda/.
   #+end_answer

9. Ante el aumento del consumo de drogas en un país, los expertos han
   señalado dos posibles explicaciones alternativas:

   - Una presencia policial cada vez más reducida en las calles ha
     facilitado el tráfico de drogas.

   - La reducción de programas de educación y de apoyo a los adictos
     han reducido la concienciación de una parte de la sociedad acerca
     de los peligros de las drogas.

   Utilice diagramas de oferta y demanda para analizar cada una de
   esas hipótesis. ¿Es posible discriminar entre esas dos
   explicaciones observando qué ha ocurrido con el precio y la
   cantidad consumida de drogas?

   #+begin_answer
     #+attr_latex: :options {0.55\linewidth}
     #+begin_minipage
       #+MATS: fig fig-probl-1_1004-drugs1-*.pdf
     #+end_minipage
     #+attr_latex: :options {0.45\linewidth}
     #+begin_minipage
       La falta de presencia policial aumenta la oferta de drogas en
       las calles.
     #+end_minipage

     #+attr_latex: :options {0.55\linewidth}
     #+begin_minipage
       #+MATS: fig fig-probl-1_1004-drugs2-*.pdf
     #+end_minipage
     #+attr_latex: :options {0.45\linewidth}
     #+begin_minipage
       La reducción de programas de concienciación aumenta la demanda
       de drogas.
     #+end_minipage

     En los dos casos aumenta la cantidad consumida, pero en el primer
     escenario disminuye el precio y en el segundo aumenta el precio.
   #+end_answer

10. Las medicinas tienen una demanda inelástica mientras que los
    ordenadores tienen una demanda elástica. Suponga que como
    consecuencia del progreso tecnológico la oferta de ambos productos
    se duplica.
    #+latex: \ClearPage

    a) ¿Qué ocurrirá con el equilibrio en cada uno de estos mercados?
       Represente gráficamente.

       #+begin_answer
         #+attr_latex: :options {0.6\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-medicines-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.4\linewidth}
         #+begin_minipage
           Demanda inelástica.
         #+end_minipage

         #+attr_latex: :options {0.6\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-computers-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.4\linewidth}
         #+begin_minipage
           Demanda elástica.
         #+end_minipage

         En los dos casos aumenta la cantidad de equilibrio y
         disminuye el precio.
       #+end_answer

    b) ¿En qué mercado se experimentará el mayor cambio en el precio?
       ¿Y el mayor cambio en la cantidad?

       #+begin_answer
         En el mercado con la demanda más elástica se ve más afectada
         la cantidad. En el mercado con demanda menos elástica se ve
         más afectado el precio.
       #+end_answer
       #+latex: \ClearPage

    c) ¿Cómo se verá afectado el gasto de los consumidores en cada
       bien?

       #+begin_answer
         Cuando se reduce el precio en el mercado con demanda
         inelástica disminuye el gasto de los consumidores. En el
         mercado con demanda elástica, el precio y el gasto de los
         consumidores se mueven en direcciones opuestas.
       #+end_answer

11. En el mercado del bien $X$ las curvas de demanda y de oferta son:
    \begin{gather*}
      X^d = \num{85000} - 20 P_X \\
      X^o = \num{15000} + 15 P_X
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

       #+begin_answer
         #+attr_latex: :options {0.65\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-comp1-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.35\linewidth}
         #+begin_minipage
           Equilibrio:
           #+begin_export latex
           \begin{gather*}
             P^* = \price{2500} \\
             Q^* = \units{45000}
           \end{gather*}
           #+end_export
         #+end_minipage
       #+end_answer

    b) Represente gráficamente los efectos sobre el equilibrio de un
       aumento del precio de un bien sustitutivo, /ceteris
       paribus/. ¿Es posible predecir inequívocamente cómo cambiará el
       precio de equilibrio del bien $X$? ¿Y la cantidad de equilibrio?

       #+begin_answer
         #+attr_latex: :options {0.55\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-comp2-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.45\linewidth}
         #+begin_minipage
           Como consecuencia del aumento de la demanda, el precio y la
           cantidad de equilibrio aumentan.
         #+end_minipage
       #+end_answer

    c) Partiendo de la situación inicial, represente los efectos sobre
       el equilibrio de un aumento de la renta de los consumidores,
       /ceteris paribus/. ¿Es posible predecir inequívocamente cómo
       cambiarán el precio y la cantidad de equilibrio?

       #+begin_answer
         #+attr_latex: :options {0.55\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-comp2-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.45\linewidth}
         #+begin_minipage
           En el caso de un bien normal la demanda aumenta y el precio y la
           cantidad de equilibrio aumentan.
         #+end_minipage

         #+attr_latex: :options {0.55\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-comp3-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.45\linewidth}
         #+begin_minipage
           En el caso de un bien inferior la demanda disminuye y el
           precio y la cantidad de equilibrio se reducen.
         #+end_minipage
       #+end_answer

12. El mercado de coches eléctricos de un país es competitivo y
    actualmente las curvas de demanda y oferta son:
    #+begin_export latex
    \begin{gather*}
      Q^{d} = \num{10000} - P/6 \\
      Q^{o} = -6000 + P/2
    \end{gather*}
    #+end_export
    a) Determine el precio y la cantidad de equilibrio.

       #+begin_answer
         #+attr_latex: :options {0.65\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-cars1-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.35\linewidth}
         #+begin_minipage
           Equilibrio:
           #+begin_export latex
           \begin{gather*}
             P^* = \price{24000} \\
             Q^* = \units{6000}
           \end{gather*}
           #+end_export
         #+end_minipage
       #+end_answer
       #+latex: \ClearPage

    b) Calcule el nuevo equilibrio si la demanda aumenta en un 20%
       (para cada precio se demanda una cantidad un 20% superior) y la
       oferta pasa a ser:
       #+begin_export latex
       \[
         Q^o = -2700 + P/2
       \]
       #+end_export
       Represente gráficamente.

       #+begin_answer
         La nueva curva de demanda es:
         #+begin_export latex
         \[
           Q^d = \num{12000} - P/5
         \]
         #+end_export
         #+attr_latex: :options {0.65\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-cars2-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.35\linewidth}
         #+begin_minipage
           Equilibrio:
           #+begin_export latex
           \begin{gather*}
             P^* = \price{21000} \\
             Q^* = \units{7800}
           \end{gather*}
           #+end_export
         #+end_minipage
       #+end_answer

13. El mercado de un bien inferior se encuentra en equilibrio. Si
    simultáneamente se encarecen los costes de producción y aumenta la
    renta de los consumidores, ¿disminuirán tanto el precio como la
    cantidad en el nuevo equilibrio?

    #+begin_answer
      #+attr_latex: :options {0.55\linewidth}
      #+begin_minipage
        #+MATS: fig fig-probl-1_1004-inferior1-*.pdf
      #+end_minipage
      #+attr_latex: :options {0.45\linewidth}
      #+begin_minipage
        La cantidad de equilibrio disminuye. El precio baja si el
        cambio en la oferta es relativamente menor que el cambio en la
        demanda.
      #+end_minipage

      #+attr_latex: :options {0.55\linewidth}
      #+begin_minipage
        #+MATS: fig fig-probl-1_1004-inferior2-*.pdf
      #+end_minipage
      #+attr_latex: :options {0.45\linewidth}
      #+begin_minipage
        La cantidad de equilibrio disminuye. El precio sube si el
        cambio en la oferta es relativamente mayor que el cambio en la
        demanda.
      #+end_minipage
    #+end_answer

14. Cuando un país subió los impuestos sobre el tabaco, el precio
    medio de la cajetilla subió de \money{4} a \money{4.6}. Se estimó
    que como consecuencia de esta subida de precio la cantidad
    demandada cayó de $52$ a $47.5$ millones de cajetillas.  Calcule
    la elasticidad de la demanda de tabaco.

    #+begin_answer
      Utilizamos la fórmula del punto medio:
      #+begin_export latex
      \[
        E_d = \iratio{Q^d}{P} \frac{P_m}{Q^d_m}
      \]
      #+end_export
      La pendiente de la curva de demanda es:
      #+begin_export latex
      \[
        \iratio{Q^d}{P} = \frac{47.5 - 52}{4.6 - 4} = -7.5
      \]
      #+end_export
      El precio y la cantidad medios son:
      #+begin_export latex
      \[
        Q^d_m = (52 + 47.5)/2 = 49.75; \qquad
        P_m = (4 + 4.6)/2 = 4.3.
      \]
      #+end_export
      La elasticidad es:
      #+begin_export latex
      \[
        E_d = -7.5 \cdot 4.3/ 49.75 \approx -0.65
      \]
      #+end_export
    #+end_answer

15. Dos conductores repostan todos los lunes en la misma
    gasolinera. Ninguno de los dos mira nunca el precio y siempre
    actúan igual: mientras que uno pide $15$ litros, el otro pide
    \money{20} de gasóleo. ¿Cuál es la elasticidad precio de la
    demanda de cada conductor?

    #+begin_answer
      El primer consumidor siempre demanda la misma cantidad: su
      demanda, $Q^d = 15$, es perfectamente inelástica, $E_d = 0$.

      El segundo siempre gasta lo mismo: su curva de demanda, $Q^d =
      20 / P$, tiene elasticidad unitaria, $E_d = -1$.
    #+end_answer

16. Ana paga \money{2} por cada unidad de alimentos, gasta \money{5000}
    en alimentos al año y su renta monetaria anual es de
    \money{25000}. En esta situación, la elasticidad-precio de su
    demanda anual de alimentos es $-1$ mientras que la
    elasticidad-renta es $0.5$. ¿Cuál sería el consumo de alimentos de
    Ana si obtiene una beca de \money{1000} que puede gastar libremente
    en aquello que prefiera?

    #+begin_answer
      Las unidades de alimentos que inicialmente compra Ana durante un
      año son: $Q = 5000 / 2 = \units{2500}$.

      El incremento porcentual de la renta de Ana a causa de la beca es:
      $\incrpct{M} = \num{1000} / \num{25000} \times 100 = 4\%$.

      Usando la elasticidad renta
      #+begin_export latex
      \[
        E_{d}^{M} = \ipctratio{Q^d}{M} = 0.5
      \]
      #+end_export
      calculamos la variación del consumo de
      alimentos:
      #+begin_export latex
      \[
        \incrpct{Q} = E_{d}^{M} \times \incrpct{M} = 0.5 \times 4= 2\%
      \]
      #+end_export
      Por tanto, el consumo de alimentos de Ana aumenta un 2% y será
      igual a $Q' = (1 + 0.02) \times 2500 = 2550$ unidades, lo que
      supone un gasto anual de \money{5100}.
    #+end_answer

17. El mercado del bien $X$ está caracterizado por las siguientes
    funciones de demanda y oferta:
    #+begin_export latex
    \begin{gather*}
      X^d = 250 - 30 P_{X} + 2 R - 5 P_{Y}, \\
      X^o = 15 P_{X} - 25,
    \end{gather*}
    #+end_export
    donde $R$ es la renta media de los consumidores y $P_Y$ el precio
    del bien $Y$. Actualmente $R = \money{100}$ y $P_Y = \price{5}$.

    a) Calcule el precio y la cantidad de equilibrio y represéntelo
       gráficamente. Calcule las elasticidades precio de la demanda y
       de la oferta en el equilibrio.

       #+begin_answer

         #+attr_latex: :options {0.55\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-eq-elast-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.45\linewidth}
         #+begin_minipage
           Curva de demanda:
           #+begin_export latex
           \[
             X^d = 425 - 30 P
           \]
           #+end_export

           Equilibrio:
           #+begin_export latex
           \begin{gather*}
             P^* = \price{10} \\
             Q^* = \units{125}
           \end{gather*}
           #+end_export
         #+end_minipage

         Elasticidad precio de la demanda:
         #+begin_export latex
         \[
           E_d = \frac{\diff X^d}{\diff P_X} \frac{P_X}{X^d} =
           -30 \cdot\frac{10}{125} = -2.4
         \]
         #+end_export
         Elasticidad precio de la oferta:
         #+begin_export latex
         \[
           E_o = \frac{\diff X^o}{\diff P_X} \frac{P_X}{X^o} =
           15 \cdot\frac{10}{125} = 1.2
         \]
         #+end_export
       #+end_answer

    b) Calcule la elasticidad cruzada de la demanda. ¿Qué tipo de
       relación existe entre los bienes $X$ e $Y$?

       #+begin_answer
         Elasticidad cruzada de la demanda:
         #+begin_export latex
         \[
           E_d^{P_Y} = \frac{\diff X^d}{\diff P_Y} \frac{P_Y}{X^d} =
           -5 \cdot\frac{5}{125} = -0.2
         \]
         #+end_export
         El bien $Y$ es complementario del bien $X$.
       #+end_answer

    c) Si la renta media de los consumidores disminuye en \money{10},
       ¿se puede afirmar que $X$ es un bien inferior?

       #+begin_answer
         Elasticidad renta de la demanda:
         #+begin_export latex
         \[
           E_d^{R} = \frac{\diff X^d}{\diff R} \frac{R}{X^d} =
           2 \cdot\frac{100}{125} = 1.6
         \]
         #+end_export
         $X$ es un bien normal.
       #+end_answer

18. La empresa que gestiona un túnel se está planteando alterar el
    peaje que cobra a los usuarios del túnel. Actualmente el peaje es
    de \money{6} y \num{2400} conductores utilizan el túnel
    diariamente. Una consultora ha estimado que la función $Q =
    \num{6000} - \num{600} P$ describe la demanda diaria del túnel.

    a) ¿Cuál es la elasticidad de la demanda al precio actual?

       #+begin_answer
         #+begin_export latex
         \[
           E_d = \frac{\diff Q}{\diff P} \frac{P}{Q} =
           -600 \cdot\frac{6}{2400} = -1.5
         \]
         #+end_export
       #+end_answer

    b) Si la empresa persigue aumentar sus ingresos, ¿sería conveniente
       que rebajase el peaje?

       #+begin_answer
         Sí: se encuentra en un tramo elástico de la demanda por lo
         que la relación entre precio e ingresos es negativa.
       #+end_answer

    c) ¿Cuál es el peaje que maximizaría los ingresos de la empresa?
       ¿Cuál es la elasticidad de la demanda en este caso?

       #+begin_answer
         Obtenemos los ingresos multiplicado la demanda por el precio:
         #+begin_export latex
         \[
           I = P Q = P (6000 - 600 P) = 6000 P - 600 P^2
         \]
         #+end_export

         Derivamos los ingresos con respecto a $P$:
         #+begin_export latex
         \[
           \frac{\diff I}{\diff P} = 6000 - 1200 P
         \]
         #+end_export
         Igualando la expresión anterior a 0 y despejando obtenemos
         $P^* = \price{5}$. El túnel lo usarían $3000$ viajeros y la
         empresa obtendría unos ingresos de \money{15000}.

         La elasticidad de la demanda es:
         #+begin_export latex
         \[
           E_d = \frac{\diff Q}{\diff P} \frac{P}{Q} =
           -600 \cdot\frac{5}{3000} = -1
         \]
         #+end_export
       #+end_answer

19. Un club de fútbol dispone de un cupo máximo de \num{125000} socios.
    La demanda de abonos anuales de los aficionados es:
    #+begin_export latex
    \[
      Q^d = \num{125000} - 100 P +10 P_O + 10 M,
    \]
    #+end_export
    donde:

    - $P$ es el precio del abono del club.

    - $P_O$ es el precio del abono del otro club con estadio en la
      misma ciudad

    - $M$ es la renta anual media de los aficionados.

    Este año el club rival ha anunciado un precio de sus abonos de $P_O
    = \money{600}$. Por otro lado, se estima que $M =  \money{15000}$.

    a) Represente gráficamente las curvas de demanda y de oferta de
       abonos y determine el equilibrio en este mercado.

       #+begin_answer
         #+attr_latex: :options {0.63\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-football-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.37\linewidth}
         #+begin_minipage
           Curva de demanda:
           #+begin_export latex
           \[
             Q^d = \num{281000} - 100 P
           \]
           #+end_export

           Curva de oferta:
           #+begin_export latex
           \[
             Q^o = \num{125000}
           \]
           #+end_export

           Equilibrio:
           #+begin_export latex
           \begin{gather*}
             P^* = \price{1560} \\
             Q^* = \units{125000}
           \end{gather*}
           #+end_export
         #+end_minipage
       #+end_answer

    b) Calcule las elasticidades de la demanda y de la oferta de abonos
       del club en la situación de equilibrio e interprete los valores
       de esas elasticidades.

       #+begin_answer
         Elasticidad precio de la demanda:
         #+begin_export latex
         \[
           E_d = \frac{\diff Q^d}{\diff P} \frac{P}{Q^d} =
           -100 \cdot\frac{1560}{\num{125000}} = -1.248
         \]
         #+end_export
         Elasticidad precio de la oferta:
         #+begin_export latex
         \[
           E_o = \frac{\diff Q^o}{\diff P} \frac{P}{Q^o} =
           0 \cdot\frac{1560}{\num{125000}} = 0
         \]
         #+end_export

         En el punto de equilibrio la demanda es elástica. La oferta
         es perfectamente inelástica.
       #+end_answer

    c) Calcule la elasticidad de la demanda con respecto al precio del
       abono del equipo rival en la situación de equilibrio e
       interprete el valor obtenido.

       #+begin_answer
         Elasticidad cruzada de la demanda:
         #+begin_export latex
         \[
           E_d^{P_O} = \frac{\diff Q^d}{\diff P_O} \frac{P_O}{Q^d} =
           10 \cdot\frac{600}{\num{125000}} = 0.048
         \]
         #+end_export
         Los abonos de los dos equipos son débilmente sustitutivos.
       #+end_answer

    d) Calcule la elasticidad renta de la demanda en la situación de
       equilibrio e interprete el valor obtenido.

       #+begin_answer
         Elasticidad renta de la demanda:
         #+begin_export latex
         \[
           E_d^{M} = \frac{\diff Q^d}{\diff M} \frac{M}{Q^d} =
           10 \cdot\frac{\num{15000}}{\num{125000}} = 1.2
         \]
         #+end_export
         Los abonos son un bien de lujo.
       #+end_answer

20. En el mercado de un bien las curvas de demanda y de oferta son:
    \begin{gather*}
      Q^d = \num{100000} - 20 P \\
      Q^o = \num{40000} + 40 P
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

       #+begin_answer
         #+attr_latex: :options {0.63\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-before-tax-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.37\linewidth}
         #+begin_minipage
           Equilibrio:
           #+begin_export latex
           \begin{gather*}
             P^* = \price{1000} \\
             Q^* = \units{80000}
           \end{gather*}
           #+end_export
         #+end_minipage
       #+end_answer

    b) Describa y represente gráficamente los efectos sobre el mercado
       del bien $X$ del establecimiento de un impuesto sobre los
       vendedores de \money{150} por unidad vendida. ¿Cuánto pagarán
       los compradores por cada unidad? ¿Cuánto ingresarán los
       vendedores?

       #+begin_answer
         #+attr_latex: :options {0.63\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-tax-sellers-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.37\linewidth}
         #+begin_minipage
           Curva de oferta:
           #+begin_export latex
           \[
             Q^o = \num{34000} + 40 P
           \]
           #+end_export

           Equilibrio:
           #+begin_export latex
           \begin{gather*}
             P^* = \price{1100} \\
             Q^* = \units{78000}
           \end{gather*}
           #+end_export
         #+end_minipage

         Los compradores pagan \money{1000} por unidad; \money{100}
         más que antes de impuestos. Una vez descontados los
         impuestos, los vendedores ingresan \money{950} por unidad;
         \money{50} menos que antes de impuestos.
       #+end_answer

    c) ¿Cuál habría sido el resultado si el impuesto hubiese recaído
       sobre los compradores?

       #+begin_answer
         #+attr_latex: :options {0.63\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-tax-buyers-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.37\linewidth}
         #+begin_minipage
           Curva de demanda:
           #+begin_export latex
           \[
             Q^d = \num{97000} - 20 P
           \]
           #+end_export

           Equilibrio:
           #+begin_export latex
           \begin{gather*}
             P^* = \price{950} \\
             Q^* = \units{78000}
           \end{gather*}
           #+end_export
         #+end_minipage

         El resultado es idéntico al apartado anterior. Los vendedores
         cobran \money{950} por unidad. Los compradores pagan el
         precio más el impuesto: un total de \money{1100} por unidad.
       #+end_answer

21. En el mercado del bien $X$ las curvas de demanda y de oferta son:
    \begin{gather*}
      X^d = 100 - P_X / 40 \\
      X^o = 50 + P_X / 40
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

       #+begin_answer
         En equilibrio, $P_X^* = \price{1000}$ y $X^* = \units{75}$.
       #+end_answer

    b) Describa y represente gráficamente los efectos sobre el mercado
       del bien $X$ del establecimiento de un precio mínimo de
       \price{1200}. ¿Cuántas unidades se venderían? ¿A qué precio?

       #+begin_answer
         #+attr_latex: :options {0.6\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-min-price-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.4\linewidth}
         #+begin_minipage
           El precio mínimo está por encima del de equilibrio, por lo
           que se venden 70 unidades a \price{1200} y hay un exceso de
           oferta de 10 unidades.
         #+end_minipage
       #+end_answer

22. En un mercado competitivo en equilibrio se venden \num{96000}
    unidades a un precio de \price{300}. En esta situación la
    elasticidad precio de la demanda es $-1.5$ mientras que la
    elasticidad de la oferta es igual a $2$. Usando esta información
    estime el efecto que tendría una ley que establezca un precio
    máximo de \price{294}.

    #+begin_answer
      La regulación implica una caída del precio $\incrpct{P} =
      -6/300\times100 = 2\%$. De acuerdo con las elasticidades
      proporcionadas:
      #+begin_export latex
      \begin{gather*}
        \incrpct{Q^{d}} = -1.5 \times (-2\%) = 3\% \\
        \incrpct{Q^{o}} = 2 \times (-2\%) = -4\%
      \end{gather*}
      #+end_export
      Por lo que se produce un exceso de demanda de un 7% con respecto
      a la cantidad inicial: se produce una escasez de unas 6720
      unidades.
    #+end_answer

23. Las curvas de demanda y oferta de mercado del bien $X$ son:
    \begin{gather*}
      X = 200 - 5 P_{X} + 3 P_{Y} + 2 R \\
      X = 100 + 2 P_{X}
    \end{gather*}
    donde $R$ es la renta media de los consumidores y $P_Y$ es el
    precio del bien $Y$, siendo $R = \money{100}$ y $P_Y =
    \price{5}$. Una ley prohíbe que el precio de $X$ supere
    los $\money{50}$.
    a) ¿Qué cantidad se venderá del bien $X$? ¿A qué
       precio? Represente gráficamente.

       #+begin_answer
         Igualando oferta y demanda: $P_X^* = \price{45}$ y $X^* = 190$
         unidades. Dado que el precio máximo es superior al precio de
         equilibrio, nada impide que se alcance el equilibrio en este
         mercado.

         #+MATS: fig fig-probl-1_1004-eq1-*.pdf
       #+end_answer

    b) Si la renta media aumenta hasta $R = \money{170}$, calcule
       cuántas unidades de $X$ se venderán ahora y a qué
       precio. Represente gráficamente.

       #+begin_answer
         Igualando la oferta y la nueva demanda se obtiene un precio
         de equilibrio igual a $P_X^* = \price{65}$. Puesto que éste
         es superior al precio máximo, el mercado no puede alcanzar el
         equilibrio. Al precio $P_X = P_{X}^{\max} = \price{50}$ se
         venderían todas las unidades ofrecidas, $X^o(50) = 200$, y se
         produciría una situación de escasez dado que la demanda sería
         mucho mayor: $X^d(50) = 305$ unidades.

         #+MATS: fig fig-probl-1_1004-eq2-*.pdf
       #+end_answer

24. Razone la veracidad o falsedad de la siguiente afirmación: "Si se
    establece un precio máximo superior al precio de equilibrio, la
    cantidad comprada y la cantidad vendida coincidirá con el
    equilibrio en este mercado."

    #+begin_answer
      Un precio máximo superior al de equilibrio no impide al mercado
      que se ajuste por lo que la afirmación es verdadera.
    #+end_answer

25. El mercado de alquiler en una ciudad está representado por las
    curvas de demanda y de oferta:
    #+begin_export latex
    \begin{gather*}
      Q^{d} = \num{25000} - 30 P \\
      Q^{o} = \num{5000} +10 P
    \end{gather*}
    #+end_export

    a) Determine el equilibrio en este mercado.

       #+begin_answer
         #+attr_latex: :options {0.55\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-subsidy1-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.45\linewidth}
         #+begin_minipage
           En equilibrio, $P^* = \price{500}$ y $Q^* = \units{10000}$.
         #+end_minipage
       #+end_answer

    b) Si se establece una subvención a cada inquilino de \money{200},
       ¿cuánto dinero pagarán los inquilinos? ¿Cuál será el alquiler
       que recibirán los caseros?

       #+begin_answer
         #+attr_latex: :options {0.55\linewidth}
         #+begin_minipage
           #+MATS: fig fig-probl-1_1004-subsidy2-*.pdf
         #+end_minipage
         #+attr_latex: :options {0.45\linewidth}
         #+begin_minipage
           Los caseros reciben \money{650} y los inquilinos pagan
           \money{450} por casa alquilada. El coste total del programa
           de subvenciones asciende a $200 \times 11500 =
           \money{2300000}$.
         #+end_minipage
       #+end_answer
