#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 4


* La elección intertemporal

1. Un consumidor tiene unas preferencias con respecto a su consumo
   presente, $C_1$, y su consumo futuro, $C_2$, que vienen
   representadas por la función de utilidad $U(C_1, C_2) = C_1
   C_2$. La renta que obtiene el consumidor en cada uno de los
   periodos es $M_1 = \money{1000}$ y $M_2 = \money{1500}$. El tipo
   de interés es $r = 0.5$.

   a) Escriba la restricción presupuestaria intertemporal de este
      individuo en valor futuro.

   b) Determine si el individuo ahorra o no, así como el nivel de
      consumo en cada periodo.

   c) Suponga ahora que el consumidor considera ambos bienes como
      complementos perfectos y su función de utilidad es: $U(C_1, C_2)
      = \min\{C_1, C_2\}$. Obtenga el perfil de consumo intertemporal
      óptimo en este caso.

2. Las preferencias entre el consumo presente, $C_1$, y consumo
   futuro, $C_2$, de un individuo están representadas por la función
   de utilidad: $U(C_1, C_2)= C_1^2 C_2$.  En el primer periodo el
   individuo tiene una renta de \money{200}, mientras que en el
   segundo periodo obtiene una renta de \money{220}. El tipo de
   interés al que se presta dinero es del 5%, y el tipo de interés al
   se pide prestado es del 10%.

   a) Exprese analíticamente la restricción presupuestaria del
      individuo y represéntela gráficamente.

   b) Calcule el equilibrio del consumidor y determine si será
      prestamista o prestatario.

   c) Si el Banco Central Europeo fija un tipo de interés único del 8%
      tanto para prestar como para pedir prestado, calcule el nuevo
      equilibrio y determine si el consumidor mejora o empeora en
      términos de bienestar.

3. Un consumidor vive dos periodos y sus preferencias vienen
   representadas por: \[ U = C_1^3 C_2.\] Su elección óptima es $C_1 =
   \money{9750}$ y $C_2 = \money{3575}$.

   a) ¿Cuál es el tipo de interés?

   b) Sabiendo que el ahorro de este consumidor es $S = \money{250}$,
      escriba y represente gráficamente la restricción intertemporal.

4. Un consumidor vive dos periodos. En el primer periodo obtiene una
   renta de \money{600} y en el segundo de \money{440}. El tipo de
   interés es del 10%.

   a) Obtenga la restricción intertemporal del consumidor y
      represéntela gráficamente. ¿Qué interpretación tienen los
      puntos de corte con los ejes?

   b) Suponga que en esas condiciones la decisión óptima del
      consumidor es consumir toda la renta del primer periodo de
      forma que el ahorro es 0. ¿Cómo habría cambiado la elección si
      el tipo de interés hubiera sido superior? Represente
      gráficamente.

5. Explique y justifique si considera correcta o incorrecta cada una
   de las siguientes afirmaciones (use el análisis gráfico cuando lo
   considere oportuno):

   a) Si no existiera un mercado de crédito que permitiera al
      consumidor prestar y pedir prestado, éste no podría ahorrar en
      el periodo presente para consumir por encima de su renta
      monetaria en el futuro.

6. La renta monetaria de un individuo en el periodo actual es
   \money{2500} y en este periodo ahorra una cantidad de
   \money{1000}. En el periodo futuro su renta monetario disminuirá
   un 20%.

   a) Si existe un mercado financiero que le permite prestar y pedir
      prestado, ¿cuál es el tipo de interés para el que el consumo
      óptimo en el futuro sea de \money{3010}?

   b) Represente gráficamente la restricción presupuestaria y señale
      el consumo óptimo de este consumidor.

7. Las preferencias entre consumo presente, $C_1$, y consumo futuro,
   $C_2$, de un individuo están representadas por la función de
   utilidad: $U(C_1, C_2) = C_1^2 C_2$. En el primer periodo el
   individuo tiene una renta de \money{200}, mientras que en el
   segundo periodo su renta es \money{220}. El tipo de interés al que
   se presta en la economía es del 5%, y el tipo de interés al que se
   pide prestado es del 10%.

   a) Exprese analíticamente la restricción presupuestaria y
      represéntela gráficamente.

   b) Calcule el equilibrio del consumidor y determine si será
      prestamista o prestatario.
