# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 2.4

Considere un mercado competitivo de manzanas y trace un diagrama de
oferta y demanda que muestre los efectos sobre el equilibrio de una
enfermedad de los manzanos que perjudique a la cosecha. ¿Podrían
aumentar los ingresos de los agricultores en este caso?  ¿Qué
condiciones se tendrían que cumplir?

** Answer

La oferta de manzanas se reduce. Se venden menos manzanas a un precio
superior.
#+xxx: fig fig-ans-probl-2_1004-apples-*.pdf

Los ingresos de los productores solo crecerán si el mercado se
encuentra en un tramo inelástico de la curva de demanda.



* 3.1

Las medicinas tienen demanda inelástica mientras que los
ordenadores tienen demanda elástica. Suponga que la oferta se
duplica en cada uno de esos mercados como consecuencia del
progreso tecnológico.

a) ¿Qué ocurrirá con el equilibrio en cada uno de estos mercados?
   Represente gráficamente.

b) ¿En qué mercado se experimentará el mayor cambio en el precio?
   ¿Y el mayor cambio en la cantidad?

c) ¿Cómo cambiará el gasto de los consumidores en cada bien?


** Answer

a) Demanda inelástica.
   #+xxx: fig fig-ans-probl-3_1004-medicines-*.pdf

   Demanda elástica.
   #+xxx: fig fig-ans-probl-3_1004-computers-*.pdf

b) En el mercado con la demanda más elástica se ve más afectada la
   cantidad. En el mercado con demanda menos elástica se ve más
   afectado el precio.

c) Cuando se reduce el precio en el mercado con demanda inelástica
   disminuye el gasto de los consumidores. En el mercado con demanda
   elástica, el gasto aumenta.



* 3.2

Cuando un país subió los impuestos sobre el tabaco, el precio de los
cigarrillos subió de \money{4} a \money{4.6} por cajetilla. Los
economistas estiman que la cantidad demandada cayó de $52$ a $47.5$
millones de cajetillas como consecuencia de esta subida de precio.
Calcule la elasticidad de la demanda de cigarrillos.


** Answer

La pendiente de la curva de demanda es:
#+begin_export latex
\[
  \incr Q^d/\incr P = (47.5 - 52)/(4.6 - 4) = -7.5
\]
#+end_export
El precio y la cantidad medios son:
#+begin_export latex
\[
  Q^d_m = (52 + 47.5)/2 = 49.75; \qquad
  P_m = (4 + 4.6)/2 = 4.3.
\]
#+end_export
La elasticidad, usando la fórmula del punto medio, es:
#+begin_export latex
\[
  E_d = -7.5 \cdot 4.3/ 49.75 \approx -0.65
\]
#+end_export


* 3.3

Dos conductores repostan todos los lunes en la misma gasolinera y
ninguno comprueba el precio antes de hacer su pedido. Mientras que
el primero siempre pide $15$ litros, el segundo siempre pide
\money{20} de gasóleo. ¿Cuáles son las elasticidades precio de la
demanda de gasóleo de cada conductor?


** Answer

El primer consumidor siempre demanda la misma cantidad: su demanda,
$Q^d = 15$, es perfectamente inelástica, $E_d = 0$.

El segundo siempre gasta lo mismo: su curva de demanda, $Q^d = 20 /
P$, tiene elasticidad unitaria, $E_d = -1$.


* 3.4

Ana paga \money{2} por cada unidad de alimentos, gasta
\money{5000} en alimentos al año y su renta monetaria anual es de
\money{25000}. La elasticidad-precio de su demanda de alimentos es
$-1$ mientras que la elasticidad-renta es $0.5$. Si Ana obtiene
una beca de \money{1000} que puede gastar libremente en aquello
que prefiera, ¿cuál sería su consumo de alimentos?


** Answer

El incremento porcentual de la renta de Ana a causa de la beca
es: $\incrpct{M} = \num{1000} / \num{25000} \cdot 100 =
4\%$. La variación del consumo de alimentos es:
#+begin_export latex
\[
  \incrpct{Q} = E_{d}^{M} \cdot \incrpct{M} = 0.5 \cdot 4= 2\%
\]
#+end_export
Las unidades de alimentos que inicialmente compra Ana durante un
año son: $Q = 5000 / 2 = \units{2500}$. Después de recibir la
beca, el consumo de alimentos será un 2% superior:
$2550$ unidades.


* 3.5

El mercado del bien $X$ está caracterizado por las funciones de
demanda y oferta:
#+begin_export latex
\begin{gather*}
  X^d = 250 - 30 P_{X} - 5 P_{Y} + 2 R \\
  X^o = 15 P_{X} - 25
\end{gather*}
#+end_export
donde $R$ es la renta media de los consumidores y $P_Y$ el precio
del bien $Y$. Actualmente, $R = \money{100}$ y $P_Y = \price{5}$.

a) Calcule el precio y la cantidad de equilibrio y represéntelo
   gráficamente. Calcule las elasticidades precio de la demanda y
   de la oferta en el equilibrio.

b) Calcule la elasticidad cruzada de la demanda. ¿Qué tipo de
   relación existe entre los bienes $X$ e $Y$?

c) Si la renta media de los consumidores disminuye en \money{10},
   ¿se puede afirmar que $X$ es un bien inferior?


** Answer

a) La curva de demanda es: $X^d = 425 - 30 P_X$ y en equilibrio:
   $P_X^* = \price{10}$ y $X^* = \units{125}$.
   #+xxx: fig fig-ans-probl-3_1004-eq-elast-*.pdf

   Elasticidad de la demanda:
   #+begin_export latex
   \[
     E_d = \frac{\diff X^d}{\diff P_X} \frac{P_X}{X^d} =
     -30 \cdot\frac{10}{125} = -2.4
   \]
   #+end_export

   Elasticidad de la oferta:
   #+begin_export latex
   \[
     E_o = \frac{\diff X^o}{\diff P_X} \frac{P_X}{X^o} =
     15 \cdot\frac{10}{125} = 1.2
   \]
   #+end_export

b) Elasticidad cruzada de la demanda:
     #+begin_export latex
     \[
       E_d^{P_Y} = \frac{\partial X^d}{\partial P_Y} \frac{P_Y}{X^d} =
       -5 \cdot\frac{5}{125} = -0.2
     \]
     #+end_export
     El bien $Y$ es complementario del bien $X$.


c) Elasticidad renta de la demanda:
     #+begin_export latex
     \[
       E_d^{R} = \frac{\partial X^d}{\partial R} \frac{R}{X^d} =
       2 \cdot\frac{100}{125} = 1.6
     \]
     #+end_export
     El bien $X$ es normal.


* 3.6

La empresa que gestiona un túnel se está planteando alterar el
peaje que cobra a los usuarios del túnel. Actualmente el peaje es
de \money{6} y \num{2400} conductores utilizan el túnel
diariamente. Una consultora ha estimado que la función $Q =
\num{6000} - \num{600} P$ describe con precisión la demanda diaria
del túnel.

a) ¿Cuál es la elasticidad de la demanda al precio actual?

b) Si la empresa persigue aumentar sus ingresos, ¿sería conveniente
   que rebajase el peaje?

c) ¿Cuál es el peaje que maximizaría los ingresos de la empresa?
   ¿Cuál es la elasticidad de la demanda en este caso?


** Answer

a) Elasticidad de la demanda:
   #+begin_export latex
   \[
     E_d = \frac{\diff Q}{\diff P} \frac{P}{Q} =
     -600 \cdot\frac{6}{2400} = -1.5
   \]
   #+end_export

b) Sí: se encuentra en un tramo elástico de la demanda.


c) Ingresos:
   #+begin_export latex
   \[
     I = P Q = P (6000 - 600 P) = 6000 P - 600 P^2
   \]
   #+end_export
   Maximizando con respecto a P obtenemos $P^* = \price{5}$,
   $Q^* = 3000$ viajeros e $I^* = \money{15000}$ al día. La
   elasticidad de la demanda es:
   #+begin_export latex
   \[
     E_d = \frac{\diff Q}{\diff P} \frac{P}{Q} =
     -600 \cdot\frac{5}{3000} = -1
   \]
   #+end_export


* 3.7

Un club de fútbol puede ofrecer \num{125000} abonos anuales. La
función de demanda de esos abonos es:
#+begin_export latex
\[
  Q^d = \num{125000} - 100 P +10 P_O + 10 M,
\]
#+end_export
donde:

- $P$ es el precio del abono.

- $P_O$ es el precio del abono del otro club con estadio en la
  misma ciudad

- $M$ es la renta anual media de los aficionados.

El equipo rival vende sus abonos a un precio de $P_O =
\money{600}$. Se estima que $M = \money{15000}$.

a) Represente gráficamente las curvas de demanda y de oferta de
   abonos y determine el equilibrio en este mercado.

b) Calcule las elasticidades de la demanda y de la oferta en el
   equilibrio e interprete los valores de esas elasticidades.

c) Calcule la elasticidad de la demanda con respecto al precio del
   abono del equipo rival en la situación de equilibrio e
   interprete el valor obtenido.

d) Calcule la elasticidad renta de la demanda en la situación de
   equilibrio e interprete el valor obtenido.


** Answer

a) La urva de demanda es $Q^d = \num{281000} - 100 P$. La curva de
   oferta es $Q^o = \num{125000}$. En equilibrio: $P^* = \price{1560}$
   y $Q^* = \units{125000}$.
   #+xxx: fig fig-ans-probl-3_1004-football-*.pdf

b) Elasticidades de la demanda y de la oferta en el
   equilibrio:
   #+begin_export latex
     \begin{gather*}
       E_d = \frac{\diff Q^d}{\diff P} \frac{P}{Q^d} =
       -100 \cdot\frac{1560}{\num{125000}} = -1.248 \\[2ex]
       E_o = \frac{\diff Q^o}{\diff P} \frac{P}{Q^o} =
       0 \cdot\frac{1560}{\num{125000}} = 0
     \end{gather*}
     #+end_export

     En el punto de equilibrio la demanda es elástica. La oferta
     es perfectamente inelástica.


c) Elasticidad cruzada de la demanda en el equilibrio:
     #+begin_export latex
     \[
       E_d^{P_O} = \frac{\partial Q^d}{\partial P_O} \frac{P_O}{Q^d} =
       10 \cdot\frac{600}{\num{125000}} = 0.048
     \]
     #+end_export
     Los abonos de los dos equipos son débilmente sustitutivos.


d) Elasticidad renta de la demanda en la situación de
   equilibrio:
     #+begin_export latex
     \[
       E_d^{M} = \frac{\partial Q^d}{\partial M} \frac{M}{Q^d} =
       10 \cdot\frac{\num{15000}}{\num{125000}} = 1.2
     \]
     #+end_export
     Los abonos son un bien de lujo.
