# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

* 6.1

The utility function of a consumer is $U = X^2 Y$, her income is $M =
\money{100}$ and the prices of the goods are $P_X = \price{10}$ and
$P_Y = \price{10}$. Obtain the income consumption curve and the Engel
curve for good $X$. Calculate the income elasticity of $X$. What kind
of good is X?


* 6.2

Consider a consumer who only buys two goods. Is it possible that they
are both inferior goods simultaneously?


* 6.3

A consumer purchases only two goods whose prices are $P_X =
\price{1}$ and $P_Y = \price{1}$. The following figure shows her
income consumption curve:

#+MATS: fig fig-probl-6_1004-crc1-*.pdf

a) If $M = \money{70}$, how many units would she demand of each one
   of the goods?

b) Is any of the two goods an inferior good? For what values of the
   income?


* 6.4

Consider a competitive economy where all consumers have the same
preferences and consume some units of good $X$ and good $Y$. Will they
all buy the same amount of $X$? Will there be differences in the
valuation of good $X$ by each consumer?


* 6.5

The preferences of a consumer can be represented by the utility
function:
#+begin_export latex
\[
  U (X, Y) = X Y + 24 Y
\]
#+end_export
The price of good $X$ is \price{6}, the price of good $Y$ is
\price{8} and the consumer has an income of \money{240}.

a) Obtain the price-consumption curve. What kind of relationship
   exists between $X$ and $Y$?

b) Obtain the demand curve for good $X$.


* 6.6

Both Adela and Blas have \money{100} to spend on goods $X$ and
$Y$. Adela only cares about how many units of $X$ she can consume,
since she do not get any satisfaction from good $Y$. On the other
side, Blas is always willing to exchange a unit of good $X$ for a
unit of good $Y$. The prices of the goods are $P_X = \price{2}$ and
$P_Y = \price{4}$. Obtain the demand curves for good $X$ of Adela
and Blas.


* 6.7

The preferences of a consumer are given by the utility function:
$U(X, Y) = X^{1/4} Y^{1/8}$ and her income is $M = \money{17496}$.
Prices are $P_X = \price{54}$ and $P_Y = \price{36}$.

a) Obtain the demand curve for good $X$.

b) Calculate how much the consumption of the two goods varies when the
   price of good $X$ decreases to $P_X = \price{16}$.

c) Decompose the impact on each good's consumption into the
   corresponding income and substitution effects.  What is
   the sign of these effects?


* 6.8

The goods $X$ and $Y$ are perfect complements. Represent
graphically how the optimal consumption choice would change if the
price of good $X$ increases. Decompose the total effect on the
consumption of $X$ into the substitution effect and the income
effect.


* 6.9

Dulce keeps buying the same amount of salt even though its price
has decreased by 50%. Does this mean that the substitution effect
is zero? Is salt an inferior good for Dulce?


* 6.10

"The quantity demanded of a Giffen good increases with its price
and also increases when the consumer's income increases." Is the
previous statement correct? Justify your answer.


* 6.11

The following graph shows the optimal choices of a consumer before
and after a decrease in the price of good $X$:

#+MATS: fig fig-probl-6_1004-fxs-*.pdf

Note that the slopes of the indifference curves are the same in
the baskets $A$ and $B$, on the one hand, and in the baskets $C$
and $D$, on the other hand.

Decompose the total effect on consumption of $X$ into the income
effect and the substitution effect. Obtain the signs of these
effects and determine what kind of good is $X$ for this consumer.


* 6.12

The mayor of Lazy Town has decided to introduce a new tax on
sugary drinks of \money{0.50} per can of soda. The tax is
completely transferred to buyers and the price of the can
increases from \money{0.50} to \money{1.00}.

Stephanie is a typical citizen of Lazy Town whose utility function
is:
#+begin_export latex
\[
  U (S, Y) = (S + 20)^{0.1} Y^{0.9}
\]
#+end_export
where $S$ is the number of soda cans she consumes and $Y$ is a
composite good that includes her remaining expenditure on
food. Stephanie has \money{470} every month to spend on $S$ and
$Y$.

a) How many cans of soda did Stephanie consume per month before
   the introduction of the tax?

b) Calculate Stephanie's optimal choice after the introduction of
   the tax. Is this tax effective in reducing her consumption of
   sugary drinks? How much money will she pay for the tax?

c) In view of the increasing complaints from the inhabitants of
   the city, the mayor decides to keep the tax and give
   \money{14.50} in cash to each citizen. Calculate how many cans
   will Stephany consume now. Is she still consuming less soda
   than in the initial situation?  Is the city council spending
   more money than the amount collected with the tax?
