# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 9.1.

Un consumidor vive dos periodos. Su renta en el primer periodo es
\money{1000} y en el segundo periodo es \money{3300}. El tipo de
interés es del 10%. Sus preferencias vienen dadas por:
#+begin_export latex
\[
  U(C_1, C_2) = C_1^{3/4} C_2^{1/4}
\]
#+end_export

a) Obtenga la restricción intertemporal del consumidor y
   represéntela gráficamente. ¿Qué interpretación tienen los
   puntos de corte con los ejes?

b) Obtenga el consumo óptimo en cada periodo. ¿Cuánto ahorrará el
   consumidor?  Represente gráficamente.


** Answer

a) Restricción intertemporal:
   #+begin_export latex
   \[
     \num{4400} = 1.1 C_1 + C_2.
   \]
   #+end_export

   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-7_1004-ex1-budget-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Los puntos de corte son los consumos máximos en cada periodo.
   #+xxx: endcol

b) Condición de tangencia:
   #+begin_export latex
   \[
     3 C_2 / C_1 = 1.1.
   \]
   #+end_export
   La elección óptima es: $C^*_1 = \num{3000}$ y $C^*_2 = \num{1100}$.

   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-7_1004-ex1-opt-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El consumidor ahorra:
   #+begin_export latex
   \[
     S = M_1 - C_1 = -\money{2000}.
   \]
   #+end_export
   #+xxx: endcol


* 9.2.

"Si no existiera un mercado de crédito que permitiera al consumidor
prestar y pedir prestado, éste no podría ahorrar en el periodo
presente para consumir por encima de su renta monetaria en el
futuro." ¿Es correcta la afirmación anterior? Justifique su
respuesta. Represente la restricción intertemporal de un consumidor
que no tenga acceso al mercado de crédito.


** Answer

#+ATTR_LATEX: :options [t]{0.55\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-7_1004-ex2-budget-*.pdf
#+ATTR_LATEX: :options [t]{0.45\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
Es incorrecta: puede ahorrar para gastar en el futuro, aunque
no recibirá intereses. Por otro lado, no puede pedir prestado.
#+xxx: endcol




* 9.3.

Un consumidor vive dos periodos y puede prestar y pedir prestado
dinero a un tipo de interés del 10%. En el primer periodo obtiene
una renta de \money{1000} mientras que en el segundo período
obtiene \money{750}. En estas condiciones el consumidor decide no
ahorrar nada. Si el tipo de interés disminuyera al 5%, ¿qué
ocurriría con el ahorro? ¿Qué situación preferiría el consumidor:
un tipo de interés del 10% o del 5%? Represente gráficamente.


** Answer

Restricción intertemporal: $C_2 = 1850 - 1.1 C_1$.

#+ATTR_LATEX: :options [t]{0.55\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-7_1004-ex3-r10-*.pdf
#+ATTR_LATEX: :options [t]{0.45\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
En el óptimo se cumple:
#+begin_export latex
\[
  \RMS(E_0) = 1.1.
\]
#+end_export
#+xxx: endcol



Con un tipo de interés del 5%, $E_0$ no puede ser óptima:
\begin{equation*}
  \RMS(E_0) = 1.1 > 1 + r = 1.05,
\end{equation*}
por lo que aumentará el consumo presente, $C_1$, y el ahorro será
negativo, $S < 0$.

#+ATTR_LATEX: :options [t]{0.55\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-7_1004-ex3-r5-*.pdf
#+ATTR_LATEX: :options [t]{0.45\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
Cuando $r= 0.05$ tanto $E_0$ como $E_1$ son factibles. Si elige $E_1$
es porque proporciona mayor utilidad al consumidor.
#+xxx: endcol
El consumidor prefiere la situación en la que $r = 0.05$.




* 9.4.

Las preferencias intertemporales de un consumidor vienen dadas por la
función: $U(C_1, C_2)= C_1 C_2^{1/2}$.  Su renta en el primer periodo
es \money{200} y en el segundo periodo es \money{220}. El tipo de
interés al que se presta dinero es del 5%, y el tipo de interés al se
pide prestado es del 10%.

a) Obtenga la restricción presupuestaria del individuo y represéntela
   gráficamente.

b) Calcule el equilibrio del consumidor y determine si será
   prestamista o prestatario.

c) Si el Banco Central Europeo fija un tipo de interés único del 8%
   tanto para prestar como para pedir prestado, calcule el nuevo
   equilibrio y determine si el bienestar del consumidor mejora o
   empeora.


** Answer

a) La restricción intertemporal tiene dos tramos con pendientes
   diferentes:
   #+ATTR_LATEX: :booktabs t :center t :align lrr
   |---------------+----------------------+------------------------|
   | Situación     | Condición            | Restricción            |
   |---------------+----------------------+------------------------|
   | Pide prestado | $C_1 \geq 200$       | $C_2 = 440 - 1.10 C_1$ |
   | Presta        | $C_1 \leq 200$       | $C_2 = 430 - 1.05 C_1$ |
   |---------------+----------------------+------------------------|

   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-7_1004-ex4-budget-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Restricción intertemporal.
   #+xxx: endcol

b) Calculamos la solución que se obtendría en cada caso:

   - El consumidor presta: $C_1 \leq 200$.

     Restricción intertemporal: $C_2 =  430 - 1.05 C_1$.

     Condición de tangencia: $2 C_2 = 1.05 C_1$.

     #+ATTR_LATEX: :options [t]{0.55\linewidth}
     #+xxx: col
     #+latex: \vspace{0pt}
     #+ATTR_LATEX: :center nil
     #+xxx: fig fig-ans-probl-7_1004-ex4-lender-*.pdf
     #+ATTR_LATEX: :options [t]{0.45\linewidth}
     #+xxx: col
     #+latex: \vspace{1ex}
     Resolviendo:
     #+begin_export latex
     \begin{gather*}
       C_1 = \money{273.02},\\ C_2 = \money{143.33}.
     \end{gather*}
     #+end_export
     #+xxx: endcol
     No puede ser la solución óptima ya que $C_1 > 200$.

   - El consumidor pide prestado: $C_1 \geq 200$.

     Restricción intertemporal es: $C_2 = 440 - 1.1 C_1$.

     Condición de tangencia: $2 C_2 = 1.1 C_1$.

     #+ATTR_LATEX: :options [t]{0.55\linewidth}
     #+xxx: col
     #+latex: \vspace{0pt}
     #+ATTR_LATEX: :center nil
     #+xxx: fig fig-ans-probl-7_1004-ex4-borrower-*.pdf
     #+ATTR_LATEX: :options [t]{0.45\linewidth}
     #+xxx: col
     #+latex: \vspace{1ex}
     Resolviendo:
     #+begin_export latex
     \begin{gather*}
       C_1 = \money{266.67}, \\ C_2 = \money{146.67}.
     \end{gather*}
     #+end_export
     #+xxx: endcol

     En este caso sí se cumple nuestro supuesto inicial y la solución
     encontrada es la elección óptima. El consumidor pide prestado
     $C_1 - M_1 = \money{66.67}$.

c) Restricción intertemporal: $C_2 = 436 - 1.08 C_2$.

   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-7_1004-ex4-flat-budget-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Las zonas sombreadas son opciones que antes no estaban disponibles.
   #+xxx: endcol

   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-7_1004-ex4-flat-choice-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Elección óptima:
   #+begin_export latex
   \begin{gather*}
     C_1 = \money{269.14}, \\ C_2 = \money{145.33}.
   \end{gather*}
   #+end_export
   #+xxx: endcol

   El consumidor disfruta de un mayor nivel de utilidad con un tipo de
   interés único del 8%:
   #+begin_export latex
   \begin{gather*}
     U(E_0) = 266.67 \cdot 146.73^{1/2} = \num{3230.23}, \\
     U(E_1) = 269.14 \cdot 145.33^{1/2} = \num{3244.56}.
   \end{gather*}
   #+end_export


* 9.5.

Un consumidor tiene unas preferencias con respecto a su consumo
presente, $C_1$, y a su consumo futuro, $C_2$, que vienen
representadas por la función de utilidad $U(C_1, C_2) = \min\{C_1,
C_2\}$. La renta del consumidor en cada periodo es $M_1 =
\money{4200}$ y $M_2 = \money{1050}$, y el tipo de interés es $r =
0.1$.

a) Escriba la restricción presupuestaria intertemporal en valor futuro
   y represéntela gráficamente.

b) Determine si el consumidor ahorra o no, así como el consumo en cada
   periodo.


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-7_1004-ex5-budget-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Restricción intertemporal:
   #+begin_export latex
   \[
     \num{5670} = 1.1 C_1 + C_2.
   \]
   #+end_export
   #+xxx: endcol

b)
   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-7_1004-ex5-opt-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Elección óptima:
   #+begin_export latex
   \begin{equation*}
     C_1 = C_2 = \money{2700}.
   \end{equation*}
   #+end_export
   Ahorro:
   #+begin_export latex
   \begin{equation*}
     S = M_1 - C_1 = \money{1500}.
   \end{equation*}
   #+end_export
   #+xxx: endcol


* 9.6.

Un consumidor vive dos periodos y puede prestar y pedir prestado a un
mismo tipo de interés. Durante el primer periodo obtiene una renta de
\money{2500}, ahorra \money{1000}, y su renta en el segundo periodo es
un 20% inferior a la del primer periodo. Calcule el tipo de interés
sabiendo que la elección óptima en el segundo periodo es consumir
\money{3010}. Obtenga y represente gráficamente la restricción
intertemporal.


** Answer

Consumo en el primer periodo:
#+begin_export latex
\[ C_1 = M_1 - S_1 = \num{2500} - \num{1000} = \money{1500}.\]
#+end_export
Renta en el segundo periodo:
#+begin_export latex
\[ M_2 = 0.8 M_1 = \money{2000}.\]
#+end_export
Restricción intertemporal:
#+begin_export latex
  \[ \num{2500} (1 + r) + \num{2000} = \num{1500} (1 + r) + \num{3010}. \]
#+end_export
Por tanto: $r = 0,01$.

#+ATTR_LATEX: :options [t]{0.55\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-7_1004-ex6-budget-*.pdf
#+ATTR_LATEX: :options [t]{0.45\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
Restricción intertemporal:
#+begin_export latex
  \[ \num{4525} = 1.01 C_1 + C_2 \]
#+end_export
#+xxx: endcol



* 9.7.

Un consumidor vive dos periodos y sus preferencias vienen
representadas por:
#+begin_export latex
\[
  U(C_1, C_2) = C_1^3 C_2
\]
#+end_export

a) Sabiendo que su elección óptima es $C_1 = \money{9750}$ y $C_2 =
   \money{3575}$, ¿cuál es el tipo de interés?

b) El ahorro de este consumidor es $S = \money{250}$. Exprese la
   restricción intertemporal en valor presente.


** Answer

a) Condición de tangencia:
   #+begin_export latex
   \[
     \RMS = 3 C_2 / C_1 = 3 \cdot 3575 / 9750 = 1 + r
   \]
   #+end_export
   Por lo que $r = 0.1$.

b) Si $S = 250$, entonces $M_1 = S_1 + C_1 = \money{10000}$. La
   elección óptima satisface la restricción intertemporal:
   #+begin_export latex
   \[
     \num{10000} \cdot 1.1 + M_2 = 9750 \cdot 1.1 + 3575.
   \]
   #+end_export
   Por lo que: $M_2 = \money{3300}$. Restricción intertemporal:
   #+begin_export latex
   \[
     \num{13000} =  C_1 + 0.91 C_2
   \]
   #+end_export
