# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 2


1. Un consumidor gasta su renta $M$ en los bienes $X$ e $Y$.

   a) ¿Como cambiaría su recta presupuestaria si se establece un
      impuesto sobre el consumo que eleva el precio de los bienes en
      un 25%?

   b) ¿Y si, en vez del impuesto al consumo, se establece un impuesto
      sobre la renta que reduce $M$ un 25%?

   c) ¿Cuál de las dos opciones preferirá el consumidor?

2. Un consumidor dispone de \money{20} para comprar carne y
   patatas. En el supermercado en el que suele hacer la compra, el kg
   de carne vale \money{4} mientras que cada kg de patatas cuesta
   \money{2}.

   a) Obtenga y represente la restricción presupuestaria.

      #+begin_answer
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
      #+MATS: fig fig-probl-2_1004-budget1-*.pdf
      #+end_minipage
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
        La restricción presupuestaria original es:
        \begin{equation*}
          20 = 4 C + 2 P
        \end{equation*}
      #+end_minipage
      #+end_answer

   b) El supermercado introduce una oferta por la que regala
      \units[kg]{2} más de patatas a todo el que compre \units[kg]{4}
      o más. Obtenga y represente la restricción presupuestaria en
      este caso.

      #+begin_answer
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
      #+MATS: fig fig-probl-2_1004-budget2-*.pdf
      #+end_minipage
      #+attr_latex: :options {0.5\linewidth}
      #+begin_minipage
        Nueva restricción presupuestaria:
        \begin{equation*}
          C =
          \begin{cases}
            5 - P / 2 & \text{si $P < 4$} \\
            6 - P / 2 & \text{si $P \geq 6$}
          \end{cases}
        \end{equation*}
      #+end_minipage
      #+end_answer

3. Las preferencias entre el pollo y el pescado de Amaia y Alejandro
   son diferentes. A Amaia le gusta el pescado, mientras que el pollo
   le resulta indiferente; no le importa comerlo pero no le reporta
   ninguna satisfacción. Por otro lado, a Alejandro no le gusta el
   pescado pero sí el pollo y sólo está dispuesto a comer algo de
   pescado si a cambio recibe una porción extra de pollo. Representa
   gráficamente las preferencias de Amaia y de Alejandro.

4. Las preferencias de un consumidor están representadas por la
   función de utilidad: $U(X, Y)= 5X Y^2$. La renta del consumidor es
   de \money{900} y los precios de los bienes $X$ e $Y$ son $P_X =
   \price{10}$ y $P_Y = \price{5}$. Calcule la elección óptima del
   consumidor.

5. *Añade función de utilidad* Un consumidor dispone de una renta de
   \money{1000} para comprar los bienes $X$ e $Y$, cuyos precios son
   $P_X = \price{5}$ y $P_Y = \price{1}$.

   a) Obtenga y represente el conjunto presupuestario del consumidor.

   b) ¿Cómo cambiaría el conjunto presupuestario si el consumidor
      obtiene un descuento de \money{1} por cada unidad comprada del
      bien $X$ por encima de \num{25} unidades? Justifique su
      respuesta.

6. Un consumidor racional elige una cesta que contiene cantidades
   positivas de todos los bienes. Si aumenta el precio de un bien, ¿se
   reducirá la utilidad del consumidor? Justifique su respuesta.

7. *RMS*.

8. Las preferencias de un consumidor entre gasolina, $G$, y un bien
   compuesto, $Y$, que recoge las compras del consumidor en los
   restantes bienes, están representadas por la función de utilidad:
   $U(G, Y)= (G + 10) Y$. El precio de la gasolina es de $P_G =
   \price[l]{2}$ y la renta del consumidor es $M = \money{24}$.

   a) Indique la expresión matemática de la restricción presupuestaria
      y represéntela gráficamente.

   b) La empresa para la que trabaja este consumidor está considerando
      la posibilidad de ofrecer incentivos para los trabajadores más
      eficientes y estudia diferentes posibilidades:

      + Entregar un vale al trabajador que le permite adquirir
        \num{6} litros de gasolina de forma gratuita.

      + Ofrecer al trabajador un descuento de \money{1} por cada litro
        de gasolina que consuma.

      + Entregarle una gratificación de \money{12} en metálico.

      Indique la expresión matemática de la restricción presupuestaria
      en cada uno de los casos y represéntelas en un mismo gráfico.

   c) ¿Cuál de las opciones preferirá el consumidor? Razone su respuesta.

9. *Cambiar a descuento por volumen* El precio del bien $X$ cambia
   dependiendo de la cantidad que se compre: las 50 primeras unidades
   cuestan \price{1}, mientras que para cada unidad comprada por
   encima de la quincuagésima el precio es \price{2}.

   a) Obtenga y represente gráficamente la restricción presupuestaria
      de un consumidor que dispone de una renta monetaria de
      \money{200}. [/Pista/: Utilice un bien compuesto.]

   b) Si las preferencias de este consumidor son tales que: $\RMS = Y
      / 4X$, ¿cuál sería la elección óptima?

10. Las preferencias de un consumidor pueden representarse por la
    función de utilidad: $U(X, Y) = X (Y + 100)$. El precio del bien
    $X$ es \price{1} y el del bien $Y$ es \price{4}. El consumidor
    dispone de una renta monetaria de \money{250}.

    a) Calcule la elección óptima de consumo.

    b) Si se raciona el bien $X$ de forma que no es posible consumir
       más de 100 unidades de $X$, ¿cuál sería la elección
       óptima?. Represente gráficamente.

11. La función de utilidad de un individuo respecto de los bienes $X$ e
    $Y$ viene dada por $U(X,Y) = 3X + 3Y$. Los precios de mercado son
    $P_X = \price{2}$ y $P_Y = \price{5}$ y la renta monetaria del
    consumidor es $M = \money{100}$.

    a) ¿Es $(X,Y) = (10, 40)$ una cesta óptima? ¿Por qué?

    b) ¿Cuál es la elección óptima del consumidor?

    c) ¿Cómo se vería modificada la elección del consumidor si $P_X =
       \price{10}$?

12. Un consumidor /siempre/ está dispuesto a intercambiar 2 unidades del
    bien $X$ por 1 unidad del bien $Y$. El precio del bien $X$ es de
    $4$ €/unidad y el precio del bien $Y$ es de $3$ €/unidad. Con esta
    información, ¿es posible determinar cuantas unidades del bien $X$
    consumirá? ¿Y del bien $Y$? Razone la respuesta.

13. *Complementarios perfectos*.

14. Un consumidor posee una renta de \money{4} que gasta en los bienes
    $X$ e $Y$, cuyos precios son $P_X = \price{3}$ y $P_Y =
    \price{2}$. Cuando consume $2$ unidades de $Y$ y no consume nada de
    $X$, la relación marginal de sustitución es igual a $2$. ¿Es esta
    la elección óptima del consumidor o estaría mejor consumiendo más
    unidades de $X$ y menos de $Y$?

    #+begin_answer
      El consumidor gasta toda su renta comprando la cesta $X=0$ e
      $Y=2$, pero la relación marginal de sustitución, $\mathit{RMS} =
      2$, es superior a los precios relativos, $P_X/P_Y = 1.5$. Esto
      quiere decir que la valoración que el consumidor hace de una
      unidad de $X$ es superior a lo que le cuesta conseguirla en el
      mercado: por cada unidad de $X$ estaría dispuesto a renunciar a 2
      unidades de $Y$ pero sólo tendría que pagar el equivalente a
      $1.5$ unidades de $Y$. En consecuencia, aumentaría su utilidad si
      disminuye el consumo de $Y$ y aumenta el de $X$.
    #+end_answer

15. *Bono gimnasio*
