# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 4.1

\TASK El siguiente gráfico muestra las curvas de demanda y de oferta
de un mercado competitivo:

#+xxx: fig fig-probl-4_1004-price-controls-*.pdf

Encuentre la cantidad que se vendería y a qué precio en cada una de
las siguientes situaciones:

a) Se establece un precio mínimo de \price{1.50}.

b) Se establece un precio máximo de \price{1.50}.

c) Se establece un precio mínimo de \price{4.00}.

d) Se establece un precio máximo de \price{4.00}.


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-price-controls-a-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El precio de equilibrio es superior al precio mínimo y el mercado
   se halla en equilibrio. Se venden 350 unidades a un precio unitario
   de \price{2.50}.
   #+xxx: endcol

b)
   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-price-controls-b-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El precio de equilibrio es superior al precio máximo y hay un
   exceso de demanda en el mercado. Se venden 250 unidades a un precio
   unitario de \price{1.50}.
   #+xxx: endcol

c)
   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-price-controls-c-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El precio de equilibrio es inferior al precio mínimo y hay un
   exceso de oferta en el mercado. Se venden 50 unidades a un precio
   unitario de \price{4.00}.
   #+xxx: endcol

d)
   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-price-controls-d-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El precio de equilibrio es inferior al precio máximo y el mercado
   se halla en equilibrio. Se venden 350 unidades a un precio unitario
   de \price{2.50}.
   #+xxx: endcol





* 4.2

En el mercado del bien $X$ las curvas de demanda y de oferta son:
#+begin_export latex
\begin{gather*}
  X^d = 100 - P_X / 40 \\
  X^o = 50 + P_X / 40
\end{gather*}
#+end_export

a) Determine el precio y la cantidad de equilibrio.

b) Describa y represente gráficamente los efectos sobre el mercado
   del bien $X$ del establecimiento de un precio mínimo de
   \price{1200}. ¿Cuántas unidades se venderían? ¿A qué precio?


** Answer

a) En equilibrio: $P_X^* = \price{1000}$ y $X^* = \units{75}$.

b)
   #+ATTR_LATEX: :options [t]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-min-price-*.pdf
   #+ATTR_LATEX: :options [t]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El precio mínimo está por encima del de equilibrio, por lo que se
   venden 70 unidades a \price{1200} y hay un exceso de oferta de
   10 unidades.
   #+xxx: endcol


* 4.3

El precio en un mercado competitivo de azúcar es \money{0.75} por
kilo. Represente gráficamente y explique las efectos sobre
este mercado del establecimiento de un precio mínimo de
\price[kg]{0.60}. ¿Se venderán más o menos kilos de azúcar?



** Answer

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-4_1004-sugar-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
El precio de equilibrio es superior al precio mínimo, por lo que la
regulación no tiene efecto sobre el precio de mercado ni sobre la
cantidad intercambiada.
#+xxx: endcol


* 4.4

\DANGER En un mercado competitivo en equilibrio, se venden \num{96000}
unidades a un precio de \price{300}. La elasticidad precio de la
demanda es $-1.5$ y que la elasticidad precio de la oferta es igual
a $2$. Si se aprueba una ley que establece un precio máximo de
\price{294}, ¿qué efectos tendrá sobre el mercado? Represente
gráficamente.


** Answer

El precio de equilibrio está por encima del precio máximo.
La regulación implica una caída del precio de mercado:
#+begin_export latex
\[
  \incrpct{P} = -6/300 \cdot 100 = -2.
\]
#+end_export
Usando los valores de las elasticidades de la
demanda y de la oferta:
#+begin_export latex
\begin{gather*}
  \incrpct{Q^{d}} = E_d \incrpct{P} = -1.5 \cdot (-2) = 3. \\
  \incrpct{Q^{o}} = E_o \incrpct{P} = 2 \cdot (-2) = -4.
\end{gather*}
#+end_export
Se produce un exceso de demanda de un 7% con respecto a la
cantidad inicial: la cantidad ofrecida será unas \num{6720} unidades
menor que la cantidad demandada.


* 4.5

\TASK Las curvas de demanda y oferta de mercado del bien $X$ son:
#+begin_export latex
\begin{gather*}
  X^{d} = 200 - 5 P_{X} + 3 P_{Y} + 2 M \\
  X^{o} = 100 + 2 P_{X}
\end{gather*}
#+end_export
donde $M$ es la renta media de los consumidores y $P_Y$ es el precio
del bien $Y$, siendo $M = \money{100}$ y $P_Y = \price{5}$. Una ley
prohíbe que el precio de $X$ supere los $\money{50}$.

a) <<ex4.4:item-a>>¿Qué cantidad del bien $X$ se venderá? ¿A qué
   precio? Represente gráficamente.

b) Describa como cambiarían sus respuestas en [[ex4.4:item-a]] si la
   renta media aumentara hasta $M = \money{170}$.


** Answer

a) La curva de demanda es:
   #+begin_export latex
   \[
     X^d_a = 200 - 5 P_X + 3 \cdot 5 + 2 \cdot 100 = 415 - 5 P_X.
   \]
   #+end_export

   #+ATTR_LATEX: :options [t]{0.50\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-eq1-*.pdf
   #+ATTR_LATEX: :options [t]{0.50\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Equilibrio: $P^*_X = \price{45}$ y $X^* = \units{190}$. El precio
   máximo es superior al precio de equilibrio y nada impide que este
   mercado alcance el equilibrio.
   #+xxx: endcol

b) La nueva curva de demanda es:
   #+begin_export latex
   \[
     X^d_b = 200 - 5 P_X + 3 \cdot 5 + 2 \cdot 170 = 555 - 5 P_X.
   \]
   #+end_export

   #+ATTR_LATEX: :options [t]{0.50\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-eq2-*.pdf
   #+ATTR_LATEX: :options [t]{0.50\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   El precio de equilibrio, $P_X^* = \price{65}$, no se puede alcanzar
   ya que es mayor que el precio máximo. Se venderían todas las
   unidades ofrecidas, $X^o(50) = \units{200}$, a un precio $P_X =
   \price{50}$.
   #+xxx: endcol


* 4.6

Razone la veracidad o falsedad de la siguiente afirmación: "Si se
establece un precio máximo superior al precio de equilibrio, la
cantidad vendida coincidirá con la cantidad de equilibrio."


** Answer

La afirmación es verdadera: un precio máximo mayor que el de
equilibrio no impide que el mercado se equilibre.


* 4.7

En el mercado de un bien las curvas de demanda y de oferta son:
#+begin_export latex
\begin{gather*}
  Q^d = \num{100000} - 20 P \\
  Q^o = \num{40000} + 40 P
\end{gather*}
#+end_export

a) Determine el precio y la cantidad de equilibrio.

b) <<ex4.7:item-b>>Describa y represente gráficamente los efectos
   sobre el mercado del establecimiento de un impuesto sobre los
   vendedores de \money{150} por unidad vendida. ¿Cómo se reparte la
   carga del impuesto entre los compradores y vendedores?

c) Calcule las elasticidades de la demanda y de la oferta en el
   equilibrio anterior a la introducción del impuesto ¿Qué relación
   existe entre la distribución de la carga del impuesto y estas
   elasticidades?

d) Explique como cambiarían sus respuestas en [[ex4.7:item-b]] si el
   impuesto se estableciera sobre los compradores.


** Answer

a) Igualando oferta y demanda se obtiene el equilibrio de mercado:
   $P^* = \price{1000}$ y $Q^* = \units{80000}$.

b) La curva de oferta después del impuesto es:
   #+begin_export latex
   \[
     Q^o_t = \num{40000} + 40 (P - 150) = \num{34000} + 40 P.
   \]
   #+end_export

   #+ATTR_LATEX: :options [t]{0.6\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-tax-sellers-*.pdf
   #+ATTR_LATEX: :options [t]{0.4\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Después del impuesto:
   #+begin_export latex
   \begin{gather*}
     P^* = \price{1100}, \\
     Q^* = \units{78000}.
   \end{gather*}
   #+end_export
   #+xxx: endcol

   Los compradores pagan \money{100} más que antes del impuesto.  Los
   vendedores ingresan \money{50} menos que en la situación inicial.

c) Las elasticidades de la demanda y de la oferta en el equilibrio
   antes de impuestos son:
   #+begin_export latex
   \begin{gather*}
     E_{d} = \frac{\diff Q^{d}}{\diff P} \frac{P}{Q^{d}} = -20
     \frac{\num{1000}}{\num{80000}} = -0.25, \\
     E_{o} = \frac{\diff Q^{o}}{\diff P} \frac{P}{Q^{o}} = 40
     \frac{\num{1000}}{\num{80000}} = 0.5.
   \end{gather*}
   #+end_export
   La demanda es relativamente más inelástica que la oferta. En
   consecuencia, los compradores soportan una mayor parte de la carga
   del impuesto.

d) La curva de demanda después del impuesto es:
   #+begin_export latex
   \[
     Q^d_t = \num{100000} - 20 (P + 150) = \num{97000} -20 P.
   \]
   #+end_export

   #+ATTR_LATEX: :options [t]{0.6\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-tax-buyers-*.pdf
   #+ATTR_LATEX: :options [t]{0.4\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Después del impuesto:
   #+begin_export latex
   \begin{gather*}
     P^* = \price{950}, \\
     Q^* = \units{78000}.
   \end{gather*}
   #+end_export
   #+xxx: endcol

   Los resultados son idénticos a los del apartado [[ex4.7:item-b]]: los
   vendedores ingresan \money{950} por unidad y los compradores pagan
   el precio más el impuesto: \money{1100} por unidad.



* 4.8

\TASK El mercado de alquiler de viviendas en una ciudad está
representado por las curvas de demanda y de oferta:
#+begin_export latex
\begin{gather*}
  Q^{d} = \num{25000} - 30 P, \\
  Q^{o} = \num{5000} +10 P.
\end{gather*}
#+end_export

a) Determine el equilibrio de mercado.

b) El ayuntamiento establece un programa de ayudas al alquiler por el
   que los inquilinos reciben una subvención de \money{200} al
   mes. ¿Cómo afectará este programa al alquiler mensual que cobran
   los caseros? ¿Cómo cambiará la cantidad que paga cada inquilino por
   el alquiler? ¿Cuál será el coste total del programa de subvenciones
   para el ayuntamiento? Represente gráficamente.



** Answer

a) El alquiler mensual de equilibrio es $P^* = \money{500}$ y
   se alquilan $Q^* = \num{10000}$ viviendas.

b) Cuando se introduce la subvención la curva de demanda es:
   #+begin_export latex
   \[
     Q^d_s = \num{25000} - 30 (P - 200) = \num{31000} - 30 P.
   \]
   #+end_export

   #+ATTR_LATEX: :options [t]{0.6\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-4_1004-subsidy2-*.pdf
   #+ATTR_LATEX: :options [t]{0.4\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Después de la subvención:
   #+begin_export latex
   \begin{gather*}
     P^* = \price{650}, \\
     Q^* = \units{11500}.
   \end{gather*}
   #+end_export
   #+xxx: endcol

   Los caseros reciben \money{650} y los inquilinos pagan \money{450}
   por vivienda. El coste total de las subvenciones es de $200 \cdot
   \num{11500} = \money{2300000}$.
