# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

* 1.1

An economy produces two goods, vehicles and food, using labor as the
only factor of production. There are \num{100000} labor hours per
month available. The following table shows how many units of each good
can be produced according to the labor hours devoted to each activity:

#+latex: \vspace*{2ex}
#+ATTR_LATEX: :options {0.48\linewidth}
#+xxx: col
#+ATTR_LATEX: :booktabs t :center t :align @{}rR{2.5cm}@{}
|------------------+-------------|
|            Labor |    Vehicles |
| (thousand hours) | (thousands) |
|------------------+-------------|
|                0 |           0 |
|               10 |          50 |
|               20 |          95 |
|               30 |         135 |
|               40 |         170 |
|               50 |         200 |
|               60 |         225 |
|               70 |         245 |
|               80 |         260 |
|               90 |         270 |
|              100 |         275 |
|------------------+-------------|

#+ATTR_LATEX: :options {0.48\linewidth}
#+xxx: col
#+ATTR_LATEX: :booktabs t :center t :align @{}rR{2.5cm}@{}
|------------------+---------------|
|            Labor |          Food |
| (thousand hours) | (thousand kg) |
|------------------+---------------|
|                0 |             0 |
|               10 |            80 |
|               20 |           150 |
|               30 |           200 |
|               40 |           240 |
|               50 |           270 |
|               60 |           290 |
|               70 |           305 |
|               80 |           315 |
|               90 |           320 |
|              100 |           322 |
|------------------+---------------|
#+xxx: endcol

a) <<ex1.1:item-a>>Obtain and draw the Production Possibility
   Frontier, PPF.

b) If \units[kg]{150000} of food are produced, ¿is it possible to
   produce \num{300000} vehicles? If your answer is negative,indicate
   how many vehicles could be produced at most.

c) What effect on the PPF would have an organizational improvement in
   the production of vehicles? Obtain and draw the PPF if the
   improvement caused a 20% increase in the production of vehicles per
   hour.

d) Which would be the consequences on the PPF of the reduction of the
   labor hours by half as a result of an armed conflict?  Represent
   graphically the PPF if just \num{50000} hours of labor can be used
   and compare the results with the ones obtained in [[ex1.1:item-a]].

# #+latex: \clearpage{}

* 1.2

The table below shows different efficient combinations for an economy
in which only two goods are produced: guns and butter.

#+ATTR_LATEX: :booktabs t :center t :align @{}p{1cm}*{2}{R{2cm}}@{}
|-----+----------+-------------|
|     | Butter   | Cannons     |
|     | (Tons)   | (Units)     |
|-----+----------+-------------|
| *A* | \num{20} | \num{0}     |
| *B* | \num{18} | \num{1}     |
| *C* | \num{15} | \num{2}     |
| *D* | \num{11} | \num{3}     |
| *E* | \num{6}  | \num{4}     |
| *F* | \num{0}  | \num{5}     |
|-----+----------+-------------|

a) Draw the Production Possibility Frontier, PPF.

c) Construct a table that reflects the opportunity cost of producing
   each cannon.

d) How many tons of butter must be given up to produce the first
   cannon? And the second one?

e) What is the relationship between the PPF shape and the opportunity
   cost?


* 1.3

The production possibilities frontier, PPF, of a country producing
just two goods, $X$ and $Y$ can be expressed as:
#+begin_export latex
\[
  Y = \num{1000} - 0.1 X
\]
#+end_export

a) Represent graphically the PPF.

b) If the economy is efficiently using all production factors and
   \num{1000} units of good $X$ are produced. Which is the opportunity
   cost of producing an additional unit of good $X$?

c) If instead of \num{1000} units, the economy produces \num{5000}
   units of good $X$, how would your answer to the previous point
   change?

d) What is the relationship between the behavior of the opportunity
   cost and the shape of the PPF?

# #+latex: \enlargethispage{2\baselineskip}


* 1.4

The following figure shows the production possibilities frontier of
an economy where only fish and coconuts are produced:

#+xxx: fig fig-probl-1_1004-ppf-*.pdf

Rank the production options $A$, $B$, $C$, and $D$ from higher to
lower opportunity cost of producing fish.


* 1.5

Consider an economy where only two goods are produced: $X$ and $Y$.

#+xxx: fig fig-probl-1_1004-ppf-multi-*.pdf

Associate each one of the previous graphs with the following
statements. Justify your answers.

a) The rise in birth rate in previous decades has the effect of
   considerably increasing the number of working-age people.

b) A higher share of unemployed people get a job.

c) A higher share of working people migrate abroad looking for a
   better job.

d) An administrative reform makes it much more difficult and costly to
   hire workers.
