#+SETUPFILE: ./course-en.org

#+TITLE: Exercise Booklet 3

* The effect of price and income changes on individual demand

1. A consumer has a monetary income $M = \money{16}$ and preferences
   that may be described by the utility function $U(X, Y) = X Y$.  The
   consumer is initially in equilibrium and buys 4 units of good
   $X$ and 8 units of good $Y$. The prices of good $X$ and good $Y$
   are $P_X = \price{2}$ and $P_Y = \price{1}$.

   a) Draw the initial equilibrium.

   b) Assume that the price of $X$ falls and it is now $P_X =
      \price{1}$. Compute and represent the new equilibrium.

   c) Draw the price offer curve and the demand function of the
      consumer.

   d) Starting from the initial equilibrium, consider an income
      increase equal to \money{4}. Compute and plot the new
      equilibrium.

   e) Work out and draw the income offer curve and the Engel curve.

2. The preferences of a consumer are represented by the utility
   function: $U(X, Y) = X^2 Y$ and her income is $M =
   \money{1200}$. The prices of good $X$ and good $Y$ are $P_X = P_Y =
   \price{4}$.

   a) Calculate and represent the equilibrium situation and the demand
      function for good $X$.

   b) What kind of relationship exists between goods $X$ and $Y$?

   c) Calculate the effect on consumption of both goods of a reduction
      of \money{3} in the unit price of good $X$.

   d) Decompose graphically and analytically the impact on the
      consumption of both goods of the variation in the price of $X$
      distinguishing between the income and the substitution effects.

3. The utility function of a consumer is:  $U(X, Y) = X^{1/4}
   Y^{1/8}$, while $P_X = \price{2}$, $P_Y = \price{3}$ and $M =
   \money{340}$.

   a) Compute the optimal consumption basket.

   b) Suppose the unit price of good $X$ rises by
      $\money{2}$. Calculate the total effects on the demands of goods
      $X$ and $Y$.

   c) Decompose the total effects into the substitution effects and
      the income effects.

   d) Compute the demand functions for good $X$ and good $Y$.

4. Each resident in a small town spends \money{38} per month between
   sport activities, $S$, and cultural activities, $C$. The unit price
   of these activities is $P_S = \price{2}$ y $P_C = \price{1}$. The
   preferences of each resident with respect to sport and cultural
   activities may be represented by the utility function: $U(S, C) =
   S C + C$.

   a) Determine the number of sports and cultural activities that the
      local authorities should provide if their objective is the
      maximization of the residents utility.

   b) Suppose that the local authorities approve the Sports
      Development Plan that subsidizes 50% of the price of sport
      activities. Compute and plot the effect of this policy on the
      consumption choices by the residents.

   c) Decompose the total impact of the Plan into income and
      substitution effects.
