# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

* 5.1

A consumer spends her income $M$ on goods $X$ and $Y$.

a) How would her budget line change if a tax on consumption were
   introduced and the prices of both goods rose by 25%?

b) And what if, instead of the tax on consumption, an income tax were
   levied and $M$ decreased by 25%?

c) Which option would the consumer prefer?


* 5.2

A consumer has \money{20} to buy meat and potatoes. He usually shops
at a supermarket where the meat is sold for \price[kg]{4}, and one
kilo of potatoes costs \money{2}.

a) Obtain and represent the budget constraint.

b) The supermarket run a sales promotion where the customers that buy
   more than \units[kg]{4} of potatoes will get two additional kilos
   for free. Obtain and represent the budget constraint in this case.


* 5.3

Amaia likes fish, while she neither likes nor dislikes
chicken. Alejandro, meanwhile, does not like fish but he does like
chicken, and he is only willing to eat some fish if he gets an extra
portion of chicken in return. Represent the preferences of Amaia and
Alejandro.


* 5.4

The preferences of a consumer can be described with the utility
function: $U(X, Y) = 5 X Y^2$. The consumer's income is \money{900}
and the prices are $P_X = \price{10}$ and $P_Y = \price{5}$. Calculate
and represent the consumer's optimal choice.


* 5.5

The optimal basket for a consumer with regular preferences contains
positive amounts of all goods. If the price of one of the goods
increases, will this reduce the consumer's utility? Justify your
answer.


* 5.6

The utility function of a consumer is $U (X, Y) = X Y$. The optimal
basket consists of 10 units of good $X$ and 5 units of good
$Y$. Knowing that the price of $X$ is \price{6}, how much is the
consumer's income?


* 5.7

A consumer has an income of \money{40} that she spends on goods $X$
and $Y$, whose prices are $P_X = \price{3}$ and $P_Y =
\price{2}$. When she consumes $20$ units of $Y$ and none of $X$, the
marginal rate of substitution is equal to $2$. Is this her optimal
choice or would she be better off buying more units of good $X$ and
less of good $Y$?


* 5.8

The function $U (N, Y) = (N + 4) Y$ describes the preferences of a
consumer between nuts, $N$, and a composite good that comprises the
money spent on all other goods, $Y$. The price of nuts is $P_N =
\price[kg]{8}$ and the consumer's income is $M =\money{40}$.

a) Obtain and represent the optimal choice of the consumer.

b) The Government aims to promote the consumption of nuts and it is
   considering different alternatives:

   + A subsidy that reduces the price of nuts by 20%. The subsidy
     can only be applied to the purchase of one and a half
     kilograms of nuts per consumer.

   + Give each consumer a voucher that can be redeemed for one and
     a half kilos of nuts.

   + Give each consumer \money{12} in cash.

   What would the consumer choose in each of these cases?

c) Which alternative would the consumer prefer? Justify your answer.


* 5.9

A consumer has an income of \money{800} to buy goods $X$ and $Y$,
whose prices are $P_X = \price{4}$ and $P_Y = \price{2}$. Her
preferences can be described by the following utility function:
#+begin_export latex
\[
  U (X, Y) = X^{0.25} Y^{0.75}
\]
#+end_export

a) Obtain the consumer's optimal choice.

b) If a price discount of \money{2} were applied to each unit of
   $X$ beyond the first 75 units, how would the optimal choice change?


* 5.10

The preferences of a consumer are given by the utility function:
$U(X, Y) = X (Y + 100)$. The price of good $X$ is \price{1} and
that of good $Y$ is \price{4}. The consumer has a monetary income
of \money{250}.

a) Determine the optimal consumption bundle.

b) If good $X$ were rationed so that nobody were allowed to buy
   more than 100 units of $X$, which would be the optimal choice?
   Represent graphically.


* 5.11

The utility function of an individual with respect to goods $X$
and $Y$ is given by $U(X, Y) = 3X + 3Y$. The market prices are
$P_X = \price{2}$ and $P_Y = \price{5}$ and the monetary income of
the consumer is $M = \money{100}$.

a) Is $(X, Y) = (10, 40)$ the optimal basket? Why?

b) Which is the optimal choice for the consumer?

c) How would the optimal choice change if $P_X = \price{10}$?


* 5.12

Rocío likes to eat cereal with milk for breakfast. She always
combines them in the same proportion: she adds exactly 20 grams of
cereal per every \units[ml]{250} of milk and discards any excess
of milk or cereal.

a) Represent Rocío's preferences regarding milk and cereal.

b) If Rocío spends \money{6} a month on milk and cereal, the
   price of the milk is \price[l]{0.80} and the price of cereals
   is \price[kg]{2}, what will be her optimal choice?
