# -*- ispell-dictionary: "spanish" -*-
#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 5

* La producción

1. Discuta la veracidad o falsedad de las siguientes afirmaciones:

   a) Si el producto marginal es decreciente, el producto medio debe
      ser también decreciente.

   b) Una fábrica contrata a un trabajador y posteriormente descubre
      que el producto medio de todos sus trabajadores ha aumentado. De
      esto se deduce que el producto marginal del nuevo trabajador
      está por debajo de la producción por trabajador antes de la
      nueva incorporación.

   c) En una empresa el producto marginal del trabajo es actualmente
      igual al producto medio. Si fuera uno de los trabajadores a
      contratar por la empresa preferiría que su salario
      correspondiera al valor del producto medio y no del producto
      marginal.

2. Dada la función de producción $Q = L^2K - L^3$ y sabiendo que $K =
   \units{4}$, determine:

   a) La función de producto total del trabajo.

   b) Las funciones de producto medio y marginal del trabajo.

   c) Los niveles de trabajo que hacen máximo el producto marginal, el
      producto medio y el producto total. Represente gráficamente los
      resultados obtenidos.

3. Considere las siguientes funciones de producción:

   + $Q  = K^{1/4} L^{1/4}$

   + $Q  = (2KL)^{1/2}$

   + $Q  = 2K + 3L$

   + $Q  = K^2 L^2$

   Para cada caso:

   a) ¿Qué tipo de rendimientos presenta la función de producción?

   b) Obtenga la tasa de sustitución entre los factores de producción.

   c) Compruebe si se cumple la ley de rendimientos decrecientes del
      factor trabajo cuando $K=\units{4}$.

4. Explique y justifique si considera correcta o incorrecta cada una
   de las siguientes afirmaciones (use el análisis gráfico cuando lo
   considere oportuno):

   a) En una empresa cuya función de producción, $Q = F(K, L)$, presenta
      rendimientos decrecientes de escala, si duplicamos el uso del
      factor capital se duplicará su producción.

   b) La función de producción $Q = K + L$, presenta rendimientos
      crecientes de escala.

1. Una fábrica utiliza trabajo y capital para producir
   zapatos. Después de aumentar el número de trabajadores en un 50% la
   producción crece en un 60%. ¿Quiere esto decir que la función de
   producción de la empresa presenta rendimientos crecientes a escala?

   #+begin_answer
     No. Cuando se habla de rendimientos a escala se hace referencia a
     una situación en la que /todos/ los factores de producción
     aumentan en la /misma/ proporción. En el caso descrito en el
     enunciado sólo aumenta el trabajo por lo que no es posible
     deducir qué tipo de rendimientos a escala presenta la función de
     producción.
   #+end_answer
