# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

#+TITLE: Exercise Booklet 3


1. La función de utilidad de un consumidor es $U = X^2 Y$, su renta es
   $M = \money{100}$ y los precios del bienes son $P_X = \price{10}$ y
   $P_Y = \price{10}$. Obtenga la curva renta consumo y la curva de
   Engel del bien $X$. Calcule la elasticidad renta de $X$.  ¿Qué tipo
   de bien es?

2. Considere un consumidor que sólo compra dos bienes. ¿Pueden ser
   inferiores los dos bienes simultáneamente?

3. Un consumidor compra solo dos bienes cuyos precios son $P_X =
   \price{1}$ y $P_Y = \price{1}$. La figura siguiente muestra su
   curva renta consumo:

   #+MATS: fig fig-probl-3_1004-crc1-*.pdf

   a) Si $M = \money{70}$, ¿qué cantidad demandará de cada uno de los
      bienes?

   b) ¿Alguno de los bienes es inferior? ¿Para qué valores de la
      renta?

4. Considere una economía competitiva donde todos los consumidores
   tienen las mismas preferencias y consumen alguna unidad tanto del
   bien $X$ como del bien $Y$. ¿Comprarán todos la misma cantidad del
   bien $X$?  ¿Habrá diferencias en las valoraciones del bien $X$ por
   parte de cada uno de los consumidores?

5. Las preferencias de un consumidor pueden representarse por la
   función de utilidad:
   #+begin_export latex
   \[
     U(X, Y) = X Y + 24 Y
   \]
   #+end_export
   El precio del bien $X$ es \price{6}, el del bien $Y$ es \price{8} y
   el consumidor dispone de una renta de \money{240}.

   a) Obtenga la curva de precio-consumo. ¿Qué tipo de relación se da
      entre los bienes $X$ e $Y$?

   b) Obtenga la curva de demanda del bien $X$.

6. Adela y Blas sólo consumen los bienes $X$ e $Y$ y cada uno dispone
   de \money{100}.  A Adela sólo le importa cuántas unidades de $X$
   puede consumir ya que el bien $Y$ no le reporta ninguna
   satisfacción. Por su parte, Blas está siempre dispuesto a
   intercambiar una unidad del bien $X$ por una unidad del bien
   $Y$. Los precios de los bienes son $P_X = \price{2}$ y $P_Y =
   \price{4}$. Obtenga las curvas de demanda del bien $X$ de Adela y
   Blas.

7. Las preferencias de un consumidor vienen dadas por la función de
   utilidad: $U(X, Y) = X^{1/4} Y^{1/8}$ y su renta es $M =
   \money{17496}$. Los precios son $P_X = \price{54}$ y $P_Y =
   \price{36}$.

   a) Calcule curva de demanda del bien $X$.

   b) Calcule cuánto varía el consumo de los dos bienes cuando el
      precio de $X$ disminuye hasta $P_X = \price{16}$.

   c) Descomponga el impacto sobre el consumo de cada uno de los
      bienes en los correspondientes efecto renta y efecto
      sustitución. ¿Cuál es el signo de los diferentes efectos?

8. Los bienes $X$ e $Y$ son complementos perfectos. Represente
   gráficamente como cambiaría la elección de consumo óptima si
   aumenta el precio del bien $X$. ¿Qué ocurre con el efecto
   sustitución y el efecto renta?

9. Dulce sigue comprando la misma cantidad de sal a pesar de que su
   precio ha disminuido un 50%. ¿Quiere esto decir que el efecto
   sustitución es nulo? ¿Es la sal un bien inferior para Dulce?

10. "La cantidad demandada de un bien Giffen aumenta cuando aumenta su
    precio y también aumenta cuando crece la renta de los
    consumidores."  ¿Es correcta la afirmación anterior?  Justifique
    su respuesta.

11. El siguiente gráfico muestra las elecciones óptimas de un
    consumidor antes y después de una disminución del precio del bien
    $X$:

    #+MATS: fig fig-probl-3_1004-fxs-*.pdf

    Observe que coinciden las pendientes de las curvas de indiferencia
    en las cestas $A$ y $B$, por un lado, y en las cestas $C$ y $D$,
    por otro lado.

    Descomponga el efecto total sobre el consumo de $X$ en efecto renta
    y efecto sustitución. Obtenga los signos de estos efectos y
    determine qué tipo de bien es $X$ para este consumidor.

12. El alcalde de Lazy Town ha decidido introducir un nuevo impuesto
    sobre las refrescos azucarados de \money{0.50} por lata de
    refresco. El impuesto se traslada por completo a los compradores y
    el precio de la lata aumenta desde \money{0.50} hasta
    \money{1.00}.

    Stephanie es una ciudadana típica de Lazy Town cuya función de
    utilidad es:
    #+begin_export latex
    \[
      U(R, Y) = (R + 20)^{0.1} Y^{0.9}
    \]
    #+end_export
    donde $R$ es el número de latas de refresco que consume e $Y$ es
    un bien compuesto que recoge los restantes gastos en
    alimentación. Stephanie dispone cada mes de \money{470} para
    gastar en $R$ e $Y$.

    a) ¿Cuántas latas de refresco consumía Stephanie al mes antes de
       la introducción del impuesto?

    b) Calcule la elección óptima de Stephanie después de la
       introducción del impuesto. ¿En cuántas latas se reduce su
       consumo de refrescos? ¿Cuánto dinero pagará por el impuesto?

    c) Ante las protestas de los habitantes de la ciudad, el alcalde
       decide mantener el impuesto pero entregar a cada ciudadano
       \money{14.50} en metálico. Calcule cuantas latas consumirá
       ahora Stephanie. ¿Sigue consumiendo menos refrescos que en la
       situación inicial?  ¿Entregará el ayuntamiento más dinero que
       el que recaude con el impuesto?
