# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 6.1

Considera las preferencias representadas en los siguientes gráficos,
donde las flechas indican la dirección en que aumenta la utilidad:

#+xxx: fig fig-probl-06_1004-maps-*.pdf

Determine en cada caso que supuestos de las preferencias regulares se están incumpliendo. Justifique su respuesta.

** Answer

Por hacer.


* 6.2

A Amaia le gusta el pescado, mientras que el pollo ni le gusta ni
le disgusta. Por su parte, a Alejandro no le gusta el pescado pero
sí el pollo y sólo está dispuesto a comer algo de pescado si a
cambio recibe una porción extra de pollo. Represente las
preferencias de Amaia y de Alejandro.


** Answer

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-06_1004-neutral-*.pdf
#+begin_center
Amaia
#+end_center
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-06_1004-bad-*.pdf
#+begin_center
Alejandro
#+end_center
#+xxx: endcol
#+latex: \vspace*{2ex}

Para Amaia el pollo es un bien neutral: su utilidad permanece
constante si consume más pollo y no cambia su consumo de pescado. Sólo
accedería a curvas de indiferencia superiores si se incrementa su
consumo de pescado.

Para Alejandro el pescado es un mal: su utilidad disminuye si crece su
consumo de pescado y no varía su consumo de pollo. Para mantenerse en
el mismo nivel de utilidad, un incremento de su consumo de pescado
debería compensarse con un incremento de su consumo de pollo.


* 6.3

Pablo se muestra indiferente entre la cesta $A$, que contiene 6
manzanas y 2 naranjas, y la cesta $B$, con 2 manzanas y 6
naranjas. Responda a las siguientes preguntas teniendo en cuenta que
las preferencias de Pablo son regulares:

a) Si Pablo tuviera que elegir entre la cesta $A$ y la cesta $C$, que
   contiene 3 manzanas y 7 naranjas, ¿cuál sería su mejor opción?

b) ¿Y si la elección fuera entre la cesta $A$ y la cesta $D$, con 4
   manzanas y 4 naranjas?

** Answer

Por hacer.


* 6.4

Sabiendo que las preferencias de un consumidor se pueden representar
con la función de utilidad $U(X, Y) = X Y$, complete los datos que
faltan en la siguiente tabla:

#+ATTR_LATEX: :booktabs t :center t :align @{}*{5}{rp{0.65cm}}r@{}
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|
| $X$ |   | $Y$ |   | $U$ |   | $\UMX$ |   | $\UMY$ |   | $\RMS$ |
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|
|   2 |   |   3 |   |     |   |     12 |   |        |   |        |
|   4 |   |     |   |     |   |      8 |   |        |   |        |
|     |   |     |   |     |   |      6 |   |      1 |   |        |
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|


** Answer

Por hacer.


* 6.5

La función de utilidad de Carlos es $U(X, Y) = X Y$. Si consume la
cesta $A$, que consta de 2 unidades del bien $X$ y 10 unidades del
bien $Y$:

a) ¿Cuál sería la utilidad de Carlos? ¿Aumentaría su utilidad si
   obtuviera 1 unidad más de $X$ a cambio de 2 unidades de $Y$?

b) Obtenga y represente la curva de indiferencia que contiene la cesta
   $A$.

c) En la cesta $A$, ¿a cuántas unidades del bien $Y$ estaría dispuesto
   a renunciar Carlos a cambio de una unidad adicional del bien $X$?


* 6.6

Las preferencias de Luna y Aurora son idénticas y se pueden
representar por la función de utilidad: $U(X, Y) = 6 X + 3 Y$. Luna
consume la cesta $L = (1, 5)$ mientras que Aurora consume la cesta $A
= (3, 2)$.

a) Calcule los niveles de utilidad de Luna y de Aurora.

b) Obtenga la relación marginal de sustitución de Luna y de Aurora.

c) Dibuje las curvas de indiferencia que pasan por las cestas $L$ y $A$.


** Answer

Por hacer.


* 6.7

 Carmen es coleccionista de fotos antiguas. Hoy ha acudido a un
 mercadillo donde ha comprado 50 fotos para su colección y aún dispone
 de \money{150} para otras compras. En uno de los puestos del
 mercadillo ha encontrado un lote de 10 fotos que le interesan y por
 el que piden \money{25}. La función de utilidad de Carmen es:
 #+begin_export latex
 \[
   U(F, Y) = (F + 10) Y^{2}
 \]
 #+end_export
 donde $F$ es el número de fotos que compra e $Y$ un bien compuesto.

 a) ¿Comprará el lote de 10 fotos?

 b) ¿Cuánto estará dispuesta a pagar Carmen por $10$ fotos adicionales?


** Answer

a) Si no comprara el lote de fotos, la utilidad de Carmen sería:
   #+begin_export latex
   \[ U(50, 150) = 60 \times 150^2 = \num{1350000}.\]
   #+end_export
   En cambio, si lo comprara, tendría 60 fotos y le quedarían
   \money{125} para gastar en otras cosas. Su utilidad sería:
   #+begin_export latex
   \[ U(60, 125) = 70 \times 125^2 = \num{1093750}.\]
   #+end_export
   Carmen no compraría el lote de fotos ya que disfruta de un mayor
   nivel de utilidad en ese caso.

b) Si Carmen comprara las fotos por $V$ euros su utilidad sería:
   #+begin_export latex
   \[ U(60, 150 -V) = 70 (150 - V)^2. \]
   #+end_export
   Carmen sólo compraría el lote de fotos si su utilidad no
   disminuyera:
   #+begin_export latex
   \[ U(60, 150 - V) \geq U(50, 150). \]
   #+end_export
   La expresión anterior implica:
   #+begin_export latex
   \[ 70 (150 - V)^2 \geq \num{1350000}. \]
   #+end_export
   Operando:
   #+begin_export latex
   \[
     V
     \leq 150 - \left(\frac{\num{1350000}}{70} \right)^{1/2}
     \approx \money{11.13}.
   \]
   #+end_export
   Carmen pagaría hasta \money{11.13} por el lote de 10 fotos.
