#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 3


* Variaciones en la renta o en el precio de un bien

1. Un consumidor dispone de una renta monetaria de $M =
   \money{16}$. Sus preferencias pueden describirse con la función de
   utilidad $U(X, Y) = X Y$. Inicialmente se encuentra en equilibrio
   adquiriendo 4 unidades del bien $X$ y 8 unidades del bien $Y$. Los
   precios de los bienes $X$ e $Y$ son $P_X = \price{2}$ y $P_Y =
   \price{1}$.

   a) Represente la situación de equilibrio inicial.

   b) Suponga que el precio de $X$ disminuye hasta situarse en $P'_X =
      \price{1}$. Deduzca y represente la nueva situación de
      equilibrio.

   c) Obtenga y represente la curva de precio consumo y la función de
      demanda.

   d) Dada la situación de equilibrio inicial, suponga un incremento
      de la renta igual a \money{4}. Calcule el nuevo equilibrio y
      represéntelo gráficamente.

   e) Obtenga y represente la curva renta consumo y la curva de Engel.

2. Las preferencias de un consumidor vienen dadas por la función de
   utilidad: $U(X, Y) = X^2 Y$ y su renta es $M = \money{1200}$. Los
   precios de los bienes $X$ e $Y$ son $P_X = P_Y = \price{4}$.

   a) Calcule y represente la situación de equilibrio así como la
      función de demanda del bien $X$.

   b) ¿Qué tipo de relación hay entre los bienes $X$ e $Y$?

   c) Calcule el efecto sobre el consumo de los dos bienes de una
      disminución en el precio por unidad del bien $X$ en \money{3}.

   d) Descomponga, tanto gráfica como analíticamente, el impacto sobre
      el consumo de ambos bienes de la variación en el precio de $X$ en
      los efectos renta y sustitución.

3. La función de utilidad de un consumidor es $U(X, Y) = X^{1/4}
   Y^{1/8}$, mientras que $P_X = \price{2}$, $P_Y = \price{3}$ y $M =
   \money{340}$.

   a) Calcule la cesta de consumo óptima.

   b) Suponga que el precio por unidad del bien $X$ sube en
      \money{2}. Calcule los efectos totales sobre las demandas de los
      bienes $X$ e $Y$.

   c) Descomponga los efectos totales en efecto sustitución y efecto
      renta.

   d) Calcule las funciones de demanda de los bienes $X$ e $Y$.

4. En una pequeña ciudad cada uno de los vecinos se gasta \money{38}
   al mes en actividades deportivas, $D$, y culturales, $C$. El precio
   unitario de cada una de estas actividades es de $P_D = \price{2}$ y
   $P_C = \price{1}$. Las preferencias de cada uno de los vecinos con
   respecto a estas actividades pueden representarse por la función de
   utilidad: $U(D, C) = D C + C$.

   a) Determine el número de actividades deportivas y culturales que
      debería ofrecer el ayuntamiento si pretende maximizar la
      utilidad de los vecinos.

   b) Suponga que el equipo de gobierno aprueba el llamado Plan de
      Fomento del Deporte de modo que se subvenciona el 50% del precio
      de las actividades deportivas. Obtenga y represente gráficamente
      el impacto que tendrá la política municipal sobre las decisiones
      consumo de los residentes.

   c) Descomponga el efecto total del Plan en los efectos renta y
      sustitución.

5. Las preferencias de un consumidor pueden representarse por la
   función de utilidad: \[ U(X, Y) = X^2 Y \] El precio del bien
   $X$ es \price{4} y el del bien $Y$ es \price{2}. El consumidor
   dispone de una renta monetaria de \money{120}.

   a) Calcule la elección óptima de consumo.

   b) Obtenga la curva de Engel del bien $X$.

6. Las preferencias de un consumidor pueden representarse por la
   función de utilidad: \[ U(X, Y) = X^3 Y^2 \] El precio del bien
   $X$ es \price{6} y el del bien $Y$ es \price{8}. El consumidor
   dispone de una renta monetaria de \money{240}.

   a) Calcule la elección óptima de consumo.

   b) Obtenga la curva de precio-consumo.

7. Explique y justifique si considera correcta o incorrecta cada una
   de las siguientes afirmaciones (use el análisis gráfico cuando lo
   considere oportuno):

   a) La función de utilidad de un consumidor es: $U(X, Y) = X
      Y$. Partiendo de una situación de equilibrio, un aumento de la
      renta del consumidor elevará la cantidad que consume de cada
      uno de los bienes, ya que un aumento en la renta genera un
      efecto sustitución en el consumo con signo positivo.

   b) Si un aumento del precio del bien genera un efecto renta o
      sustitución positivo, podemos asegurar que el bien en cuestión
      es un bien inferior.

   c) Suponiendo que el bien $X$ es un bien inferior, un aumento de
      su precio provocaría un efecto renta negativo, dando lugar a un
      descenso en el consumo final del bien $X$.

8. Las preferencias de un consumidor están definidas por la función
   de utilidad: \[ U(X, Y) = X Y ^{1/2}. \] Este individuo dispone de
   una renta de \money{600} y los precios unitarios de ambos bienes son
   iguales a \money{2}.

   a) Obtenga el equilibrio del consumidor. Suponga ahora que el
      precio unitario del bien $X$ se incrementa a \money{4}. ¿Cuál
      será la nueva cesta óptima?

   b) Descomponga el efecto total sobre el consumo del bien $X$ en
      efecto renta y efecto sustitución. Interprete los
      resultados. El bien $X$, ¿es normal o inferior?

9. Las preferencias de un consumidor están representadas por la
   siguiente función de utilidad: $U(X, Y) = 2 X Y$. Este individuo
   dispone de una renta de \money{40} y los precios son $P_X =
   \price{3}$ y $P_Y = \price{4}$.

   a) Calcule la cantidad que consumirá de cada uno de los bienes
      para maximizar su utilidad.

   b) Calcule el efecto total sobre el consumo del bien $X$ de una
      disminución en el precio del bien $X$ de \price{1}.

   c) Calcule el efecto sobre el consumo de $X$ de un aumento de la
      renta de $\money{10}$ y explique el valor que toma el efecto
      sustitución en este caso.

10. Las preferencias de un consumidor están representadas por la
    siguiente función de utilidad: $U(X, Y) = X Y$. Este individuo
    dispone de una renta de \money{150} y los precios son $P_X =
    \price{10}$ y $P_Y = \price{10}$.

    a) Calcule la cantidad que consumirá de cada uno de los bienes
       para maximizar su utilidad y el efecto que tendrá sobre la
       cesta óptima un aumento en el precio del bien $X$ hasta
       \price{12}.

    b) Descomponga analítica y gráficamente el impacto sobre el
       consumo del bien $X$ en efecto renta y efecto
       sustitución. Teniendo en cuenta los resultados obtenidos,
       identifique qué tipo de bien es $X$.

11. El siguiente gráfico muestra las elecciones óptimas de un
    consumidor antes y después de una disminución del precio del bien
    $X$:

    #+MATS: fig fig-probl-3_1004-fxs-*.pdf

    Observe que la tasa a la que estaría dispuesto el consumidor a
    sustituir $X$ por $Y$ es la misma en los puntos $A$ y $B$, por un
    lado, y en los puntos $C$ y $D$, por otro lado.

    Descomponga el efecto total sobre el consumo de $X$ en efecto renta
    y efecto sustitución. Obtenga los signos de estos efectos y
    determine qué tipo de bien es $X$ para este consumidor.

    #+begin_answer
    - Las restricciones presupuestarias antes y después del cambio en
      el precio son las rectas que cortan el eje de ordenadas en
      $M/P_Y$. La restricción inicial es la más próxima al origen en el
      gráfico ya que corresponde a un precio más alto de $X$. La cesta
      óptima a los precios iniciales es $A$, mientras que la elección
      óptima cuando disminuye el precio de $X$ es $C$.  El efecto total
      es:
      \begin{equation*}
        \mathit{ET} = X_{C} - X_{A} = 30 - 15 = 15\text{\ unidades.}
      \end{equation*}
      La cesta $D$ corresponde a la decisión del consumidor cuando los
      precios son los finales pero la renta real (nivel de utilidad) es
      la inicial. El efecto sustitución sería:
      \begin{equation*}
        \mathit{ES} = X_{D} - X_{A} = 35 - 15 = 20\text{\ unidades.}
      \end{equation*}
      El efecto renta es:
      \begin{equation*}
        \mathit{ER} = X_{C} - X_{D} = 30 - 35 = -5\text{\ unidades.}
      \end{equation*}

    - El precio de $X$ disminuye al mismo tiempo que aumenta la
      cantidad demandada por lo que el signo del /efecto total/ es
      /negativo/. De la misma forma el /efecto sustitución/ es
      /negativo/, ya que precio y cantidad se mueven en dirección
      contraria cuando se mantiene la renta real constante. Finalmente,
      el cambio en el precio y el cambio en la demanda atribuible a una
      variación de la renta real son ambos negativos en nuestro caso,
      por lo que el /efecto renta/ es /positivo/. Por lo tanto, $X$ es
      un bien inferior y su curva de demanda tiene pendiente negativa.
    #+end_answer

12. Las preferencias de un consumidor pueden representarse por la
    función de utilidad: $U(X, Y) = X (Y + 100)$. El precio del bien
    $X$ es \price{1} y el del bien $Y$ es \price{4}. El consumidor
    dispone de una renta monetaria de \money{250}. Calcule la elección
    óptima y represente gráficamente el equilibrio del
    consumidor. Obtenga la curva de demanda del bien $X$.

    #+begin_answer
    - La restricción presupuestaria es:
      \begin{equation*}
        250 = X + 4 Y
      \end{equation*}
      mientras que la tangencia de la restricción y una curva de
      indiferencia implica:
      \begin{equation*}
        \mathit{RMS} = (Y + 100)/X = 1/4 = P_X/P_Y
      \end{equation*}
      Operando en la expresión anterior: $X = 4 Y + 400$. Sustituyendo
      en la restricción presupuestaria: $Y = \units{-18.75}$. Esto
      quiere decir que la elección óptima del consumidor corresponde a
      una solución de esquina donde no consume ninguna unidad del bien
      $Y$ y gasta toda su renta en el bien $X$:
      \begin{equation*}
        X = M / P_X = \units{250}
      \end{equation*}

      #+MATS: fig fig-probl-3_1004-corner-*.pdf

    - Los puntos de la curva de demanda tienen que satisfacer las
      siguientes condiciones:
      \begin{gather*}
        250 = P_{X} X + 4 Y \\
        (Y + 100)/X = P_{X}/4
      \end{gather*}
      Operando en la segunda ecuación: $P_X X = 4 Y + 400$ y
      sustituyendo en la primera ecuación se obtiene $Y =
      \units{-18.75}$ sea cual sea $P_X$. Por tanto, sea cual sea el
      precio de $X$ el consumidor no compra ninguna unidad del bien $Y$
      y gasta toda su renta en el bien $X$. En estas condiciones, la
      curva de demanda del bien $X$ es:
      \begin{equation*}
        X = 250 / P_X
      \end{equation*}
    #+end_answer

13. La función de utilidad $U = X^2 Y$ describe las preferencias de un
    consumidor que dispone de una renta de \money{100}. Los precios de
    los bienes $X$ e $Y$ son $P_X = \price{10}$ y $P_Y =
    \price{10}$. Obtenga la curva de Engel del bien $X$. Calcule la
    elasticidad renta de $X$ y determine de qué tipo es.
    #+begin_answer
      Para obtener la curva de Engel necesitamos considerar como cambia
      la decisión óptima del consumidor al cambiar la renta. Por un
      lado, obtenemos la senda de expansión de la renta:
      \[ \mathit{RMS} = 2 Y/X = 10 / 10 = P_X/P_Y \]
      por lo que:
      \[ Y = X / 2 \]
      Por otro lado, consideramos la restricción presupuestaria:
      \[ M = 10 X + 10 Y \]
      Utilizando estas dos ecuaciones y operando, obtenemos la curva de Engel:
      \[ X(M) = M / 15 \]

      Elasticidad renta:
      \[ \frac{\mathit{d}\,X}{\mathit{d}\,M} \frac{M}{X} = 1/15 \cdot \frac{100}{100/15} = 1 \]
      La elasticidad renta es unitaria: el bien $X$ es un bien normal.
    #+end_answer
