#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 3


* Variaciones en la renta o en el precio de un bien

1. Un consumidor dispone de una renta monetaria de $M =
   \money{16}$. Sus preferencias pueden describirse con la función de
   utilidad $U(X, Y) = X Y$. Inicialmente se encuentra en equilibrio
   adquiriendo 4 unidades del bien $X$ y 8 unidades del bien $Y$. Los
   precios de los bienes $X$ e $Y$ son $P_X = \price{2}$ y $P_Y =
   \price{1}$.

   a) Represente la situación de equilibrio inicial.

   b) Suponga que el precio de $X$ disminuye hasta situarse en $P'_X =
      \price{1}$. Deduzca y represente la nueva situación de
      equilibrio.

   c) Obtenga y represente la curva de precio consumo y la función de
      demanda.

   d) Dada la situación de equilibrio inicial, suponga un incremento
      de la renta igual a \money{4}. Calcule el nuevo equilibrio y
      represéntelo gráficamente.

   e) Obtenga y represente la curva renta consumo y la curva de Engel.

2. Las preferencias de un consumidor vienen dadas por la función de
   utilidad: $U(X, Y) = X^2 Y$ y su renta es $M = \money{1200}$. Los
   precios de los bienes $X$ e $Y$ son $P_X = P_Y = \price{4}$.

   a) Calcule y represente la situación de equilibrio así como la
      función de demanda del bien $X$.

   b) ¿Qué tipo de relación hay entre los bienes $X$ e $Y$?

   c) Calcule el efecto sobre el consumo de los dos bienes de una
      disminución en el precio por unidad del bien $X$ en \money{3}.

   d) Descomponga, tanto gráfica como analíticamente, el impacto sobre
      el consumo de ambos bienes de la variación en el precio de $X$ en
      los efectos renta y sustitución.

3. La función de utilidad de un consumidor es $U(X, Y) = X^{1/4}
   Y^{1/8}$, mientras que $P_X = \price{2}$, $P_Y = \price{3}$ y $M =
   \money{340}$.

   a) Calcule la cesta de consumo óptima.

   b) Suponga que el precio por unidad del bien $X$ sube en
      \money{2}. Calcule los efectos totales sobre las demandas de los
      bienes $X$ e $Y$.

   c) Descomponga los efectos totales en efecto sustitución y efecto
      renta.

   d) Calcule las funciones de demanda de los bienes $X$ e $Y$.

4. En una pequeña ciudad cada uno de los vecinos se gasta \money{38}
   al mes en actividades deportivas, $D$, y culturales, $C$. El precio
   unitario de cada una de estas actividades es de $P_D = \price{2}$ y
   $P_C = \price{1}$. Las preferencias de cada uno de los vecinos con
   respecto a estas actividades pueden representarse por la función de
   utilidad: $U(D, C) = D C + C$.

   a) Determine el número de actividades deportivas y culturales que
      debería ofrecer el ayuntamiento si pretende maximizar la
      utilidad de los vecinos.

   b) Suponga que el equipo de gobierno aprueba el llamado Plan de
      Fomento del Deporte de modo que se subvenciona el 50% del precio
      de las actividades deportivas. Obtenga y represente gráficamente
      el impacto que tendrá la política municipal sobre las decisiones
      consumo de los residentes.

   c) Descomponga el efecto total del Plan en los efectos renta y
      sustitución.

5. Las preferencias de un consumidor pueden representarse por la
   función de utilidad: \[ U(X, Y) = X^2 Y \] El precio del bien
   $X$ es \price{4} y el del bien $Y$ es \price{2}. El consumidor
   dispone de una renta monetaria de \money{120}.

   a) Calcule la elección óptima de consumo.

   b) Obtenga la curva de Engel del bien $X$.

6. Las preferencias de un consumidor pueden representarse por la
   función de utilidad: \[ U(X, Y) = X^3 Y^2 \] El precio del bien
   $X$ es \price{6} y el del bien $Y$ es \price{8}. El consumidor
   dispone de una renta monetaria de \money{240}.

   a) Calcule la elección óptima de consumo.

   b) Obtenga la curva de precio-consumo.

7. Explique y justifique si considera correcta o incorrecta cada una
   de las siguientes afirmaciones (use el análisis gráfico cuando lo
   considere oportuno):

   a) La función de utilidad de un consumidor es: $U(X, Y) = X
      Y$. Partiendo de una situación de equilibrio, un aumento de la
      renta del consumidor elevará la cantidad que consume de cada
      uno de los bienes, ya que un aumento en la renta genera un
      efecto sustitución en el consumo con signo positivo.

   b) Si un aumento del precio del bien genera un efecto renta o
      sustitución positivo, podemos asegurar que el bien en cuestión
      es un bien inferior.

   c) Suponiendo que el bien $X$ es un bien inferior, un aumento de
      su precio provocaría un efecto renta negativo, dando lugar a un
      descenso en el consumo final del bien $X$.

8. Las preferencias de un consumidor están definidas por la función
   de utilidad: \[ U(X, Y) = X Y ^{1/2}. \] Este individuo dispone de
   una renta de \money{600} y los precios unitarios de ambos bienes son
   iguales a \money{2}.

   a) Obtenga el equilibrio del consumidor. Suponga ahora que el
      precio unitario del bien $X$ se incrementa a \money{4}. ¿Cuál
      será la nueva cesta óptima?

   b) Descomponga el efecto total sobre el consumo del bien $X$ en
      efecto renta y efecto sustitución. Interprete los
      resultados. El bien $X$, ¿es normal o inferior?

9. Las preferencias de un consumidor están representadas por la
   siguiente función de utilidad: $U(X, Y) = 2 X Y$. Este individuo
   dispone de una renta de \money{40} y los precios son $P_X =
   \price{3}$ y $P_Y = \price{4}$.

   a) Calcule la cantidad que consumirá de cada uno de los bienes
      para maximizar su utilidad.

   b) Calcule el efecto total sobre el consumo del bien $X$ de una
      disminución en el precio del bien $X$ de \price{1}.

   c) Calcule el efecto sobre el consumo de $X$ de un aumento de la
      renta de $\money{10}$ y explique el valor que toma el efecto
      sustitución en este caso.

10. Las preferencias de un consumidor están representadas por la
    siguiente función de utilidad: $U(X, Y) = X Y$. Este individuo
    dispone de una renta de \money{150} y los precios son $P_X =
    \price{10}$ y $P_Y = \price{10}$.

    a) Calcule la cantidad que consumirá de cada uno de los bienes
       para maximizar su utilidad y el efecto que tendrá sobre la
       cesta óptima un aumento en el precio del bien $X$ hasta
       \price{12}.

    b) Descomponga analítica y gráficamente el impacto sobre el
       consumo del bien $X$ en efecto renta y efecto
       sustitución. Teniendo en cuenta los resultados obtenidos,
       identifique qué tipo de bien es $X$.
