# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

* 6.1

The utility function of a consumer is $U = X^2 Y$, her income is $M =
\money{100}$ and the prices of the goods are $P_X = \price{10}$ and
$P_Y = \price{10}$. Obtain the income consumption curve and the Engel
curve for good $X$. Calculate the income elasticity of $X$. What kind
of good is X?

** Answer

Not done yet.


* 6.2

The following graph shows the ICC of a consumer when the price of good
$X$ is $P_X = \price{10}$ and the price of good $Y$ is $\price{20}$:

#+xxx: fig fig-probl-6_1004-crc20-*.pdf

Plot the Engel curve for the two goods. What kind of goods are $X$ and $Y$?


** Answer

Not done yet.


* 6.3

A consumer purchases only two goods whose prices are $P_X =
\price{1}$ and $P_Y = \price{1}$. The following figure shows her
income consumption curve:

#+xxx: fig fig-probl-6_1004-crc1-*.pdf

a) If $M = \money{70}$, how many units would she demand of each one
   of the goods?

b) Is any of the two goods an inferior good? For what values of the
   income?

** Answer

Not done yet.


* 6.4

Consider a consumer who only buys two goods. Is it possible that the
two goods are inferior goods simultaneously?

** Answer

Not done yet.


* 6.5

The preferences of a consumer can be represented by the utility
function:
#+begin_export latex
\[
  U (X, Y) = X Y^{4}
\]
#+end_export
The price of good $X$ is \price{6}, the price of good $Y$ is
\price{8} and the consumer has an income of \money{240}.

a) Obtain and plot the price-consumption curve. What kind of relationship
   exists between $X$ and $Y$?

b) Obtain and plot the demand curve for good $X$. Calculate the price
   elasticity of demand.

** Answer

Not done yet.


* 6.6

The following graph shows the PCC of a consumer when the price of good
$Y$ is $P_Y = \price{2}$ and the income is $M= \money{120}$:

#+xxx: fig fig-probl-6_1004-cpc22-*.pdf

a) How many units of good $X$ would the consumer buy if the price of
   that good is $P_X = \price{2}$? And how many units would she buy of
   good $Y$?

b) Also obtain the quantity demanded of $X$ when $P_X$ takes the values
   $3, 4, 4.8$, and \price{6} and represent the demand curve of good $X$.

c) What kind of relationship does it exist between goods $X$ and $Y$?


** Answer

Not done yet.


* 6.7

The optimal basket for a consumer with regular preferences contains
positive amounts of all goods. If the price of one of the goods
increases, will this reduce the consumer's utility? Explain how the
consumer's utility varies along the demand curve. Justify your answers.


** Answer

Not done yet.


* 6.8

In a market $n$ identical consumers participate and the demand curve
for each one of them is:
#+begin_export latex
  \[ X_i^d(P_X) = a - b P_X \qquad
     \begin{array}{l}a,b > 0\\ i = 0, 1, \dots, n\end{array}\]
#+end_export

a) Determine the slope of the market demand curve. When you represent
   it graphically, will be the slope higher or lower that that of the
   individual demand curves?

b) What is the relationship between the price elasticity of individual
   demands and the price elasticity of the market demand curve?


** Answer

Not done yet.


* 6.9

Both Adela and Blas have \money{100} to spend on goods $X$ and
$Y$. Adela only cares about how many units of $X$ she can consume,
since she does not get any satisfaction from good $Y$. On the other
side, Blas is always willing to exchange a unit of good $X$ for a
unit of good $Y$. The prices of the goods are $P_X = \price{2}$ and
$P_Y = \price{4}$. Obtain the demand curves for good $X$ of Adela
and Blas.


** Answer

Not done yet.


* 6.10

Rocío likes eating milk with cereals. She always combines them in the
same proportion: she adds exactly \units[g]{20} of cereals by each
[ml]{250} of milk and she throws away all the additional amount of
either milk or cereals.  Obtain the demand curve for cereals knowing
that the price of milk is \price[l]{0.80} and that Rocío spends
\money{6} per month on milk and cereals. If cereals are sold at
\price[kg]{2}, which quantity will Rocío demand?


** Answer

Not done yet.


* 6.11

The preferences of a consumer are given by the utility function:
$U(X, Y) = X^{1/4} Y^{1/8}$ and her income is $M = \money{17496}$.
Prices are $P_X = \price{54}$ and $P_Y = \price{36}$.

a) Obtain the demand curve for good $X$.

b) Calculate how much the consumption of the two goods varies when the
   price of good $X$ decreases to $P_X = \price{16}$.

c) Decompose the impact on each good's consumption into the
   corresponding income and substitution effects.  What is
   the sign of these effects?

** Answer

Not done yet.


* 6.12

The goods $X$ and $Y$ are perfect complements. Represent
graphically how the optimal consumption choice would change if the
price of good $X$ increases. Decompose the total effect on the
consumption of $X$ into the substitution effect and the income
effect.


* 6.13

Dulce keeps buying the same amount of salt even though its price
has decreased by 50%. Does this mean that the substitution effect
is zero? Is salt an inferior good for Dulce?

** Answer

Not done yet.


* 6.14

"The quantity demanded of a Giffen good increases with its price
and also increases when the consumer's income increases." Is the
previous statement correct? Justify your answer.

** Answer

Not done yet.


* 6.15

The following graph shows the optimal choices of a consumer before
and after a decrease in the price of good $X$:

#+xxx: fig fig-probl-6_1004-fxs-*.pdf

Note that the slopes of the indifference curves are the same in
the baskets $A$ and $B$, on the one hand, and in the baskets $C$
and $D$, on the other hand.

Decompose the total effect on consumption of $X$ into the income
effect and the substitution effect. Obtain the signs of these
effects and determine what kind of good is $X$ for this consumer.

** Answer

Not done yet.


* 6.16

The mayor of Lazy Town has decided to introduce a new tax on
sugary drinks of \money{0.50} per can of soda. The tax is
completely transferred to buyers and the price of the can
increases from \money{0.50} to \money{1.00}.

Stephanie is a typical citizen of Lazy Town whose utility function is:
#+begin_export latex
\[
  U (S, Y) = (S + 20)^{0.1} Y^{0.9}
\]
#+end_export
where $S$ is the number of soda cans she consumes and $Y$ is a
composite good that includes her remaining expenditure on
food. Stephanie has \money{470} every month to spend on $S$ and
$Y$.

a) How many cans of soda did Stephanie consume per month before
   the introduction of the tax?

b) Calculate Stephanie's optimal choice after the introduction of
   the tax. Is this tax effective in reducing her consumption of
   sugary drinks? How much money will she pay for the tax?

c) In view of the increasing complaints from the inhabitants of
   the city, the mayor decides to keep the tax and give
   \money{14.50} in cash to each citizen. Calculate how many cans
   will Stephany consume now. Is she still consuming less soda
   than in the initial situation?  Is the city council spending
   more money than the amount collected with the tax?

** Answer

a) Restricción presupuestaria: $470 = 0.5 R + Y$.

   Condición de tangencia: $(1/9) Y/(R + 20) = 0.5$.

   Elección óptima: $R_1 = 76$ latas e $Y_1 = \money{432}$.

b) Restricción presupuestaria: $470 = R + Y$.

   Condición de tangencia: $(1/9) Y/(R + 20) = 1$.

   Elección óptima: $R_2 = 29$ latas e $Y_2 = \money{441}$.

   Paga: $R_2 t = \money{14.5}$.

c) Restricción presupuestaria: $484.5 = R + Y$.

   Condición de tangencia: $(1/9) Y/(R + 20) = 1$.

   Elección óptima: $R_3 = 30.45$ latas e $Y_3 = \money{454.05}$.

   La recaudación del impuesto per capita, $0.5 R_3 = \money{15.225}$,
   es superior a la cuantía del cheque, \money{14.50}.
