# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

#+TITLE: Exercise Booklet 1


1. An economy produces two goods, vehicles and food, using labor as
   the only factor of production. There are \num{50000} labor hours
   available. The following table shows how many units of each good
   can be produced according to the labor hours devoted to each
   activity:

   #+ATTR_LATEX: :booktabs t :center t :align rrp{1cm}rr
   |-------------+--------------+---+-------------+--------------|
   | Labor       | Vehicles     |   | Labor       | Food         |
   | (hours)     | (units)      |   | (hours)     | (kg)         |
   |-------------+--------------+---+-------------+--------------|
   | \num{0}     | \num{0}      |   | \num{0}     | \num{0}      |
   | \num{12500} | \num{40000}  |   | \num{12500} | \num{50000}  |
   | \num{25000} | \num{70000}  |   | \num{25000} | \num{75000}  |
   | \num{37500} | \num{90000}  |   | \num{37500} | \num{90000}  |
   | \num{50000} | \num{100000} |   | \num{50000} | \num{100000} |
   |-------------+--------------+---+-------------+--------------|

   a) Draw the Production Possibility Frontier, PPF.

   b) What effect on the PPF would have an improvement on the
      procedures used in the production of food that raises the output
      per labor hour? And an organizational improvement in the
      production chain of vehicles? And what would happen if both
      improvements occur simultaneously as a result of a widespread
      technical progress?

   c) Which would be the consequences on the PPF of the reduction of
      the labor hours by half as a result of an armed conflict?

2. The table below shows different efficient production combinations
   for an economy in which there are only two goods: $X$ and $Y$.

   #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{>{\raggedleft\arraybackslash}p{2cm}}
   |-----+------------+------------|
   |     | $X$        | $Y$        |
   |-----+------------+------------|
   | *A* | \num{20}   | \num{0}    |
   | *B* | \num{18}   | \num{1}    |
   | *C* | \num{15}   | \num{2}    |
   | *D* | \num{11}   | \num{3}    |
   | *E* | \num{6}    | \num{4}    |
   | *F* | \num{0}    | \num{5}    |
   |-----+------------+------------|

   a) Draw the PPF. What can be said about the particular shape of PPF?

   b) Is it feasible to produce 2 units of $Y$ and 10 units of $X$?
      What happens in this situation?

   c) Construct a table that reflects the opportunity cost of
      producing each unit of $Y$.

   d) How many units of $X$ must be given up to produce the first
      unit of $Y$? And the second one?

3. The following figure shows the production possibilities frontier of
   an economy where only fish and coconuts are produced:

   #+MATS: fig fig-probl-1_1004-ppf-*.pdf

   Sort the production options $A$, $B$, $C$, and $D$ from higher to
   lower opportunity cost of producing fish.

4. State whether the following sentence is true or false and justify
   your answer: "When a great number of unemployed workers find a job,
   the production possibilities frontier shifts to the right."

5. El mercado de un bien está formado por tres compradores cuyas
   curvas de demanda son:

   #+ATTR_LATEX: :center t :align lc
   | Comprador 1: | $Q^d_1(P) = 1000 - 10 P$ |
   | Comprador 2: | $Q^d_2(P) = 600 - 2 P$   |
   | Comprador 3: | $Q^d_3(P) = 750 - 5 P$   |

   Determine la curva de demanda de mercado.

6. En el mercado de un bien participan \num{1000} compradores
   idénticos, cada uno de ellos con curva de demanda:
   #+begin_export latex
   \[
     Q^d_i(P) = 5 - P, \qquad i = 1, ..., \num{1000}.
   \]
   #+end_export
   El bien es vendido por \num{625} empresas idénticas, cada una
   con curva de oferta:
   #+begin_export latex
   \[
     Q^o_j(P) = 2.4 P , \qquad j = 1, ..., \num{625}.
   \]
   #+end_export

   a) Halle las curvas de demanda y oferta de mercado y la
      solución de equilibrio. Represente gráficamente.

   b) ¿Qué ocurriría si el precio de mercado fuera \price{4}? ¿Y si
      el precio de mercado fuera \price{1}?

7. "Durante los años que van desde 2003 hasta 2006 el precio de la
   gasolina aumentó considerablemente y, sin embargo, el consumo de
   gasolina creció." ¿Contradice esta afirmación la ley de la demanda?

8. Considere un mercado competitivo de manzanas y use un diagrama de
   oferta y demanda para analizar cómo afectaría al equilibrio una
   enfermedad de los manzanos que perjudique a la cosecha. ¿Es posible
   que los ingresos de los agricultores aumenten en este caso? ¿Qué
   condiciones se tendrían que cumplir?

9. Ante el aumento del consumo de drogas en un país, los expertos han
   señalado dos posibles explicaciones alternativas:

   - Una presencia policial cada vez más reducida en las calles ha
     favorecido el aumento del número de traficantes.

   - La reducción de programas de educación y de apoyo a los adictos
     han reducido la concienciación de una parte de la sociedad acerca
     de los peligros de las drogas.

   Utilice diagramas de oferta y demanda para analizar cada una de
   esas hipótesis. ¿Es posible discriminar entre esas dos
   explicaciones observando qué ha ocurrido con el precio y la
   cantidad consumida de drogas?

10. Las medicinas tienen una demanda inelástica mientras que los
    ordenadores tienen una demanda elástica. Suponga que como
    consecuencia del progreso tecnológico la oferta de ambos productos
    se duplica.

    a) ¿Qué ocurrirá con el equilibrio en cada uno de estos mercados?
       Represente gráficamente.

    b) ¿En qué mercado se experimentará el mayor cambio en el precio?
       ¿Y el mayor cambio en la cantidad?

    c) ¿Cómo se verá afectado el gasto de los consumidores en cada
       bien?

11. En el mercado del bien $X$ las curvas de demanda y de oferta son:
    \begin{gather*}
      X^d = \num{85000} - 20 P_X \\
      X^o = \num{15000} + 15 P_X
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

    b) Represente gráficamente los efectos sobre el equilibrio de un
       aumento del precio de un bien sustitutivo, /ceteris
       paribus/. ¿Es posible predecir inequívocamente cómo cambiará el
       precio de equilibrio del bien $X$? ¿Y la cantidad de equilibrio?

    c) Partiendo de la situación inicial, represente los efectos sobre
       el equilibrio de un aumento de la renta de los consumidores,
       /ceteris paribus/. ¿Es posible predecir inequívocamente cómo
       cambiarán el precio y la cantidad de equilibrio?

12. El mercado de coches eléctricos de un país es competitivo y
    actualmente las curvas de demanda y oferta son:
    #+begin_export latex
    \begin{gather*}
      Q^{d} = \num{10000} - P/6 \\
      Q^{o} = -6000 + P/2
    \end{gather*}
    #+end_export
    a) Determine el precio y la cantidad de equilibrio.

    b) Calcule el nuevo equilibrio si la demanda aumenta en un 20%
       (para cada precio se demanda una cantidad un 20% superior) y la
       oferta pasa a ser:
       #+begin_export latex
       \[
         Q^o = -2700 + P/2
       \]
       #+end_export
       Represente gráficamente.

13. El mercado de un bien inferior se encuentra en equilibrio. Si
    simultáneamente se encarecen los costes de producción y aumenta la
    renta de los consumidores, ¿disminuirán tanto el precio como la
    cantidad en el nuevo equilibrio?

14. Cuando un país subió los impuestos sobre el tabaco, el precio
    medio de la cajetilla subió de \money{4} a \money{4.6}. Se estimó
    que como consecuencia de esta subida de precio la cantidad
    demandada cayó de $52$ a $47.5$ millones de cajetillas.  Calcule
    la elasticidad de la demanda de tabaco.

15. Dos conductores repostan todos los lunes en la misma
    gasolinera. Ninguno de los dos mira nunca el precio y siempre
    actúan igual: mientras que uno pide $15$ litros, el otro pide
    \money{20} de gasóleo. ¿Cuál es la elasticidad precio de la
    demanda de cada conductor?

16. Ana paga \money{2} por cada unidad de alimentos, gasta \money{5000}
    en alimentos al año y su renta monetaria anual es de
    \money{25000}. En esta situación, la elasticidad-precio de su
    demanda anual de alimentos es $-1$ mientras que la
    elasticidad-renta es $0.5$. ¿Cuál sería el consumo de alimentos de
    Ana si obtiene una beca de \money{1000} que puede gastar libremente
    en aquello que prefiera?

17. El mercado del bien $X$ está caracterizado por las siguientes
    funciones de demanda y oferta:
    #+begin_export latex
    \begin{gather*}
      X^d = 250 - 30 P_{X} + 2 R - 5 P_{Y}, \\
      X^o = 15 P_{X} - 25,
    \end{gather*}
    #+end_export
    donde $R$ es la renta media de los consumidores y $P_Y$ el precio
    del bien $Y$. Actualmente $R = \money{100}$ y $P_Y = \price{5}$.

    a) Calcule el precio y la cantidad de equilibrio y represéntelo
       gráficamente. Calcule las elasticidades precio de la demanda y
       de la oferta en el equilibrio.

    b) Calcule la elasticidad cruzada de la demanda. ¿Qué tipo de
       relación existe entre los bienes $X$ e $Y$?

    c) Si la renta media de los consumidores disminuye en \money{10},
       ¿se puede afirmar que $X$ es un bien inferior?

18. La empresa que gestiona un túnel se está planteando alterar el
    peaje que cobra a los usuarios del túnel. Actualmente el peaje es
    de \money{6} y \num{2400} conductores utilizan el túnel
    diariamente. Una consultora ha estimado que la función $Q =
    \num{6000} - \num{600} P$ describe la demanda diaria del túnel.

    a) ¿Cuál es la elasticidad de la demanda al precio actual?

    b) Si la empresa persigue aumentar sus ingresos, ¿sería conveniente
       que rebajase el peaje?

    c) ¿Cuál es el peaje que maximizaría los ingresos de la empresa?
       ¿Cuál es la elasticidad de la demanda en este caso?

19. Por limitaciones de su estadio, un club de fútbol puede ofrecer
    \num{125000} abonos anuales, cuya demanda es:
    #+begin_export latex
    \[
      Q^d = \num{125000} - 100 P +10 P_O + 10 M,
    \]
    #+end_export
    donde:

    - $P$ es el precio del abono.

    - $P_O$ es el precio del abono del otro club con estadio en la
      misma ciudad

    - $M$ es la renta anual media de los aficionados.

    Este año el equipo rival ha anunciado un precio de sus abonos de $P_O
    = \money{600}$. Por otro lado, se estima que $M =  \money{15000}$.

    a) Represente gráficamente las curvas de demanda y de oferta de
       abonos y determine el equilibrio en este mercado.

    b) Calcule las elasticidades de la demanda y de la oferta de abonos
       del club en la situación de equilibrio e interprete los valores
       de esas elasticidades.

    c) Calcule la elasticidad de la demanda con respecto al precio del
       abono del equipo rival en la situación de equilibrio e
       interprete el valor obtenido.

    d) Calcule la elasticidad renta de la demanda en la situación de
       equilibrio e interprete el valor obtenido.

20. En el mercado de un bien las curvas de demanda y de oferta son:
    \begin{gather*}
      Q^d = \num{100000} - 20 P \\
      Q^o = \num{40000} + 40 P
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

    b) Describa y represente gráficamente los efectos sobre el mercado
       del establecimiento de un impuesto sobre los vendedores de
       \money{150} por unidad vendida. ¿Cuánto pagarán los compradores
       por cada unidad? ¿Cuánto ingresarán los vendedores?

    c) ¿Cuál habría sido el resultado si el impuesto hubiese recaído
       sobre los compradores?

21. En el mercado del bien $X$ las curvas de demanda y de oferta son:
    \begin{gather*}
      X^d = 100 - P_X / 40 \\
      X^o = 50 + P_X / 40
    \end{gather*}

    a) Determine el precio y la cantidad de equilibrio.

    b) Describa y represente gráficamente los efectos sobre el mercado
       del bien $X$ del establecimiento de un precio mínimo de
       \price{1200}. ¿Cuántas unidades se venderían? ¿A qué precio?

22. En un mercado competitivo en equilibrio se venden \num{96000}
    unidades a un precio de \price{300}. En esta situación la
    elasticidad precio de la demanda es $-1.5$ mientras que la
    elasticidad de la oferta es igual a $2$. Usando esta información
    estime el efecto que tendría una ley que establezca un precio
    máximo de \price{294}.

23. Las curvas de demanda y oferta de mercado del bien $X$ son:
    \begin{gather*}
      X = 200 - 5 P_{X} + 3 P_{Y} + 2 R \\
      X = 100 + 2 P_{X}
    \end{gather*}
    donde $R$ es la renta media de los consumidores y $P_Y$ es el
    precio del bien $Y$, siendo $R = \money{100}$ y $P_Y =
    \price{5}$. Una ley prohíbe que el precio de $X$ supere
    los $\money{50}$.
    a) ¿Qué cantidad se venderá del bien $X$? ¿A qué
       precio? Represente gráficamente.

    b) Si la renta media aumenta hasta $R = \money{170}$, calcule
       cuántas unidades de $X$ se venderán ahora y a qué
       precio. Represente gráficamente.

24. Razone la veracidad o falsedad de la siguiente afirmación: "Si se
    establece un precio máximo superior al precio de equilibrio, la
    cantidad comprada y la cantidad vendida coincidirá con el
    equilibrio en este mercado."

25. El mercado de alquiler en una ciudad está representado por las
    curvas de demanda y de oferta:
    #+begin_export latex
    \begin{gather*}
      Q^{d} = \num{25000} - 30 P \\
      Q^{o} = \num{5000} +10 P
    \end{gather*}
    #+end_export

    a) Determine el equilibrio en este mercado.

    b) Si se establece una subvención a cada inquilino de \money{200},
       ¿cuánto dinero pagarán los inquilinos? ¿Cuál será el alquiler
       que recibirán los caseros? ¿Cuál sería el coste total del
       programa de subvenciones?

* Basic principles of economic organization                        :noexport:


1. The total resources of a country are \num{50000} units of a
   production factor (such as labour, capital or land) used to produce
   two types of goods: vehicles and food. From the information
   contained in the following table, which specifies the amount of
   vehicles and food that can be produced with different quantities of
   production factors:

   #+ATTR_LATEX: :booktabs t :center t :align rrp{1cm}rr
   |-------------+--------------+---+-------------+--------------|
   | Factor      | Vehicles     |   | Factor      | Food         |
   | (units)     | (units)      |   | (hourss)    | (Tm)         |
   |-------------+--------------+---+-------------+--------------|
   | \num{0}     | \num{0}      |   | \num{0}     | \num{0}      |
   | \num{12500} | \num{40000}  |   | \num{12500} | \num{50000}  |
   | \num{25000} | \num{70000}  |   | \num{25000} | \num{75000}  |
   | \num{37500} | \num{90000}  |   | \num{37500} | \num{90000}  |
   | \num{50000} | \num{100000} |   | \num{50000} | \num{100000} |
   |-------------+--------------+---+-------------+--------------|

   a) Draw the Production Possibility Frontier (PPF) of this country.

   b) What can be said about the particular shape of PPF?

   c) If the production of vehicles increases, would the opportunity
      cost of vehicles increase or decrease?

   d) What effect on the PPF would have an innovation that improves
      the resistance of agricultural products to pests? And an
      organizational improvement in the production of vehicles? And if
      there is an increase in production efficiency in both goods due
      to a general technical progress in society?

   e) On the contrary, what effect would have on the PPF a war that
      destroys half the units of the production factor?

2. The table below shows different efficient production combinations
   for an economy in which there are only two goods: $X$ and $Y$.

   #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{r}
   |-----+------------+------------|
   |     | $X$        | $Y$        |
   |     | (units)    | (units)    |
   |-----+------------+------------|
   | *A* | \num{20}   | \num{0}    |
   | *B* | \num{18}   | \num{1}    |
   | *C* | \num{15}   | \num{2}    |
   | *D* | \num{11}   | \num{3}    |
   | *E* | \num{6}    | \num{4}    |
   | *F* | \num{0}    | \num{5}    |
   |-----+------------+------------|

   a) Draw the PPF. What can be said about the particular shape of PPF?

   b) Is it feasible to produce 2 units of $Y$ and 10 units of $X$?
      What happens in this situation?

   c) Construct a table that reflects the opportunity cost of
      producing each unit of $Y$.

   d) How many units of $X$ must be given up to produce the second
      unit of $Y$?

3. In the market for good $X$ there are \num{1000} identical
   consumers, each with demand curve: \[X^D_i = 5 - P_X, \qquad i
   = 1, ..., \num{1000},\] The good $X$ is produced by
   \num{500} identical firms, each with supply curve: \[X^O_j =
   2.4 P_X , \qquad j = 1, ..., \num{500}. \]

   a) Compute the market demand and supply curvas as well as the market
      equilibrium solution.

   b) Which would be the consequences in this market if producers
      decide to set a price equal to \price{4}? And if they consider
      that the best pricing strategy is to set a price equal to
      \price{1}?

   c) After an increase in the of consumers income, the market demand
      curve becomes: \[X^D = \num{7500} - \num{1000} P_X.\] Find the
      new equilibrium.

   d) In the initial equilibrium, a technological improvement in the
      sector shifts the market supply curve to: \[X^O =
      \num{2500} + \num{1200} P_X.\] Find the new equilibrium.

   e) In the initial equilibrium, what would happen if the government
      decided to set a maximum price of \price{1} for this good? What
      if the government set a minimum price of \price{3}?

4. The firm that operates a toll tunnel is considering lowering the
   toll. Currently, it charges \money{6} and the tunnel is used daily by
   2400 drivers. A consultant has estimated that the function $Q =
   \num{6000} - \num{600} P$ describes the daily demand of the tunnel.

   a) What is the elasticity of demand at the current toll?

   b) If the objective of the company is to get higher returns, would
      you advise to reduce or to increase the toll?

   c) Which toll level would maximize the returns of the firm?

5. A university offers 100 new places each year in the Bachelor's
   Degree in Economics and the demand of those places is: \[ Q =
   1901 - 2 P_{EC} + 0.1 P_{BA} \] where $Q$ are the number of
   students enrolled in the Economics program; $P_{EC}$ and $P_{BA}$
   are the tuition fees of the Bachelor's Degree in Economics and the
   Bachelor's Degree in Business Administration, respectively. If
   $P_{BA} = \money{1000}$:

   a) What will happen if the university sets the tuition fees of the
      Economics program equal to $P_{EC} = \money{1000}$?

   b) What is the maximum fee the university should set it they want
      to cover all the offered places?

   c) What type of good is the Bachelor's Degree in Economics with
      respect to the Bachelor's Degree in Business Administration?

   d) Which effect on the Bachelor's Degree in Economics demand would
      have an increase of $P_{BA}$?

6. A football club has a maximum quota of \num{125000} members.  The
   demand for season tickets is: \[Q = \num{125000} - 100 P +10 P_O +
   10 M,\] where:

   - $P$ is the price of the season tickets of the club.

   - $P_O$ is the price of season tickets of other rival club whose
     stadium is located in the same city.

   - $M$ is the average yearly income of the football fans.

   This year the rival club is selling its seasonal tickets at $P_O =
   \money{600}$ and it is estimated that $M = \money{15000}$.

   a) Compute the price the club should set in order to sell the
      \num{125000} season tickets. Plot the demand and supply curves
      of season tickets in this situation.

   b) Compute the price elasticities of demand and supply in the
      equilibrium situation. Explain the signs and values of the
      elasticities.

   c) Compute the elasticity of demand with respect to the price for
      the season tickets of the other club in the equilibrium
      situation. Explain the sign and value obtained.

   d) Calculate the income elasticity of demand in the equilibrium
      situation. Explain the sign and value obtained.
