# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 4


* La elección intertemporal

1. Un consumidor tiene unas preferencias con respecto a su consumo
   presente, $C_1$, y su consumo futuro, $C_2$, que vienen
   representadas por la función de utilidad $U(C_1, C_2) = C_1
   C_2$. La renta que obtiene el consumidor en cada uno de los
   periodos es $M_1 = \money{1000}$ y $M_2 = \money{1500}$. El tipo
   de interés es $r = 0.5$.

   a) Escriba la restricción presupuestaria intertemporal de este
      individuo en valor futuro.

      #+begin_answer
      El equilibrio presupuestario intertemporal del consumidor
      implica que el valor futuro de su flujo de rentas debe ser igual
      al valor futuro de su flujo de consumos:
      #+begin_export latex
      \[(1 + r) M_1 + M_2 = (1 + r) C_1 + C_2.\]
      #+end_export

      Con los datos del enunciado:
      #+begin_export latex
      \[1.5 \times 1000 + 1500 = 1.5 C_1 + C_2.\]
      #+end_export
      Por tanto:
      #+begin_export latex
      \[C_2 = 3000 - 1.5 C_1\]
      #+end_export

      #+MATS: fig fig-probl-4_1004-ex1-1-*.pdf
      #+end_answer


   b) Determine si el individuo ahorra o no, así como el nivel de
      consumo en cada periodo.

      #+begin_answer
      Si la elección óptima es interior, se tiene que cumplir la
      condición de tangencia:
      #+begin_export latex
      \[
        \RMS = \frac{\UMg_{C_1}}{\UMg_{C_2}} = \frac{C_2}{C_1} = 1 + r.
      \]
      #+end_export
      Puesto que $1 + r = 1.5$, la condición de tangencia implica:
      #+begin_export latex
      \[ C_2 = 1.5 C_1 \]
      #+end_export

      Sustituyendo esta última expresión en la restricción
      intertemporal:
      #+begin_export latex
      \[ C_2 = 3000 - C_2, \]
      #+end_export
      de donde se obtiene que $C_2 = \money{1500}$ y $C_1 =
      \money{1000}$.

      #+MATS: fig fig-probl-4_1004-ex1-2-*.pdf

      La elección óptima implica consumir completamente la renta de
      cada uno de los periodos: $C_1 = M_1 = \money{1000}$ y $C_2 =
      M_2 = \money{1500}$.  El ahorro de este consumidor es nulo: $S =
      M_1 - C_1 = \money{0}$.
      #+end_answer


   c) Suponga ahora que el consumidor considera ambos bienes como
      complementos perfectos y su función de utilidad es: $U(C_1, C_2)
      = \min\{C_1, C_2\}$. Obtenga el perfil de consumo intertemporal
      óptimo en este caso.

      #+begin_answer
      De acuerdo con las preferencias del consumidor, el perfil
      temporal óptimo de consumo debe cumplir la condición:
      #+begin_export latex
      \[ C_1 = C_2. \]
      #+end_export

      Sustituyendo esta condición en la restricción intertemporal:
      #+begin_export latex
      \[ C_2 = 3000 - 1.5 C_2. \]
      #+end_export
      La elección óptima es $C_1 = C_2 = \money{1200}$.

      #+MATS: fig fig-probl4-ex1-3-*.pdf

      En el primer periodo el consumidor pediría un préstamo de $C_1 -
      M_1 = \money{200}$.
      #+end_answer


2. Las preferencias entre el consumo presente, $C_1$, y consumo
   futuro, $C_2$, de un individuo están representadas por la función
   de utilidad: $U(C_1, C_2)= C_1^2 C_2$.  En el primer periodo el
   individuo tiene una renta de \money{200}, mientras que en el
   segundo periodo obtiene una renta de \money{220}. El tipo de
   interés al que se presta dinero es del 5%, y el tipo de interés al
   se pide prestado es del 10%.

   a) Exprese analíticamente la restricción presupuestaria del
      individuo y represéntela gráficamente.

      #+begin_answer
      La restricción presupuestaria tiene dos tramos debido a que el tipo
      de interés relevante es diferente según sea el consumidor
      prestamista o prestatario.

      Si el consumidor es *prestamista*:
      #+begin_export latex
      \[ C_1 \leq M_1 = 200. \]
      #+end_export

      El tipo de interés en este caso es de $r_l = 0.05$. La
      restricción intertemporal implica:
      #+begin_export latex
      \[ C_2 = M_2 + (1 + r_l) (M_1 - C_1). \]
      #+end_export

      Con los datos del enunciado:
      #+begin_export latex
      \[ C_2 = 220 + 1.05 (200 - C_1) = 430 - 1.05 C_1. \]
      #+end_export

      Si el consumidor es *prestatario*:
      #+begin_export latex
      \[ C_1 \geq M_1 = 200. \]
      #+end_export

      El tipo de interés de pedir un préstamo es $r_b = 0.10$. La
      restricción intertemporal implica:
      #+begin_export latex
      \[ C_2 = M_2 - (1 + r_b) (C_1 - M_1). \]
      #+end_export

      Con los datos del enunciado:
      #+begin_export latex
      \[ C_2 = 220 - 1.10 (C_1 - 200) = 440 - 1.10 C_1. \]
      #+end_export

      #+MATS: fig fig-probl-4_1004-ex2-1-*.pdf

      Restricción intertemporal:
      #+begin_export latex
      \[
        C_2 =
        \begin{cases}
          430 - 1.05 C_1 & \text{si $C_1 \leq 200$} \\
          440 - 1.10 C_1 & \text{si $C_1 \geq 200$}
        \end{cases}
      \]
      #+end_export
      #+end_answer


   b) Calcule el equilibrio del consumidor y determine si será
      prestamista o prestatario.

      #+begin_answer
        La relación marginal de sustitución es:
        \[\RMS = \frac{\UMg_{C_1}}{\UMg_{C_2}} =
         2\frac{C_2}{C_1} \]

        Supongamos, en primer lugar, que el consumidor es
        *prestamista*, es decir: \[ C_1 \leq 200. \]
        El tramo relevante de la restricción intertemporal es:
        \[C_2 =  430 - 1.05 C_1. \]

        Si el individuo es prestamista, la condición de tangencia
        es:
        \[\RMS = 1 + r_l,\]
        por lo que
        \[ 2 C_2 = 1.05 C_1. \]

        Resolviendo las dos condiciones de óptimo obtenemos
        #+begin_export latex
          \begin{gather*}
            C_2 = \money{143.33}, \\
            C_1 = \money{273.02}. \\
          \end{gather*}
        #+end_export

        Pero esta combinación no puede ser la solución óptima ya que
        $C_1 > M_1$, lo que contradice el supuesto inicial de que el
        individuo era prestamista.

        #+MATS: fig fig-probl-4_1004-ex2-2-*.pdf

        Suponemos ahora que el consumidor *toma prestado*:
        \[C_1 > 200. \]

        El tramo relevante de la restricción presupuestaria es: \[C_2
        = 440 - 1.1 C_1.\]

        Si el individuo pide prestado en el primer periodo, la
        condición de tangencia es: \[\RMS = 1 + r_b,\] por lo que: \[
        2 C_2 = 1.1 C_1. \]

        Resolviendo las dos condiciones de óptimo, obtenemos:
        #+BEGIN_EXPORT LaTeX
          \begin{gather*}
            C_2 = \money{146.67}, \\
            C_1 = \money{266.67}. \\
          \end{gather*}
        #+END_EXPORT

        La solución obtenida es compatible con nuestro supuesto inicial de
        que el consumidor era prestatario, $C_1 > M_1$.

        #+MATS: fig fig-probl-4_1004-ex2-3-*.pdf

        En conclusión, en el primer periodo consume $C_1 =
        \money{266.67}$ por lo que tiene que pedir prestado $C_1 - M_1
        = \money{66.67}$.  En el segundo periodo, el consumidor tiene
        que devolver el principal y los intereses del préstamo, esto
        es $66.67 \times 1.1 = \money{73.33}$ por lo que sólo puede
        consumir una parte de la renta de ese periodo: \[ C_2 = M_2 -
        (1 + r_b) (C_1 - M_1) = 220 - 73.33 = \money{146.67}. \]
      #+end_answer


   c) Si el Banco Central Europeo fija un tipo de interés único del 8%
      tanto para prestar como para pedir prestado, calcule el nuevo
      equilibrio y determine si el consumidor mejora o empeora en
      términos de bienestar.

      #+begin_answer
        La nueva restricción intertemporal es: \[ C_2 = 220 + 1.08
        (200 - C_1) = 436 - 1.08 C_2.\] El consumidor sigue pudiendo
        escoger ahora cualquier combinación que tenía disponible en la
        situación inicial.  También puede escoger perfiles de consumo
        que antes no estaban disponibles.

        #+MATS: fig fig-probl-4_1004-ex2-4-*.pdf

        Por otro lado, la condición de tangencia es ahora:
        \[ 2 C_2 = 1.08 C_1 \]


        Resolviendo estas dos ecuaciones se obtiene el perfil
        intertemporal de consumo óptimo:
        #+BEGIN_EXPORT LaTeX
          \begin{gather*}
            C_1 = \money{269.14} \\
            C_2 = \money{145.33} \\
          \end{gather*}
        #+END_EXPORT

        #+MATS: fig fig-probl-4_1004-ex2-5-*.pdf

        El valor de la función de utilidad asociado a la nueva
        combinación óptima es: \[ U(E_1) = 269.14^2 \times 145.33 =
        \num{10527173}. \]

        Antes de la introducción del tipo de interés único el consumidor
        elegía $C_1 = 266.67$ y $C_2 = 146.73$. Su nivel de utilidad era:
        \[ U(E_0) = 266.67^2 \times 146.73 = \num{10434394}. \]

        El consumidor disfruta de un mayor nivel de utilidad con un tipo de
        interés único del 8%.
      #+end_answer


3. Un consumidor vive dos periodos y sus preferencias vienen
   representadas por: \[ U = C_1^3 C_2.\] Su elección óptima es $C_1 =
   \money{9750}$ y $C_2 = \money{3575}$.

   a) ¿Cuál es el tipo de interés?

   b) Sabiendo que el ahorro de este consumidor es $S = \money{250}$,
      escriba y represente gráficamente la restricción intertemporal.

4. Un consumidor vive dos periodos. En el primer periodo obtiene una
   renta de \money{600} y en el segundo de \money{440}. El tipo de
   interés es del 10%.

   a) Obtenga la restricción intertemporal del consumidor y
      represéntela gráficamente. ¿Qué interpretación tienen los
      puntos de corte con los ejes?

   b) Suponga que en esas condiciones la decisión óptima del
      consumidor es consumir toda la renta del primer periodo de
      forma que el ahorro es 0. ¿Cómo habría cambiado la elección si
      el tipo de interés hubiera sido superior? Represente
      gráficamente.

5. Explique y justifique si considera correcta o incorrecta cada una
   de las siguientes afirmaciones (use el análisis gráfico cuando lo
   considere oportuno):

   a) Si no existiera un mercado de crédito que permitiera al
      consumidor prestar y pedir prestado, éste no podría ahorrar en
      el periodo presente para consumir por encima de su renta
      monetaria en el futuro.

6. La renta monetaria de un individuo en el periodo actual es
   \money{2500} y en este periodo ahorra una cantidad de
   \money{1000}. En el periodo futuro su renta monetario disminuirá
   un 20%.

   a) Si existe un mercado financiero que le permite prestar y pedir
      prestado, ¿cuál es el tipo de interés para el que el consumo
      óptimo en el futuro sea de \money{3010}?

   b) Represente gráficamente la restricción presupuestaria y señale
      el consumo óptimo de este consumidor.

7. Las preferencias entre consumo presente, $C_1$, y consumo futuro,
   $C_2$, de un individuo están representadas por la función de
   utilidad: $U(C_1, C_2) = C_1^2 C_2$. En el primer periodo el
   individuo tiene una renta de \money{200}, mientras que en el
   segundo periodo su renta es \money{220}. El tipo de interés al que
   se presta en la economía es del 5%, y el tipo de interés al que se
   pide prestado es del 10%.

   a) Exprese analíticamente la restricción presupuestaria y
      represéntela gráficamente.

   b) Calcule el equilibrio del consumidor y determine si será
      prestamista o prestatario.

8. Un consumidor vive dos periodos y puede prestar y pedir prestado a
   un tipo de interés del 10%. En el primer periodo obtiene una renta
   monetaria de \money{1000} mientras que en el segundo período
   obtiene \money{750}. En estas condiciones el consumidor decide no
   ahorrar nada. Si el tipo de interés disminuyera al 5%, ¿qué
   ocurriría con el ahorro? ¿Qué situación preferiría el consumidor:
   un tipo de interés del 10% o del 5%? Represente
   gráficamente.

   #+begin_answer
   La restricción intertemporal cuando el tipo de interés es del 10%
   es:
   \begin{equation*}
     C_2 = 1850 - 1.1 C_1
   \end{equation*}

   #+attr_latex: :options {0.55\linewidth}
   #+begin_minipage
   #+MATS: fig fig-probl-4_1004-r10-*.pdf
   #+end_minipage
   #+attr_latex: :options {0.45\linewidth}
   #+begin_minipage
     Dado que el ahorro óptimo es $0$, el consumo y la renta de cada
     periodo coinciden: $C_1 = M_1 = \money{1000}$ y $C_2 = M_2 =
     \money{750}$. La relación marginal de sustitución en la
     combinación óptima es igual a $\mathit{RMS} = 1 + r$, por lo que:
     \begin{equation*}
       \mathit{RMS}(E_0) = 1.1
     \end{equation*}
   #+end_minipage

   La restricción intertemporal cuando baja el tipo de interés es:
   \begin{equation*}
     C_2 = 1800 - 1.05 C_1
   \end{equation*}
   La combinación inicial no puede ser óptima con un tipo de interés
   del 5%, pues:
   \begin{equation*}
     \mathit{RMS}(E_0) = 1.1 > 1 + r = 1.05
   \end{equation*}
   por lo que el consumidor aumentará su consumo presente a costa de
   consumo futuro y su ahorro será ahora negativo.

   #+attr_latex: :options {0.55\linewidth}
   #+begin_minipage
   #+MATS: fig fig-probl-4_1004-r5-*.pdf
   #+end_minipage
   #+attr_latex: :options {0.45\linewidth}
   #+begin_minipage
     El consumidor prefiere la situación donde $r = 5\%$: en el nuevo
     punto óptimo el consumidor alcanza una curva de indiferencia más
     alejada del origen. Aunque podría elegir $E_0$, el consumidor
     rechaza esa opción en favor de otra combinación de consumo: $E_1$
     es preferida a $E_0$.
   #+end_minipage
   #+end_answer

9. Un consumidor vive dos periodos y puede prestar y pedir prestado a
   un mismo tipo de interés. Obtiene una renta de \money{2500}, ahorra
   \money{1000}, y su renta en el segundo periodo es un 20%
   inferior. Calcule el tipo de interés sabiendo que la elección
   óptima del consumidor en el segundo periodo es \money{3010}. Obtenga
   y represente gráficamente la restricción intertemporal.
   #+begin_answer
     El consumo en el primer periodo se puede deducir de los datos del enunciado:
     \[ C_1 = M_1 - S_1 = 2500 - 1000 = \money{1500}.\]
     La renta en el segundo periodo es un 20% inferior a la del primer periodo:
     \[ M_2 = 0.8 M_1 = \money{2000}. \]
     La restricción intertemporal implica:
     \[ M_1 (1 + r) + M_2 = C_1 (1 + r) + C_2 \]
     Por lo que:
     \[ 2500 (1 + r) + 2000 = 1500 (1 + r) + 3010 \]
     Despejando se obtiene $r = 0.01$.

     Una vez calculado el tipo de interés podemos determinar el valor
     futuro del flujo de rentas del consumidor:
     \[ M_1 (1 + r) + M_2 = 2500 \cdot 1.01 + 2000 = \money{4525} \]
     La restricción intertemporal es:
     \[ 4525 = 1.01 C_1 + C_2 \]

     #+MATS: fig fig-probl-4_1004-budget-*.pdf
     #+end_answer
