# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 3.1

Cuando un país subió los impuestos sobre el tabaco, el precio de los
cigarrillos subió de \money{4} a \money{4.6} por cajetilla. Se estima
que la cantidad demandada cayó de $52$ a $47.5$ millones de cajetillas
como consecuencia de esta subida de precio.  Calcule la elasticidad de
la demanda de cigarrillos.


** Answer

La pendiente de la curva de demanda es:
#+begin_export latex
\[
  \incr Q^d/\incr P = (47.5 - 52)/(4.60 - 4) = -7.5.
\]
#+end_export
El precio y la cantidad medios son:
#+begin_export latex
\begin{gather*}
  Q^d_m = (52 + 47.5)/2 = 49.75, \\
  P_m = (4 + 4.60)/2 = 4.30.
\end{gather*}
#+end_export
La elasticidad, usando la fórmula del punto medio, es:
#+begin_export latex
\[
  E_d = \iratio{Q^d}{P}\frac{P_m}{Q^d_m} =
  -7.5 \cdot \frac{4.30}{49.75} \approx -0.65.
\]
#+end_export


* 3.2

La demanda de gas natural por parte de los hogares presenta una
elasticidad precio igual a $-0.2$ en el corto plazo y a $-0.7$ en el
largo plazo.

a) Si el precio del gas aumenta desde \price[\kWh]{0.054} hasta
   \price[\kWh]{0.066}, ¿qué ocurrirá con la cantidad demandada a
   corto plazo? ¿Y a largo plazo? Use la fórmula del punto medio en
   sus cálculos.

b) ¿Por qué podría depender la demanda de gas natural del horizonte
   temporal?


** Answer

a) Precio medio:
   #+begin_export latex
   \[
     P_{m} = (0.054 + 0.066) / 2 = \price[\kWh]{0.060}.
   \]
   #+end_export
   Cambio porcentual del precio:
   #+begin_export latex
   \[
     \incrpct{P} = 100 (0.066 - 0.054) / 0.060 = 20.
   \]
   #+end_export
   Para calular el efecto sobre la cantidad demandada usamos la
   relación $\incrpct{Q} = E_d \times \incrpct{P}$:
   #+begin_export latex
   \begin{gather*}
     \text{Corto plazo:\ }\incrpct{Q} = -0.2\times 20 = -4. \\
     \text{Largo plazo:\ }\incrpct{Q} = -0.7\times 20 = -14.
   \end{gather*}
   #+end_export

b) A corto plazo, la reducción en el consumo es relativamente pequeña:
   $-4\%$.  Pero, el consumo de gas disminuye un $14\%$ a largo
   plazo. Esta mayor caída del consumo se explica porque los hogares
   necesitan tiempo para adecuar su comportamiento a los nuevos
   precios. A largo plazo pueden sustituir el gas natural por otras
   fuentes de energía más baratas, mejorar el aislamiento térmico de
   sus viviendas, instalar calderas más eficientes, etc.


* 3.3

Dos conductores repostan todos los lunes en la misma gasolinera y
ninguno comprueba el precio antes de hacer su pedido. Mientras que
el primero siempre pide $15$ litros, el segundo siempre pide
\money{20} de gasóleo. ¿Cuáles son las elasticidades precio de la
demanda de gasóleo de cada conductor?


** Answer

El primer conductor siempre demanda la misma cantidad. Su demanda,
$Q^d = 15$, es perfectamente inelástica: $E_d = 0$.

El otroo conductor siempre gasta lo mismo: $P Q = \money{20}$, y
su curva de demanda es $Q^d = 20 / P$. La elasticidad de la demanda
del segundo conductor es unitaria:
#+begin_export latex
\[
  E_d = \frac{\diff Q^d}{\diff P}\frac{P}{Q_d} =
  - \frac{20}{P^2}\frac{P}{20 / P} =  - 1.
\]
#+end_export


* 3.4

A causa de un cambio en el precio, la cantidad demandada de un bien
disminuye un 5%, mientras que los ingresos de los vendedores aumentan
en un 3%. ¿Es elástica o inelástica la demanda?  Calcule el valor de
la elasticidad precio con la información proporcionada.


** Answer

Podemos aproximar la variación porcentual de los ingresos como:
$\incrpct{I} \approx \incrpct{P} + \incrpct{Q}$.  Dado que
$\incrpct{Q} = -5$ y $\incrpct{I} = 3$, la variación porcentual del
precio es $\incrpct{P} \approx 8$.

Calculamos la elasticidad de la demanda como el cociente de las
variaciones porcentuales de la cantidad demandada y del precio:
#+begin_export latex
\[
  E_d = \ipctratio{Q^d}{P} \approx \frac{-5}{8} = -0.625.
\]
#+end_export
La demanda del bien es inelástica.


* 3.5

La empresa que gestiona un túnel se está planteando alterar el
peaje que cobra a los usuarios del túnel. Actualmente el peaje es
de \money{6} y \num{2400} conductores utilizan el túnel
diariamente. Una consultora ha estimado que la función $Q =
\num{6000} - \num{600} P$ describe con precisión la demanda diaria
del túnel.

a) ¿Cuál es la elasticidad de la demanda al precio actual?

b) Si la empresa persigue aumentar sus ingresos, ¿sería conveniente
   que rebajase el peaje?

c) ¿Cuál es el peaje que maximizaría los ingresos de la empresa?
   ¿Cuál es la elasticidad de la demanda en este caso?


** Answer

a) Elasticidad de la demanda:
   #+begin_export latex
   \[
     E_d = \frac{\diff Q}{\diff P} \frac{P}{Q} =
     -600 \frac{6}{\num{2400}} = -1.5.
   \]
   #+end_export

b) Sí: se encuentra en un tramo elástico de la demanda.


c) Ingresos:
   #+begin_export latex
   \[
     I = P Q = P (\num{6000} - 600 P) = \num{6000} P - 600 P^2
   \]
   #+end_export
   Derivando la expresión anterior con respecto a $P$ e igualando a
   \num{0}, obtenemos el precio que maximiza los ingresos, $P^* =
   \price{5}$. A ese precio $Q^* = \num{3000}$ conductores cruzan el
   túnel diariamente y la empresa obtiene unos ingresos de $I^* =
   \money{15000}$ al día. La elasticidad de la demanda sería:
   #+begin_export latex
   \[
     E_d = \frac{\diff Q}{\diff P} \frac{P}{Q} =
     -600 \frac{5}{\num{3000}} = -1.
   \]
   #+end_export


* 3.6

Considere un mercado competitivo de manzanas y trace un diagrama de
oferta y demanda que muestre los efectos sobre el equilibrio de una
enfermedad de los manzanos que perjudique a la cosecha. ¿Podrían
aumentar los ingresos de los agricultores en este caso?  ¿Qué
condiciones se tendrían que cumplir?



** Answer

La oferta de manzanas se reduce. Se venden menos manzanas a un precio
superior.
#+xxx: fig fig-ans-probl-3_1004-apples-*.pdf

Los ingresos de los productores solo crecerán si el equilibrio inicial
se encuentra en un tramo inelástico de la curva de demanda.



* 3.7

Las medicinas tienen demanda inelástica mientras que los
ordenadores tienen demanda elástica. Suponga que la oferta se
duplica en cada uno de esos mercados como consecuencia del
progreso tecnológico.

a) ¿Qué ocurrirá con el equilibrio en cada uno de estos mercados?
   Represente gráficamente.

b) ¿En qué mercado se experimentará el mayor cambio en el precio?
   ¿Y el mayor cambio en la cantidad?

c) ¿Cómo cambiará el gasto de los consumidores en cada bien?


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-3_1004-medicines-*.pdf
   #+begin_center
   Demanda inelástica.
   #+end_center
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-3_1004-computers-*.pdf
   #+begin_center
   Demanda elástica.
   #+end_center
   #+xxx: endcol
   #+latex: \vspace*{2ex}

b) En el mercado con la demanda más elástica se ve más afectada la
   cantidad. En el mercado con demanda menos elástica se ve más
   afectado el precio.

c) Cuando se reduce el precio en el mercado con demanda inelástica
   disminuye el gasto de los consumidores. En el mercado con demanda
   elástica, el gasto aumenta.



* 3.8

Los precios de las habitaciones de hotel en las grandes ciudades
suelen depender del día de la semana en que se alquilan. En una semana
típica, los precios de las habitaciones son mucho más bajos los fines
de semana que los días laborables. Utilice diagramas de oferta y
demanda para explicar este comportamiento.


** Answer

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-2_1004-hotels-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
La oferta de habitaciones de hotel es la misma entre semana que en fin
de semana: la curva de oferta no cambia.  Pero la demanda entre
semana, $D_e$, es muy diferente a la demanda de fin de semana, $D_f$.
#+xxx: endcol
#+latex: \vspace*{2ex}


- Entre semana se demandan muchas habitaciones por motivos laborales y
  de negocios. Este tipo de viajeros tiene una elevada disposición a
  pagar por las habitaciones.

- En fin de semana la demanda de habitaciones por motivos de turismo y
  ocio es mayoritaria. Este tipo de viajeros tiene una menor
  disposición a pagar y, si el precio de las habitaciones es muy
  elevado, buscará destinos alternativos más baratos.




* 3.9

El mercado del bien $X$ está caracterizado por las funciones de
demanda y oferta:
#+begin_export latex
\begin{gather*}
  X^d = 250 - 30 P_{X} - 5 P_{Y} + 2 M \\
  X^o = 15 P_{X} - 25
\end{gather*}
#+end_export
donde $M$ es la renta media de los consumidores y $P_Y$ el precio
del bien $Y$. Actualmente, $M = \money{100}$ y $P_Y = \price{5}$.

a) Obtenga el precio y la cantidad de equilibrio y represéntelo
   gráficamente. Calcule las elasticidades precio de la demanda y
   de la oferta en el equilibrio.

b) Calcule la elasticidad cruzada de la demanda en el equilibrio de
   mercado. ¿Qué tipo de relación existe entre los bienes $X$ e $Y$?

c) Calcule la elasticidad renta de la demanda en el equilibrio de
   mercado.  ¿Se puede afirmar que $X$ es un bien inferior?


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-3_1004-eq-elast-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   La curva de demanda es:
   #+begin_export latex
   \[ X^d = 425 - 30 P_X, \]
   #+end_export
   y en equilibrio:
   #+begin_export latex
   \begin{gather*}
     P_X^* = \price{10},\\
     X^* = \units{125}.\\
   \end{gather*}
   #+end_export
   #+xxx: endcol

   Elasticidad de la demanda:
   #+begin_export latex
   \[
     E_d = \frac{\diff X^d}{\diff P_X} \frac{P_X}{X^d} =
     -30 \frac{10}{125} = -2.4.
   \]
   #+end_export

   Elasticidad de la oferta:
   #+begin_export latex
   \[
     E_o = \frac{\diff X^o}{\diff P_X} \frac{P_X}{X^o} =
     15 \frac{10}{125} = 1.2.
   \]
   #+end_export

b) Elasticidad cruzada de la demanda:
     #+begin_export latex
     \[
       E_d^{P_Y} = \frac{\partial X^d}{\partial P_Y} \frac{P_Y}{X^d} =
       -5 \frac{5}{125} = -0.2.
     \]
     #+end_export
     El bien $Y$ es complementario del bien $X$.

c) Elasticidad renta de la demanda:
     #+begin_export latex
     \[
       E_d^{R} = \frac{\partial X^d}{\partial R} \frac{R}{X^d} =
       2 \frac{100}{125} = 1.6.
     \]
     #+end_export
     El bien $X$ es normal.


* 3.10

Ana paga \money{2} por cada unidad de alimentos, gasta
\money{5000} en alimentos al año y su renta monetaria anual es de
\money{25000}. La elasticidad-precio de su demanda de alimentos es
$-1$ mientras que la elasticidad-renta es $0.5$. Si Ana obtiene
una beca de \money{1000} que puede gastar libremente en aquello
que prefiera, ¿cuál sería ahora la cantidad demandada de alimentos?


** Answer

El incremento porcentual de la renta de Ana a causa de la beca es:
$\incrpct{M} = \num{1000} / \num{25000} \times 100 = 4$. La variación
porcentual del consumo de alimentos es:
#+begin_export latex
\[
  \incrpct{Q} = E_{d}^{M}  \incrpct{M} = 0.5 \times 4= 2.
\]
#+end_export
Inicialmente, Ana compra $Q_1= \num{5000} / 2 = \num{2500}$ unidades
de alimentos durante un año. Después de recibir la beca, el consumo de
alimentos será un 2% superior: $Q_2 = 1.02 \times \num{2500} =
\num{2550}$ unidades.


* 3.11

La directora de una empresa que organiza espectáculos musicales
debe fijar el precio de las entradas de un concierto que se
celebrará la próxima primavera. La capacidad de la sala de
conciertos es de \num{5000} espectadores, mientras que la afluencia
de público a este tipo de conciertos, $Q$, puede estimarse con la
curva de demanda: $Q = \num{8000} - 160 P$, donde $P$ es el precio
de la entrada.

a) ¿Qué precio debería establecerse si lo que se pretende es vender
   todas las localidades? Calcule e interprete la elasticidad de la
   demanda para ese precio.

b) Calcule el precio al que se maximizarían los ingresos. ¿Cuántas
   entradas se venderían? ¿Cuál es la elasticidad de la demanda
   ahora?



** Answer

a) La demanda es igual al aforo de la sala cuando $P =
   \money{18.75}$. Para este precio, la demanda de entradas es
   inelástica:
   #+begin_export latex
   \[
      E_d = \frac{\diff Q^d}{\diff P} \frac{P}{Q^d} =
      -160  \frac{18.75}{5000} = -0.6.
   \]
   #+end_export


b)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-3_1004-max-rev-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Los ingresos se maximizan cuando $E_d = -1$. Dado que la demanda es
   lineal, la elasticidad es unitaria en el punto medio de la curva de
   demanda. En este punto $P = \money{25}$ y se venden \num{4000}
   entradas.
   #+xxx: endcol
