# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 1.1

En una economía se producen dos bienes: vehículos y alimentos, y sólo
se utiliza trabajo como único factor de producción. Se dispone de un
máximo de \num{100000} horas de trabajo al mes. La siguiente tabla
muestra las cantidades que pueden producirse dependiendo de las horas
de trabajo que se dediquen a cada actividad:
#+latex: \vspace*{2ex}

#+ATTR_LATEX: :options {0.5\linewidth}
#+xxx: col
#+ATTR_LATEX: :booktabs t :center t :align @{}rR{2.5cm}@{}
|---------------+-----------|
|       Trabajo | Vehículos |
| (miles horas) |   (miles) |
|---------------+-----------|
|             0 |         0 |
|            10 |        50 |
|            20 |        95 |
|            30 |       135 |
|            40 |       170 |
|            50 |       200 |
|            60 |       225 |
|            70 |       245 |
|            80 |       260 |
|            90 |       270 |
|           100 |       275 |
|---------------+-----------|

#+ATTR_LATEX: :options {0.5\linewidth}
#+xxx: col
#+ATTR_LATEX: :booktabs t :center t :align @{}rR{2.5cm}@{}
|---------------+------------|
|       Trabajo |  Alimentos |
| (miles horas) | (miles kg) |
|---------------+------------|
|             0 |          0 |
|            10 |         80 |
|            20 |        150 |
|            30 |        200 |
|            40 |        240 |
|            50 |        270 |
|            60 |        290 |
|            70 |        305 |
|            80 |        315 |
|            90 |        320 |
|           100 |        322 |
|---------------+------------|
#+xxx: endcol

a) <<ex1.1:item-a>>Obtenga y represente gráficamente la frontera de
   posibilidades de producción, FPP.

b) Si se producen \units[kg]{150000} de alimentos, ¿es posible
   producir \num{300000} vehículos? Si su respuesta es negativa,
   indique cuántos vehículos podrían fabricarse como máximo.

c) ¿Qué efecto tendría sobre la FPP una mejora organizativa en la
   producción de vehículos? Obtenga y represente la FPP si la mejora
   incrementa en un 20% la producción por hora de vehículos. Compare
   los resultados con los obtenidos en el apartado [[ex1.1:item-a]]. ¿Es
   posible producir ahora \units[kg]{150000} de alimentos y
   \num{300000} vehículos? ¿Es eficiente?

d) ¿Qué consecuencias tendría sobre la FPP la reducción a la mitad de
   las horas de trabajo como consecuencia de un conflicto bélico?
   Represente gráficamente la FPP si sólo se pueden usar \num{50000}
   horas de trabajo y compare los resultados con los obtenidos en el
   apartado [[ex1.1:item-a]].


** Answer

a) En los gráficos siguientes $A$ representa automóviles, en decenas
   de miles, y $C$ denota comida, en decenas de miles de kilos.

   #+xxx: fig fig-ans-probl-1_1004-ppf-sh1-*.pdf

b) Una mejora tecnológica en la producción de comida:
   #+xxx: fig fig-ans-probl-1_1004-ppf-sh2-*.pdf

   Una mejora organizativa en la producción de automóviles:
   #+xxx: fig fig-ans-probl-1_1004-ppf-sh3-*.pdf

   Si las mejoras en los dos sectores se producen smultáneamente:
   #+xxx: fig fig-ans-probl-1_1004-ppf-sh4-*.pdf

c) Una reducción de un factor de producción desplaza la FPP hacia la
   izquierda:
   #+xxx: fig fig-ans-probl-1_1004-ppf-sh5-*.pdf



* 1.2

La tabla adjunta presenta diferentes combinaciones eficientes para una
economía en la que únicamente se producen dos bienes: cañones y mantequilla.

#+ATTR_LATEX: :booktabs t :center t :align @{}p{1cm}*{2}{R{2cm}}@{}
|-----+-------------+------------|
|     | Mantequilla |    Cañones |
|     | (Toneladas) | (Unidades) |
|-----+-------------+------------|
| *A* |          20 |          0 |
| *B* |          18 |          1 |
| *C* |          15 |          2 |
| *D* |          11 |          3 |
| *E* |           6 |          4 |
| *F* |           0 |          5 |
|-----+-------------+------------|

a) Represente la frontera de posibilidades de producción, FPP.

c) Construya una tabla que refleje el coste de oportunidad de producir
   cada cañón.

d) ¿A cuántas toneladas de mantequilla se debe renunciar para producir
   el primer cañón? ¿Y el segundo?

e) ¿Qué relación existe entre la forma de la FPP y el coste de
   oportunidad?


** Answer

a) La frontera de posibilidades de producción es cóncava.
   #+xxx: fig fig-ans-probl-1_1004-ppf-oc1-*.pdf

b) Es factible producir 2 unidades de $Y$ y 10 de $X$, pero es una
   combinación de producción ineficiente:
   #+xxx: fig fig-ans-probl-1_1004-ppf-oc2-*.pdf

c) La útima columna muestra el coste de oportunidad de cada unidad del
   bien $Y$:
   #+ATTR_LATEX: :booktabs t :center t :align @{}p{0.75cm}*{4}{R{0.75cm}}r@{}
   |-----+----------+---------+------------+------------+---------------------------|
   |     | $X$      | $Y$     | $\incr{X}$ | $\incr{Y}$ | $\abs{\incr{X}/\incr{Y}}$ |
   |-----+----------+---------+------------+------------+---------------------------|
   | *A* | \num{20} | \num{0} | ---        | ---        | ---                       |
   | *B* | \num{18} | \num{1} | \num{-2}   | \num{1}    | \num{2}                   |
   | *C* | \num{15} | \num{2} | \num{-3}   | \num{1}    | \num{3}                   |
   | *D* | \num{11} | \num{3} | \num{-4}   | \num{1}    | \num{4}                   |
   | *E* | \num{6}  | \num{4} | \num{-5}   | \num{1}    | \num{5}                   |
   | *F* | \num{0}  | \num{5} | \num{-6}   | \num{1}    | \num{6}                   |
   |-----+----------+---------+------------+------------+---------------------------|

d) Para poder producir la primera unidad de $Y$ hay que renunciar a
   $2$ unidades de $X$, mientras que el coste de oportunidad de la
   segunda es $3$ unidades de $X$.

e) Cuando el coste de oportunidad es creciente, la FPP es cóncava.


* 1.3

La frontera de posibilidades de producción, FPP, de un país que sólo
produce dos bienes, $X$ e $Y$ puede expresarse como:
#+begin_export latex
\[
  Y = \num{1000} - 0.1 X
\]
#+end_export

a) Represente gráficamente la FPP.

b) Si la economía está utilizando eficientemente todos los factores de
   producción y se producen \num{1000} unidades del bien $X$, ¿cuál es
   el coste de oportunidad de producir una unidad adicional del bien
   $X$?

c) Si en vez de \num{1000} se produjeran \num{5000} unidades del bien
   $X$, ¿cómo cambiaría la respuesta al apartado anterior?

d) ¿Que relación existe entre el comportamiento del coste de
   oportunidad y la forma de la FPP?


** Answer

Por hacer.

* 1.4

El siguiente gráfico representa la frontera de posibilidades de
producción de una economía donde sólo se producen cocos y pescado:

#+xxx: fig fig-probl-1_1004-ppf-*.pdf

Ordene las opciones de producción $A$, $B$, $C$ y $D$ de mayor a
menor coste de oportunidad de producir pescado.


** Answer

El coste de oportunidad sería mayor en $D$ que en $A$, ya que la
pendiente es más pronunciada en $D$.  Combinaciones como $B$ no son
eficientes y el coste de oportunidad es $0$. Puntos como el $C$ son
inaccesibles y el coste de oportunidad no está definido.



* 1.5

Considere una economía donde sólo se producen dos bienes: $X$ e $Y$.

#+xxx: fig fig-probl-1_1004-ppf-multi-*.pdf

Relacione cada uno de los gráficos anteriores con las siguientes
afirmaciones. Razone sus respuestas.

a) El incremento de la natalidad en las décadas previas hace que el
   número personas en edad de trabajar aumente
   considerablemente.

b) Una gran parte de los trabajadores que estaban desempleados han
   encontrado un empleo.

c) Una gran parte de los trabajadores emigra al extranjero buscando un
   mejor empleo.

d) Una reforma administrativa hace mucho más difícil y costosa la
   contratación de trabajadores.


** Answer

Por hacer.
