# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

#+TITLE: Exercise Booklet 1


1. An economy produces two goods, vehicles and food, using labor as
   the only factor of production. There are \num{50000} labor hours
   available. The following table shows how many units of each good
   can be produced according to the labor hours devoted to each
   activity:

   #+ATTR_LATEX: :booktabs t :center t :align rrp{1cm}rr
   |-------------+--------------+---+-------------+--------------|
   | Labor       | Vehicles     |   | Labor       | Food         |
   | (hours)     | (units)      |   | (hours)     | (kg)         |
   |-------------+--------------+---+-------------+--------------|
   | \num{0}     | \num{0}      |   | \num{0}     | \num{0}      |
   | \num{12500} | \num{40000}  |   | \num{12500} | \num{50000}  |
   | \num{25000} | \num{70000}  |   | \num{25000} | \num{75000}  |
   | \num{37500} | \num{90000}  |   | \num{37500} | \num{90000}  |
   | \num{50000} | \num{100000} |   | \num{50000} | \num{100000} |
   |-------------+--------------+---+-------------+--------------|

   a) Draw the Production Possibility Frontier, PPF.

   b) What effect on the PPF would have an improvement on the
      procedures used in the production of food that raises the output
      per labor hour? And an organizational improvement in the
      production chain of vehicles? And what would happen if both
      improvements occur simultaneously as a result of a widespread
      technical progress?

   c) Which would be the consequences on the PPF of the reduction of
      the labor hours by half as a result of an armed conflict?

2. The table below shows different efficient combinations for an
   economy in which only two goods are produced: $X$ and $Y$.

   #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{>{\raggedleft\arraybackslash}p{2cm}}
   |-----+------------+------------|
   |     | $X$        | $Y$        |
   |-----+------------+------------|
   | *A* | \num{20}   | \num{0}    |
   | *B* | \num{18}   | \num{1}    |
   | *C* | \num{15}   | \num{2}    |
   | *D* | \num{11}   | \num{3}    |
   | *E* | \num{6}    | \num{4}    |
   | *F* | \num{0}    | \num{5}    |
   |-----+------------+------------|

   a) Draw the PPF. What can be said about the particular shape of PPF?

   b) Is it feasible to produce 2 units of $Y$ and 10 units of $X$?
      What happens in this situation?

   c) Construct a table that reflects the opportunity cost of
      producing each unit of $Y$.

   d) How many units of $X$ must be given up to produce the first
      unit of $Y$? And the second one?

3. The following figure shows the production possibilities frontier of
   an economy where only fish and coconuts are produced:

   #+MATS: fig fig-probl-1_1004-ppf-*.pdf

   Sort the production options $A$, $B$, $C$, and $D$ from higher to
   lower opportunity cost of producing fish.

4. State whether the following sentence is true or false and justify
   your answer: "When a great number of unemployed workers find a job,
   the production possibilities frontier shifts to the right."

5. There are three buyers in a market whose demand curves are:

   #+ATTR_LATEX: :center t :align lc
   | Buyer 1: | $Q^d_1(P) = 1000 - 10 P$ |
   | Buyer 2: | $Q^d_2(P) = 600 - 2 P$   |
   | Buyer 3: | $Q^d_3(P) = 750 - 5 P$   |

   Determine the market demand curve.

6. Consider a competitive market where \num{1000} identical buyers
   participate, each one with demand curve:
   #+begin_export latex
   \[
     Q^d_i(P) = 5 - P, \qquad i = 1, ..., \num{1000}.
   \]
   #+end_export
   There are also
   \num{625} identical firms, each one with supply curve:
   #+begin_export latex
   \[
     Q^o_j(P) = 2.4 P , \qquad j = 1, ..., \num{625}.
   \]
   #+end_export

   a) Find and plot the market equilibrium.

   b) What would happen if the price were \price{4}? And if the price
      were \price{1}?

7. "The price of gasoline considerably increased during the years from
   2003 to 2006, and yet the consumption of gasoline grew."  Does this
   claim contradict the law of demand?

8. Consider a competitive market for apples and draw a demand and
   supply diagram showing the effects on the equilibrium of an apple
   tree disease that adversely affects the harvest. Could farmers'
   revenues rise in that case? What conditions must be met?

9. A country is facing an increase in drug use. Experts have
   put forward two alternative explanations:

   - The decreasing police budget has led to an increase in drugs on
     the streets.

   - Cutbacks in education efforts have decreased awareness of the
     dangers of drug use.

   Use demand and supply diagrams to analyze each of these
   hypotheses. Is it possible to discern between the two explanations
   by observing what happened to the price and the consumption of drugs?

10. Medicines have inelastic demand, while computers have elastic
    demand. Suppose that the supply doubles on each of these markets
    as a consequence of technological progress.

    a) What happens to the equilibrium of those markets?  Represent
       graphically.

    b) Which market will experience a larger change in price?  And a
       larger change in quantity?

    c) How will consumer spending on each product be affected?

11. The demand and supply curves of the market for good $X$ are:
    #+begin_export latex
    \begin{gather*}
      X^d = \num{85000} - 20 P_X \\
      X^o = \num{15000} + 15 P_X
    \end{gather*}
    #+end_export

    a) Determine the equilibrium price and quantity.

    b) Plot the effects on the market equilibrium of an increase in
       the price of a substituitive good. Is it possible to
       unequivocally predict how the equilibrium price of good $X$
       will change? And the equilibrium quantity?

    c) Starting from the initial equilibrium, consider now the effects
       of an increase in the consumers' income. Is it possible to
       unambiguously predict how the equilibrium price and quantity
       will change?

12. The electric car market of a country is competitive, and the
    demand and supply curves are:
    #+begin_export latex
    \begin{gather*}
      Q^{d} = \num{10000} - P/6 \\
      Q^{o} = -6000 + P/2
    \end{gather*}
    #+end_export

    a) Determine the equilibrium price and quantity.

    b) Find and plot the new equilibrium if demand increases by 20% (the
       quantity demanded is 20% greater at each price) and the supply
       curve becomes:
       #+begin_export latex
       \[
         Q^o = -2700 + P/2
       \]
       #+end_export

13. The market for an inferior good is in equilibrium. If production
    costs and consumer income increase simultaneously, will both the
    price and the quantity decrease in the new equilibrium?

14. When the government of a country increased the cigarette tax, the
    price of cigarettes rose from \money{4} to \money{4.6} per
    pack. Economists estimate that the quantity demanded dropped from
    $52$ to $47.5$ million packs due to the price increase.  Calculate
    the price elasticity of cigarette demand.

15. Two drivers pull up to the same gas station every Monday and place
    their orders without checking first the price. While the first
    driver always asks for 15 liters, the second one always asks for
    20€ worth of gas. What are the price elasticities of demand for
    gas of each driver?

16. Anna pays \money{2} for each unit of food, spends \money{5000} per
    year in food and her annual income is \money{25000}. The price
    elasticity of her demand for food is $-1$ while the income
    elasticity is $0.5$. If Anna wins a \money{1000} grant that she
    can spend freely on what she prefers, what would be her food
    consumption?

17. The market for good $X$ is characterized by the demand and supply
    functions:
    #+begin_export latex
    \begin{gather*}
      X^d = 250 - 30 P_{X} - 5 P_{Y} + 2 I \\
      X^o = 15 P_{X} - 25
    \end{gather*}
    #+end_export
    where $I$ is the consumers' average income, and $P_Y$ is the price
    of good $Y$. Currently, $I = \money{100}$ and $P_Y = \price{5}$.

    a) Calculate the equilibrium price and quantity and plot a
       graph. Find the price elasticities of demand and supply at
       equilibrium.

    b) Calculate the cross elasticity of demand. What kind of
       relationship holds between goods $X$ and $Y$?

    c) If the consumers' average income drops by \money{10},
       can it be said that $X$ is an inferior good?

18. The firm that operates a road tunnel is considering lowering the
    toll it charges to the users of the tunnel. Currently, the toll is
    \money{6} and 2400 drivers pass through the tunnel daily. A
    consulting firm has estimated that the function $Q = \num{6000} -
    \num{600} P$ accurately describes the daily demand of the tunnel.

    a) What is the elasticity of demand at the current toll?

    b) If firm seeks to get higher returns, would it be reasonable to
       reduce the toll?

    c) Which toll would maximize the returns of the firm? What would
       be the elasticity of demand in that case?

19. A football club offers \num{125000} season tickets. The demand
    function for those tickets is:
    #+begin_export latex
    \[
      Q^d = \num{125000} - 100 P +10 P_O + 10 M,
    \]
    #+end_export
    where:

    - $P$ is the price of the season tickets.

    - $P_O$ is the price of season tickets of other rival club whose
      stadium is located in the same city.

    - $M$ is the average yearly income of football fans.

    The rival club is selling its seasonal tickets at $P_O =
    \money{600}$. It is estimated that $M = \money{15000}$.

    a) Plot the demand and supply curves of season tickets and find
       the market equilibrium.

    b) Compute the price elasticities of demand and supply at
       equilibrium and explain the obtained values.

    c) Compute the elasticity of demand with respect to the price for
       the season tickets of the other club at equilibrium and explain
       the value obtained.

    d) Calculate the income elasticity of demand at equilibrium and
       explain the value obtained.

20. In a competitive market, the demand and supply curves are:
    #+begin_export latex
    \begin{gather*}
      Q^d = \num{100000} - 20 P \\
      Q^o = \num{40000} + 40 P
    \end{gather*}
    #+end_export

    a) Determine the equilibrium price and quantity.

    b) <<ex20:itemb>>Describe and show graphically the effects on this
       market of a tax of \money{150} per unit imposed on sellers. How
       much money will buyers pay per unit? How much will sellers
       receive per unit?

    c) Explain how your answers in [[ex20:itemb]] would change if the tax
       were levied on buyers.

21. The market demand and supply curves for good $X$ are:
    #+begin_export latex
    \begin{gather*}
      X^d = 100 - P_X / 40 \\
      X^o = 50 + P_X / 40
    \end{gather*}
    #+end_export

    a) Determine the equilibrium price and quantity.

    b) Describe and show graphically the effects on this market of
       setting a minimum price at \price{1200}. How many units will
       sell? At what price?

22. In a competitive market in equilibrium, \num{96000} units are sold
    at a price of \price{300}. The price elasticity of demand
    is $-1.5$, and the price elasticity of supply is equal to $2$. If
    a law that sets a maximum price of \price{294} is passed, which
    effect would it have on the market?

23. The market demand and supply curves for good $X$ are:
    #+begin_export latex
    \begin{gather*}
      X = 200 - 5 P_{X} + 3 P_{Y} + 2 I \\
      X = 100 + 2 P_{X}
    \end{gather*}
    #+end_export
    where $I$ is the consumers' average income and $P_Y$ is the price
    of good $Y$, with $I = \money{100}$ and $P_Y = \price{5}$. A law
    has been passed that does not allow $P_X$ to rise above
    $\money{50}$.

    a) <<ex23:itema>>How many units of $X$ will be sold? At what
       price? Represent graphically.

    b) Describe how your answers in [[ex23:itema]] would change if average
       income increased up to $I = \money{170}$.

24. Discuss the truth or falsity of the following statement: "If a
    maximum price is set above the equilibrium price, the quantity
    sold will be the same as the equilibrium quantity."

25. The residential rental market in a city is represented by the
    demand and supply curves:
    #+begin_export latex
    \begin{gather*}
      Q^{d} = \num{25000} - 30 P \\
      Q^{o} = \num{5000} +10 P
    \end{gather*}
    #+end_export

    a) Determine the market equilibrium.

    b) If tenants get a \money{200} rental subsidy, how much will pay
       tenants?  How much will landlords receive? Which will be the
       total cost of the subsidy?
