# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

* 5.21

Juan has a monthly monetary income of \money{150}. With that income he
can buy bread, at a price of \price[kg]{3}, and water, at a price of
\price[l]{0.75}.

a) Obtain Juan’s budget constraint and represent it graphically.

b) Juan consumes $60$ liters of water and $35$ kilos of bread every
   month. Which is the opportunity cost of consuming an additional
   liter of water? Which would be the opportunity cost if Juan
   consumed $50$ liters of water and $30$ kilos of bread?

c) An extended drought makes the price of water double. Obtain and
   represent the new budget constraint.

d) In view of the seriousness of the situation, the Government rations
   water so that no consumer can consume more than $20$ liters of
   water per month. Which is the budget constraint in this case?

** Answer

Not done yet.


* 5.25

Suppose that 4 pears can be bought with the money needed to buy one
apple. If David, who spends all his money on pears and apples, buys
100 pears and 20 apples, how many pears could he have bought at most?
And apples? Obtain and represent David’s budget constraint.


** Answer

Not done yet.


* 5.23

Julia has \money{6} this month for buying milk, which has a price of
\price[l]{0.75}, and cookies, with a price of \price[kg]{3}.

a) Obtain and represent the budget constraint.

b) Now, let’s suppose all prices rise by 10%. If the money Julia can
   spend also increases by 10%, how will her budget constraint change?

c) If originally, Julia bought $4$ liters of milk and $1$ kilo of
   cookies, how will her choice vary after the rise in prices and
   income?


** Answer

Not done yet.


* 5.1

A consumer spends her income $M$ on goods $X$ and $Y$.

a) How would her budget line change if a tax on consumption were
   introduced and the prices of both goods rose by 25%?

b) And what if, instead of the tax on consumption, an income tax were
   levied and $M$ decreased by 25%?

c) Which option would the consumer prefer?


** Answer

Not done yet.

* 5.20

Nikola has \money{120} for spending on natural gas and electricity.
The price of electricity depends on consumption: the first
\units[\kWh]{1000} cost \money{0.06} per kWh, whereas the kWh from
\num{1000} on are paid at \price[\kWh]{0.03}. On the other hand, the
price of natural gas is always \price[\kWh]{0.05}. Obtain and
represent graphically the budget set for Nikola.


** Answer

Not done yet.


* 5.22

A consumer has an income of $100$ € per week and consumes rice, at a
price of \money{1} per kilo. Obtain the mathematical expression and
represent the consumer’s budget constraint in the following situations
(use a composite good):

a) The consumer has a subsidy of \price[kg]{0.25} for the first five
   kilos of rice bought and pays the market price for the additional
   kilos bought.

b) The consumer gets $5$ kilos of rice for free.

c) The consumer gets a check of \money{5}.


** Answer

Not done yet.


* 5.2

A consumer has \money{20} to buy meat and potatoes. He usually shops
at a supermarket where the meat is sold for \price[kg]{4}, and one
kilo of potatoes costs \money{2}.

a) Obtain and represent the budget constraint.

b) The supermarket run a sales promotion where the customers that buy
   more than $4$ kilos of potatoes will get two additional kilos for
   free. Obtain and represent the budget constraint in this case.


** Answer

Not done yet.


* 5.24

Eugenio and Ana share an apartment. Each one of them has a monthly
income of \money{1000} that they entirely spend on food and
clothes. When the price of food is \price{8} and the price of clothes
is \price{40}, Ana buys 10 units of clothes and Eugenio buys 20 units.

After a tax reform, food price decreases until \price{4} and the price
for clothes increases up to \price{50}. With the information given, is
it possible to know if Ana’s satisfaction has increased or decreased?
And Eugenio’s?


** Answer

Not done yet.


* 5.25

Ángeles has \money{100} per month that she spends on phone calls and a
composite good. Her phone company just charges \money{0.02} per
minute.

a) Obtain and represent Ángeles’s budget constraint.

b) <<ex5.25:itemb>>Ángeles receives an offer by which, paying a fixed
   amount of \money{15} she would obtain \num{2000} minutes of
   calls. Each additional minute would cost \money{0.04}. Obtain and
   represent Ángeles’s budget constraint if she contracts this rate.

c) Represent both rates in the same graph and determine when the rate
   in [[ex5.25:itemb]] is more advantageous.


** Answer

Not done yet.


* 5.3

Amaia likes fish, while she neither likes nor dislikes
chicken. Alejandro, meanwhile, does not like fish but he does like
chicken, and he is only willing to eat some fish if he gets an extra
portion of chicken in return. Represent the preferences of Amaia and
Alejandro.


** Answer

Not done yet.


* 5.27

 Carmen collects old pictures. Today she has gone to a street market
 where she has bought 50 pictures for her collection, and she has
 still \money{150} to purchase other things. In one of the stands in
 the street market she has found a set of 10 pictures she is
 interested in, for which \money{25} are asked. Carmen’s utility
 function is:
 #+begin_export latex
 \[
   U(P, Y) = (P + 10) Y^{2}
 \]
 #+end_export
 where $P$ is the number of pictures she buys and $Y$ is a composite good.

 a) Will she buy the set of 10 pictures?

 b) How much will Carmen be willing to pay for $10$ additional
    pictures?


** Answer

Not done yet.


* 5.28

Five friends have bought fruit and each one of them has obtained the
same combination: 3 apples and 6 pears. The price of an apple is
\money{1} whereas a pear costs \money{0.50}. The following table shows
the marginal utility for apples and pears for each one of the
consumers:

#+ATTR_LATEX: :booktabs t :center t :align @{}l*{2}{r}@{}
|--------------+------------+----------|
|              | Apples     | Pears    |
|--------------+------------+----------|
| Jerry        | $12$       | $6$      |
| George       |  $6$       | $6$      |
| Elaine       |  $6$       | $3$      |
| Kramer       |  $3$       | $6$      |
| Newman       | $12$       | $3$      |
|--------------+------------+----------|

a) Which consumers, if any, *are not* choosing an optimal combination
   of apples and pears? How should they change their choice in order
   to increase their utility?

b) With the information given, is it possible to determine if any
   consumer is maximising utility?


** Answer

Not done yet.


* 5.4

The preferences of a consumer can be described with the utility
function: $U(X, Y) = 5 X Y^2$. The consumer's income is \money{900}
and the prices are $P_X = \price{10}$ and $P_Y = \price{5}$. Calculate
and represent the consumer's optimal choice.


** Answer

Not done yet.


* 5.6

The utility function of a consumer is $U (X, Y) = X Y$. The optimal
basket consists of 10 units of good $X$ and 5 units of good
$Y$. Knowing that the price of $X$ is \price{6}, how much is the
consumer's income?


** Answer

Not done yet.


* 6.4

Consider a competitive economy where all consumers have the same
preferences and consume some units of good $X$ and good $Y$. Will they
all buy the same amount of $X$? Will there be differences in the
valuation of good $X$ by each consumer?


** Answer

Not done yet.


* 5.7

A consumer has an income of \money{40} that she spends on goods $X$
and $Y$, whose prices are $P_X = \price{3}$ and $P_Y =
\price{2}$. When she consumes $20$ units of $Y$ and none of $X$, the
marginal rate of substitution is equal to $2$. Is this her optimal
choice or would she be better off buying more units of good $X$ and
less of good $Y$?


** Answer

Not done yet.


* 5.29

Determine the optimal combination for a consumer with income $M =
\money{500}$ and utility function: $U(X, Y) = X^2 (Y + 80)$, being the
prices of the goods $P_X = \price{2}$ y $P_Y = \price{5}$.


** Answer

Not done yet.


* 5.8

The function $U (N, Y) = (N + 4) Y$ describes the preferences of a
consumer between nuts, $N$, and a composite good that comprises the
money spent on all other goods, $Y$. The price of nuts is $P_N =
\price[kg]{8}$ and the consumer's income is $M =\money{40}$.

a) Obtain and represent the optimal choice of the consumer.

b) The Government aims to promote the consumption of nuts and it is
   considering different alternatives:

   + A subsidy that reduces the price of nuts by 20%. The subsidy
     can only be applied to the purchase of one and a half
     kilograms of nuts per consumer.

   + Give each consumer a voucher that can be redeemed for one and
     a half kilos of nuts.

   + Give each consumer \money{12} in cash.

   What would the consumer choose in each of these cases?

c) Which alternative would the consumer prefer? Justify your answer.


** Answer

Not done yet.


* 5.30

Rafa likes playing tennis and whenever he can he plays in a club near
his home. Renting a tennis court costs \money{5} per hour. His utility
function is:
#+begin_export latex
\[
  U(H, Y) = H Y^{3/2}
\]
#+end_export
where $H$ are the hours he plays tennis per month and $Y$ is a
composite good. Rafa has \money{100} per month to spend on $H$ and
$Y$.

a) Obtain the optimal choice of $H$ and $Y$.

b) Rafa is considering to become a member of the tennis club. If he
   paid a monthly fee of \money{30}, the rent for the court would be
   reduced to \money{2.50} per hour. Should he become a member of the
   club? Represent graphically.


** Answer

Not done yet.


* 5.10

The preferences of a consumer are given by the utility function:
$U(X, Y) = X (Y + 100)$. The price of good $X$ is \price{1} and
that of good $Y$ is \price{4}. The consumer has a monetary income
of \money{250}.

a) Determine the optimal consumption bundle.

b) If good $X$ were rationed so that nobody were allowed to buy
   more than 100 units of $X$, which would be the optimal choice?
   Represent graphically.


** Answer

Not done yet.


* 5.11

The utility function of an individual with respect to goods $X$
and $Y$ is given by $U(X, Y) = 3X + 3Y$. The market prices are
$P_X = \price{2}$ and $P_Y = \price{5}$ and the monetary income of
the consumer is $M = \money{100}$.

a) Is $(X, Y) = (10, 40)$ the optimal basket? Why?

b) Which is the optimal choice for the consumer?

c) How would the optimal choice change if $P_X = \price{10}$?


** Answer

Not done yet.


* 5.12

Rocío likes to eat cereal with milk for breakfast. She always
combines them in the same proportion: she adds exactly 20 grams of
cereal per every \units[ml]{250} of milk and discards any excess
of milk or cereal.

a) Represent Rocío's preferences regarding milk and cereal.

b) If Rocío spends \money{6} a month on milk and cereal, the
   price of the milk is \price[l]{0.80} and the price of cereals
   is \price[kg]{2}, what will be her optimal choice?


** Answer

Not done yet.
