# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 10.1.

Complete la siguiente tabla que describe la producción a corto
plazo de una empresa.

#+ATTR_LATEX: :booktabs t :center t :align @{}c*{3}{r}@{}
|--------------+------------+----------+----------|
|              | Producción | Producto | Producto |
| Trabajadores | total      | marginal | medio    |
|--------------+------------+----------+----------|
| $0$          | $0$        | ---      | ---      |
| $1$          |            | $120$    |          |
| $2$          | $210$      |          |          |
| $3$          |            |          | $95$     |
| $4$          |            | $31$     |          |
| $5$          |            |          | $64$     |
| $6$          | $306$      |          |          |
|--------------+------------+----------+----------|

¿Se cumple la ley de rendimientos marginales decrecientes?  ¿Son
técnicamente eficientes todos los niveles de contratación de
trabajadores mostrados en la tabla? ¿Por qué?


** Answer

Para completar la tabla se han utilizado las relaciones
#+begin_export latex
\begin{equation*}
  \PMeL = \frac{Q}{L} \qtext{y}\quad
  \PMgL \approx \iratio{Q}{L}.
\end{equation*}
#+end_export

#+ATTR_LATEX: :booktabs t :center t :align @{}c*{3}{r}@{}
|--------------+------------+----------+----------|
|              | Producción | Producto | Producto |
| Trabajadores | total      | marginal | medio    |
|--------------+------------+----------+----------|
| $0$          | $0$        | ---      | ---      |
| $1$          | $120$      | $120$    | $120$    |
| $2$          | $210$      | $90$     | $105$    |
| $3$          | $285$      | $75$     | $95$     |
| $4$          | $316$      | $31$     | $79$     |
| $5$          | $320$      | $4$      | $64$     |
| $6$          | $306$      | $-14$    | $51$     |
|--------------+------------+----------+----------|

Se cumple la ley de rendimientos decrecientes del factor trabajo.
Contratar 6 trabajadores no es técnicamente eficiente: el producto
marginal del sexto trabajador es negativo.



* 10.2.

Dada la función de producción $Q = L^2 K - 0.01 L^3$ y sabiendo que
el capital es fijo, $\Kbar = 6$, determine:

a) La curva de producto total.

b) Las curvas de producto medio y marginal del trabajo.

c) Los niveles del factor trabajo que hacen máximo el producto
   marginal, el producto medio y el producto total. Represente
   gráficamente los resultados obtenidos.


** Answer

a) Curva de producto total cuando $\Kbar = 6$:
   #+begin_export latex
   \[
     Q = 6 L^2 - 0.01 L^3.
   \]
   #+end_export

b) Producto medio:
   #+begin_export latex
   \[
     \PMeL = \frac{Q}{L} = 6 L - 0.01 L^2.
   \]
   #+end_export

   Producto marginal:
   #+begin_export latex
   \[
     \PMgL = \frac{\diff Q}{\diff L} = 12 L - 0.03 L^2.
   \]
   #+end_export

c) /Maximización del \PMgL/: La derivada del producto marginal es:
   #+begin_export latex
   \[
     \frac{\diff \PMgL}{\diff L} = 12 - 0.06 L.
   \]
   #+end_export
   Igualando a 0 la expresión anterior y resolviendo $L$, obtenemos
   $L_A = 200$.

   /Maximización del \PMeL/: La derivada del producto medio es:
   #+begin_export latex
   \[
     \frac{\diff \PMeL}{\diff L} = 6 - 0.02 L.
   \]
   #+end_export
   Igualando a 0 la expresión anterior y resolviendo $L$, obtenemos
   $L_B = 200$.

   /Maximización de la producción/: La derivada del producto total es
   el producto marginal.  Resolviendo $L$ en la ecuación $\PMgL = 0$,
   obtenemos $L_C = 400$.

   #+ATTR_LATEX: :options [b]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-pmgl-*.pdf
   #+ATTR_LATEX: :options [b]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-fprod-*.pdf
   #+xxx: endcol



* 10.3

Con las siguientes funciones de producción:

#+ATTR_LATEX: :options [leftmargin=4pc, labelwidth=\widthof{XX.}, align=left, label=\Roman*. ]
A. $Q  = 2 K + 3 L$

B. $Q  = K^{1/2} L^{1/2}$

C. $Q  = K L^2$

y sabiendo que el capital es un factor fijo, $\Kbar = 4$:

a) Represente las curvas de producto total en cada caso.

b) ¿Cumple alguna de esas funciones de producción la ley de
   rendimientos decrecientes del factor trabajo?


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.33\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-total-a-*.pdf

   #+begin_export latex
     \centering%
     \mbox{I. $Q = 8 + 3 L$}
   #+end_export
   #+ATTR_LATEX: :options [t]{0.34\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-total-b-*.pdf

   #+begin_export latex
     \centering%
     \mbox{II. $Q = 2 L^{1/2}$}
   #+end_export
   #+ATTR_LATEX: :options [t]{0.33\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-total-c-*.pdf

   #+begin_export latex
     \centering%
     \mbox{III. $Q = 4 L^2$}
   #+end_export
   #+xxx: endcol

b)
   #+ATTR_LATEX: :options [t]{0.33\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-marginal-a-*.pdf

   #+begin_export latex
     \centering%
     \mbox{I. $\PMgL = 3$}
   #+end_export
   #+ATTR_LATEX: :options [t]{0.34\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-marginal-b-*.pdf

   #+begin_export latex
     \centering%
     \mbox{II. $\PMgL = L^{-1/2}$}
   #+end_export
   #+ATTR_LATEX: :options [t]{0.33\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-marginal-c-*.pdf

   #+begin_export latex
     \centering%
     \mbox{III. $\PMgL = 8 L$}
   #+end_export
   #+xxx: endcol
   #+latex: \vspace*{1.5ex}

   Sólo es decreciente el $\PMgL$ de la segunda función.



* 10.4

Dibuje en cada uno de los siguientes gráficos donde se situaría la
curva de producto marginal del trabajo. Justifique su respuesta.

#+xxx: fig fig-probl-8_1004-pmel-*.pdf


** Answer


#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-8_1004-pmel-a-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
*(A)*: Si el producto marginal es mayor que el medio, el producto
medio es creciente. Si el producto marginal es menor que el medio, el
producto medio es decreciente. Coinciden en el máximo del producto
medio.
#+xxx: endcol

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-8_1004-pmel-b-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
*(B)*: Cuando el producto medio es decreciente, el producto marginal
se sitúa por debajo del medio.
#+xxx: endcol

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-8_1004-pmel-c-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
*(C)*: Cuando el producto medio es creciente, el producto marginal
está por encima del medio.
#+xxx: endcol

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-8_1004-pmel-d-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
*(D)*: Cuando el producto medio es constante, coinciden el producto
marginal coincide y el producto medio.
#+xxx: endcol



* 10.5.

Si el producto marginal del trabajo es decreciente en el corto plazo,
¿el producto medio debe ser también decreciente?


** Answer

No: el producto medio decrece cuando el producto marginal es inferior
al medio.

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-8_1004-pmel-decr-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
En el área sombreada el producto marginal es decreciente y, sin
embargo, el producto medio es creciente.
#+xxx: endcol



* 10.6.

La producción por trabajador en una empresa es de 20 sillas al día. El
propietario de la empresa ha calculado que un trabajador adicional
elevaría la producción diaria en 10 sillas. ¿Qué ocurrirá con el
producto medio si la empresa contrata otro trabajador?


** Answer

El producto marginal en esta empresa se corresponde con las 10 sillas
en que aumentaría la producción si se contrata un trabajador más. Por
otro lado, la producción media es de 20 sillas por trabajador.  Como
$\PMgL < \PMeL$, el producto medio es decreciente.



* 10.7.

El siguiente gráfico muestra algunas isocuantas de la función de
producción de una empresa:

#+xxx: fig fig-probl-8_1004-const-returns-*.pdf

a) Si la empresa produce eficientemente 250 unidades y contrata 5
   trabajadores, ¿cuántas unidades de capital está utilizando? ¿Y si
   produce 125 unidades con 4 trabajadores?

b) Si la empresa está empleando 8 trabajadores y 6 unidades de
   capital, ¿es posible que la producción sea de 400 unidades?
   ¿Sería posible producir 200 unidades? ¿Qué ocurriría en este
   caso?

c) ¿Qué tipo de rendimientos de escala presenta la función de
   producción?


** Answer

a)
   #+ATTR_LATEX: :options [t]{\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+xxx: fig fig-ans-probl-8_1004-const-returns-a-*.pdf
   #+xxx: endcol
   #+latex: \vspace*{1ex}

   Si produce eficientemente $250$ unidades y utiliza 5 trabajadores,
   la empresa ha escogido la combinación de factores *A*, donde emplea
   5 unidades de capital. Si produjera $125$ unidades con 4
   trabajadores, se encontraría en *B* y usaría 2 unidades de capital.

b) La combinación $L = 8$ y $K = 6$ está representada por el punto *C*
   del gráfico anterior. Esta punto se halla por debajo de la
   isocuanta $Q = 375$. Por tanto no es posible producir
   $400$ unidades en esas condiciones.

   Por otro lado, el punto *C* está por encima de la isocuanta $Q =
   250$, por lo que es posible producir $200$ unidades con 8
   trabajadores y 6 unidades de capital. Pero ese nivel de producción
   no sería eficiente.

c) Cuando se usan 5 trabajadores y 5 unidades de capital, combinación
   *A*, se producen $125$ unidades. Si se duplican los factores y se
   emplea 10 trabajadores y 10 unidades de capital, combinación *D*,
   la producción asciende a $250$ unidades. La función de producción
   presenta rendimientos constantes de escala: cuando se duplica el
   uso de factores se duplica también el nivel de producción.



* 10.8.

¿Es correcta la siguiente afirmación? Justifique su respuesta: "Una
empresa cuya función de producción $Q = F(K, L)$ presenta rendimientos
constantes de escala verá duplicada su producción cuando duplique el
uso del factor capital."


** Answer

No es correcta. Si la tecnología que usa la empresa es de rendimientos
constantes de escala, la producción se duplicará cuando se dupliquen
/todos/ los factores de producción, no sólo el factor trabajo.


* 10.9.

Una fábrica utiliza trabajo y capital para producir zapatos. Después
de aumentar el número de trabajadores en un 50% la producción crece en
un 60%. ¿Qué tipo de rendimientos de escala presenta la función de
producción de la empresa?


** Answer

No es posible determinar los rendimientos de escala de la función de
producción si sólo ha cambiado el número de trabajadores. Sería
necesario saber en qué proporción aumenta la producción de la empresa
cuando /todos/ los factores de producción aumentan en la /misma/
proporción.


* 10.10.

El siguiente gráfico muestra algunas isocuantas de la función de
producción de una empresa:

#+xxx: fig fig-probl-8_1004-incr-returns-*.pdf

a) ¿Qué tipo de rendimientos de escala exhibe la función de producción
   de la empresa?

b) Si $\Kbar = 5$, ¿se cumple la ley de rendimientos marginales
   decrecientes?


** Answer

a)
   #+ATTR_LATEX: :options [t]{\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+xxx: fig fig-ans-probl-8_1004-incr-returns-a-*.pdf
   #+xxx: endcol
   #+latex: \vspace*{1ex}

   Se producen 250 unidades cuando se emplean 5 unidades de trabajo y
   5 unidades de capital, combinación *B*. Si se duplica el uso de los
   factores, combinación *E*, la producción superará las 750
   unidades. Por tanto, la función de producción presenta rendimientos
   crecientes de escala: al duplicar los factores se obtiene un nivel
   de producción que es más del triple que el inicial.

b) La siguiente tabla contiene información de algunas combinaciones de
   factores y la producción que se obtendría con ellas. En todas estas
   combinaciones se mantiene fijo el capital, $\Kbar = 5$:
   #+ATTR_LATEX: :booktabs t :center t :align @{}l*{4}{R{1.125cm}}@{}
   |------------+---------+------+-------+---------------------|
   |            | $\Kbar$ | $L$  | $Q$   | $\PMgL$             |
   |------------+---------+------+-------+---------------------|
   | \textbf{A} | $5$     | $2$  | $100$ | ---                 |
   | \textbf{B} | $5$     | $5$  | $250$ | $50$                |
   | \textbf{C} | $5$     | $10$ | $500$ | $50$                |
   | \textbf{D} | $5$     | $15$ | $750$ | $50$                |
   |------------+---------+------+-------+---------------------|
   La última columna es el cociente de las variaciones de producción y
   trabajo cuando pasamos de una fila de la tabla a la siguiente.  Por
   ejemplo, el valor del $\PMgL$ en la segunda fila se obtiene como:
   #+begin_export latex
   \[
     \PMgL \approx \eval{\iratio{Q}{L}}{\Kbar} =  \frac{250 - 100}{5 - 2} = 50
   \]
   #+end_export

   Examinando la última columna de la tabla, concluimos que no se
   cumple la ley de rendimientos marginales decrecientes: los
   rendimientos del factor trabajo son constantes.


* 10.11.

Considere las siguientes funciones de producción:

#+ATTR_LATEX: :options [leftmargin=4pc, labelwidth=\widthof{XX.}, align=left, label=\Roman*. ]
A. $Q  = K^{3/4} L^{1/4}$

B. $Q  = K^{3/2} L^{1/2}$

C. $Q  = 2K + 4L$

D. $Q  = (K + L)^{1/2}$

E. $Q  = (K + L)^{2}$

Responda a las siguientes preguntas para cada una de las funciones
de producción:

a) Obtenga la tasa de sustitución entre los factores de producción.

b) <<ex8.11:item-b>>¿Qué tipo de rendimientos de escala presenta la función de
   producción?

c) <<ex8.11:item-c>>Compruebe si se cumple la ley de rendimientos marginales
   decrecientes cuando $\Kbar=16 \text{\ unidades}$.

d) Comparando los resultados de [[ex8.11:item-b]] y [[ex8.11:item-c]], ¿hay
   algún tipo de relación entre los rendimientos de escala y los
   rendimientos del factor trabajo?


** Answer

a)
   #+latex: \begin{adjustbox}{valign=t}
   #+ATTR_LATEX: :booktabs t :center nil :align @{}p{1cm}*{3}{>{$}l<{$}}@{}
   |------+------------------------+------------------------+----------|
   |      | \PMgL                  | \PMgK                  |    \RMST |
   |------+------------------------+------------------------+----------|
   | I.   | (1/4) K^{3/4} L^{-3/4} | (3/4) K^{-1/4} L^{1/4} | (1/3)K/L |
   | II.  | (1/2) K^{3/2} L^{-1/2} | (3/2) K^{1/2} L^{1/2}  | (1/3)K/L |
   | III. | 4                      | 2                      |        2 |
   | IV.  | (1/2)(K+L)^{-1/2}      | (1/2)(K+L)^{-1/2}      |        1 |
   | V.   | 2(K + L)               | 2(K+L)                 |        1 |
   |------+------------------------+------------------------+----------|
   #+latex: \end{adjustbox}

   La \RMST es la tasa a la que se pueden sustituir los factores sin
   alterar el nivel de producción y se calcula dividiendo los
   productos marginales del trabajo y del capital. La tabla anterior
   muestra la \RMST de cada una de las funciones de producción-

b) Para determinar el tipo de rendimientos de escala, calculamos el
   nivel de producción que se obtiene al multiplicar los factores de
   producción por $s$. Si, por ejemplo, $s = 2$ estamos calculando qué
   cantidad se produce cuando se duplican los factores.

   Consideremos la primera función de producción:
   #+begin_export latex
   \begin{equation*}
     F(L, K) = K^{3/4}L^{1/4}
   \end{equation*}
   #+end_export
   Si multiplicamos los factores por $s$:
   #+begin_export latex
   \begin{equation*}
     F(sL, sK) = (sK)^{3/4}(sL)^{1/4} =
     sK^{3/4}L^{1/4}
   \end{equation*}
   #+end_export
   Por tanto:
   #+begin_export latex
   \begin{equation*}
     F(sL, sK) = s F(L, K)
   \end{equation*}
   #+end_export
   La producción aumenta en la misma proporción que lo han hecho los
   factores y la función de producción exhibe rendimientos constantes
   de escala.

   La siguiente tabla resume los resultados de aplicar el mismo
   procedimiento a las restantes funciones de producción.

   #+ATTR_LATEX: :booktabs t :center nil :align @{}p{1cm}p{2.5cm}l@{}
   |------+-------------------+------------------------|
   |      | $F(s L, s K)$     | Rendimientos de escala |
   |------+-------------------+------------------------|
   | I.   | $s F(L, K)$       | Constantes             |
   | II.  | $s^2 F(K, L)$     | Crecientes             |
   | III. | $s F(L, K)$       | Constantes             |
   | IV.  | $s^{1/2} F(L, K)$ | Decrecientes           |
   | V.   | $s^{2} F(L, K)$   | Crecientes             |
   |------+-------------------+------------------------|

c) Podemos verificar si se cumple la ley de rendimientos decrecientes
   comprobando el signo de la derivada del producto marginal del
   trabajo:

   #+ATTR_LATEX: :booktabs t :center nil :align @{}p{1cm}p{2.5cm}l@{}
   |------+-------------------------+-------------------------|
   |      | $\diff \PMgL / \diff L$ | Rendimientos del factor |
   |------+-------------------------+-------------------------|
   | I.   | $-(3/2)L^{-7/4}$        | Decrecientes            |
   | II.  | $-16 L^{-3/2}$          | Decrecientes            |
   | III. | $0$                     | Constantes              |
   | IV.  | $-(1/4)(L + 16)^{-3/2}$ | Decrecientes            |
   | V.   | $2$                     | Crecientes              |
   |------+-------------------------+-------------------------|

   El producto marginal de la función III es constante (su derivada es
   0). En el caso de la función V el producto marginal es creciente
   (su derivada es positiva). Las restantes funciones de producción
   cumplen con la ley de rendimientos marginales decreciente ya que
   las derivadas del producto marginal son negativas.

d) No hay relación entre el tipo de rendimientos de escala de una
   función de producción y el comportamiento de sus rendimientos
   marginales.

   #+latex: \begin{adjustbox}{valign=t}
   #+ATTR_LATEX: :booktabs t :center nil :align @{}lll@{}
   |------+------------------------+-------------------------|
   |      | Rendimientos de escala | Rendimientos del factor |
   |------+------------------------+-------------------------|
   | I.   | Constantes             | Decrecientes            |
   | II.  | Crecientes             | Decrecientes            |
   | III. | Constantes             | Constantes              |
   | IV.  | Decrecientes           | Decrecientes            |
   | V.   | Crecientes             | Crecientes              |
   |------+------------------------+-------------------------|
   #+latex: \end{adjustbox}
