#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 1


* Principios básicos de la organización económica

1. Un país dispone de \num{50000} unidades de un factor de producción
   (horas de trabajo, por ejemplo) con el que se producen dos tipos de
   bienes: automóviles y comida. La siguiente tabla muestra las
   cantidades de estos bienes que pueden producirse dependiendo de las
   unidades del factor que se dediquen a cada actividad:

   #+ATTR_LATEX: :booktabs t :center t :align rrp{1cm}rr
   |-------------+--------------+---+-------------+--------------|
   | Factor      | Automóviles  |   | Factor      | Comida       |
   | (unidades)  | (unidades)   |   | (unidades)  | (Tm)         |
   |-------------+--------------+---+-------------+--------------|
   | \num{0}     | \num{0}      |   | \num{0}     | \num{0}      |
   | \num{12500} | \num{40000}  |   | \num{12500} | \num{50000}  |
   | \num{25000} | \num{70000}  |   | \num{25000} | \num{75000}  |
   | \num{37500} | \num{90000}  |   | \num{37500} | \num{90000}  |
   | \num{50000} | \num{100000} |   | \num{50000} | \num{100000} |
   |-------------+--------------+---+-------------+--------------|

   a) Represente gráficamente la Frontera de Posibilidades de
      Producción (FPP) del país.

   b) ¿Qué tiene de particular la forma de la FPP obtenida?

   c) Al incrementar la producción de automóviles: ¿aumenta o
      disminuye su coste de oportunidad?

   d) ¿Qué efectos tendría sobre la FPP una mejora transgénica que
      mejorara la resistencia de los productos agrícolas a las
      plagas? ¿Y una mejora organizativa en la cadena de producción
      de automóviles? ¿Y si ambas mejoras se diesen simultáneamente
      como consecuencia de un progreso técnico generalizado en la
      sociedad?

   e) ¿Qué consecuencias tendría sobre la FPP la destrucción de la
      mitad de las unidades del factor de producción como consecuencia
      de un conflicto bélico?

2. La tabla adjunta presenta diferentes combinaciones eficientes de
   producción para una economía en la que únicamente se producen dos
   bienes: $X$ e $Y$.

   #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{r}
   |-----+------------+------------|
   |     | $X$        | $Y$        |
   |     | (unidades) | (unidades) |
   |-----+------------+------------|
   | *A* | \num{20}   | \num{0}    |
   | *B* | \num{18}   | \num{1}    |
   | *C* | \num{15}   | \num{2}    |
   | *D* | \num{11}   | \num{3}    |
   | *E* | \num{6}    | \num{4}    |
   | *F* | \num{0}    | \num{5}    |
   |-----+------------+------------|

   a) Represente la FPP.

   b) ¿Se pueden producir \num{2} unidades de $Y$ y \num{10} unidades
      de $X$?  ¿Qué ocurre en esta situación?

   c) Construya una tabla que refleje el coste de oportunidad de
      producir cada unidad del bien $Y$.

   d) ¿A cuántas unidades de $X$ se debe renunciar para producir la
      segunda unidad de $Y$?

3. En el mercado del bien $X$ participan \num{1000} consumidores
   idénticos, cada uno de ellos con curva de demanda: \[X^D_i = 5 -
   P_X, \qquad i = 1, ..., \num{1000}.\] El bien $X$ es producido por
   \num{500} empresas idénticas, cada una con curva de oferta:
   \[X^O_j = 2.4 P_X , \qquad j = 1, ..., \num{500}. \]

   a) Halle las curvas de demanda y oferta de mercado y la
      solución de equilibrio.

   b) ¿Qué ocurriría en este mercado si los oferentes decidieran fijar
      un precio de \price{4}? ¿Y si deciden que el mejor precio es
      \price{1.5}?

   c) Si se produce un incremento de la renta de los consumidores, de
      forma que la curva de demanda de mercado pasa a ser: \[X^D =
      \num{7500} - \num{1000} P_X,\] ¿cuál es el nuevo equilibrio?

   d) En la situación de equilibrio inicial, una mejora tecnológica en
      el sector desplaza la curva de oferta de mercado hasta \[X^O =
      \num{2500} + \num{1200} P_X.\] Determine el nuevo equilibrio.

   e) En la situación de equilibrio inicial, ¿qué ocurriría si el
      gobierno decidiese fijar un precio máximo de \price{1} para este
      bien?  ¿Y si se estableciera un precio mínimo de \price{3}?

4. La empresa que gestiona un túnel se está planteando alterar el
   peaje que cobra a los usuarios del túnel. Actualmente el peaje es
   de \money{6} y \num{2400} conductores utilizan el túnel
   diariamente. Una consultora ha estimado que la función $Q =
   \num{6000} - \num{600} P$ describe la demanda diaria del túnel.

   a) ¿Cuál es la elasticidad de la demanda al precio actual?

   b) Si la empresa persigue aumentar sus ingresos, ¿sería conveniente
      que rebajase el peaje?

   c) ¿Cuál es el peaje que maximizaría los ingresos de la empresa?

5. Una universidad ofrece 100 plazas en el Grado en Economía y la
   demanda de estos estudios viene dada por: \[Q =
   1901 - 2 P_{EC} + 0.1 P_{AE}\] donde $Q$ es el número de alumnos
   que demandan una plaza en el Grado en Economía; $P_{EC}$ y $P_{AE}$
   son, respectivamente, los precios de las matrículas del Grado en
   Economía y del Grado en Administración de Empresas. Sabiendo que
   $P_{AE} = \money{1000}$:

   a) ¿Qué ocurrirá si se fija el precio de la matrícula en $P_{EC} =
      \money{1000}$?

   b) ¿Cuál es el precio máximo que puede establecerse para que todas
      las plazas ofertadas se cubran?

   c) ¿Qué tipo de bien son los estudios de Grado en Economía con
      respecto a los estudios de Grado en Administración de Empresas?

   d) ¿Qué efecto tendrá sobre la demanda de plazas en Grado en
      Economía un aumento de $P_{BA}$?

6. Un club de fútbol dispone de un cupo máximo de \num{125000} socios.
   La demanda de abonos anuales de los aficionados es: \[Q =
   \num{125000} - 100 P +10 P_O + 10 M,\] donde:

   - $P$ es el precio del abono del club.

   - $P_O$ es el precio del abono del otro club con estadio en la
     misma ciudad

   - $M$ es la renta anual media de los aficionados.

   Este año el club rival ha anunciado un precio de sus abonos de $P_O
   = \money{600}$. Por otro lado, se estima que $M =  \money{15000}$.

   a) Calcule el precio que se debería fijar para vender exactamente
      \num{125000} abonos. Represente gráficamente las curvas de
      demanda y de oferta de abonos en esta situación.

   b) Calcule las elasticidades de la demanda y de la oferta de abonos
      del club en la situación de equilibrio e interprete los valores
      y los signos de esas elasticidades.

   c) Calcule la elasticidad de la demanda con respecto al precio del
      abono del equipo rival en la situación de equilibrio e
      interprete el valor y el signo obtenidos.

   d) Calcule la elasticidad renta de la demanda en la situación de
      equilibrio e interprete el valor y el signo obtenidos.
