# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

* 4.1

\TASK The following graph shows the demand and supply curves for a
competitive market:

#+xxx: fig fig-probl-4_1004-price-controls-*.pdf

Find the quantity that would be sold and at what price in each of
the following situations:

a) A minimum price of \price{1.50} is established.

b) A maximum price of \price{1.50} is established.

c) A minimum price of \price{4.00} is established.

d) A maximum price of \price{4.00} is established.


** Answer

Not done yet.


* 4.2

The market demand and supply curves for good $X$ are:
#+begin_export latex
\begin{gather*}
  X^d = 100 - P_X / 40 \\
  X^o = 50 + P_X / 40
\end{gather*}
#+end_export

a) Determine the equilibrium price and quantity.

b) Describe and show graphically the effects on this market of
   setting a minimum price at \price{1200}. How many units will
   be sold? At what price?


** Answer

Not done yet.


* 4.3

The price in a competitive sugar market is \money{0.75} per
kilo. Represent graphically and explain the effects on this market of
setting a minimum price of \price[kg]{0.60}. Will more or
less kilos of sugar be sold?


** Answer

Not done yet.


* 4.4

\DANGER In a competitive market in equilibrium, \num{96000} units are
sold at a price of \price{300}. The price elasticity of demand
is $-1.5$, and the price elasticity of supply is equal to $2$. If a
law that establishes a maximum price of \price{294} is passed, which
effect would it have on the market? Represent graphically.


** Answer

Not done yet.


* 4.5

\TASK The market demand and supply curves for good $X$ are:
#+begin_export latex
\begin{gather*}
  X = 200 - 5 P_{X} + 3 P_{Y} + 2 I \\
  X = 100 + 2 P_{X}
\end{gather*}
#+end_export
where $I$ is the consumers' average income and $P_Y$ is the price
of good $Y$, with $I = \money{100}$ and $P_Y = \price{5}$. A law
has been passed that does not allow $P_X$ to rise above
$\money{50}$.

a) <<ex4.4:item-a>>How many units of $X$ will be sold? At what
   price? Represent graphically.

b) Describe how your answers in [[ex4.4:item-a]] would change if average
   income increased up to $I = \money{170}$.


** Answer

Not done yet.


* 4.6

Discuss the truth or falsity of the following statement: "If a
maximum price is set above the equilibrium price, the quantity
sold will be the same as the equilibrium quantity."


** Answer

Not done yet.


* 4.7

In a market, the demand and supply curves are:
#+begin_export latex
\begin{gather*}
  Q^d = \num{100000} - 20 P \\
  Q^o = \num{40000} + 40 P
\end{gather*}
#+end_export

a) Determine the equilibrium price and quantity.

b) <<ex4.1:item-b>>Describe and show graphically the effects on this
   market of a tax of \money{150} per unit imposed on sellers. How is
   the tax burden distributed between buyers and sellers?

c) Calculate the price elasticity of demand and supply at the
   equilibrium before the tax. What is the relationship between the
   distribution of the tax burden and those elasticities?

d) Explain how your answers in [[ex4.1:item-b]] would change if the tax
   was imposed on buyers.


** Answer

Not done yet.


* 4.8

\TASK The residential rental market in a city is represented by the
demand and supply curves:
#+begin_export latex
\begin{gather*}
  Q^{d} = \num{25000} - 30 P \\
  Q^{o} = \num{5000} +10 P
\end{gather*}
#+end_export

a) Determine the market equilibrium.

b) The city council establishes a rental subsidy program whereby
   tenants receive a grant of \money{200} per month. How will this
   program affect the monthly rent that landlords charge? How will the
   amount each tenant pays for rent change? What will be the total
   cost of the rental subsidy program for the city council? Represent
   graphically.


** Answer

Not done yet.
