# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 6.1

Considere las preferencias representadas en los siguientes gráficos,
donde las flechas indican la dirección en que aumenta la utilidad:

#+xxx: fig fig-probl-06_1004-maps-*.pdf

Determine en cada caso qué supuestos de las preferencias regulares se
están incumpliendo. Justifique sus respuestas.


** Answer

- *(A)*: En el caso del bien $X$ se incumple el supuesto de no
  saturación. $X$ es un bien neutro.

- *(B)*: En todos las combinaciones se incumple el supuesto de no
  saturación para alguno de los dos bienes. Los bienes $X$ e $Y$ son
  complementos perfectos.

- *(C)*: No se cumple el supuesto de no saturación para $Y$. De hecho,
  el consumidor empeora conforme más unidades de $Y$ consume. $Y$ es
  un mal.

- *(D)*: Las curvas de indiferencia no son /estrictamente/
  convexas. Los bienes $X$ e $Y$ son perfectamente sustitutivos.



* 6.2

A Amaia le gusta el pescado, mientras que el pollo ni le gusta ni
le disgusta. Por su parte, a Alejandro no le gusta el pescado pero
sí el pollo y sólo está dispuesto a comer algo de pescado si a
cambio recibe una porción extra de pollo. Represente las
preferencias de Amaia y de Alejandro.


** Answer

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-06_1004-neutral-*.pdf
#+begin_center
Amaia
#+end_center
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-06_1004-bad-*.pdf
#+begin_center
Alejandro
#+end_center
#+xxx: endcol
#+latex: \vspace*{2ex}

Para Amaia el pollo es un bien neutral: su utilidad permanece
constante si consume más pollo y no cambia su consumo de pescado.

Para Alejandro el pescado es un mal: su utilidad disminuye si crece su
consumo de pescado y no varía su consumo de pollo.

* 6.3

Pablo se muestra indiferente entre la cesta $A$, que contiene 6
manzanas y 2 naranjas, y la cesta $B$, con 2 manzanas y 6
naranjas. Responda a las siguientes preguntas teniendo en cuenta que
las preferencias de Pablo son regulares:

a) Si Pablo tuviera que elegir entre la cesta $A$ y la cesta $C$, que
   contiene 3 manzanas y 7 naranjas, ¿cuál sería su mejor opción?

b) ¿Y si la elección fuera entre la cesta $A$ y la cesta $D$, con 5
   manzanas y 4 naranjas?


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-06_1004-rega-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   La cesta $C$ contiene más manzanas y naranjas que la cesta $B$: el supuesto
   de no saturación implica que $C \succ B$. Dado que $B \sim A$ y las
   preferencias son transitivas, concluimos que $C \succ A$.
   #+xxx: endcol

b)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-06_1004-regb-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Si las preferencias son (estrictamente) convexas, todas las cestas situadas
   en el segmento $\overline{AB}$ (como $M$) serán preferidas a $A$: $M \succ
   A$. Por otro lado, $D$ contiene más naranjas que $M$ por lo que $D \succ
   M$. Finalmente, por la transitividad de las preferencias, deducimos que $D
   \succ A$.
   #+xxx: endcol


* 6.4

Sabiendo que las preferencias de un consumidor se pueden representar con la
función de utilidad $U(X, Y) = X^2 Y$, complete los datos que faltan en la
siguiente tabla:

#+ATTR_LATEX: :booktabs t :center t :align @{}*{5}{rp{0.65cm}}r@{}
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|
| $X$ |   | $Y$ |   | $U$ |   | $\UMX$ |   | $\UMY$ |   | $\RMS$ |
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|
|   2 |   |   3 |   |     |   |     12 |   |        |   |        |
|   4 |   |     |   |     |   |      8 |   |        |   |        |
|     |   |     |   |     |   |      6 |   |      1 |   |        |
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|


** Answer

#+ATTR_LATEX: :booktabs t :center t :align @{}*{5}{rp{0.1cm}}r@{}
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|
| $X$ |   | $Y$ |   | $U$ |   | $\UMX$ |   | $\UMY$ |   | $\RMS$ |
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|
|   2 |   |   3 |   | 12  |   |     12 |   |      4 |   |      3 |
|   4 |   |   1 |   | 16  |   |      8 |   |     16 |   |    1/2 |
|   1 |   |   6 |   |  6  |   |      6 |   |      1 |   |      6 |
|-----+---+-----+---+-----+---+--------+---+--------+---+--------|




* 6.5

La función de utilidad de Carlos es $U(X, Y) = X Y$. Si consume la
cesta $A$, que consta de 2 unidades del bien $X$ y 10 unidades del
bien $Y$:

a) ¿Cuál sería la utilidad de Carlos? ¿Aumentaría su utilidad si
   obtuviera 1 unidad más de $X$ a cambio de 2 unidades de $Y$?

b) Obtenga y represente la curva de indiferencia que contiene la cesta
   $A$.

c) ¿A cuántas unidades del bien $Y$ estaría dispuesto a renunciar
   Carlos a cambio de una unidad adicional del bien $X$?


** Answer

a) La utilidad de Carlos cuando consume $A$ es: $U(2, 10) = 2 \cdot 10 = 20$. Si
   cambia dos unidades de $Y$ por una unidad de $X$, aumentaría su utilidad:
   $U(3, 8) = 24$.

b)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-06_1004-cd-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Todas las cestas indiferentes a $A$ cumplen: $20 = XY$. La curva
   de indiferencia que pasa por $A$, $I_A$, puede expresarse como:
   #+begin_export latex
   \[
     Y = \frac{20}{X}
   \]
   #+end_export
   #+xxx: endcol

c) La relación marginal de sustitución
   #+begin_export latex
   \[
     \RMS = \frac{\UMX}{\UMY} = \frac{Y}{X}
   \]
   #+end_export
   muestra a cuántas unidades de $Y$ renunciaría Carlos a cambio de
   una unidad adicional de $X$.  En la cesta $A$: $\RMS(2, 10) = 10 /
   2 = 5$ unidades de $Y$ por unidad de $X$.


* 6.6

Luna y Aurora son dos hermanas cuyas preferencias son idénticas y se pueden
representar por la función de utilidad: $U(X, Y) = 6 X + 3 Y$. Luna
consume la cesta $L = (1, 5)$ mientras que Aurora consume la cesta $A
= (3, 2)$.

a) Calcule los niveles de utilidad de Luna y de Aurora.

b) Obtenga la relación marginal de sustitución de cada hermana.

c) Obtenga y dibuje las curvas de indiferencia de Luna y de Aurora.


** Answer

a) En el caso de Luna: $U_L = 6 \cdot 1 + 3 \cdot 5 = 21$. La utilidad
   de Aurora es $U_A = 6 \cdot 3 + 3 \cdot 2 = 24$.

b) Las utilidades marginales de las dos hermanas no dependen de las unidades que se consumen de $X$ o de $Y$. La relación marginal de sustitución es la misma para Luna y para Aurora:
   #+begin_export latex
   \[
     \RMS = \frac{\UMX}{\UMY} = \frac{6}{3} = 2.
   \]
   #+end_export
   Ambas estarían dispuestas a cambiar hasta 2 unidades de $Y$ por 1
   unidad de $X$.

c)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-06_1004-subst-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Para Luna y Aurora los bienes $X$ e $Y$ son perfectamente
   sustitutivos y sus curvas de indiferencia son líneas rectas:

   - Luna: $Y = 7 - 2 X$.

   - Aurora: $Y = 8 - 2 X$.
   #+xxx: endcol



* 6.7

 Carmen es coleccionista de fotos antiguas. Hoy ha acudido a un
 mercadillo donde ha comprado 50 fotos para su colección y aún dispone
 de \money{150} para otras compras. En uno de los puestos del
 mercadillo ha encontrado un lote de 10 fotos que le interesan y por
 el que piden \money{25}. La función de utilidad de Carmen es:
 #+begin_export latex
 \[
   U(F, Y) = (F + 10) Y^{2}
 \]
 #+end_export
 donde $F$ es el número de fotos que compra e $Y$ un bien compuesto.

 a) ¿Comprará el lote de 10 fotos?

 b) ¿Cuánto estará dispuesta a pagar Carmen por $10$ fotos adicionales?


** Answer

a) Si no comprara el lote de fotos, la utilidad de Carmen sería:
   #+begin_export latex
   \[ U(50, 150) = 60 \cdot 150^2 = \num{1350000}.\]
   #+end_export
   En cambio, si lo comprara, tendría 60 fotos y le quedarían
   \money{125} para gastar en otras cosas. Su utilidad sería:
   #+begin_export latex
   \[ U(60, 125) = 70 \cdot 125^2 = \num{1093750}.\]
   #+end_export
   Carmen no compraría el lote de fotos ya que disfruta de un mayor
   nivel de utilidad en ese caso.

b) Si Carmen comprara las fotos por $V$ euros su utilidad sería:
   #+begin_export latex
   \[ U(60, 150 -V) = 70 (150 - V)^2. \]
   #+end_export
   Carmen sólo compraría el lote de fotos si su utilidad no
   disminuyera:
   #+begin_export latex
   \[ U(60, 150 - V) \geq U(50, 150). \]
   #+end_export
   La expresión anterior implica:
   #+begin_export latex
   \[ 70 (150 - V)^2 \geq \num{1350000}. \]
   #+end_export
   Operando:
   #+begin_export latex
   \[
     V
     \leq 150 - \left(\frac{\num{1350000}}{70} \right)^{1/2}
     \approx \money{11.13}.
   \]
   #+end_export
   Carmen pagaría hasta \money{11.13} por el lote de 10 fotos.
