# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 5.21

Juan dispone de una renta monetaria mensual de \money{150}.
Con ella puede comprar pan, a un precio de \price[kg]{3}, y agua, a un
precio de \price[l]{0.75}.

a) Obtenga la restricción presupuestaria de Juan y represéntela
   gráficamente.

b) Juan consume actualmente $60$ litros de agua y $35$ kilos de pan al
   mes. ¿Cuál es el coste de oportunidad de consumir un litro
   adicional de agua? ¿Cuál sería el coste de oportunidad si Juan
   consumiera $50$ litros de agua y $30$ kilos de pan?

c) Una sequía prolongada provoca que el precio del agua se
   duplique. Obtenga y represente la nueva restricción presupuestaria.

d) Ante la gravedad de la situación, el Gobierno raciona el agua de
   forma que ningún consumidor puede consumir más de $20$ litros de
   agua al mes. ¿Cuál es la restricción presupuestaria en este caso?


* 5.25

Suponga que se pueden comprar 4 peras con el dinero necesario para
comprar una manzana. Si un consumidor, que gasta todo su dinero en
peras y manzanas, compra 100 peras y 20 manzanas, ¿cuántas peras
podría haber comprado como máximo? ¿Y manzanas?


* 5.23

Julia dispone de \money{6} este mes para comprar leche, cuyo precio es
\price[l]{0.75}, y galletas, que cuestan \price[kg]{3}.

a) Obtenga y represente la restricción presupuestaria.

b) Suponga ahora que todos los precios aumentan un 10%. Si el dinero
   que Julia puede usar para sus gastos también se incrementa un 10%, ¿cómo
   cambiará su restricción presupuestaria?

c) Si inicialmente Julia compraba $4$ litros de leche y $1$ kilo de
   galletas, ¿cómo cambiará su elección después de que se eleven los
   precios y la renta?


* 5.1

Un consumidor gasta su renta $M$ en los bienes $X$ e $Y$.

a) ¿Como cambiaría su recta presupuestaria si se estableciera un
   impuesto sobre el consumo y el precio de ambos bienes aumentara
   un 25%?

b) ¿Y si, en vez del impuesto al consumo, se estableciera un
   impuesto sobre la renta y $M$ se redujera un 25%?

c) ¿Qué opción preferiría el consumidor?


** Answer

a) La recta presupuestaria después del impuesto al consumo es:
   #+begin_export latex
   \[
     M = 1.25 P_X X + 1.25 P_Y Y
   \]
   #+end_export
   Los puntos de corte con los ejes de la nueva restricción
   presupuestaria serían: $X_{\max} = 0.8 M / P_X$ e $Y_{\max} = 0.8 M
   / P_Y$.
   #+xxx: fig fig-ans-probl-5_1004-budget-tax1-*.pdf

b) La recta presupuestaria después del impuesto a la renta es:
   #+begin_export latex
   \[
     0.75 M = 1.25 P_X X + 1.25 P_Y Y
   \]
   #+end_export
   #+xxx: fig fig-ans-probl-5_1004-budget-tax2-*.pdf

c) Su conjunto de oportunidades es mayor en el primer caso: preferiría
   el impuesto al consumo.


* 5.20

Nikola dispone de \money{120} para gastar en gas natural y en
electricidad. El precio de la electricidad depende del consumo: los
primeros \units[\kWh]{1000} cuestan \money{0.06} por kWh, mientras que
los kWh que excedan de \num{1000} se pagan a \price[\kWh]{0.03}. Por
otro lado, el precio del gas natural siempre es
\price[\kWh]{0.05}. Obtenga y represente gráficamente el conjunto
presupuestario de Nikola.


* 5.22

Un consumidor dispone de una renta de $100$ € a la semana y se
alimenta de arroz, que cuesta \money{1} el kilo. Obtenga y represente
la restricción presupuestaria del consumidor en las siguientes
situaciones (utilice un bien compuesto):

a) El consumidor se beneficia de una subvención de \money{0.25} por
   cada kilo de arroz que compre.

b) El consumidor sólo puede disfrutar de una subvención de
   \price[kg]{0.25} en los cinco primeros kilos de arroz que compre y
   paga el precio de mercado por los restantes kilos que adquiera.

c) El consumidor obtiene $5$ kilos de arroz gratuitamente.

d) El consumidor recibe un cheque por valor de \money{5}.


* 5.2

Un consumidor dispone de \money{20} para comprar carne y
patatas. Suele comprar en un supermercado donde la carne se vende a
\price[kg]{4} y un kilo de patatas cuesta \money{2}.

a) Obtenga y represente la restricción presupuestaria.

b) El supermercado introduce una oferta por la que los clientes que
   compren más de \units[kg]{4} de patatas recibirán gratis 2 kilos
   más. Obtenga y represente la restricción presupuestaria
   en este caso.


** Answer

a) Restricción presupuestaria: $20 = 4 C + 2 P$.
   #+xxx: fig fig-ans-probl-5_1004-budget1-*.pdf

b) Nueva restricción presupuestaria:
   #+begin_export latex
   \[
     C =
     \begin{cases}
       5 - P / 2 & \text{si $P < 4$} \\
       6 - P / 2 & \text{si $P \geq 6$}
     \end{cases}
   \]
   #+end_export
   #+xxx: fig fig-ans-probl-5_1004-budget2-*.pdf


* 5.24

Eugenio y Ana comparten piso. Cada uno de ellos tiene una renta
mensual de \money{1000} que gastan en su totalidad en alimentos y
vestido. Cuando el precio de los alimentos es \price{8} y el de los
vestidos es \price{40}, Ana compra 10 unidades de vestido y Eugenio
compra 20 unidades.

Después de una reforma impositiva, el precio de los alimentos baja
hasta \price{4} y el del vestido sube hasta \price{50}. Con la
información proporcionada, ¿es posible saber si la satisfacción de Ana
ha aumentado o disminuido? ¿Y la de Eugenio?

* 5.25

Ángeles dispone de \money{100} al mes para gastar en llamadas
telefónicas y un bien compuesto. Su compañía telefónica sólo le cobra
\money{0.02} por minuto de llamada.

a) Obtenga y represente la restricción presupuestaria de Ángeles.

b) <<ex5.25:itemb>>Ángeles recibe una oferta por la que pagando una
   cuota de \money{15} obtendría \num{1000} minutos de llamadas. Cada
   minuto adicional le costaría \money{0.04}. Obtenga y represente la
   restricción presupuestaria de Ángeles si contrata esta tarifa.

c) Represente las dos tarifas en el mismo gráfico y determine cuándo
   sería más ventajosa la tarifa del apartado [[ex5.25:itemb]].

* 5.3

A Amaia le gusta el pescado, mientras que el pollo ni le gusta ni
le disgusta. Por su parte, a Alejandro no le gusta el pescado pero
sí el pollo y sólo está dispuesto a comer algo de pescado si a
cambio recibe una porción extra de pollo. Represente las
preferencias de Amaia y de Alejandro.


** Answer

Para Amaia el pollo es un bien neutral.
#+xxx: fig fig-ans-probl-5_1004-neutral-*.pdf

Para Alejandro el pescado es un mal.
#+xxx: fig fig-ans-probl-5_1004-bad-*.pdf


* 5.4

Las preferencias de un consumidor pueden describirse con la
función de utilidad: $U(X, Y)= 5X Y^2$. La renta del consumidor es
de \money{900} y los precios son $P_X = \price{10}$ y $P_Y =
\price{5}$. Calcule y represente la elección óptima del consumidor.


** Answer

Recta presupuestaria:  $900 = 10 X + 5 Y$.

Condición de tangencia: $Y = 4 X$.

Cesta óptima: $X^* = \units{30}, Y^* = \units{120}$
#+xxx: fig fig-ans-probl-5_1004-choice-*.pdf


* 5.5

La cesta óptima de un consumidor con preferencias regulares
contiene cantidades positivas de todos los bienes. Si aumenta el
precio de un bien, ¿se reducirá la utilidad del consumidor?
Justifique su respuesta.


** Answer

Con los nuevos precios no puede comprar la cesta inicial. Tiene que
elegir una cesta que podría haber elegido con los precios iniciales
pero no lo hizo: su utilidad es menor.



* 5.6

La función de utilidad de un consumidor es $U(X, Y) = X Y$. La cesta
óptima está compuesta por 10 unidades del bien $X$ y 5 unidades del
bien $Y$. Sabiendo que el precio del bien $X$ es de \price{6}, ¿cuál
es la renta del consumidor?


** Answer

Solución interior: $\RMS = Y/X = 5 / 10$ es igual a $P_X / P_Y =
6 / P_Y$. Por tanto, $P_Y = 12$. Finalmente, $M = \money{120}$.


* 5.7

Una consumidora posee una renta de \money{40} que gasta en los bienes
$X$ e $Y$, cuyos precios son $P_X = \price{3}$ y $P_Y =
\price{2}$. Cuando ella consume $20$ unidades de $Y$ y ninguna de $X$,
la relación marginal de sustitución es igual a $2$. ¿Es esta su
elección óptima o estaría mejor comprando más unidades de $X$ y menos
de $Y$?


** Answer

Cuando compra $X=0$ e $Y=2$, $\RMS = 2 > P_X/P_Y = 1.5$.  Su utilidad
aumentaría si disminuye el consumo de $Y$ y aumenta el de $X$.



* 6.4.

Considere una economía competitiva donde todos los consumidores
tienen las mismas preferencias y consumen alguna unidad tanto del
bien $X$ como del bien $Y$. ¿Comprarán todos la misma cantidad del
bien $X$?  ¿Habrá diferencias en las valoraciones del bien $X$ por
parte de cada uno de los consumidores?


** Answer

No comprarán la misma cantidad si tienen diferentes niveles de renta.

Las valoraciones de $X$, $\RMS_i$, coincidirán: todos los consumidores
se enfrentan a los mismos precios y la cesta óptima de cada uno de
ellos cumple la condición $\RMS_i = P_x/P_Y$.


* 5.8

La función $U(N, Y) = (N+4) Y$ describe las preferencias de un
consumidor entre nueces, $N$, y un bien compuesto que recoge el
dinero gastado en todos los otros bienes, $Y$. El precio de las
nueces es $P_N = \price[kg]{8}$ y la renta del consumidor es $M =
\money{40}$.

a) Obtenga y represente la elección óptima del consumidor.

b) El Gobierno quiere fomentar el consumo de nueces y está
   estudiando diferentes alternativas:

   + Una subvención que reduce un 20% el precio de las nueces. La
     subvención sólo se puede aplicar a la compra de un kilo y
     medio de nueces por consumidor.

   + Entregar a cada consumidor un vale que puede canjearse por un
     kilo y medio de nueces.

   + Entregar a cada consumidor \money{12} en metálico.

   ¿Qué elegiría el consumidor en cada uno de estos casos?

c) ¿Qué alternativa preferiría el consumidor? Razone su respuesta.


** Answer

a) Recta presupuestaria: $40 = 8N + Y$.

   Condición de tangencia: $Y = 8N + 32$.

   Cesta óptima: $N^* = \units[kg]{0.500}, Y^* = \money{36.00}$
   #+xxx: fig fig-ans-probl-5_1004-walnut1-*.pdf

b) Subvención (la restricción se quiebra en $X = 1.5$ e $Y =
   30.4$). Cesta óptima: $N^* = \units[kg]{1.125}, Y^* =
   \money{32.80}$.
   #+xxx: fig fig-ans-probl-5_1004-walnut2-*.pdf

   Donación especie. Cesta óptima: $N^* = \units[kg]{1.500}, Y^* =
   \money{40.00}$.
   #+xxx: fig fig-ans-probl-5_1004-walnut3-*.pdf

   Donación metálico. Cesta óptima: $N^* = \units[kg]{1.250}, Y^* =
   \money{42.00}$.
   #+xxx: fig fig-ans-probl-5_1004-walnut4-*.pdf


c) La donación en metálico le permite alcanzar un mayor nivel de
   utilidad.


* 5.9

Un consumidor dispone de una renta de \money{800} para comprar los
bienes $X$ e $Y$, cuyos precios son $P_X = \price{4}$ y $P_Y =
\price{2}$. Sus preferencias pueden describirse con la función de
utilidad:
#+begin_export latex
\[
  U(X, Y) = X^{0.25} Y^{0.75}
\]
#+end_export

a) Obtenga la elección óptima del consumidor.

b) Si se aplicara un descuento de \money{2} a cada unidad de $X$
   por encima de las primeras 75 unidades, ¿cómo cambiaría la
   elección óptima?


** Answer

a) Recta presupuestaria: $800 = 4 X + 2 Y$.

   Condición de tangencia: $Y = 6 X$.

   Cesta óptima: $X^* = \units{50}, Y^* = \units{300}$.
   #+xxx: fig fig-ans-probl-5_1004-discount1-*.pdf


b) La restricción presupuestaria tiene dos tramos:
   #+begin_export latex
   \[
     Y =
     \begin{cases}
       400 - 2 X & \text{si $X < 75$} \\
       325 - X & \text{si $X \geq 75$}
     \end{cases}
   \]
   #+end_export

   Obtenemos la solución en cada uno de los tramos:

   #+ATTR_LATEX: :booktabs t :center t :align @{}lrr@{}
   |----------+-----------------------+-----------------------------|
   |          | $X < 75$              | $X > 75$                    |
   |----------+-----------------------+-----------------------------|
   | RP       | $800 = 4 X + 2 Y$     | $650 = 2X + 2Y$             |
   | CT       | $Y = 6 X$             | $Y = 3 X$                   |
   | Óptimo   | $X^* = 50, Y^* = 300$ | $X^* = 81.25, Y^* = 243.75$ |
   | Utilidad | $191.68$              | $185.21$                    |
   |----------+-----------------------+-----------------------------|

   Las dos soluciones cumplen las condiciones de óptimo interior,
   pero la utilidad que obtiene el consumidor es mayor eligiendo
   $X^* = 50$ e $Y^* = 300$: la elección no cambiaría.


* 5.10

Las preferencias de un consumidor vienen dadas por la función de
utilidad: $U(X, Y) = X (Y + 100)$. El precio del bien $X$ es
\price{1} y el del bien $Y$ es \price{4}. El consumidor dispone de
una renta monetaria de \money{250}.

a) Determine la cesta óptima de consumo.

b) Si se racionara el bien $X$ de forma que no se permitiera a
   nadie comprar más de 100 unidades de $X$, ¿cuál sería la
   elección óptima?  Represente gráficamente.


** Answer

a) Recta presupuestaria: $250 = X + 4 Y$.

   Relación marginal de sustitución: $\RMS = (Y + 100) / X$.

   Solución de esquina: $X^* = \units{250}, Y^* = \units{0}$
   #+xxx: fig fig-ans-probl-5_1004-corner1-*.pdf

b) Elección óptima: $X^* = \units{100}, Y^* = \units{37.5}$.
   #+xxx: fig fig-ans-probl-5_1004-corner2-*.pdf


* 5.11

La función de utilidad de un individuo respecto de los bienes $X$ e
$Y$ viene dada por $U(X,Y) = 3X + 3Y$. Los precios de mercado son
$P_X = \price{2}$ y $P_Y = \price{5}$ y la renta monetaria del
consumidor es $M = \money{100}$.

a) ¿Es $(X,Y) = (10, 40)$ la cesta óptima? ¿Por qué?

b) ¿Cuál es la elección óptima del consumidor?

c) ¿Cómo cambiaría la elección del consumidor si $P_X =
   \price{10}$?


** Answer

a) No, no tiene suficiente renta para comprarla.

b) $\RMS = 1 > P_X / P_Y = 0.4$. Solución de esquina: $X^* = 50; Y^* =
   0$.

c) $\RMS = 1 < P_X / P_Y = 2$. Solución de esquina: $X^* = 0; Y^* =
   20$.


* 5.12

A Rocío le gusta tomar leche con cereales. Siempre los combina en
la misma proporción: añade exactamente \units[g]{20} de cereales
por cada \units[ml]{250} de leche y desecha cualquier cantidad
sobrante de leche o cereales.

a) Represente las preferencias de Rocío con respecto a la leche y
   los cereales.

b) Si Rocío gasta \money{6} al mes en leche y cereales, el precio
   de la leche es de \price[l]{0.80} y el de los cereales es de
   \price[kg]{2}, ¿cuál será su elección óptima?


** Answer

a) Preferencias sobre $L$, litros de leche, y $C$, kg de cereales:
   #+begin_export latex
   \[
     U = \min\{L/0.250, C/0.020\}
   \]
   #+end_export
   Por tanto:
   #+begin_export latex
   \[
     U = \min\{4L, 50C\}
   \]
   #+end_export
   #+xxx: fig fig-ans-probl-5_1004-compl1-*.pdf

b) Restricción presupuestaria: $6 = 0.8 L + 2 C$.
   Proporciones exactas: $4L = 50C$.
   Óptimo: $L^* = \units[l]{6.250}, C^* = \units[kg]{0.500}$.
   #+xxx: fig fig-ans-probl-5_1004-compl2-*.pdf
