# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 1.1

En una economía se producen dos bienes: vehículos y alimentos, y sólo
se utiliza trabajo como único factor de producción. Se dispone de un
máximo de \num{100000} horas de trabajo al mes. La siguiente tabla
muestra las cantidades que pueden producirse dependiendo de las horas
de trabajo que se dediquen a cada actividad:
#+latex: \vspace*{2ex}

#+ATTR_LATEX: :options {0.5\linewidth}
#+xxx: col
#+ATTR_LATEX: :booktabs t :center t :align @{}rR{2.5cm}@{}
|---------------+-----------|
|       Trabajo | Vehículos |
| (miles horas) |   (miles) |
|---------------+-----------|
|             0 |         0 |
|            10 |        50 |
|            20 |        95 |
|            30 |       135 |
|            40 |       170 |
|            50 |       200 |
|            60 |       225 |
|            70 |       245 |
|            80 |       260 |
|            90 |       270 |
|           100 |       275 |
|---------------+-----------|

#+ATTR_LATEX: :options {0.5\linewidth}
#+xxx: col
#+ATTR_LATEX: :booktabs t :center t :align @{}rR{2.5cm}@{}
|---------------+------------|
|       Trabajo |  Alimentos |
| (miles horas) | (miles kg) |
|---------------+------------|
|             0 |          0 |
|            10 |         80 |
|            20 |        150 |
|            30 |        200 |
|            40 |        240 |
|            50 |        270 |
|            60 |        290 |
|            70 |        305 |
|            80 |        315 |
|            90 |        320 |
|           100 |        322 |
|---------------+------------|
#+xxx: endcol

a) <<ex1.1:item-a>>Obtenga y represente gráficamente la frontera de
   posibilidades de producción, FPP.

b) Si se producen \units[kg]{150000} de alimentos, ¿es posible
   producir \num{300000} vehículos? Si su respuesta es negativa,
   indique cuántos vehículos podrían fabricarse como máximo.

c) ¿Qué efecto tendría sobre la FPP una mejora organizativa en la
   producción de vehículos? Obtenga y represente la FPP si la mejora
   incrementa en un 20% la producción por hora de vehículos. Compare
   los resultados con los obtenidos en el apartado [[ex1.1:item-a]]. ¿Es
   posible producir ahora \units[kg]{150000} de alimentos y
   \num{300000} vehículos? ¿Es eficiente?

d) ¿Qué consecuencias tendría sobre la FPP la reducción a la mitad de
   las horas de trabajo como consecuencia de un conflicto bélico?
   Represente gráficamente la FPP si sólo se pueden usar \num{50000}
   horas de trabajo y compare los resultados con los obtenidos en el
   apartado [[ex1.1:item-a]].


** Answer

Representamos con $A$ y $V$ las producciones de alimentos, en miles de
kilos, y de vehículos, en miles, respectivamente; $L_A$ y $L_V$
representan el trabajo, en miles de horas, empleado en la producción
de alimentos y de vehículos, respectivamente. La siguiente tabla muestra las combinaciones de producción que se obtienen cuando todas las horas de trabajo se dedican a alguna de las dos actividades productivas. La última columna se utiliza en el apartado c)

#+ATTR_LATEX: :booktabs t :center t :align @{}rR{1cm}p{0.6cm}*{2}{R{1cm}}p{0.3cm}R{1cm}@{}
|-------+-------+-+-----+-----+-+-----|
| $L_A$ | $L_V$ | | $A$ | $V$ | | $V'$ |
|-------+-------+-+-----+-----+-+-----|
|     0 |   100 | |   0 | 275 | | 330 |
|    10 |    90 | |  80 | 270 | | 324 |
|    20 |    80 | | 150 | 260 | | 312 |
|    30 |    70 | | 200 | 245 | | 294 |
|    40 |    60 | | 240 | 225 | | 270 |
|    50 |    50 | | 270 | 200 | | 240 |
|    60 |    40 | | 290 | 170 | | 204 |
|    70 |    30 | | 305 | 135 | | 162 |
|    80 |    20 | | 315 |  95 | | 114 |
|    90 |    10 | | 320 |  50 | |  60 |
|   100 |     0 | | 322 |   0 | |   0 |
|-------+-------+-+-----+-----+-+-----|

a) Representamos la FPP con los valores contenidos en las columnas $A$
   y $V$ de la tabla:

   #+xxx: fig fig-ans-probl-1_1004-ppf-shift-a-*.pdf

b) No: es una combinación inalcanzable.

c) Una mejora organizativa hace que, usando los mismos recursos, la
   producción de vehículos aumente un 20%: $V' = 1.2 \cdot V$. Usamos
   las columnas $A$ y $V'$ de la tabla anterior para representar la
   nueva FPP.

   #+xxx: fig fig-ans-probl-1_1004-ppf-shift-c-*.pdf

   La frontera se desplaza hacia arriba pero la producción máxima de
   alimentos no cambia.

   Ahora es factible producir \units[kg]{150000} de alimentos y
   \num{300000} vehículos, pero sería ineficiente: produciendo esa
   cantidad de alimentos se podrían fabricar hasta \num{312000}
   vehículos.

d) Calculamos las combinaciones de producción eficientes cuando sólo
   se dispone de \num{50000} horas de trabajo:
   #+ATTR_LATEX: :booktabs t :center t :align @{}rR{1.25cm}p{1.25cm}*{2}{R{1.25cm}}@{}
   |-------+-------+---+-----+-----|
   | $L_A$ | $L_V$ |   | $A$ | $V$ |
   |-------+-------+---+-----+-----|
   |     0 |    50 |   |   0 | 200 |
   |    10 |    40 |   |  80 | 170 |
   |    20 |    30 |   | 150 | 135 |
   |    30 |    20 |   | 200 |  95 |
   |    40 |    10 |   | 240 |  50 |
   |    50 |     0 |   | 270 |   0 |
   |-------+-------+---+-----+-----|

   Cundo disminuyen los recursos productivos del país, la frontera se
   desplaza hacia abajo y hacia la izquierda.

   #+xxx: fig fig-ans-probl-1_1004-ppf-shift-d-*.pdf



* 1.2

La tabla adjunta presenta diferentes combinaciones eficientes para una
economía en la que sólo se producen dos bienes: cañones y mantequilla.

#+ATTR_LATEX: :booktabs t :center t :align @{}p{1cm}*{2}{R{2cm}}@{}
|-----+-------------+------------|
|     | Mantequilla |    Cañones |
|     | (Toneladas) | (Unidades) |
|-----+-------------+------------|
| *A* |          20 |          0 |
| *B* |          18 |          1 |
| *C* |          15 |          2 |
| *D* |          11 |          3 |
| *E* |           6 |          4 |
| *F* |           0 |          5 |
|-----+-------------+------------|

a) Represente la frontera de posibilidades de producción, FPP.

c) Construya una tabla que refleje el coste de oportunidad de producir
   cada cañón.

d) ¿A cuántas toneladas de mantequilla se debe renunciar para producir
   el primer cañón? ¿Y el segundo?

e) ¿Qué relación existe entre la forma de la FPP y el coste de
   oportunidad?


** Answer

a) Frontera de posibilidades de producción:
   #+xxx: fig fig-ans-probl-1_1004-ppf-oc1-*.pdf

b) La última columna de la tabla muestra el coste de oportunidad de
   cada cañón medido en toneladas de mantequilla:
   #+begin_export latex
   \[
     \text{Coste de oportunidad} = \left|
       \frac{\Delta\;\text{Mantequilla}}{\Delta\;\text{Cañones}}
     \right|
   \]
   #+end_export
   #+ATTR_LATEX: :booktabs t :center t :align @{}p{0.75cm}*{2}{r}r@{}
   |-----+---------+-------------+-------------|
   |     |         |             | Coste de    |
   |     | Cañones | Mantequilla | oportunidad |
   |-----+---------+-------------+-------------|
   | *A* |       0 |          20 |         --- |
   | *B* |       1 |          18 |           2 |
   | *C* |       2 |          15 |           3 |
   | *D* |       3 |          11 |           4 |
   | *E* |       4 |           6 |           5 |
   | *F* |       5 |           0 |           6 |
   |-----+---------+-------------+-------------|

c) El primer cañón cuesta $2$ toneladas de mantequilla; el segundo
   cuesta 3 toneladas.

d) El coste de oportunidad es creciente, por lo que la frontera de
   posibilidades de producción es cóncava.


* 1.3

La frontera de posibilidades de producción, FPP, de un país que sólo
produce dos bienes, $X$ e $Y$ puede expresarse como:
#+begin_export latex
\[
  Y = \num{1000} - 0.1 X
\]
#+end_export

a) Represente gráficamente la FPP.

b) Si la economía está utilizando eficientemente todos los factores de
   producción y se producen \num{1000} unidades del bien $X$, ¿cuál es
   el coste de oportunidad de producir una unidad adicional del bien
   $X$?

c) Si en vez de \num{1000} se produjeran \num{5000} unidades del bien
   $X$, ¿cómo cambiaría la respuesta al apartado anterior?

d) ¿Que relación existe entre el comportamiento del coste de
   oportunidad y la forma de la FPP?


** Answer


a) Frontera de posibilidades de producción:

   #+xxx: fig fig-ans-probl-1_1004-ppf-lin-*.pdf

b) El coste de oportunidad puede calcularse como el valor absoluto de
   la pendiente de la frontera de posibilidades de producción:
   #+begin_export latex
   \[
     \text{Coste de oportunidad} = \left|
       \frac{\diff Y}{\diff X}
     \right| = 0.1
   \]
   #+end_export
   El coste de oportunidad de una unidad adicional de $X$ es igual a
   $0.1$ unidades del bien $Y$.

c) El coste de oportunidad es $0.1$ unidades del bien $Y$ por cada
   unidad adicional de $X$, independientemente del valor que tome $X$.

d) La frontera es una línea recta, por lo que el coste de oportunidad
   es constante.



* 1.4

El siguiente gráfico representa la frontera de posibilidades de
producción de una economía donde sólo se producen cocos y pescado:

#+xxx: fig fig-probl-1_1004-ppf-*.pdf

Ordene las opciones de producción $A$, $B$, $C$ y $D$ de mayor a
menor coste de oportunidad de producir pescado.


** Answer

Excluimos $C$ ya que el coste de oportunidad no está definido para
combinaciones de producción inaccesibles. En combinaciones
ineficientes, como $B$, el coste de oportunidad es $0$. En
combinaciones eficientes, como $A$ y $B$, el coste de oportunidad es
mayor cuanto más pronunciada es la pendiente de la FPP.

Ordenando las opciones factibles de mayor a menor coste de
oportunidad: $D$, $A$ y $B$.



* 1.5

Considere una economía donde sólo se producen dos bienes: $X$ e $Y$.

#+xxx: fig fig-probl-1_1004-ppf-multi-*.pdf

Relacione cada uno de los gráficos anteriores con las siguientes
afirmaciones. Razone sus respuestas.

a) El incremento de la natalidad en las décadas previas hace que el
   número personas en edad de trabajar aumente
   considerablemente.

b) Una gran parte de los trabajadores que estaban desempleados han
   encontrado un empleo.

c) Una gran parte de los trabajadores emigra al extranjero buscando un
   mejor empleo.

d) Una reforma administrativa hace mucho más difícil y costosa la
   contratación de trabajadores.


** Answer

a) *(B)*: aumenta el número de trabajadores en el país y la frontera
   se desplaza hacia afuera.

b) *(C)*: hay menos recursos productivos sin emplear y la economía se
   aproxima a la frontera.

c) *(A)*: disminuye el número de trabajadores en el país y la
   frontera se desplaza hacia adentro.

d) *(D)*: es más difícil emplear eficientemente los recursos
   existentes y la economía se aleja de la frontera.
