# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 8.1.

Complete la siguiente tabla que describe la producción a corto
plazo de una empresa.

#+ATTR_LATEX: :booktabs t :center t :align @{}c*{3}{r}@{}
|--------------+------------+----------+----------|
|              | Producción | Producto | Producto |
| Trabajadores | total      | marginal | medio    |
|--------------+------------+----------+----------|
| $0$          | $0$        | ---      | ---      |
| $1$          |            | $120$    |          |
| $2$          | $210$      |          |          |
| $3$          |            |          | $95$     |
| $4$          |            | $31$     |          |
| $5$          |            |          | $64$     |
| $6$          | $306$      |          |          |
|--------------+------------+----------+----------|

¿Se cumple la ley de rendimientos marginales decrecientes?  ¿Son
técnicamente eficientes todos los niveles de contratación de
trabajadores mostrados en la tabla? ¿Por qué?


** Answer

Se han utilizado las relaciones:
#+begin_export latex
\begin{equation*}
  \PMeL = \frac{Q}{L} \qtext{y}\quad
  \PMgL \approx \iratio{Q}{L}
\end{equation*}
#+end_export
para completar la tabla.
#+ATTR_LATEX: :booktabs t :center t :align @{}c*{3}{r}@{}
|--------------+------------+----------+----------|
|              | Producción | Producto | Producto |
| Trabajadores | total      | marginal | medio    |
|--------------+------------+----------+----------|
| $0$          | $0$        | ---      | ---      |
| $1$          | $120$      | $120$    | $120$    |
| $2$          | $210$      | $90$     | $105$    |
| $3$          | $285$      | $75$     | $95$     |
| $4$          | $316$      | $31$     | $79$     |
| $5$          | $320$      | $4$      | $64$     |
| $6$          | $306$      | $-14$    | $51$     |
|--------------+------------+----------+----------|

Se cumple la ley de rendimientos decrecientes del factor trabajo: el
producto marginal del trabajo disminuye cuantos más trabajadores se
contratan.

La situación correspondiente a la última fila de la tabla, contratar 6
trabajadores, no es técnicamente eficiente: el producto marginal es
negativo y se podría producir más contratando a menos trabajadores.



* 8.2.

Dada la función de producción $Q = L^2 K - 0.01 L^3$ y sabiendo que
el capital es fijo, $\Kbar = 6$, determine:

a) La curva de producto total.

b) Las curvas de producto medio y marginal del trabajo.

c) Los niveles del factor trabajo que hacen máximo el producto
   marginal, el producto medio y el producto total. Represente
   gráficamente los resultados obtenidos.


** Answer

a) Curva de producto total cuando $\Kbar = 6$:
   #+begin_export latex
   \[
     Q = 6 L^2 - 0.01 L^3
   \]
   #+end_export

b) Producto medio:
   #+begin_export latex
   \[
     \PMeL = \frac{Q}{L} = 6 L - 0.01 L^2.
   \]
   #+end_export

   Producto marginal:
   #+begin_export latex
   \[
     \PMgL = \frac{\diff Q}{\diff L} = 12 L - 0.03 L^2.
   \]
   #+end_export

c) /Maximización del \PMgL/: La derivada del producto marginal es:
   #+begin_export latex
   \[
     \frac{\diff \PMgL}{\diff L} \PMgL = 12 - 0.06 L.
   \]
   #+end_export
   Igualando a 0 la expresión anterior y resolviendo $L$, obtenemos
   $L_A = 200$.

   /Maximización del \PMeL/: La derivada del producto medio es:
   #+begin_export latex
   \[
     \frac{\diff \PMeL}{\diff L} = 6 - 0.02 L.
   \]
   #+end_export
   Igualando a 0 la expresión anterior y resolviendo $L$, obtenemos
   $L_B = 200$.

   /Maximización de la producción/: La derivada del producto total es
   el producto marginal.  Resolviendo $L$ en la ecuación $\PMgL = 0$,
   obtenemos $L_C = 400$.

   #+ATTR_LATEX: :options [b]{0.55\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-pmgl-*.pdf
   #+ATTR_LATEX: :options [b]{0.45\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-fprod-*.pdf
   #+xxx: endcol



* 8.3

Con las siguientes funciones de producción:

#+ATTR_LATEX: :options [leftmargin=4pc, labelwidth=\widthof{XX.}, align=left, label=\Roman*. ]
A. $Q  = 2 K + 3 L$

B. $Q  = K^{1/2} L^{1/2}$

C. $Q  = K L^2$

y sabiendo que el capital es un factor fijo, $\Kbar = 4$:

a) Represente las curvas de producto total en cada caso.

b) ¿Cumple alguna de esas funciones de producción la ley de
   rendimientos decrecientes del factor trabajo?


** Answer

a)
   #+ATTR_LATEX: :options [t]{0.33\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-total-a-*.pdf

   #+begin_export latex
     \centering%
     \mbox{I. $Q = 8 + 3 L$}
   #+end_export
   #+ATTR_LATEX: :options [t]{0.34\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-total-b-*.pdf

   #+begin_export latex
     \centering%
     \mbox{II. $Q = 2 L^{1/2}$}
   #+end_export
   #+ATTR_LATEX: :options [t]{0.33\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-total-c-*.pdf

   #+begin_export latex
     \centering%
     \mbox{III. $Q = 4 L^2$}
   #+end_export
   #+xxx: endcol

b)
   #+ATTR_LATEX: :options [t]{0.33\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-marginal-a-*.pdf

   #+begin_export latex
     \centering%
     \mbox{I. $\PMgL = 3$}
   #+end_export
   #+ATTR_LATEX: :options [t]{0.34\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-marginal-b-*.pdf

   #+begin_export latex
     \centering%
     \mbox{II. $\PMgL = L^{-1/2}$}
   #+end_export
   #+ATTR_LATEX: :options [t]{0.33\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-8_1004-marginal-c-*.pdf

   #+begin_export latex
     \centering%
     \mbox{III. $\PMgL = 8 L$}
   #+end_export
   #+xxx: endcol
   #+latex: \vspace*{1.5ex}

   Sólo es decreciente el $\PMgL$ de la segunda función. Por tanto,
   sólo la función de producto total $Q = 2 L^{1/2}$ cumple la ley de
   rendimientos decrecientes del factor trabajo.



* 8.4

Dibuje en cada uno de los siguientes gráficos donde se situaría la
curva de producto marginal del trabajo. Justifique su respuesta.

#+xxx: fig fig-probl-8_1004-pmel-*.pdf


** Answer

Por hacer.


* 8.5.

Si el producto marginal del trabajo es decreciente en el corto plazo,
¿el producto medio debe ser también decreciente?


** Answer

No: el producto medio decrece cuando el producto marginal es inferior
al medio, independientemente de que el producto marginal sea creciente
o no.



* 8.6.

La producción por trabajador en una empresa es de 20 sillas al día. El
propietario de la empresa ha calculado que un trabajador adicional
elevaría la producción diaria en 10 sillas. ¿Qué ocurrirá con el
producto medio si la empresa contrata otro trabajador?


** Answer

No: el producto marginal es menor que el medio, por lo que el producto
medio es decreciente.



* 8.7.

El siguiente gráfico muestra algunas isocuantas de la función de
producción de una empresa:

#+xxx: fig fig-probl-8_1004-const-returns-*.pdf

a) Si la empresa produce eficientemente 250 unidades y contrata 5
   trabajadores, ¿cuántas unidades de capital está utilizando? ¿Y si
   produce 125 unidades con 4 trabajadores?

b) Si la empresa está empleando 8 trabajadores y 6 unidades de
   capital, ¿es posible que la producción sea de 400 unidades?
   ¿Sería posible producir 200 unidades? ¿Qué ocurriría en este
   caso?

c) ¿Qué tipo de rendimientos de escala presenta la función de
   producción?


** Answer

a) En la isocuanta $Q = 250$, $K = 5$ cuando $L = 5$.

   En la isocuanta $Q = 125$, $K = 2$ cuando $L = 4$.

b) La producción no puede ser de $400$ unidades: la combinación
   $L = 8$ y $K = 6$ está debajo de la isocuanta $Q = 375$.

   Es posible pero no eficiente producir $200$: se pueden
   producir $250$ unidades con $L=8$ y $K < 6$.

c) Rendimientos constantes de escala: por ejemplo, comparar producción
   en $(5, 5)$ y $(10, 10)$.



* 8.8.

¿Es correcta la siguiente afirmación? Justifique su respuesta: "Una
empresa cuya función de producción $Q = F(K, L)$ presenta rendimientos
constantes de escala verá duplicada su producción cuando duplique el
uso del factor capital."


** Answer

  Es incorrecta. Se duplicará la producción cuando se duplique el
  uso de /todos/ los factores de producción.


* 8.9.

Una fábrica utiliza trabajo y capital para producir zapatos. Después
de aumentar el número de trabajadores en un 50% la producción crece en
un 60%. ¿Qué tipo de rendimientos de escala presenta la función de
producción de la empresa?


** Answer

  No: si sólo aumenta el trabajo no es posible deducir nada sobre
  los rendimientos de escala.


* 8.10.

El siguiente gráfico muestra algunas isocuantas de la función de
producción de una empresa:

#+xxx: fig fig-probl-8_1004-incr-returns-*.pdf

a) ¿Qué tipo de rendimientos de escala exhibe la función de producción
   de la empresa?

b) Si $\Kbar = 5$, ¿se cumple la ley de rendimientos marginales
   decrecientes?


** Answer

a) Rendimientos crecientes de escala.


b) No: los rendimientos del factor trabajo son constantes.

   #+ATTR_LATEX: :booktabs t :center t :align @{}*{4}{r}@{}
   |---------+------+-------+---------------------|
   | $\Kbar$ | $L$  | $Q$   | $\incr Q / \incr L$ |
   |---------+------+-------+---------------------|
   | $5$     | $2$  | $100$ | ---                 |
   | $5$     | $5$  | $250$ | $50$                |
   | $5$     | $10$ | $500$ | $50$                |
   | $5$     | $15$ | $750$ | $50$                |
   |---------+------+-------+---------------------|


* 8.11.

Considere las siguientes funciones de producción:

#+ATTR_LATEX: :options [leftmargin=4pc, labelwidth=\widthof{XX.}, align=left, label=\Roman*. ]
A. $Q  = K^{3/4} L^{1/4}$

B. $Q  = K^{3/2} L^{1/2}$

C. $Q  = 2K + 4L$

D. $Q  = (K + L)^{1/2}$

E. $Q  = (K + L)^{2}$

Responda a las siguientes preguntas para cada una de las funciones
de producción:

a) Obtenga la tasa de sustitución entre los factores de producción.

b) <<ex8.11:item-b>>¿Qué tipo de rendimientos de escala presenta la función de
   producción?

c) <<ex8.11:item-c>>Compruebe si se cumple la ley de rendimientos marginales
   decrecientes cuando $\Kbar=16 \text{\ unidades}$.

d) Comparando los resultados de [[ex8.11:item-b]] y [[ex8.11:item-c]], ¿hay
   algún tipo de relación entre los rendimientos de escala y los
   rendimientos del factor trabajo?


** Answer

a)
   #+latex: \begin{adjustbox}{valign=t}
   #+ATTR_LATEX: :booktabs t :center nil :align @{}lp{2.5cm}l@{}
   |---------+-------------------+------------------------|
   | Función | $F(s L, s K)$     | Rendimientos de escala |
   |---------+-------------------+------------------------|
   | I       | $s F(L, K)$       | Constantes             |
   | II      | $s^2 F(K, L)$     | Crecientes             |
   | III     | $s F(L, K)$       | Constantes             |
   | IV      | $s^{1/2} F(L, K)$ | Decrecientes           |
   |---------+-------------------+------------------------|
   #+latex: \end{adjustbox}

b)
   #+latex: \begin{adjustbox}{valign=t}
   #+ATTR_LATEX: :booktabs t :center nil :align @{}ll@{}
   |---------+------------|
   | Función | $\RMST$    |
   |---------+------------|
   | I       | $(1/3)K/L$ |
   | II      | $3K/L$     |
   | III     | $2$        |
   | IV      | $1$        |
   |---------+------------|
   #+latex: \end{adjustbox}

c)
   #+latex: \begin{adjustbox}{valign=t}
   #+ATTR_LATEX: :booktabs t :center nil :align @{}lp{3.25cm}l@{}
   |---------+-------------------------+-------------------------|
   | Función | $\diff \PMgL / \diff L$ | Rdtos. del factor       |
   |---------+-------------------------+-------------------------|
   | I       | $-(6/4)L^{-7/4}$        | Decrecientes            |
   | II      | $3 L^{-1/2}$            | Crecientes              |
   | III     | $0$                     | Constantes              |
   | IV      | $-(1/4)(L + 16)^{-3/2}$ | Decrecientes            |
   |---------+-------------------------+-------------------------|
   #+latex: \end{adjustbox}
