# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

* 2.1

"The price of gasoline considerably increased during the years from
2003 to 2006, and yet the consumption of gasoline grew."  Does this
claim contradict the law of demand?


* 2.2

Consider a competitive market where \num{1000} identical buyers
participate, each one with demand curve:
#+begin_export latex
\[
  Q^d_i(P) = 5 - P, \qquad i = 1, ..., \num{1000}.
\]
#+end_export
There are also \num{625} identical firms, each one with supply curve:
#+begin_export latex
\[
  Q^o_j(P) = 2.4 P , \qquad j = 1, ..., \num{625}.
\]
#+end_export

a) Find and plot the market equilibrium.

b) What would happen if the price were \price{4}? And if the price
   were \price{1}?


* 2.3

There are three buyers in a market whose demand curves are:
#+begin_export latex
\begin{gather*}
  \text{Buyer 1:\ } Q^d_1(P) = \num{1000} - 10 P \\
  \text{Buyer 2:\ } Q^d_2(P) = 600 - 2 P \\
  \text{Buyer 3:\ } Q^d_3(P) = 750 - 5 P
\end{gather*}
#+end_export
Determine the market demand curve.


* 2.4

The electric car market of a country is competitive, and the demand
and supply curves are:
#+begin_export latex
\begin{gather*}
  Q^{d} = \num{10000} - P/6 \\
  Q^{s} = \num{-6000} + P/2
\end{gather*}
#+end_export

a) Determine the equilibrium price and quantity.

b) Find and plot the new equilibrium if demand increases by 20% (the
   quantity demanded is 20% greater at each price) and the supply
   curve becomes:
   #+begin_export latex
   \[
     Q^s = \num{-2700} + P/2
   \]
   #+end_export


* 2.5

The demand and supply curves of the market for good $X$ are:
#+begin_export latex
\begin{gather*}
  X^d = \num{85000} - 20 P_X \\
  X^s = \num{15000} + 15 P_X
\end{gather*}
#+end_export

a) Determine the equilibrium price and quantity.

b) Plot the effects on the market equilibrium of an increase in the
   price of a substituitive good. Is it possible to unequivocally
   predict how the equilibrium price of good $X$ will change? And the
   equilibrium quantity?

c) Starting from the initial equilibrium, consider now the effects of
   an increase in the consumers' income. Is it possible to
   unambiguously predict how the equilibrium price and quantity will
   change?


* 2.6

A country is facing an increase in drug use. Experts have put forward
two alternative explanations:

- The decreasing police budget has led to an increase in drugs on the
  streets.

- Cutbacks in education efforts have decreased awareness of the
  dangers of drug use.

Use demand and supply diagrams to analyze each of these hypotheses. Is
it possible to discern between the two explanations by observing what
happened to the price and the consumption of drugs?


* 2.7

The market for an inferior good is in equilibrium. If production costs
and consumer income increase simultaneously, will both the price and
the quantity decrease in the new equilibrium?


* 2.8

Los precios de las habitaciones de hotel en las grandes ciudades
suelen depender del día de la semana en que se alquilan. En una semana
típica, los precios de las habitaciones son mucho más bajos los fines
de semana que los días laborables. Utilice diagramas de oferta y
demanda para explicar este comportamiento.


* 2.9

Una fuerte sequía ha dañado considerablemente la cosecha de café en
los principales países productores.

a) ¿Qué consecuencias tendrá la sequía sobre el equilibrio en el
   mercado mundial de café? Razone y represente gráficamente.

b) ¿Cuáles serán las consecuencias de la mala cosecha de café sobre el
   equilibrio en el mercado mundial de té? Razone y represente
   gráficamente.


* 2.10

El mercado de patinetes eléctricos de un país es competitivo y se
encuentra en equilibrio. Razone y represente gráficamente cómo
afectarían las siguientes situaciones al equilibrio de mercado.

a) Baja el precio de las baterías que los fabricantes montan en los
   patinetes.

b) Un informe alerta de problemas de seguridad graves y cada vez más
   frecuentes para los usuarios de patinetes eléctricos.

c) El Gobierno aprueba leyes destinadas a reducir la contaminación y
   las emisiones de $\text{CO}_2$ en las ciudades y que limitan
   considerablemente la circulación de coches en las ciudades.

d) Una nueva regulación del mercado de trabajo eleva los costes
   laborales de los fabricantes de patinetes.
