# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 2.1

Hay tres compradores en un mercado cuyas curvas de demanda son:

#+ATTR_LATEX: :center t :align lc
| Comprador 1: | $Q^d_1(P) = 1000 - 10 P$ |
| Comprador 2: | $Q^d_2(P) = 600 - 2 P$   |
| Comprador 3: | $Q^d_3(P) = 750 - 5 P$   |

Determine la curva de demanda de mercado.

** Answer

- Si $P \leq 100$ participan los 3 compradores:
  #+begin_export latex
  \[
    Q^d(P) = Q^d_1(P) + Q^d_2(P) + Q^d_3(P) = 2350 - 17 P
  \]
  #+end_export

- Si $100 < P \leq 150$ compran 2 y 3:
  #+begin_export latex
  \[
    Q^d(P) = Q^d_2(P) + Q^d_3(P) = 1350 - 7 P
  \]
  #+end_export

- Si $150 < P \leq 300$ sólo compra 2:
  #+begin_export latex
  \[
    Q^d(P) = Q^d_2(P) = 600 - 2 P
  \]
  #+end_export

#+attr_latex: :options {0.40\linewidth}
#+xxx: col
#+xxx: fig fig-probl-2_1004-market-demand-*.pdf

#+attr_latex: :options [b]{0.60\linewidth}
#+xxx: col
#+begin_export latex
\[
  Q^d(P) =
  \begin{cases}
    600 - 2 P   & \text{si $150 < P \leq 300$} \\
    1350 - 7 P  & \text{si $100 < P \leq 150$} \\
    2350 - 17 P & \text{si $P \leq 100$} \\
  \end{cases}
\]
#+end_export


* 2.2

Considere un mercado competitivo donde participan \num{1000}
compradores idénticos, cada uno de ellos con curva de demanda:
#+begin_export latex
\[
  Q^d_i(P) = 5 - P, \qquad i = 1, ..., \num{1000}.
\]
#+end_export
En el mercado hay también \num{625} empresas idénticas con curva de
oferta:
#+begin_export latex
\[
  Q^o_j(P) = 2.4 P , \qquad j = 1, ..., \num{625}.
\]
#+end_export

a) Halle y represente el equilibrio de mercado.

b) ¿Qué ocurriría si el precio fuera \price{4}? ¿Y si fuera
   \price{1}?

** Answer

a)
   #+attr_latex: :options {0.4\linewidth}
   #+xxx: col
   #+xxx: fig fig-probl-2_1004-market-eq-*.pdf

   #+attr_latex: :options {0.6\linewidth}
   #+xxx: col
   Demanda y oferta de mercado:
   #+begin_export latex
   \begin{gather*}
     Q^d(P) = 5000 - 1000 P \\
     Q^o(P) = 1500 P
   \end{gather*}
   #+end_export


b) Si el precio de mercado es $P = \price{4}$ se produce un exceso de
   oferta de \units{5000}.

   Si el precio de mercado es $P = \price{1}$ se produce un exceso de
   demanda de \units{2500}.


* 2.3

"El precio de la gasolina aumentó considerablemente durante los
años que van desde 2003 hasta 2006 y, sin embargo, el consumo de
gasolina creció." ¿Contradice esta afirmación la ley de la demanda?

** Answer

No: la ley de la demanda sólo es válida cuando lo único que cambia es
el precio. A lo largo del periodo 2003--2006 cambiaron también otros
determinantes de la demanda de gasolina.


* 2.4

Considere un mercado competitivo de manzanas y trace un diagrama de
oferta y demanda que muestre los efectos sobre el equilibrio de una
enfermedad de los manzanos que perjudique a la cosecha. ¿Podrían
aumentar los ingresos de los agricultores en este caso?  ¿Qué
condiciones se tendrían que cumplir?

** Answer

#+attr_latex: :options {0.5\linewidth}
#+xxx: col
#+xxx: fig fig-probl-2_1004-apples-*.pdf

#+attr_latex: :options {0.5\linewidth}
#+xxx: col
La oferta de manzanas se reduce. Se venden menos manzanas a un
precio superior.

Los ingresos de los productores solo crecerán si el mercado se
encuentra en un tramo inelástico de la curva de demanda.



* 2.5

Un país se enfrenta a un aumento del consumo de drogas. Los
expertos han propuesto dos explicaciones alternativas:

- El presupuesto policial cada vez más reducido ha incrementado la
  presencia de drogas en la calle.

- Los recortes en programas educativos han reducido la consciencia
  acerca de los peligros de las drogas.

Utilice diagramas de oferta y demanda para analizar cada una de
esas hipótesis. ¿Es posible discriminar entre esas dos
explicaciones observando qué ha ocurrido con el precio y el
consumo de drogas?

** Answer

#+attr_latex: :options {0.5\linewidth}
#+xxx: col
  #+latex: \begin{center}
  #+latex: \begin{minipage}{0.85\linewidth}
    Menor presupuesto policial.
  #+latex: \end{minipage}
  #+latex: \end{center}

  #+xxx: fig fig-probl-2_1004-drugs1-*.pdf

#+attr_latex: :options {0.5\linewidth}
#+xxx: col
  #+latex: \begin{center}
  #+latex: \begin{minipage}{0.85\linewidth}
    Recortes en educación.
  #+latex: \end{minipage}
  #+latex: \end{center}

  #+xxx: fig fig-probl-2_1004-drugs2-*.pdf

En los dos casos aumenta la cantidad consumida, pero el precio
disminuye en el primer escenario y aumenta en el segundo.


* 2.6

Las curvas de demanda y de oferta del mercado del bien $X$ son:
#+begin_export latex
\begin{gather*}
  X^d = \num{85000} - 20 P_X \\
  X^o = \num{15000} + 15 P_X
\end{gather*}
#+end_export

a) Determine el precio y la cantidad de equilibrio.

b) Represente gráficamente los efectos sobre el equilibrio de un
   aumento del precio de un bien sustitutivo. ¿Es posible predecir
   inequívocamente cómo cambiará el precio de equilibrio del bien
   $X$? ¿Y la cantidad de equilibrio?

c) Partiendo del equilibrio inicial, considere ahora los efectos
   de un aumento de la renta de los consumidores. ¿Es posible
   predecir con total certeza cómo cambiarán el precio y la
   cantidad de equilibrio?

** Answer

a)
   #+attr_latex: :options {0.65\linewidth}
   #+xxx: col
   #+xxx: fig fig-probl-2_1004-comp1-*.pdf

   #+attr_latex: :options {0.35\linewidth}
   #+xxx: col
   Equilibrio:
   #+begin_export latex
   \begin{gather*}
     P^*_X = \price{2000} \\
     X^* = \units{45000}
   \end{gather*}
   #+end_export

b)
   #+attr_latex: :options {0.55\linewidth}
   #+xxx: col
   #+xxx: fig fig-probl-2_1004-comp2-*.pdf

   #+attr_latex: :options {0.45\linewidth}
   #+xxx: col
   El precio y la cantidad de equilibrio aumentan.

c)
   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col
     #+xxx: fig fig-probl-2_1004-comp2-*.pdf
     #+latex: \begin{center}
     #+latex: \begin{minipage}{0.85\linewidth}
       Bien normal: el precio y la cantidad aumentan.
     #+latex: \end{minipage}
     #+latex: \end{center}

   #+attr_latex: :options {0.55\linewidth}
   #+xxx: col
     #+xxx: fig fig-probl-2_1004-comp3-*.pdf
     #+latex: \begin{center}
     #+latex: \begin{minipage}{0.85\linewidth}
       Bien inferior: el precio y la cantidad se reducen.
     #+latex: \end{minipage}
     #+latex: \end{center}


* 2.7

El mercado de coches eléctricos de un país es competitivo y las
curvas de demanda y oferta son:
#+begin_export latex
\begin{gather*}
  Q^{d} = \num{10000} - P/6 \\
  Q^{o} = -6000 + P/2
\end{gather*}
#+end_export
a) Determine el precio y la cantidad de equilibrio.

b) Calcule y represente el nuevo equilibrio si la demanda aumenta
   en un 20% (la cantidad demandada es un 20% superior para cada
   precio) y la oferta pasa a ser:
   #+begin_export latex
   \[
     Q^o = -2700 + P/2
   \]
   #+end_export

** Answer

a)
   #+attr_latex: :options {0.65\linewidth}
   #+xxx: col
   #+xxx: fig fig-probl-2_1004-cars1-*.pdf

   #+attr_latex: :options {0.35\linewidth}
   #+xxx: col
   Equilibrio:
   #+begin_export latex
   \begin{gather*}
     P^* = \price{24000} \\
     Q^* = \units{6000}
   \end{gather*}
   #+end_export

b)
   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col
   #+xxx: fig fig-probl-2_1004-cars2-*.pdf

   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col
   - Curva de demanda:
     #+begin_export latex
     \[
       Q^d = \num{12000} - P/5
     \]
     #+end_export
   - Equilibrio:
     #+begin_export latex
     \begin{gather*}
       P^* = \price{21000} \\
       Q^* = \units{7800}
     \end{gather*}
     #+end_export


* 2.8

El mercado de un bien inferior se encuentra en equilibrio. Si
simultáneamente aumentan los costes de producción y la renta de
los consumidores, ¿disminuirán tanto el precio como la cantidad en
el nuevo equilibrio?

** Answer

#+attr_latex: :options {0.5\linewidth}
#+xxx: col
  #+xxx: fig fig-probl-2_1004-inferior1-*.pdf
  #+latex: \begin{center}
  #+latex: \begin{minipage}{0.85\linewidth}
    La cantidad de equilibrio disminuye. El precio baja si el
    cambio en la oferta es relativamente menor que el cambio en
    la demanda.
  #+latex: \end{minipage}
  #+latex: \end{center}

#+attr_latex: :options {0.5\linewidth}
#+xxx: col
  #+xxx: fig fig-probl-2_1004-inferior2-*.pdf
  #+latex: \begin{center}
  #+latex: \begin{minipage}{0.85\linewidth}
    La cantidad de equilibrio disminuye. El precio sube si el
    cambio en la oferta es relativamente mayor que el cambio en
    la demanda.
  #+latex: \end{minipage}
  #+latex: \end{center}
