# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 6.1

La función de utilidad de un consumidor es $U = X^2 Y$, su renta es $M
= \money{100}$ y los precios del bienes son $P_X = \price{10}$ y $P_Y
= \price{10}$. Obtenga y represente la curva renta consumo y la curva
de Engel del bien $X$. Calcule la elasticidad renta de $X$.  ¿Qué tipo
de bien es?


** Answer

Ambas curvas se obtienen a partir de las condiciones de maximización
de la utilidad:

- Recta presupuestaria: $M = 10 X + 10 Y$.

- Condición de tangencia: $Y =  X / 2$.

/Curva renta consumo/. Coincide con la condición de tangencia:
#+begin_export latex
\[
   Y =  X / 2
\]
#+end_export

/Curva de Engel/. Se obtiene sustituyendo la condición de tangencia en la recta presupuestaria y operando:
#+begin_export latex
\[
   X =  M / 15
\]
#+end_export

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-6_1004-ic-curve-*.pdf
#+begin_center
Curva renta consumo
#+end_center
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-6_1004-engel-curve-*.pdf
#+begin_center
Curva de Engel
#+end_center
#+xxx: endcol
#+latex: \vspace*{2ex}

Elasticidad renta:
#+begin_export latex
\[
  E_d^M =
  \frac{\diff X}{\diff M} \frac{M}{X} =
  \frac{1}{15}\frac{M}{M/15} = 1
\]
#+end_export
La elasticidad renta es positiva: $X$ es un bien normal.



* 6.2

El siguiente gráfico muestra la curva renta consumo de un consumidor
cuando el precio del bien $X$ es $P_X = \price{10}$ y el precio del
bien $Y$ es $\price{20}$:

#+xxx: fig fig-probl-6_1004-crc20-*.pdf

Represente gráficamente las curvas de Engel de ambos bienes. ¿Qué tipo
de bienes son $X$ e $Y$?


** Answer

#+xxx: fig fig-ans-probl-6_1004-crc20-*.pdf

Podemos resumir la información del gráfico en la siguiente tabla:
#+ATTR_LATEX: :booktabs t :center t :align c*{3}{R{1.25cm}}
|------------+------+------+-------|
|            | $X$  | $Y$  | $M$   |
|------------+------+------+-------|
| \textbf{A} | $0$  | $0$  | $0$   |
| \textbf{B} | $4$  | $2$  | $80$  |
| \textbf{C} | $10$ | $3$  | $160$ |
| \textbf{D} | $16$ | $4$  | $240$ |
| \textbf{E} | $20$ | $6$  | $320$ |
| \textbf{F} | $16$ | $12$ | $400$ |
| \textbf{G} | $12$ | $18$ | $480$ |
|------------+------+------+-------|
Las curvas de Engel relacionan el consumo de un bien y la renta. La
pendiente de una curvas de Engel es positiva cuando el bien es normal
y es negativa cuando el bien es inferior.

#+ATTR_LATEX: :options [t]{0.52\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-6_1004-engel-x-*.pdf
#+ATTR_LATEX: :options [t]{0.48\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
Curva de Engel del bien $X$. El bien $X$ es normal cuando la renta es
inferir a \money{320} y es un bien inferior cuando la renta es mayor
que \money{320}.
#+xxx: endcol
#+latex: \vspace{1ex}

#+ATTR_LATEX: :options [t]{0.52\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-6_1004-engel-y-*.pdf
#+ATTR_LATEX: :options [t]{0.48\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
Curva de Engel del bien $Y$. El bien $Y$ es normal para todos los
valores de la renta.
#+xxx: endcol



* 6.3.

Un consumidor compra solo dos bienes cuyos precios son $P_X =
\price{1}$ y $P_Y = \price{1}$. La figura siguiente muestra su
curva renta consumo:

#+xxx: fig fig-probl-6_1004-crc1-*.pdf

a) Si $M = \money{70}$, ¿cuántas unidades demandará de cada uno de
   los bienes?

b) ¿Alguno de los bienes es inferior? ¿Para qué valores de la
   renta?


** Answer

a) La elección óptima es la intersección de \CRC y la recta
   presupuestaria correspondiente a $M = \money{70}$. Para trazar esta última,
   se unen los puntos de corte de la recta presupuestaria con los
   ejes: $M / P_X = 70$ en el eje $X$ y $M / P_Y = 70$ en el eje
   $Y$. Como puede verse en el siguiente gráfico la cesta óptima está
   compuesta por $40$ unidades de $X$ y $30$ unidades de $Y$.

   #+xxx: fig fig-ans-probl-6_1004-crc2-*.pdf

b) Conforme aumenta la renta y la recta presupuestaria se desplaza
   hacia la derecha y hacia arriba el consumo de $X$ siempre aumenta:
   $X$ es un bien normal para todos los valores que tome la renta. Por
   otro lado, el consumo del bien $Y$ aumentaría con la renta para
   valores relativamente bajos de $M$, pero se movería en dirección
   opuesta a la renta para valores de $M$ más altos. En el gráfico
   siguiente se muestra que el bien $Y$ es normal para $M \leq
   \money{120}$ y es un bien inferior para $M > \money{120}$.

   #+xxx: fig fig-ans-probl-6_1004-crc3-*.pdf


* 6.4.

Considere un consumidor que sólo compra dos bienes. ¿Pueden ser los
dos bienes inferiores simultáneamente?


** Answer

No: al menos uno de los bienes tiene que ser normal.
#+ATTR_LATEX: :options [t]{0.45\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-6_1004-inferior-*.pdf
#+ATTR_LATEX: :options [t]{0.55\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
Supongamos que el consumidor elige inicialmente la cesta $A$. Si
aumenta la renta, la recta presupuestaria se desplazaría hacia la
derecha y hacia arriba y, si los dos bienes fueran inferiores,
elegiría una cesta como la $B$, que contiene menos unidades de $X$ e
$Y$.
#+xxx: endcol
Sin embargo, el consumidor podía haber comprado las dos cestas con la
renta inicial y eligió la cesta $A$. Es decir, la elección inicial del
consumidor revela que éste prefiere $A$ a $B$. Si aumenta la renta aún
puede comprar las dos cestas y, como $A \succ B$, no elegiría $B$. Por
tanto, los dos bienes no pueden ser inferiores.


* 6.5.

Las preferencias de un consumidor pueden representarse por la
función de utilidad:
#+begin_export latex
\[
  U(X, Y) = X Y^{4}
\]
#+end_export
El precio del bien $X$ es \price{6}, el del bien $Y$ es \price{8} y
el consumidor dispone de una renta de \money{240}.

a) Obtenga y represente la curva de precio-consumo. ¿Qué tipo de relación se da
   entre $X$ e $Y$?

b) Obtenga y represente la curva de demanda del bien $X$. Calcule la elasticidad
   precio de la demanda.


** Answer

Para obtener ambas curvas se parte de las condiciones de maximización
de la utilidad:

- Recta presupuestaria: $240 = P_X X + 8 Y$.

- Condición de tangencia: $Y =  P_X X / 2$.


a)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-6_1004-cpc1-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   La curva precio consumo se puede obtener despejando $P_X$ en la
   condición de tangencia y sustituyendo en la recta presupuestaria:
   #+begin_export latex
   \[ Y = 24 \]
   #+end_export
   #+xxx: endcol
   La demanda de $Y$ no responde a cambios en $P_X$:
   #+begin_export latex
   \[
     E_{Y^d}^{P_X} =
     \frac{\diff Y}{\diff P_X} \frac{P_X}{Y} =
     0\frac{P_X}{24} = 0
   \]
   #+end_export

b)
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{0pt}
   #+ATTR_LATEX: :center nil
   #+xxx: fig fig-ans-probl-6_1004-cpc2-*.pdf
   #+ATTR_LATEX: :options [t]{0.5\linewidth}
   #+xxx: col
   #+latex: \vspace{1ex}
   Despejando $Y$ en la condición de tangencia, sustituyendo en la
   recta presupuestaria y operando se obtiene la curva de demanda:
   #+begin_export latex
   \[ X = \frac{48}{P_X} \]
   #+end_export
   #+xxx: endcol
   La curva de demanda de $X$ tiene elasticidad unitaria:
   #+begin_export latex
   \[
     E_{X^d} =
     \frac{\diff X}{\diff P_X} \frac{P_X}{X} =
     -\frac{48}{P_X^2}\frac{P_X}{48/P_X} = -1
   \]
   #+end_export



* 6.6

El siguiente gráfico muestra la curva precio consumo de un consumidor
cuando el precio del bien $Y$ es $P_Y = \price{2}$ y la renta es $M
= \money{120}$:

#+xxx: fig fig-probl-6_1004-cpc22-*.pdf

a) ¿Cuántas unidades de $X$ compraría el consumidor si el precio de
   este bien es $P_X = \price{2}$? ¿Y cuántas unidades compraría del
   bien $Y$?

b) Obtenga también la cantidad demandada de $X$ cuando $P_X$ toma los
   valores $3, 4, 4.8$, y \price{6} y represente la curva de demanda de
   $X$.

c) ¿Qué tipo de relación existe entre los bienes $X$ e $Y$?


** Answer

a)
    #+ATTR_LATEX: :options [t]{0.68\linewidth}
    #+xxx: col
    #+latex: \vspace{0pt}
    #+ATTR_LATEX: :center nil
    #+xxx: fig fig-ans-probl-6_1004-cpc22-a-*.pdf
    #+ATTR_LATEX: :options [t]{0.32\linewidth}
    #+xxx: col
    #+latex: \vspace{1ex}
    La cesta óptima es:
    #+begin_export latex
    \begin{gather*}
      X = 35 \\ Y = 25
    \end{gather*}
    #+end_export
    #+xxx: endcol
    La cesta óptima se encuentra en la intersección de la recta
    presupuestaria $120 = 2 X + 2 Y$ y de la \CPC.

b)
    #+ATTR_LATEX: :options [t]{0.68\linewidth}
    #+xxx: col
    #+latex: \vspace{0pt}
    #+ATTR_LATEX: :center nil
    #+xxx: fig fig-ans-probl-6_1004-cpc22-b-*.pdf
    #+ATTR_LATEX: :options [t]{0.32\linewidth}
    #+xxx: col
    #+latex: \vspace{1ex}
    #+ATTR_LATEX: :booktabs t :center t :align @{}c*{2}{r}@{}
    |------------+-------+------|
    |            | $P_X$ | $X$  |
    |------------+-------+------|
    | \textbf{A} | $2.0$ | $35$ |
    | \textbf{B} | $3.0$ | $30$ |
    | \textbf{C} | $4.0$ | $25$ |
    | \textbf{D} | $4.8$ | $15$ |
    | \textbf{E} | $6.0$ | $10$ |
    |------------+-------+------|
    #+xxx: endcol
    Es posible construir una tabla que relacione $P_X$ y $X$ buscando
    los puntos de intersección de la curva precio consumo y las rectas
    presupuestarias correspondientes a cada precio.

    #+ATTR_LATEX: :options [t]{0.65\linewidth}
    #+xxx: col
    #+latex: \vspace{0pt}
    #+ATTR_LATEX: :center nil
    #+xxx: fig fig-ans-probl-6_1004-demand-x-*.pdf
    #+ATTR_LATEX: :options [t]{0.35\linewidth}
    #+xxx: col
    #+latex: \vspace{1ex}
    Curva de demanda del bien $X$.
    #+xxx: endcol

c) Las elecciones de consumo óptimas para precios del bien $X$
   superiores a $\price{4}$ se encuentran en el tramo decreciente de
   la curva precio consumo. En este tramo, ante variaciones en el
   precio de $X$ se producen cambios en el consumo de los dos bienes
   en direcciones opuestas. Por tanto, $X$ e $Y$ son sustitutivos
   cuando $P_X \geq 4$.

   El tramo creciente de la \CPC contendría las cestas óptimas cuando
   $P_X < 4$. Los consumos de los dos bienes variarían en la misma
   dirección en respuesta a alteraciones del precio de $X$. Luego,
   cuando $P_X < 4$ los bienes $X$ e $Y$ son complementarios.



* 6.7

La cesta óptima de un consumidor con preferencias regulares contiene
cantidades positivas de todos los bienes. Si aumenta el precio de un
bien, ¿se reducirá la utilidad del consumidor? Describa cómo varía la
utilidad de un consumidor a lo largo de la curva de demanda de un
bien. Justifique su respuesta.


** Answer

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-6_1004-price-change-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
Al subir el precio de $X$, el consumidor no puede comprar la cesta
inicial, $A$, y elige una cesta como la $B$. Antes de subir el precio,
pudo haber comprado $B$ pero eligió comprar $A$. Esta decisión revela
que prefiere $A$ a $B$. Por tanto, al subir el precio de $X$ el
consumidor elige una cesta que le reporta menos utilidad.
#+xxx: endcol

#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{0pt}
#+ATTR_LATEX: :center nil
#+xxx: fig fig-ans-probl-6_1004-demand-utility-*.pdf
#+ATTR_LATEX: :options [t]{0.5\linewidth}
#+xxx: col
#+latex: \vspace{1ex}
En cada punto de la curva de demanda, la utilidad es diferente y es
menor cuanto mayor es el precio.
#+xxx: endcol






* 6.8

En un mercado participan $n$ consumidores idénticos y la curva de
demanda de cada uno de ellos es:
#+begin_export latex
  \[ X_i^d(P_X) = a - b P_X \qquad
     \begin{array}{l}a,b > 0\\ i = 0, 1, \dots, n\end{array}\]
#+end_export

a) Determine la pendiente de la curva de demanda de mercado. Al
   representarla gráficamente, ¿será más o menos plana que las curvas
   de demanda individuales?

b) ¿Qué relación existe entre la elasticidad precio de las demandas
   individuales y la elasticidad de la curva de demanda de mercado?



** Answer

Por hacer.


* 6.9.

Tanto Adela como Blas disponen de \money{100} para gastar en los
bienes $X$ e $Y$.  A Adela sólo le importa cuántas unidades de $X$
puede consumir ya que el bien $Y$ no le reporta ninguna
satisfacción. Por su parte, Blas está siempre dispuesto a
intercambiar una unidad del bien $X$ por una unidad del bien
$Y$. Los precios de los bienes son $P_X = \price{2}$ y $P_Y =
\price{4}$. Obtenga las curvas de demanda del bien $X$ de Adela y
Blas.


** Answer

Adela: $Y$ es neutro.
#+begin_export latex
  \[ X_A(P_X) = 100 / P_X \]
#+end_export

Blas: sustitutivos perfectos.
#+begin_export latex
\[
  X_B(P_X) =
  \begin{cases}
    100 / P_X & \text{si $P_{X} \leq 4$} \\
    0 & \text{si $P_{X} > 4$}
  \end{cases}
\]
#+end_export


* 6.10

A Rocío le gusta tomar leche con cereales. Siempre los combina en la
misma proporción: añade exactamente \units[g]{20} de cereales por cada
\units[ml]{250} de leche y desecha cualquier cantidad sobrante de
leche o cereales. Obtenga la curva de demanda de cereales sabiendo que
el precio de la leche es de \price[l]{0.80} y que Rocío gasta
\money{6} al mes en leche y cereales. Si los cereales se venden
a \price[kg]{2}, ¿qué cantidad demandará Rocío?


** Answer

Por hacer.


* 6.11.

El alcalde de Lazy Town ha decidido introducir un nuevo impuesto
sobre las refrescos azucarados de \money{0.50} por lata de
refresco. El impuesto se traslada por completo a los compradores y
el precio de la lata aumenta desde \money{0.50} hasta
\money{1.00}.

Stephanie es una ciudadana típica de Lazy Town cuya función de
utilidad es:
#+begin_export latex
\[
  U(R, Y) = (R + 20)^{0.1} Y^{0.9}
\]
#+end_export
donde $R$ es el número de latas de refresco que consume e $Y$ es
un bien compuesto que recoge los restantes gastos en
alimentación. Stephanie dispone cada mes de \money{470} para
gastar en $R$ e $Y$.

a) ¿Cuántas latas de refresco consumía Stephanie al mes antes de
   la introducción del impuesto?

b) Calcule la elección óptima de Stephanie después de la
   introducción del impuesto. ¿Consigue el impuesto reducir su
   consumo de refrescos azucarados?  ¿Cuánto dinero pagará por el
   impuesto?

c) Ante las protestas de los habitantes de la ciudad, el alcalde
   decide mantener el impuesto pero entregar a cada ciudadano
   \money{14.50} en metálico. Calcule cuantas latas consumirá ahora
   Stephanie. ¿Sigue consumiendo menos refrescos que en la situación
   inicial?  ¿Bastará con la recaudación del impuesto para pagar las
   transferencias en metálico a los ciudadanos?


** Answer

a) Restricción presupuestaria: $470 = 0.5 R + Y$.

   Condición de tangencia: $(1/9) Y/(R + 20) = 0.5$.

   Elección óptima: $R_1 = 76$ latas e $Y_1 = \money{432}$.

b) Restricción presupuestaria: $470 = R + Y$.

   Condición de tangencia: $(1/9) Y/(R + 20) = 1$.

   Elección óptima: $R_2 = 29$ latas e $Y_2 = \money{441}$.

   Paga: $R_2 t = \money{14.5}$.

c) Restricción presupuestaria: $484.5 = R + Y$.

   Condición de tangencia: $(1/9) Y/(R + 20) = 1$.

   Elección óptima: $R_3 = 30.45$ latas e $Y_3 = \money{454.05}$.

   La recaudación del impuesto per capita, $0.5 R_3 = \money{15.225}$,
   es superior a la cuantía del cheque, \money{14.50}.

#+latex: \addtocounter{section}{1}


* COMMENT OLD 6.7.

Las preferencias de un consumidor vienen dadas por la función de
utilidad: $U(X, Y) = X^{1/4} Y^{1/8}$ y su renta es $M =
\money{17496}$. Los precios son $P_X = \price{54}$ y $P_Y =
\price{36}$.

a) Obtenga la curva de demanda del bien $X$.

b) Calcule cuánto varía el consumo de los dos bienes cuando el
   precio de $X$ disminuye hasta $P_X = \price{16}$.

c) Descomponga el impacto sobre el consumo de cada uno de los
   bienes en los correspondientes efecto renta y efecto
   sustitución. ¿Cuál es el signo de estos efectos?


** Answer

a) Restricción presupuestaria: $\num{17496} = P_X X + 36 Y$.

   Condición de tangencia: $2 Y / X = P_X / 36$.

   Curva de demanda: $X(P_X) = 11664 / P_X$.

b) Elecciones óptimas para los diferentes precios
   #+ATTR_LATEX: :booktabs t :center t :align *{4}{r}
   |-------+-------+-------+-------|
   | $P_X$ | $P_Y$ | $X$   | $Y$   |
   |-------+-------+-------+-------|
   | $54$  | $36$  | $216$ | $162$ |
   | $16$  | $36$  | $729$ | $162$ |
   |-------+-------+-------+-------|

   El consumo de $X$ aumenta en $513$ unidades y el consumo de $Y$ no
   varía.

c) Para determinar los consumos si sólo cambiaran los precios relativos y se mantuviera constante la utilidad, resolvemos:
   #+begin_export latex
   \begin{gather*}
     216^{1/4} 162^{1/8} = X^{1/4} Y^{1/8} \\
     2Y/X = 16/36
   \end{gather*}
   #+end_export
   Por lo que $X_H = 324$ e $Y_H = 72$.

   #+ATTR_LATEX: :booktabs t :center t :align lrr
   |-----+-------------------+------------------|
   |     | Efecto directo    | Efecto cruzado   |
   |-----+-------------------+------------------|
   | \ES | $324 - 216 = 108$ | $72 - 162 = -90$ |
   | \ER | $729 - 324 = 405$ | $162 - 72 = 90$  |
   | \ET | $729 - 216 = 513$ | $72 - 72 = 0$    |
   |-----+-------------------+------------------|

   Todos los efectos tienen signo negativo excepto el efecto
   sustitución cruzado (que siempre tiene signo positivo).



* COMMENT OLD 6.8.

Los bienes $X$ e $Y$ son complementos perfectos. Represente
gráficamente como cambiaría la elección de consumo óptima si aumenta
el precio del bien $X$. Descomponga el cambio total en el consumo de
$X$ en el efecto sustitución y el efecto renta.


** Answer

El efecto sustitución es nulo y coinciden efecto renta y efecto total.
#+xxx: fig fig-ans-probl-6_1004-compl-*.pdf


* COMMENT OLD 6.9.

Dulce sigue comprando la misma cantidad de sal a pesar de que su
precio ha disminuido un 50%. ¿Quiere esto decir que el efecto
sustitución es nulo? ¿Es la sal un bien inferior para Dulce?


** Answer

El efecto total es $0$, por lo que la suma del efecto sustitución y el
efecto renta es igual a 0. Por tanto, $\ER = -\ES < 0$, el signo del
efecto renta es positivo y la sal es inferior para Dulce.



* COMMENT OLD 6.10.

"La cantidad demandada de un bien Giffen aumenta cuando aumenta su
precio y también aumenta cuando crece la renta de los
consumidores."  ¿Es correcta la afirmación anterior?  Justifique
su respuesta.


** Answer

No: los bienes Giffen son inferiores.



* COMMENT OLD 6.11.

El siguiente gráfico muestra las elecciones óptimas de un
consumidor antes y después de una disminución del precio del bien
$X$:

#+xxx: fig fig-probl-6_1004-fxs-*.pdf

Observe que coinciden las pendientes de las curvas de indiferencia
en las cestas $A$ y $B$, por un lado, y en las cestas $C$ y $D$,
por otro lado.

Descomponga el efecto total sobre el consumo de $X$ en efecto renta
y efecto sustitución. Obtenga los signos de estos efectos y
determine qué tipo de bien es $X$ para este consumidor.


** Answer

Ante una disminución del precio de $X$:
#+begin_export latex
\begin{gather*}
  \ET = X_{C} - X_{A} = 30 - 15 = 15 \quad\text{(signo negativo)}\\
  \ES = X_{D} - X_{A} = 35 - 15 = 20 \quad\text{(signo negativo)}\\
  \ER = X_{C} - X_{D} = 30 - 35 = -5 \quad\text{(signo positivo)}
\end{gather*}
#+end_export

$X$ es inferior y su demanda tiene pendiente negativa.
