#+SETUPFILE: ./course-es.org

#+TITLE: Cuaderno de ejercicios 4


* La elección intertemporal

1. Un consumidor tiene unas preferencias con respecto a su consumo
   presente, $C_1$, y su consumo futuro, $C_2$, que vienen
   representadas por la función de utilidad $U(C_1, C_2) = C_1
   C_2$. La renta que obtiene el consumidor en cada uno de los
   periodos es $M_1 = \money{1000}$ y $M_2 = \money{1500}$. El tipo
   de interés es $r = 0.5$.

   a) Escriba la restricción presupuestaria intertemporal de este
      individuo en valor futuro.

   b) Determine si el individuo ahorra o no, así como el nivel de
      consumo en cada periodo.

   c) Suponga ahora que el consumidor considera ambos bienes como
      complementos perfectos y su función de utilidad es: $U(C_1, C_2)
      = \min\{C_1, C_2\}$. Obtenga el perfil de consumo intertemporal
      óptimo en este caso.

2. Las preferencias entre el consumo presente, $C_1$, y consumo
   futuro, $C_2$, de un individuo están representadas por la función
   de utilidad: $U(C_1, C_2)= C_1^2 C_2$.  En el primer periodo el
   individuo tiene una renta de \money{200}, mientras que en el
   segundo periodo obtiene una renta de \money{220}. El tipo de
   interés al que se presta dinero es del 5%, y el tipo de interés al
   se pide prestado es del 10%.

   a) Exprese analíticamente la restricción presupuestaria del
      individuo y represéntela gráficamente.

   b) Calcule el equilibrio del consumidor y determine si será
      prestamista o prestatario.

   c) Si el Banco Central Europeo fija un tipo de interés único del 8%
      tanto para prestar como para pedir prestado, calcule el nuevo
      equilibrio y determine si el consumidor mejora o empeora en
      términos de bienestar.

3. Un consumidor vive dos periodos y sus preferencias vienen
   representadas por: \[ U = C_1^3 C_2.\] Su elección óptima es $C_1 =
   \money{9750}$ y $C_2 = \money{3575}$.

   a) ¿Cuál es el tipo de interés?

   b) Sabiendo que el ahorro de este consumidor es $S = \money{250}$,
      escriba y represente gráficamente la restricción intertemporal.

4. Un consumidor vive dos periodos. En el primer periodo obtiene una
   renta de \money{600} y en el segundo de \money{440}. El tipo de
   interés es del 10%.

   a) Obtenga la restricción intertemporal del consumidor y
      represéntela gráficamente. ¿Qué interpretación tienen los
      puntos de corte con los ejes?

   b) Suponga que en esas condiciones la decisión óptima del
      consumidor es consumir toda la renta del primer periodo de
      forma que el ahorro es 0. ¿Cómo habría cambiado la elección si
      el tipo de interés hubiera sido superior? Represente
      gráficamente.

5. Explique y justifique si considera correcta o incorrecta cada una
   de las siguientes afirmaciones (use el análisis gráfico cuando lo
   considere oportuno):

   a) Si no existiera un mercado de crédito que permitiera al
      consumidor prestar y pedir prestado, éste no podría ahorrar en
      el periodo presente para consumir por encima de su renta
      monetaria en el futuro.

6. La renta monetaria de un individuo en el periodo actual es
   \money{2500} y en este periodo ahorra una cantidad de
   \money{1000}. En el periodo futuro su renta monetario disminuirá
   un 20%.

   a) Si existe un mercado financiero que le permite prestar y pedir
      prestado, ¿cuál es el tipo de interés para el que el consumo
      óptimo en el futuro sea de \money{3010}?

   b) Represente gráficamente la restricción presupuestaria y señale
      el consumo óptimo de este consumidor.

7. Las preferencias entre consumo presente, $C_1$, y consumo futuro,
   $C_2$, de un individuo están representadas por la función de
   utilidad: $U(C_1, C_2) = C_1^2 C_2$. En el primer periodo el
   individuo tiene una renta de \money{200}, mientras que en el
   segundo periodo su renta es \money{220}. El tipo de interés al que
   se presta en la economía es del 5%, y el tipo de interés al que se
   pide prestado es del 10%.

   a) Exprese analíticamente la restricción presupuestaria y
      represéntela gráficamente.

   b) Calcule el equilibrio del consumidor y determine si será
      prestamista o prestatario.

8. Un consumidor vive dos periodos y puede prestar y pedir prestado a
   un tipo de interés del 10%. En el primer periodo obtiene una renta
   monetaria de \money{1000} mientras que en el segundo período
   obtiene \money{750}. En estas condiciones el consumidor decide no
   ahorrar nada. Si el tipo de interés disminuyera al 5%, ¿qué
   ocurriría con el ahorro? ¿Qué situación preferiría el consumidor:
   un tipo de interés del 10% o del 5%? Represente
   gráficamente.

   #+begin_answer
   La restricción intertemporal cuando el tipo de interés es del 10%
   es:
   \begin{equation*}
     C_2 = 1850 - 1.1 C_1
   \end{equation*}

   #+attr_latex: :options {0.55\linewidth}
   #+begin_minipage
   #+MATS: fig fig-probl-4_1004-r10-*.pdf
   #+end_minipage
   #+attr_latex: :options {0.45\linewidth}
   #+begin_minipage
     Dado que el ahorro óptimo es $0$, el consumo y la renta de cada
     periodo coinciden: $C_1 = M_1 = \money{1000}$ y $C_2 = M_2 =
     \money{750}$. La relación marginal de sustitución en la
     combinación óptima es igual a $\mathit{RMS} = 1 + r$, por lo que:
     \begin{equation*}
       \mathit{RMS}(E_0) = 1.1
     \end{equation*}
   #+end_minipage

   La restricción intertemporal cuando baja el tipo de interés es:
   \begin{equation*}
     C_2 = 1800 - 1.05 C_1
   \end{equation*}
   La combinación inicial no puede ser óptima con un tipo de interés
   del 5%, pues:
   \begin{equation*}
     \mathit{RMS}(E_0) = 1.1 > 1 + r = 1.05
   \end{equation*}
   por lo que el consumidor aumentará su consumo presente a costa de
   consumo futuro y su ahorro será ahora negativo.

   #+attr_latex: :options {0.55\linewidth}
   #+begin_minipage
   #+MATS: fig fig-probl-4_1004-r5-*.pdf
   #+end_minipage
   #+attr_latex: :options {0.45\linewidth}
   #+begin_minipage
     El consumidor prefiere la situación donde $r = 5\%$: en el nuevo
     punto óptimo el consumidor alcanza una curva de indiferencia más
     alejada del origen. Aunque podría elegir $E_0$, el consumidor
     rechaza esa opción en favor de otra combinación de consumo: $E_1$
     es preferida a $E_0$.
   #+end_minipage


   #+end_answer

9. Un consumidor vive dos periodos y puede prestar y pedir prestado a
   un mismo tipo de interés. Obtiene una renta de \money{2500}, ahorra
   \money{1000}, y su renta en el segundo periodo es un 20%
   inferior. Calcule el tipo de interés sabiendo que la elección
   óptima del consumidor en el segundo periodo es \money{3010}. Obtenga
   y represente gráficamente la restricción intertemporal.
   #+begin_answer
     El consumo en el primer periodo se puede deducir de los datos del enunciado:
     \[ C_1 = M_1 - S_1 = 2500 - 1000 = \money{1500}.\]
     La renta en el segundo periodo es un 20% inferior a la del primer periodo:
     \[ M_2 = 0.8 M_1 = \money{2000}. \]
     La restricción intertemporal implica:
     \[ M_1 (1 + r) + M_2 = C_1 (1 + r) + C_2 \]
     Por lo que:
     \[ 2500 (1 + r) + 2000 = 1500 (1 + r) + 3010 \]
     Despejando se obtiene $r = 0.01$.

     Una vez calculado el tipo de interés podemos determinar el valor
     futuro del flujo de rentas del consumidor:
     \[ M_1 (1 + r) + M_2 = 2500 \cdot 1.01 + 2000 = \money{4525} \]
     La restricción intertemporal es:
     \[ 4525 = 1.01 C_1 + C_2 \]

     #+MATS: fig fig-probl-4_1004-budget-*.pdf
     #+end_answer
