# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org

* 4.1

El siguiente gráfico muestra las curvas de demanda y de oferta de un
mercado competitivo:

#+xxx: fig fig-probl-4_1004-price-controls-*.pdf

Encuentre la cantidad que se vendería y a qué precio en cada una de
las siguientes situaciones:

a) Se establece un precio mínimo de \price{1.50}.

b) Se establece un precio máximo de \price{1.50}.

c) Se establece un precio mínimo de \price{4.00}.

d) Se establece un precio máximo de \price{4.00}.


** Answer

a) El precio de equilibrio es superior al precio mínimo y el mercado
   se halla en equilibrio. Se venden 350 unidades a un precio unitario
   de \price{2.50}.

   #+xxx: fig fig-ans-probl-4_1004-price-controls-a-*.pdf

b) El precio de equilibrio es superior al precio máximo y hay un
   exceso de demanda en el mercado. Se venden 250 unidades a un precio
   unitario de \price{1.50}.

   #+xxx: fig fig-ans-probl-4_1004-price-controls-b-*.pdf

c) El precio de equilibrio es infeerior al precio mínimo y hay un
   exceso de oferta en el mercado. Se venden 50 unidades a un precio
   unitario de \price{4.00}.

   #+xxx: fig fig-ans-probl-4_1004-price-controls-c-*.pdf

d) El precio de equilibrio es inferior al precio máximo y el mercado
   se halla en equilibrio. Se venden 350 unidades a un precio unitario
   de \price{2.50}.

   #+xxx: fig fig-ans-probl-4_1004-price-controls-d-*.pdf



* 4.2

En el mercado del bien $X$ las curvas de demanda y de oferta son:
#+begin_export latex
\begin{gather*}
  X^d = 100 - P_X / 40 \\
  X^o = 50 + P_X / 40
\end{gather*}
#+end_export

a) Determine el precio y la cantidad de equilibrio.

b) Describa y represente gráficamente los efectos sobre el mercado
   del bien $X$ del establecimiento de un precio mínimo de
   \price{1200}. ¿Cuántas unidades se venderían? ¿A qué precio?


** Answer

a) En equilibrio: $P_X^* = \price{1000}$ y $X^* = \units{75}$.

b) El precio mínimo está por encima del de equilibrio, por lo que se
   venden 70 unidades a \price{1200} y hay un exceso de oferta de
   10 unidades.

   #+xxx: fig fig-ans-probl-4_1004-min-price-*.pdf


* 4.3

El precio en un mercado competitivo de azúcar es \money{0.75} por
kilo. Represente gráficamente y explique las efectos sobre
este mercado del establecimiento de un precio mínimo de
\price[kg]{0.60}. ¿Se venderán más o menos kilos de azúcar?



** Answer

Por hacer.


* 4.4

En un mercado competitivo en equilibrio, se venden \num{96000}
unidades a un precio de \price{300}. La elasticidad precio de la
demanda es $-1.5$ y que la elasticidad precio de la oferta es igual
a $2$. Si se aprueba una ley que establece un precio máximo de
\price{294}, ¿qué efectos tendrá sobre el mercado? Represente
gráficamente.


** Answer

La regulación implica una caída del precio $\incrpct{P} = -6/300 \cdot
100 = 2\%$. De acuerdo con las elasticidades proporcionadas:
#+begin_export latex
\begin{gather*}
  \incrpct{Q^{d}} = -1.5 \cdot (-2\%) = 3\% \\
  \incrpct{Q^{o}} = 2 \cdot (-2\%) = -4\%
\end{gather*}
#+end_export
Por lo que se produce un exceso de demanda de un 7% con respecto a la
cantidad inicial: se produce una escasez de unas 6720 unidades.


* 4.5

Las curvas de demanda y oferta de mercado del bien $X$ son:
#+begin_export latex
\begin{gather*}
  X^{d} = 200 - 5 P_{X} + 3 P_{Y} + 2 M \\
  X^{o} = 100 + 2 P_{X}
\end{gather*}
#+end_export
donde $M$ es la renta media de los consumidores y $P_Y$ es el precio
del bien $Y$, siendo $M = \money{100}$ y $P_Y = \price{5}$. Una ley
prohíbe que el precio de $X$ supere los $\money{50}$.

a) <<ex4.4:item-a>>¿Qué cantidad del bien $X$ se venderá? ¿A qué
   precio? Represente gráficamente.

b) Describa como cambiarían sus respuestas en [[ex4.4:item-a]] si la
   renta media aumentara hasta $M = \money{170}$.


** Answer

a) El precio máximo es superior al precio de equilibrio: nada impide
   que se alcance el equilibrio en este mercado.
   #+xxx: fig fig-ans-probl-4_1004-eq1-*.pdf

b) El nuevo precio de equilibrio es $P_X^* = \price{65}$; mayor que el
   precio máximo. Al precio máximo $P_X = \price{50}$ se venderán
   todas las unidades ofrecidas, $X^o(50) = \units{200}$.
   #+xxx: fig fig-ans-probl-4_1004-eq2-*.pdf


* 4.6

Razone la veracidad o falsedad de la siguiente afirmación: "Si se
establece un precio máximo superior al precio de equilibrio, la
cantidad vendida coincidirá con la cantidad de equilibrio."


** Answer

Un precio máximo superior al de equilibrio no impide al mercado que se
ajuste por lo que la afirmación es verdadera.


* 4.7

En el mercado de un bien las curvas de demanda y de oferta son:
#+begin_export latex
\begin{gather*}
  Q^d = \num{100000} - 20 P \\
  Q^o = \num{40000} + 40 P
\end{gather*}
#+end_export

a) Determine el precio y la cantidad de equilibrio.

b) <<ex4.1:item-b>>Describa y represente gráficamente los efectos
   sobre el mercado del establecimiento de un impuesto sobre los
   vendedores de \money{150} por unidad vendida. ¿Cómo se reparte la
   carga del impuesto entre los compradores y vendedores?

c) Calcule las elasticidades de la demanda y de la oferta en el
   equilibrio anterior a la introducción del impuesto ¿Qué relación
   existe entre la distribución de la carga del impuesto y estas
   elasticidades?

d) Explique como cambiarían sus respuestas en [[ex4.1:item-b]] si el
   impuesto se estableciera sobre los compradores.


** Answer

a) Equilibrio: $P^* = \price{1000}$ y $Q^* = \units{80000}$.
   #+xxx: fig fig-ans-probl-4_1004-before-tax-*.pdf

b) La curva de oferta después del impuesto es: $Q^o = \num{34000} + 40
   P$. En el nuevo equilibrio: $P^* = \price{1100}$ y $Q^* =
   \units{78000}$.
   #+xxx: fig fig-ans-probl-4_1004-tax-sellers-*.pdf

   Los compradores pagan \money{1100} por unidad; \money{100} más que
   sin impuesto. Una vez descontado el impuesto, los vendedores
   ingresan \money{950} por unidad; \money{50} menos que sin impuesto.

c) La curva de demanda después del impuesto es: $Q^d = \num{97000} -
   20 P$ y en el equilibrio: $P^* = \price{950}$ y $Q^* =
   \units{78000}$.
   #+xxx: fig fig-ans-probl-4_1004-tax-buyers-*.pdf

   Los resultados son idénticos al apartado anterior. Mientras que los
   vendedores cobran \money{950} por unidad, los compradores pagan el
   precio más el impuesto: un total de \money{1100} por unidad.


* 4.8

El mercado de alquiler de viviendas en una ciudad está representado
por las curvas de demanda y de oferta:
#+begin_export latex
\begin{gather*}
  Q^{d} = \num{25000} - 30 P \\
  Q^{o} = \num{5000} +10 P
\end{gather*}
#+end_export

a) Determine el equilibrio de mercado.

b) El ayuntamiento establece un programa de ayudas al alquiler por el
   que los inquilinos reciben una subvención de \money{200} al
   mes. ¿Cómo afectará este programa al alquiler mensual que cobran
   los caseros? ¿Cómo cambiará la cantidad que paga cada inquilino por
   el alquiler? ¿Cuál será el coste total del programa de subvenciones
   para el ayuntamiento? Represente gráficamente.


** Answer

a) Equilibrio de mercado: $P^* = \price{500}$ y $Q^* = \units{10000}$.
   #+xxx: fig fig-ans-probl-4_1004-subsidy1-*.pdf

b) La demanda con subvención es: $Q^d = \num{31000} - 30 P$. En el
   nuevo equilibrio: $P^* = \price{650}$ y $Q^* = \units{11500}$.
   #+xxx: fig fig-ans-probl-4_1004-subsidy2-*.pdf

   Los caseros reciben \money{650} y los inquilinos pagan
   \money{450} por casa alquilada. El coste total del programa
   de subvenciones asciende a $200 \cdot \num{11500} =
   \money{2300000}$.
