# -*- ispell-dictionary: "castellano" -*-
#+SETUPFILE: ./course-es.org


* 1.1

En una economía se producen dos bienes, automóviles y comida, usando
trabajo como único factor de producción. Se dispone de un máximo de
\num{50000} horas de trabajo. La siguiente tabla muestra las
cantidades que pueden producirse dependiendo de las horas de trabajo
que se dediquen a cada actividad:

#+ATTR_LATEX: :options {0.5\linewidth}
#+xxx: col
#+ATTR_LATEX: :booktabs t :center t :align @{}rR{2.5cm}@{}
|-------------+--------------|
| Trabajo     | Automóviles  |
| (horas)     | (unidades)   |
|-------------+--------------|
| \num{0}     | \num{0}      |
| \num{12500} | \num{40000}  |
| \num{25000} | \num{70000}  |
| \num{37500} | \num{90000}  |
| \num{50000} | \num{100000} |
|-------------+--------------|

#+ATTR_LATEX: :options {0.5\linewidth}
#+xxx: col
#+ATTR_LATEX: :booktabs t :center t :align @{}rR{2.5cm}@{}
|-------------+--------------|
| Trabajo     | Comida       |
| (horas)     | (kg)         |
|-------------+--------------|
| \num{0}     | \num{0}      |
| \num{12500} | \num{50000}  |
| \num{25000} | \num{75000}  |
| \num{37500} | \num{90000}  |
| \num{50000} | \num{100000} |
|-------------+--------------|
#+xxx: endcol

a) Represente gráficamente la Frontera de Posibilidades de
   Producción, FPP.

b) ¿Qué efecto tendría sobre la FPP una mejora en las técnicas de
   elaboración de comida que aumentara la producción por hora de
   trabajo? ¿Y una mejora organizativa en la cadena de producción
   de automóviles? ¿Y si ambas mejoras se produjesen
   simultáneamente como consecuencia de un progreso técnico
   generalizado?

c) ¿Qué consecuencias tendría sobre la FPP la reducción a la mitad
   de las horas de trabajo como consecuencia de un conflicto
   bélico?


** Answer

a)
   #+xxx: fig fig-ans-probl-1_1004-ppf-sh1-*.pdf

b)
   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col
   #+xxx: fig fig-ans-probl-1_1004-ppf-sh2-*.pdf

   #+latex: \begin{center}
   #+latex: \begin{minipage}{0.8\linewidth}
   Una mejora tecnológica en la producción de comida.
   #+latex: \end{minipage}
   #+latex: \end{center}

   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col
   #+xxx: fig fig-ans-probl-1_1004-ppf-sh3-*.pdf

   #+latex: \begin{center}
   #+latex: \begin{minipage}{0.8\linewidth}
   Una mejora organizativa en la producción de automóviles.
   #+latex: \end{minipage}
   #+latex: \end{center}

   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col
   #+xxx: fig fig-ans-probl-1_1004-ppf-sh4-*.pdf

   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col
   Mejoras en los dos sectores.

c)
   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col

   #+xxx: fig fig-ans-probl-1_1004-ppf-sh5-*.pdf

   #+attr_latex: :options {0.5\linewidth}
   #+xxx: col
   Desplazamiento a la izquierda de la FPP.



* 1.2

La tabla adjunta presenta diferentes combinaciones eficientes para una
economía en la que únicamente se producen dos bienes: $X$ e $Y$.

#+ATTR_LATEX: :booktabs t :center t :align @{}p{1cm}*{2}{R{2cm}}@{}
|-----+------------+------------|
|     | $X$        | $Y$        |
|-----+------------+------------|
| *A* | \num{20}   | \num{0}    |
| *B* | \num{18}   | \num{1}    |
| *C* | \num{15}   | \num{2}    |
| *D* | \num{11}   | \num{3}    |
| *E* | \num{6}    | \num{4}    |
| *F* | \num{0}    | \num{5}    |
|-----+------------+------------|

a) Represente la Frontera de Posibilidades de Producción, FPP. ¿Qué
   tiene de particular la forma de la FPP?

b) ¿Se pueden producir \num{2} unidades de $Y$ y \num{10} unidades de
   $X$?  ¿Qué ocurre en esta situación?

c) Construya una tabla que refleje el coste de oportunidad de producir
   cada unidad del bien $Y$.

d) ¿A cuántas unidades de $X$ se debe renunciar para producir la
   primera unidad de $Y$? ¿Y la segunda?


** Answer

a)
    #+attr_latex: :options {0.6\linewidth}
    #+xxx: col

    #+xxx: fig fig-ans-probl-1_1004-ppf-oc1-*.pdf

    #+attr_latex: :options {0.4\linewidth}
    #+xxx: col
    La FPP es cóncava.

b)
    #+attr_latex: :options {0.6\linewidth}
    #+xxx: col

    #+xxx: fig fig-ans-probl-1_1004-ppf-oc2-*.pdf

    #+attr_latex: :options {0.4\linewidth}
    #+xxx: col
    La combinación es factible pero ineficiente.

c)
    #+ATTR_LATEX: :booktabs t :center t :align p{1cm}*{2}{r}*{3}{c}
    |-----+----------+---------+------------+------------+---------------------------|
    |     | $X$      | $Y$     | $\incr{X}$ | $\incr{Y}$ | $\abs{\incr{X}/\incr{Y}}$ |
    |-----+----------+---------+------------+------------+---------------------------|
    | *A* | \num{20} | \num{0} | ---        | ---        | ---                       |
    | *B* | \num{18} | \num{1} | \num{-2}   | \num{1}    | \num{2}                   |
    | *C* | \num{15} | \num{2} | \num{-3}   | \num{1}    | \num{3}                   |
    | *D* | \num{11} | \num{3} | \num{-4}   | \num{1}    | \num{4}                   |
    | *E* | \num{6}  | \num{4} | \num{-5}   | \num{1}    | \num{5}                   |
    | *F* | \num{0}  | \num{5} | \num{-6}   | \num{1}    | \num{6}                   |
    |-----+----------+---------+------------+------------+---------------------------|

d) Para poder producir la primera unidad de $Y$ hay que renunciar a
   $2$ unidades de $X$, mientras que el coste de oportunidad de la
   segunda es $3$ unidades de $X$.



* 1.3

El siguiente gráfico representa la frontera de posibilidades de
producción de una economía donde sólo se producen cocos y pescado:

#+xxx: fig fig-probl-1_1004-ppf-*.pdf

Ordene las opciones de producción $A$, $B$, $C$ y $D$ de mayor a
menor coste de oportunidad de producir pescado.


** Answer

El coste de oportunidad sería mayor en $D$ que en $A$, ya que la
pendiente es más pronunciada en $D$.  Combinaciones como $B$ no son
eficientes y el coste de oportunidad es $0$. Puntos como el $C$ son
inaccesibles y el coste de oportunidad no está definido.



* 1.4

Determine si la siguiente afirmación es verdadera o falsa y justifique
su respuesta: "Cuando un gran número de desempleados encuentra
trabajo, la frontera de posibilidades de producción se desplaza hacia
la derecha."


** Answer

La FPP no se desplaza ya que no hay más factores de producción que en
la situación inicial. La economía se mueve de un punto ineficiente a
otro, ambos situados debajo de la FPP.
