# -*- ispell-dictionary: "english" -*-
#+SETUPFILE: ./course-en.org

#+MACRO: Inc Inc@@latex:\@.@@

* 9.1.

Complete the following table describing the short run costs of a
company.

#+ATTR_LATEX: :booktabs t :center t :align @{}l*{7}{R{1.3cm}}@{}
|-----+-------+-------+-------+--------+--------+---------+---------|
| $Q$ | $\CT$ | $\CF$ | $\CV$ | $\CMg$ | $\CMe$ | $\CFMe$ | $\CVMe$ |
|-----+-------+-------+-------+--------+--------+---------+---------|
| $0$ |       |       |       | ---    | ---    | ---     | ---     |
| $1$ | $86$  |       |       |        |        |         |         |
| $2$ |       |       | $46$  |        |        |         |         |
| $3$ |       |       |       | $17$   |        |         |         |
| $4$ |       |       |       |        |        |         | $19$    |
| $5$ |       |       |       |        | $29$   |         |         |
| $6$ | $150$ |       | $90$  |        |        |         |         |
|-----+-------+-------+-------+--------+--------+---------+---------|


** Answer

Not done yet.


* 9.2.

The production function of a firm is: $Q = L^{1/2} K^{1/2}$ and the
input prices are $w =\price{10}$ and $r = \price{20}$. In the short
run the capital input is fixed at $\Kbar = \units{25}$.

a) Obtain and represent the total cost, fixed cost and variable
   cost curves.

b) Obtain and represent the average cost, average variable cost and
   marginal cost curves.

c) At which output level is average cost minimized?  Which is
   the minimum average cost?


** Answer

Not done yet.


* 9.3

A firm is in a situation such that $\PMgL = \PMeL$. Which is the relationship
between its average and marginal costs in the short run?
Represent graphically.


** Answer

Not done yet.


* 9.4.

The production function of a company is given by: $Q = K L$. The
hourly wage is \wage{2} and the price of capital input is
\price{4}. Determine the input combination that minimizes the cost
of producing 5000 units. Which is the minimum cost?


** Answer

Not done yet.


* 9.5.

The owner of a company has drawn the following diagram to decide how
many units of labor and capital she should hire in the long run in order to
produce 150 units when the unit prices of labor and capital are
\money{16} and \money{40}, respectively.

#+xxx: fig fig-probl-9_1004-choice-*.pdf

a) Complete the diagram by labeling the intersections of the
   isocost lines with the horizontal axis. What is the meaning of
   these intersection points?

b) If 150 units are produced at a total cost of \money{440}, is the
   firm minimizing the cost of production?

c) If $\PMgK = 30$ when costs are minimized, which is the value of
   $\PMgL$?


** Answer

Not done yet.


* 9.6.

Sauron {{{Inc}}} is a company dedicated to the production of
exclusive rings using labor and 3D printers. The daily production
would increase by 18 rings if the company hires one more
worker. If, instead of increasing the staff, the company rents an
additional printer the daily production would rise by 6
rings. Knowing that the daily wage is 4 times the daily rental
price of a 3D printer, is Sauron {{{Inc}}} minimizing its costs?
If your answer is no, what could Sauron {{{Inc}}} do to reduce its
costs? Justify your answers.


** Answer

Not done yet.


* 9.7.

A company's production function is: $Q = L^{3/2} K^{1/2}$. The
company currently hires 144 hours of labor and 12 units of
capital. If this is the optimal long run input combination and if
total costs are equal to \money{1152}, which are the prices of
capital and labor inputs?


** Answer

Not done yet.


* 9.8.

The production function of a company is: $F(L, K) = L^{2} K$ and
the input prices are: $w = \wage{16}$ and $r = \price{8}$.

a) Obtain the long run conditional demand curves for each factor of
   production.

b) Determine the long run cost curve, as well as the average and
   marginal cost curves. Which is the total cost of producing
   \num{8000} units?


** Answer

Not done yet.


* 9.9.

The long run total cost curve of a company is:
#+begin_export latex
\[
  \CT(Q) = Q^3 - 8 Q^2 + 22 Q
\]
#+end_export
Obtain and represent the average cost and marginal cost
curves. Which is the minimum unit cost? At which output level is
the unit cost minimized? Over which range of output does the
company experience economies of scale? And diseconomies of scale?


** Answer

Not done yet.


* 9.10.

Consider the production function: $Q = K L$. The inputs prices are
$w= \wage{1}$ and $r=\price{1}$ and the capital input in the short
run is fixed at $\Kbar = \units{3}$.

a) Determine the short run cost curve.

b) Obtain the long run cost curve.

b) What is the single output level at which the long run and
   short run costs coincide? Why? What does happen at any other
   output level? Represent graphically.


** Answer

Not done yet.


* 9.11.

The following figure shows some isoquants of a firm's production
function:

#+xxx: fig fig-probl-9_1004-expansion-*.pdf

The daily wage amounts to \money{80} per worker.  Each unit of
capital that uses the company also costs \money{80} per day. In
the short run the firm can only use 4 units of capital: $\Kbar =
4$.

a) Calculate the short run cost of producing $40$ units. Calculate
   also the short run cost of producing $160$ and $360$ units.

b) Calculate the long run cost of producing $40$, $160$ and $360$
   units. Do the short run and long run costs coincide at any
   output level?


** Answer

Not done yet.


* 9.12.

Explain why the following statements are correct or incorrect (if
appropriate, use diagrams to illustrate your points):

a) The average cost is maximized when it coincides with the
   marginal cost.

c) If marginal cost is higher than the average cost in the long
   run, the company is operating under increasing returns to
   scale.

c) The long run cost can never be greater than the short run cost.

d) Whenever the marginal cost is increasing, the average cost is also
   increasing.


** Answer

Not done yet.


* 9.13

The production function of a firm is $Q = 10 K^{1/2} L^{1/2}$ and the
input prices are $w = \price{20}$ y $r = \price{80}$. The firm
produces 80 units using 16 units of labor and 4 units of capital.

a) Is the firm minimizing costs? If your answer is negative, determine
   the optimal amounts of labor and capital inputs.
b) <<ex9.21:item-b>>If the firm increased its output to 100 units and
   the capital was fixed, how much would the costs of production
   increase?
c) <<ex9.21:item-c>>If the firm increased its output to 100 units and
   all inputs were variable, how much would the costs of production
   increase?
d) Compare the answers to [[ex9.21:item-b]] and [[ex9.21:item-c]]. Why do they
   differ?


** Answer

Not done yet.


* 9.12.

A small company dedicated to the production of electrical guitars
is considering the possibility of opening a new factory. When
using a single factory, the average cost curve is:
#+begin_export latex
\[
  \CMe_1(Q) = 0.01 Q^2 - 6 Q + 1400
\]
#+end_export
where $Q$ is the number of guitars produced per year. With two
factories the average cost curve would be:
#+begin_export latex
\[
  \CMe_2(Q) = 0.01 Q^2 -12 Q + 4100
\]
#+end_export

a) If the company expects to sell 600 guitars next year, should it
   run one or two factories?

b) Obtain and represent the long run average cost curve.


** Answer

Not done yet.
